### ISSUE TITLE
"More index than column in data"

### ISSUE THREAD

**Issue by tristrot** [choishingwan/PRSice#102]
Hi,

I have been having difficulty finding the cause of this error message. For some background, the .assoc and the .bim files have approximately the same number of lines (.assoc = 9570788, .bim = 9669312), but not all the SNPs are present in both files (the lists are different). The plink files are based ~500 European humans from 1000 Genomes dataset, and the .assoc file is a recent set of GWAS summary statistic for Crohn's Disease. We are testing a binary trait using BETA values.

I am attaching the first 100 lines of the .assoc and .bim files in case there is a formatting error in either one of them, as well as the full error message below.

Thanks in advance and sorry for the trouble.

[cd_beta_100.assoc.txt](https://github.com/choishingwan/PRSice/files/3048283/cd_beta_100.assoc.txt)
[eur_test_100.bim.txt](https://github.com/choishingwan/PRSice/files/3048284/eur_test_100.bim.txt)
[eur_test_100.fam.txt](https://github.com/choishingwan/PRSice/files/3048285/eur_test_100.fam.txt)

PRSice 2.1.9 (25 Feburary 2019) 
https://github.com/choishingwan/PRSice
(C) 2016-2017 Shing Wan (Sam) Choi, Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Jack Euesden Cathryn M. Lewis Paul F. O'Reilly (2015)
PRSice: Polygenic Risk Score software.
Bioinformatics 31 (9): 1466-1468

2019-04-05 13:37:52
/pwd/PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base /pwd/cd_beta.assoc \
    --binary-target T \
    --bp BP \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --interval 5e-05 \
    --lower 0.0001 \
    --model add \
    --out PRSice \
    --pvalue P \
    --seed 853902752 \
    --snp SNP \
    --stat BETA \
    --target /pwd/eur_test \
    --thread 4 \
    --upper 0.5

Loading Genotype file: 
/pwd/eur_test 
(bed) 
 

503 people (0 male(s), 0 female(s)) observed 
503 founder(s) included 
 

1345385 ambiguous variant(s) excluded 
8323927 variant(s) included 
 

1 region included 

There are a total of 1 phenotype to process 
 

Start processing cd_beta 
============================== 
 

Reading 99.99%-0.0075 
More index than column in data 
 

Error: 
Execution halted

**Comment by choishingwan** [comment]
Considering that the error comes at around 99% of the read, it is likely that your base file is corrupted / with lines where some columns are missing. A quick way to check will be to read the base file into R using read.table and see the error message (if any). That should help to pinpoint the exact line where the error occures (I will guess it is almost at the end of the file)

Sam
