### ISSUE TITLE
Competitive p-value for PRset

### ISSUE THREAD

**Issue by sarasaezALS** [choishingwan/PRSice#104]
I am running PRset using several gene sets. I did not set up --set-perm so I did not get a competitive p-value. what does the competitive p-value measure?

**Comment by choishingwan** [comment]
When it come to set base analysis, there are two types of p-value, the self-contained p-value and the competitive p-value. 

The self-contain p-value test for association whereas the competitive p-value test for enrichment. 

Imagine a situation where the genetic signals associated with disease is scattered across the whole genome evenly, then a self-contain p-value of any gene sets will be significant as there are genetic signals resided within the gene sets. On the other hand, none of the gene sets will have a significant competitive p-value as they don't have higher association with the given phenotype when ccompared to other gene sets of simular property.

You can refer to this paper: https://academic.oup.com/bib/article/9/3/189/256048

**Comment by sarasaezALS** [comment]
thanks for your feedback! so, in terms of confirm a pathway is associated with the disease, both self associated p value and competitive value should be significant?

**Comment by choishingwan** [comment]
It depends on your hypothesis. If you are looking for pathway that is enriched with disease signals, then you want to use the competitive p-value; if you are looking for pathway that is associated with the disease, then you want to use the self-contained p-value. Generally, competitive p-value are more commonly used.

**Comment by sarasaezALS** [comment]
perfect!
the problem is that I added --set-perm 10000 in my code to get the competitive p value but the script just fails constantly

**Comment by choishingwan** [comment]
Do you have the full log? (it is normal for --set-perm to run for a very long time due to the amount of computation required, we are in the process of hopefully increasing the speed of the whole permutation)

**Comment by sarasaezALS** [comment]
not at all, my script fails from the beginning. Nothing is generated

**Comment by choishingwan** [comment]
Which version do you use? PRSice should always generate a log file unless there are something really really wrong.

**Comment by sarasaezALS** [comment]
this is the error message
Error in parse_args(OptionParser(option_list = option_list)) : 
  Error in getopt(spec = spec, opt = args) : 
  long flag "set-perm" is invalid
Execution halted

**Comment by choishingwan** [comment]
Oh, you need to use the later version of PRSice. Competitive P-value is only introduced in around version 2.1.6. Any Rscript or PRSice executable from previous versions will not be able to recognize the parameter (and will have problem with the PRS calculation for sets, see our log for more information)

**Comment by sarasaezALS** [comment]
really helpful information, thanks!
I set up the last version (2.1.11) and I have still problems to run it. the log file says

After reading the covariate file, 30282 sample(s) included 
in the analysis 
 
Error: Not enough memory for permutation 

I set up --mem=480g so I don't understandthe problem.

**Comment by choishingwan** [comment]
It is possible that your system does not have sufficient memory. The memory flag works as follow:

1. PRSice ask for as many memory as the system allows
2. If the available memory is more than the user defined flag, then we will reduce the number of memory we ask for to what the user allows.
3. Otherwise, we will use as much as what the system allows.

What's your full log file looks like? How many covairates and how many gene set are you looking at?

**Comment by sarasaezALS** [comment]
this is the log file:
PRSice 2.1.11 (4 April 2019) 
https://github.com/choishingwan/PRSice
(C) 2016-2017 Shing Wan (Sam) Choi, Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Jack Euesden Cathryn M. Lewis Paul F. O'Reilly (2015)
PRSice: Polygenic Risk Score software.
Bioinformatics 31 (9): 1466-1468

2019-04-25 13:51:16
/data/PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --bar-levels 0.05 \
    --base to_2016.tab \
    --beta  \
    --binary-target T \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov-file LNG_eigenvec \
    --fastscore  \
    --feature exon,gene,protein_coding,CDS \
    --gtf Homo_sapiens.GRCh37.75.gtf \
    --ld /data/LNG/PATHWAYS/workingData \
    --model add \
    --msigdb c2.cp.reactome.v6.2.symbols.gmt.txt \
    --no-full  \
    --out /data/LNG/ALS_saratrialnew/risk.allVariants.noHits.ALS \
    --prevalence 0.00005 \
    --print-snp  \
    --pvalue p \
    --score standard \
    --se se \
    --seed 1028782335 \
    --set-perm 100 \
    --snp SNP \
    --stat b \
    --target ALL_PHENO_SEX_SEVENTY \
    --thread 12


Loading Genotype file: ALL_PHENO_SEX_SEVENTY 
(bed) 
 

30282 people (10754 male(s), 19528 female(s)) observed 
30282 founder(s) included 
 

1781910 ambiguous variant(s) excluded 
9854350 variant(s) included 
 

Processing the GTF file 

A total of 732253 entries removed due to feature selection 

A total of 2096059 genes found in the GTF file 

A total of 674 regions plus the base region are included 

There are a total of 1 phenotype to process 
 

Loading reference panel 
============================== 
 

Loading Genotype file: /data/LNG/workingData 
(bed) 
 

43257 people (15332 male(s), 27925 female(s)) observed 
43257 founder(s) included 
 

9854350 variant(s) remained 
 

Start processing to_2016 
============================== 
 

Base file: to_2016.tab 
8690497 variant(s) observed in base file, with: 
130892 duplicated variant(s) 
4792293 variant(s) excluded due to p-value threshold 
536 ambiguous variant(s) excluded 
3505490 variant(s) not found in target file 
1689 mismatched variant(s) excluded 
261736 total variant(s) included from base file 
 
Warning: Mismatched SNPs detected between base and 
         target!You should check the files are based on the same 
         genome build, or that can just be InDels 
 

Start performing clumping 

1031832 MB RAM detected; reserving 8 MB for clumping 
Allocated 8 MB successfully 
 

Number of variant(s) after clumping : 28845 
 

Phenotype is a binary phenotype 
24629 control(s) 
5653 case(s) 
 

Include Covariates: 
Name	Missing	Number of levels 
PC1	0	- 
PC2	0	- 
PC3	0	- 
PC4	0	- 
PC5	0	- 
PC6	0	- 
PC7	0	- 
PC8	0	- 
PC9	0	- 
PC10	0	- 
PC11	0	- 
PC12	0	- 
PC13	0	- 
PC14	0	- 
PC15	0	- 
PC16	0	- 
PC17	0	- 
PC18	0	- 
PC19	0	- 
PC20	0	- 
 

Processing the covariate file: LNG_eigenvec 
============================== 
 

After reading the covariate file, 30282 sample(s) included 
in the analysis 
 

Error: Not enough memory for permutation

**Comment by choishingwan** [comment]
This is helpful. Bascially, your system seems to run out of memory here. Admittedly, the error message here isn't too helpful. I will try to output how much memory were used and how much more is required in later version. For now, you will have to try and provide more memory to PRSet. If you are working on server, make sure you have submitted with the correct memory request number. It also helps if you use less thread (as the number of memory use will * number of thread use in some place, which leads to higher memory usage). 

A side note: We prefer running PRSet with all SNPs included. Imagine you have a gene set that contains 1000 SNPs, but only 1 SNPs has a p-value less than 0.05. Using a p-value thresholding as in your case will construct a PRS for this set based on the 1 SNP, and will most likely return a significant p-value for both self-contained and competitive p-value. However, this will also make it difficult to interpret the findings. 
We are trying to think of a better way of accounting for signal uncertainty, but for now, it'd be best to simply include all SNPs into your set based PRS analysis.

**Comment by sarasaezALS** [comment]
thanks so much!
about the "A side note: We prefer running PRSet with all SNPs included" you are right, I saw that in the manual.  I selected a p value thresholding of 0.05, but I feel controversial about that. I include another filter after the analysis is done, if the pathways return a small number of SNPS (since a small number of snps can not define a pathway, I removed those pathways.). For now, around a 50% of the gene contain in the pathway have snps with pvalues above 0.05, so I think still cover the genetic representation of the pathway. anyway, I will repeat it without p-value thresholding.
ABOUT the memory, I am surprise, I have always run it with no problems, even in bigger datasets. I will reduce the thread and ask for more memory to my server.

**Comment by choishingwan** [comment]
As long as you are aware of the issue, that'd be fine.

The reason why the memory for `--set-perm` is so high is that for every thread you use, we make an extra copy of the covariance matrix to ensure thread-safety, which leads to higher memory usage. PRSet also inheritly uses more memory as we are storing more information when we run the analysis. Hope this help.

**Comment by NinaRothMota** [comment]
Hi, I'm having the same problem here - running out of memory for permutation in PRSet!
I'm using the latest version (PRSice 2.2.5 (30 July 2019)), I have tried it already in two distinct clusters (LISA and Cartesius, both from SURFsara), with different combinations of queues, partitions, etc... 
Even if I ask for only 100 permutations (--set-perm 100), after clumping and processing, it gives me an error:

After reading the covariate file, 2036 sample(s) included 
in the analysis 
 
Error: Not enough memory left for permutation. User allowed 
       47554 Mb of memory but already used 
       18446744071854370816 Mb


Any thoughts that could help me out?
Thank you in advance!

**Comment by choishingwan** [comment]
At this rate, and with this error message, I am convinced that there are some problem with my memory checking algorithm (integer overflow or something). I will try to disable it for now to avoid any problem. Thanks

**Comment by choishingwan** [comment]
I have now uploaded a binary file under the 2.2.5 release. This should disable the exit clause for memory usage and continue on with the permutation. (but will still output the error message)

**Comment by sarasaezALS** [comment]
related to PRSet, for the competitive pvalue calculation, what it the default background for the set-perm?

**Comment by choishingwan** [comment]
That'd be the genic region as specified in the GTF file. Otherwise, you can use `--background` to specify your background using a bed file or a gene list. (refer to the documentation for the expected format)
