### ISSUE TITLE
No SNP numbers in imputed target files

### ISSUE THREAD

**Issue by fabianCor** [choishingwan/PRSice#105]
When using imputed PLINK files generated by the Michigan Imputation Server, the PLNIK files typically **don't** contain rsID SNP identifiers so that the variant comparison step in PRSice won't find the BASE variants in TARGET file, despite them being ALL present, just by positional identifiers, instead of rsIDs:
84533 variant(s) observed in base file, with: 
84533 variant(s) not found in target file 
0 total variant(s) included from base file

Is there a way to force SNP comparison ONLY through the position, and drop the SNP numbers ?
I tried this: --index \
    --chr 7 --bp 8 --A1 1 --A2 2 --stat 3 --se 4 --pvalue 5\ 
(no column for --snp)
but get the following error:
Error: RS index is not numeric! 
Error: No SNP name column (SNP) in file! 

Thanks in advance

**Comment by choishingwan** [comment]
We always require the SNP ID and we typically don't allow the matching be
done via the coordinates. One way to get around that is to change the SNP
IDs in the target file / base file such that they all becomes chr:bp


Dr Shing Wan Choi
Postdoctoral Fellow
Genetics and Genomic Sciences
Icahn School of Medicine, Mount Sinai, NYC

**Comment by fabianCor** [comment]
Thank you for the suggestion, It worked. I combined the CHR and BD columns (with a":") and added this column to the file and declared it as --snp. Eveverything works now
However I noticed that the top of the BARPLOT figure always gets truncated (more specifically the label gets truncated. Is it difficult to add a little change in your R script involved in the plotting to "extend' the Y axis by 10% ? or turn labels off)

**Comment by choishingwan** [comment]
Did you see any specific warning? Like ggplot2 not being able to install? In most case, the bar plot figure should always show the labels correctly (unless there are something that I didn't take into consideration). Mind showing me the figure?

**Comment by fabianCor** [comment]
No warning regarding ggplot.
I was referring to the text label at the top of the bar plot (which otherwise looks good)

**Comment by choishingwan** [comment]
You mean the p-values??

**Comment by fabianCor** [comment]
yes the diagonal text label with the p-values at the extremity of each bar, sorry that my initial question wasn’t clear.

**Comment by choishingwan** [comment]
I see. That's strange then. If you do have ggplot installed, then
PRSice-2's Rscript will actually reserve around 25% more space just for the
text. Maybe you can try go to plot.bar function and change

scale_y_continuous(limits = c(0, max(output$R2) * 1.25))

to

scale_y_continuous(limits = c(0, max(output$R2) * 1.5))

Will need to figure out a more robust way for hereon.

Thanks for the info

**Comment by fabianCor** [comment]
So I’ve found the following argument to be more consistent
(there is a similar one for expand_limits)
expand = expand_scale(mult = c(0, .25))
I replaced line 1774 :
"scale_y_continuous(limits = c(0, max(output$R2) * 1.25)) +"
with 
"scale_y_continuous(expand = expand_scale(mult = c(0, .25))) +”

actually  0.15 is plenty of extra space already(see below)

**Comment by choishingwan** [comment]
Fantastic! Thank you

**Comment by fabianCor** [comment]
You’re welcome
Thank you for the support! it’s a great tool, you wrote!

best,
Fabian
