### ISSUE TITLE
run out of memory

### ISSUE THREAD

**Issue by sarasaezALS** [choishingwan/PRSice#106]
Dear developer,
thanks for your feedback in my previous issue related to competitive pvalue. Really appreciated.
as you know, I am having problems with the memory since I am running --set-perm 1000;
I requested 480g for my job but the script dies before finish (it generate a .prsise file but never generates a .summary file).
I am trying to allocate very large amounts of memory, but the job memory footprint shows that the program uses < 10 GB before it dies.
I will set up the --memory flag to match the memory I request to my server. I am not sure if this will solve the problem.

**Comment by sarasaezALS** [comment]
even using the memory flag, it didn't work! the same problem

**Comment by choishingwan** [comment]
Hm... do you have the full log file? If the memory flag doesn't solve the problem, then this might be some deeper problem and might require me to go through the code in more details to figure out.

**Comment by sarasaezALS** [comment]
Hi Sam!
so this is the error:

Processing the covariate file: LNG_ALS.eigenvec 
============================== 
 

After reading the covariate file, 30282 sample(s) included 
in the analysis 
 

Processing 0.09%
Start competitive permutation

Error: Not enough memory for permutation 

and this is the log:
/data/LNG/PRSice_linux/PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --bar-levels 1 \
    --base to_2016.tab \
    --beta  \
    --binary-target T \
    --clump-kb 15 \
    --clump-p 1.000000 \
    --clump-r2 1.000000 \
    --cov-file LNG.eigenvec \
    --fastscore  \
    --feature exon,gene,protein_coding,CDS \
    --gtf Homo_sapiens.GRCh37.75.gtf \
    --ld /data/LNG/workingData \
    --memory 480 \
    --model add \
    --msigdb c2.cp.reactome.v6.2.symbols.gmt.txt \
    --out /data/LNG/risk.allVariants.noHits \
    --prevalence 0.00005 \
    --print-snp  \
    --pvalue p \
    --score standard \
    --se se \
    --seed 2832254446 \
    --set-perm 1000 \
    --snp SNP \
    --stat b \
    --target ALL.unrelated_PHENO_SEX_SEVENTY \
    --thread 12


Loading Genotype file: ALL.unrelated_PHENO_SEX_SEVENTY 
(bed) 
 

30282 people (10754 male(s), 19528 female(s)) observed 
30282 founder(s) included 
 

1781910 ambiguous variant(s) excluded 
9854350 variant(s) included 
 

Processing the GTF file 

A total of 732253 entries removed due to feature selection 

A total of 2096059 genes found in the GTF file 

A total of 674 regions plus the base region are included 

There are a total of 1 phenotype to process 
 

Loading reference panel 
============================== 
 

Loading Genotype file: /data/LNG/workingData 
(bed) 
 

43257 people (15332 male(s), 27925 female(s)) observed 
43257 founder(s) included 
 

9854350 variant(s) remained 
 

Start processing to_2016 
============================== 
 

Base file: to_2016.tab 
8690497 variant(s) observed in base file, with: 
130892 duplicated variant(s) 
536 ambiguous variant(s) excluded 
3505490 variant(s) not found in target file 
1689 mismatched variant(s) excluded 
5052426 total variant(s) included from base file 
 
Warning: Mismatched SNPs detected between base and 
         target!You should check the files are based on the same 
         genome build, or that can just be InDels 
 

Start performing clumping 

1031832 MB RAM detected; reserving 7 MB for clumping 
Allocated 7 MB successfully 
 

Number of variant(s) after clumping : 4878711 
 

Phenotype is a binary phenotype 
24629 control(s) 
5653 case(s) 
 

Include Covariates: 
Name	Missing	Number of levels 
PC1	0	- 
PC2	0	- 
PC3	0	- 
PC4	0	- 
PC5	0	- 
PC6	0	- 
PC7	0	- 
PC8	0	- 
PC9	0	- 
PC10	0	- 
PC11	0	- 
PC12	0	- 
PC13	0	- 
PC14	0	- 
PC15	0	- 
PC16	0	- 
PC17	0	- 
PC18	0	- 
PC19	0	- 
PC20	0	- 
 

Processing the covariate file: LNG_eigenvec 
============================== 
 

After reading the covariate file, 30282 sample(s) included 
in the analysis 
 

Error: Not enough memory for permutation

**Comment by sarasaezALS** [comment]
sorry, I meant the log file

**Comment by choishingwan** [comment]
Seems like PRSice has exited normally. The error message is unhelpful, I should've made it clearer. If you don't mind, I have just quickly patched together the following executable. This should give a more detail memory error which allow us to know what's the problem. 


[PRSice.zip](https://github.com/choishingwan/PRSice/files/3128277/PRSice.zip)

**Comment by sarasaezALS** [comment]
Thanks!
it is running. I will let you know when it fails.

**Comment by sarasaezALS** [comment]
Hi Sam,
I have just run the new PRSice you sent me.
this is the error form the log file:

PRSice 2.1.11 (4 April 2019) 

https://github.com/choishingwan/PRSice
(C) 2016-2017 Shing Wan (Sam) Choi, Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Jack Euesden Cathryn M. Lewis Paul F. O'Reilly (2015)
PRSice: Polygenic Risk Score software.
Bioinformatics 31 (9): 1466-1468

2019-04-29 15:00:54
/data/LNG/PRSice_linux/PRSice_linux-3 \
    --A1 A1 \
    --A2 A2 \
    --bar-levels 1 \
    --base to_2016.tab \
    --beta  \
    --binary-target T \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov-file LNG_eigenvec \
    --fastscore  \
    --feature exon,gene,protein_coding,CDS \
    --gtf Homo_sapiens.GRCh37.75.gtf \
    --ld /data/LNG/workingData \
    --model add \
    --msigdb c2.cp.reactome.v6.2.symbols.gmt.txt \
    --out /data/LNG/newprsise/risk.allVariants.noHits.\
    --prevalence 0.00005 \
    --pvalue p \
    --score standard \
    --se se \
    --seed 935159265 \
    --set-perm 1000 \
    --snp SNP \
    --stat b \
    --target ALL.unrelated_PHENO_SEX_SEVENTY \
    --thread 12


Loading Genotype file: ALL.unrelated_PHENO_SEX_SEVENTY 
(bed) 
 

30282 people (10754 male(s), 19528 female(s)) observed 
30282 founder(s) included 
 

1781910 ambiguous variant(s) excluded 
9854350 variant(s) included 
 

Processing the GTF file 

A total of 732253 entries removed due to feature selection 

A total of 2096059 genes found in the GTF file 

A total of 674 regions plus the base region are included 

There are a total of 1 phenotype to process 
 

Loading reference panel 
============================== 
 

Loading Genotype file: /data/LNG/workingData 
(bed) 
 

43257 people (15332 male(s), 27925 female(s)) observed 
43257 founder(s) included 
 

9854350 variant(s) remained 
 

Start processing to_2016 
============================== 
 

Base file: to_2016.tab 
8690497 variant(s) observed in base file, with: 
130892 duplicated variant(s) 
536 ambiguous variant(s) excluded 
3505490 variant(s) not found in target file 
1689 mismatched variant(s) excluded 
5052426 total variant(s) included from base file 
 
Warning: Mismatched SNPs detected between base and 
         target!You should check the files are based on the same 
         genome build, or that can just be InDels 
 

Start performing clumping 

1547809 MB RAM detected; reserving 50 MB for clumping 
Allocated 50 MB successfully 
 

Number of variant(s) after clumping : 227851 
 

Phenotype is a binary phenotype 
24629 control(s) 
5653 case(s) 
 

Include Covariates: 
Name	Missing	Number of levels 
PC1	0	- 
PC2	0	- 
PC3	0	- 
PC4	0	- 
PC5	0	- 
PC6	0	- 
PC7	0	- 
PC8	0	- 
PC9	0	- 
PC10	0	- 
PC11	0	- 
PC12	0	- 
PC13	0	- 
PC14	0	- 
PC15	0	- 
PC16	0	- 
PC17	0	- 
PC18	0	- 
PC19	0	- 
PC20	0	- 
 

Processing the covariate file: LNG_eigenvec 
============================== 
 

After reading the covariate file, 30282 sample(s) included 
in the analysis 
 

Error: Not enough memory for permutation

**Comment by sarasaezALS** [comment]
Just FYI, when I run the same script using --perm, instead --set-perm, works perfectly

**Comment by choishingwan** [comment]
Strange. My fix didn;t seems to be applied... Let me double check.

--perm runs permutation analysis which gives us the empirical p-value. Due
to the type of permutation we perform, it requires significantly less
memory. That might be the reason why --perm works for you but not --set-perm
