### ISSUE TITLE
SNPs from each pathway

### ISSUE THREAD

**Issue by sarasaezALS** [choishingwan/PRSice#108]
Hi again,
thanks so much for your help. I am using the new version now and I have realize I didn't get a file .snps per each pathways (as I used to get with the older version). How can I recover rsID snp per each pathways?

**Comment by choishingwan** [comment]
Did you use --print-snp?

It should generate one single file which contains the information of each
pathway, wtih Y indicate that the SNP is included in the pathway and N
indicate that the SNP is not

**Comment by sarasaezALS** [comment]
ok,
I used it and I got the file.snp. But I think something is missing from the file. This is how it looks like (just a few columns with N)

REACTOME_TRAF6_MEDIATED_INDUCTION_OF_TAK1_COMPLEX	REACTOME_RIG_I_MDA5_MEDIATED_INDUCTION_OF_IFN_ALPHA_BETA_PATHWAYS	REACTOME_IKK_COMPLEX_RECRUITMENT_MEDIATED_BY_RIP1	REACTOME_LIGAND_GATED_ION_CHANNEL_TRANSPORT	REACTOME_FORMATION_OF_INCISION_COMPLEX_IN_GG_NER	REACTOME_TRANSCRIPTIONAL_REGULATION_OF_WHITE_ADIPOCYTE_DIFFERENTIATION	REACTOME_ENDOSOMAL_SORTING_COMPLEX_REQUIRED_FOR_TRANSPORT_ESCRT	REACTOME_MEIOTIC_RECOMBINATION	REACTOME_IL_2_SIGNALING	REACTOME_IL_6_SIGNALING	REACTOME_PLATELET_AGGREGATION_PLUG_FORMATION	REACTOME_SIGNALING_BY_NOTCH	REACTOME_LAGGING_STRAND_SYNTHESIS	REACTOME_INTRINSIC_PATHWAY	REACTOME_INHIBITION_OF_REPLICATION_INITIATION_OF_DAMAGED_DNA_BY_RB1_E2FREACTOME_ETHANOL_OXIDATION	REACTOME_SYNTHESIS_OF_VERY_LONG_CHAIN_FATTY_ACYL_COAS	REACTOME_DNA_REPLICATION	REACTOME_CLEAVAGE_OF_GROWING_TRANSCRIPT_IN_THE_TERMINATION_REGION_	REACTOME_PKB_MEDIATED_EVENTS	REACTOME_E2F_MEDIATED_REGULATION_OF_DNA_REPLICATION	REACTOME_METABOLISM_OF_CARBOHYDRATES	REACTOME_HORMONE_SENSITIVE_LIPASE_HSL_MEDIATED_TRIACYLGLYCEROL_HYDROLYSIS	REACTOME_SIGNALING_BY_INSULIN_RECEPTOR	REACTOME_SIGNAL_ATTENUATION	REACTOME_PURINE_METABOLISM	REACTOME_SOS_MEDIATED_SIGNALLING	REACTOME_RNA_POL_III_TRANSCRIPTION_INITIATION_FROM_TYPE_3_PROMOTER	REACTOME_APOPTOSIS	REACTOME_LIPID_DIGESTION_MOBILIZATION_AND_TRANSPORT	REACTOME_HEMOSTASIS	REACTOME_INFLUENZA_LIFE_CYCLE	REACTOME_INFLUENZA_VIRAL_RNA_TRANSCRIPTION_AND_REPLICATION	REACTOME_NEP_NS2_INTERACTS_WITH_THE_CELLULAR_EXPORT_MACHINERY	REACTOME_HIV_INFECTION	REACTOME_TRANSPORT_OF_RIBONUCLEOPROTEINS_INTO_THE_HOST_NUCLEUS	REACTOME_HIV_LIFE_CYCLE	REACTOME_ABORTIVE_ELONGATION_OF_HIV1_TRANSCRIPT_IN_THE_ABSENCE_OF_TAT	REACTOME_EARLY_PHASE_OF_HIV_LIFE_CYCLE	REACTOME_HOST_INTERACTIONS_OF_HIV_FACTORS	REACTOME_RNA_POL_III_TRANSCRIPTION_TERMINATION	REACTOME_RESPIRATORY_ELECTRON_TRANSPORT_ATP_SYNTHESIS_BY_CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS_	REACTOME_FORMATION_OF_THE_HIV1_EARLY_ELONGATION_COMPLEX	REACTOME_RAF_MAP_KINASE_CASCADE	REACTOME_VIRAL_MESSENGER_RNA_SYNTHESIS	REACTOME_LATE_PHASE_OF_HIV_LIFE_CYCLE	REACTOME_SHC_MEDIATED_SIGNALLING	REACTOME_INTERACTIONS_OF_VPR_WITH_HOST_CELLULAR_PROTEINS	REACTOME_FORMATION_OF_ATP_BY_CHEMIOSMOTIC_COUPLING	REACTOME_APC_C_CDH1_MEDIATED_DEGRADATION_OF_CDC20_AND_OTHER_APC_C_CDH1_TARGETED_PROTEINS_IN_LATE_MITOSIS_EARLY_G1	REACTOME_ACTIVATION_OF_ATR_IN_RESPONSE_TO_REPLICATION_STRESS	REACTOME_UNWINDING_OF_DNA	REACTOME_APC_C_CDC20_MEDIATED_DEGRADATION_OF_MITOTIC_PROTEINS	REACTOME_GLUCURONIDATION	REACTOME_AUTODEGRADATION_OF_CDH1_BY_CDH1_APC_C	REACTOME_MYD88_MAL_CASCADE_INITIATED_ON_PLASMA_MEMBRANE	REACTOME_INNATE_IMMUNE_SYSTEM	REACTOME_REGULATION_OF_GLUCOKINASE_BY_GLUCOKINASE_REGULATORY_PROTEIN	REACTOME_MITOTIC_PROMETAPHASE	REACTOME_APC_C_CDC20_MEDIATED_DEGRADATION_OF_CYCLIN_B	REACTOME_SCF_BETA_TRCP_MEDIATED_DEGRADATION_OF_EMI1	REACTOME_LIPOPROTEIN_METABOLISM	REACTOME_G1_S_SPECIFIC_TRANSCRIPTION	REACTOME_THE_ROLE_OF_NEF_IN_HIV1_REPLICATION_AND_DISEASE_PATHOGENESIS	REACTOME_CHYLOMICRON_MEDIATED_LIPID_TRANSPORT	REACTOME_SIGNALING_BY_TGF_BETA_RECEPTOR_COMPLEXREACTOME_CONVERSION_FROM_APC_C_CDC20_TO_APC_C_CDH1_IN_LATE_ANAPHASE	REACTOME_ACTIVATED_TLR4_SIGNALLING	REACTOME_IMMUNE_SYSTEM	REACTOME_BINDING_AND_ENTRY_OF_HIV_VIRION	REACTOME_PHOSPHORYLATION_OF_THE_APC_C	REACTOME_CYTOSOLIC_SULFONATION_OF_SMALL_MOLECULES	REACTOME_INTEGRATION_OF_PROVIRUS	REACTOME_GLUTATHIONE_CONJUGATION	REACTOME_COMPLEMENT_CASCADE	REACTOME_PHASE_II_CONJUGATION	REACTOME_MTORC1_MEDIATED_SIGNALLING	REACTOME_TOLL_RECEPTOR_CASCADES	REACTOME_ACTIVATION_OF_BH3_ONLY_PROTEINS	REACTOME_GLUCOSE_METABOLISM	REACTOME_RNA_POL_III_CHAIN_ELONGATION	REACTOME_VOLTAGE_GATED_POTASSIUM_CHANNELS	REACTOME_ADAPTIVE_IMMUNE_SYSTEM	REACTOME_NOD1_2_SIGNALING_PATHWAY	REACTOME_CYTOKINE_SIGNALING_IN_IMMUNE_SYSTEM	REACTOME_MEIOTIC_SYNAPSIS	REACTOME_ANTIGEN_PRESENTATION_FOLDING_ASSEMBLY_AND_PEPTIDE_LOADING_OF_CLASS_I_MHC	REACTOME_THE_NLRP3_INFLAMMASOME	REACTOME_CLASS_I_MHC_MEDIATED_ANTIGEN_PROCESSING_PRESENTATION	REACTOME_NONSENSE_MEDIATED_DECAY_ENHANCED_BY_THE_EXON_JUNCTION_COMPLEX	REACTOME_PIP3_ACTIVATES_AKT_SIGNALING	REACTOME_ANTIGEN_PROCESSING_UBIQUITINATION_PROTEASOME_DEGRADATION	REACTOME_TANDEM_PORE_DOMAIN_POTASSIUM_CHANNELS	REACTOME_INFLAMMASOMES	REACTOME_POTASSIUM_CHANNELS	REACTOME_NUCLEOTIDE_BINDING_DOMAIN_LEUCINE_RICH_REPEAT_CONTAINING_RECEPTOR_NLR_SIGNALING_PATHWAYS	REACTOME_INWARDLY_RECTIFYING_K_CHANNELS	REACTOME_AMYLOIDS	REACTOME_PACKAGING_OF_TELOMERE_ENDS	REACTOME_TELOMERE_MAINTENANCE	REACTOME_PLATELET_ACTIVATION_SIGNALING_AND_AGGREGATION	REACTOME_REMOVAL_OF_THE_FLAP_INTERMEDIATE_FROM_THE_C_STRAND	REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS	REACTOME_APC_CDC20_MEDIATED_DEGRADATION_OF_NEK2A	REACTOME_INITIAL_TRIGGERING_OF_COMPLEMENT	REACTOME_EXTENSION_OF_TELOMERES	REACTOME_G2_M_CHECKPOINTS	REACTOME_G2_M_DNA_DAMAGE_CHECKPOINT	REACTOME_S_PHASE	REACTOME_SCFSKP2_MEDIATED_DEGRADATION_OF_P27_P21	REACTOME_TRYPTOPHAN_CATABOLISM	REACTOME_DNA_STRAND_ELONGATION	REACTOME_RESOLUTION_OF_AP_SITES_VIA_THE_SINGLE_NUCLEOTIDE_REPLACEMENT_PATHWAY	REACTOME_FGFR_LIGAND_BINDING_AND_ACTIVATION	REACTOME_CHOLESTEROL_BIOSYNTHESIS	REACTOME_APOBEC3G_MEDIATED_RESISTANCE_TO_HIV1_INFECTION	REACTOME_GAP_JUNCTION_TRAFFICKING	REACTOME_FGFR2C_LIGAND_BINDING_AND_ACTIVATION	REACTOME_METABOLISM_OF_PORPHYRINS	REACTOME_FGFR4_LIGAND_BINDING_AND_ACTIVATION	REACTOME_VIF_MEDIATED_DEGRADATION_OF_APOBEC3G	REACTOME_SIGNALING_BY_FGFR	REACTOME_DIGESTION_OF_DIETARY_CARBOHYDRATE	REACTOME_FGFR1_LIGAND_BINDING_AND_ACTIVATION	REACTOME_GAP_JUNCTION_ASSEMBLY	REACTOME_SYNTHESIS_OF_GLYCOSYLPHOSPHATIDYLINOSITOL_GPI	REACTOME_RNA_POL_I_TRANSCRIPTION_INITIATION	REACTOME_PYRIMIDINE_METABOLISM	REACTOME_INTRINSIC_PATHWAY_FOR_APOPTOSIS	REACTOME_PI3K_CASCADE	REACTOME_APOPTOTIC_EXECUTION_PHASE	REACTOME_SHC_RELATED_EVENTS
1	rs3094315	752566	0.3615	Y	N	N	N	N	N
1	rs11240777	798959	0.1832	Y	N	N	N	N	N
1	rs117086422	845635	0.7913	Y	N	N	N	N	N
1	rs57760052	845938	0.4934	Y	N	N	N	N	N
1	rs28612348	846078	0.763	Y	N	N	N	N	N
1	rs58781670	846398	0.7677	Y	N	N	N	N	N
1	rs60454217	846465	0.1473	Y	N	N	N	N	N
1	rs79396034	846543	0.2057	Y	N	N	N	N	N
1	rs4475691	846808	0.855	Y	N	N	N	N	N

**Comment by choishingwan** [comment]
Ok, this is definitely a bug then. I am currently test running the latest
version. Will let you know once that's ready. Should solve most of the
problems that you've encountered so far (I hope).

**Comment by sarasaezALS** [comment]
Great!
I was using an older version and I never had any other problem with it. For publication quality I just wanted to do it with the last version.

**Comment by choishingwan** [comment]
Btw, this problem should've been fixed on v2.2.0
