### ISSUE TITLE
--maf

### ISSUE THREAD

**Issue by sarasaezALS** [choishingwan/PRSice#109]
Good morning!
I am using the flag --maf to exclude variants with low allele frequency from my target file. Should I do the same in the base file?

**Comment by choishingwan** [comment]
That depends on what you want. Generally it is a good idea to filter out SNPs with low frequency to avoid false positives and genotyping error.

**Comment by sarasaezALS** [comment]
I agree. the thing is: if I only filter out SNPs in my target file but my summary stats is not filter, will MY PREDICTION model worst?

**Comment by choishingwan** [comment]
It's all a matter of data quality. If you summary stat data is of high quality and have sufficiently high sample size to provide for good estimate for SNPs with low MAF, then it is ok for you to retain the SNPs in the base.

**Comment by sarasaezALS** [comment]
I see. Thanks for your input!
