### ISSUE TITLE
--beta T does not specify BETA column

### ISSUE THREAD

**Issue by JoniColeman** [choishingwan/PRSice#11]
Hi Sam,

When I specified **--beta T** below, PRSice failed with _WARNING: OR detected but user suggest the input is beta!_ .

The log file shows PRSice is still looking for a column entitled "OR":

_User Defined Column Headers_
_==============================_
_Chr            : CHR_
_SNP            : SNP_
_BP             : BP_
_Ref Allele     : A1_
_Alt Allele     : A2_
_Statistic      : OR_
_Standard Error : SE_
_P-value        : P_

This appears to be resolved by specifying **--stat BETA**

Can 

1. **--stat BETA** be automatically set when **--beta T** is set, or 

2. can the user be prompted to add **--stat BETA** when using **--beta T** ?

Cheers

**Comment by choishingwan** [comment]
Actually, this was a bug. Original design was to follow what Joni suggested yet as one variable was not declared, the function was not functioning. 
This is now fixed.
