### ISSUE TITLE
Redundant stuff in option parser

### ISSUE THREAD

**Issue by nievergeltlab** [choishingwan/PRSice#112]
I get this warning when I try to run PRSice v2.2.0, downloaded from https://choishingwan.github.io/PRSice/

Error in parse_args(OptionParser(option_list = option_list)) :
  Error in getopt(spec = spec, opt = args) :
  redundant short names for flags (column 2 of spec matrix).
 did you forget to set ``add_help_option=FALSE`` in ``OptionParser``

This seems to be due to the option parser having redundant entries. See lines 470/471 

 make_option(c("-f", "--pheno-file"), type = "character", dest = "pheno_file"),
  make_option(c("-f", "--pheno"), type = "character", dest = "pheno_file"),

and 500/501
  make_option(c("-C", "--cov-file"), type = "character", dest = "cov_file"),
  make_option(c("-C", "--cov"), type = "character", dest = "cov_file"),

It doesn't like that the shortcut commands -f and -C repeat over different options. Suggest changing the shortcut.

thanks

**Comment by choishingwan** [comment]
Yes, I have already changed it in 2.2.1. Will be updating soom. You just
need to remove -f and -C from pheno-file and cov-file respectively.

Sam

**Comment by choishingwan** [comment]
This is fixed in 2.2.1
