### ISSUE TITLE
Filtering on "--base-maf" error

### ISSUE THREAD

**Issue by Genutty** [choishingwan/PRSice#113]
It the documentation for base file, it states to use the "--base-maf" to filter on maf in the base file; however, this returns the error “long flag "base-maf" is invalid”. However, if I flip to "--maf-base", which is reccomended in the step-by-step documentation, it seems to be working. Is this the correct way of specifying an maf threshold in the base file?

**Comment by choishingwan** [comment]
Which version are you using? We have updated both the parameters and the
document for 2.2.0 (as this is a major release). For version before 2.2.0,
the correct parameter are indeed --maf-base and --info-base. We changed
that in v2.2.0 to make it more consistent with the --<File>-<Parameter>
scheme we use

Dr Shing Wan Choi
Postdoctoral Fellow
Genetics and Genomic Sciences
Icahn School of Medicine, Mount Sinai, NYC

**Comment by Genutty** [comment]
Great, thank you for the confirmation.
