### ISSUE TITLE
PRSice on windows 10 - how to make it work

### ISSUE THREAD

**Issue by PsychSilvia** [choishingwan/PRSice#114]
Hi all,

I am new to PRSice and PRS analysis and I am actually a bit stuck. 

At the moment I am trying to follow the guide book and use the content of the PRSice zipped file, downloadable from the website, just to learn how to use this software on windows 10.

So I have created a PRSice folder with the unzipped content of the PRSice file and my R.exe program. Using command prompt on windows, I am able to access R and install and load all the packages required by PRSice. However when I try to move to PRSice using the code outlined in the guide book (see below) I receive an error saying "Fatal error: cannot open file "./PRSice_v1.25.R": No such file or directory.  

```
R --file=PRSice_v1.25.R -q --args \
plink ./plink_1.9_mac_160914 \
base TOY_BASE_GWAS.assoc \
target TOY_TARGET_DATA \
slower 0 \
sinc 0.01 \
supper 0.5
```

I thought that this could be due to a couple of things:
1) On the website, it says that window users should use Rscript.exe instead of Rscript. However it is not clear what it's referring to as I don't have files with such names. There's Rscript.exe alongside R.exe when you install R but this doesn't seem to be accessible using command prompt.
2) the unzipped PRSice file downloaded from the software doesn't have a file named "PRSice_v1.25.R", but even renaming it into "PRSice_win64.exe" doesn't work. 

I was wondering if you have any suggestions on how to make it work.
Thank you in advance.

Silvia

**Comment by choishingwan** [comment]
Seems like you are using PRSice 1.25. Maybe try out PRSice 2? The user manual can be found here https://choishingwan.github.io/PRSice/

**Comment by choishingwan** [comment]
Also, if you are downloading form this github repository, then the version you downloaded is PRSice-2. And the manul for that is in the link above

**Comment by PsychSilvia** [comment]
Thank you so much for your response. You were right, it was as simple as that.. now it works perfectly and the link has been really useful to adjust my code.
