### ISSUE TITLE
Error in version PRSice 2.2.0 (13 May 2019) with --ld option

### ISSUE THREAD

**Issue by eshaikho** [choishingwan/PRSice#115]
Hi Sam,
The following command works fine with PRSice PRSice 2.1.9 (25 Feburary 2019), while it returns and error with PRSice 2.2.0 (13 May 2019).
The error is: Calculating allele frequencies: 3.02%Error: Cannot read the bed file(read):
targetFile.bed. Can you please tell me how to resolve this issue?
2019-06-05 16:15:21
./PRSice_linux \
    --A1 Allele1 \
    --A2 Allele2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base baseFile \
    --beta  \
    --binary-target T \
    --clump-kb 1000 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --extract test_uc_std.valid \
    --interval 5e-05 \
    --ld 1k_eu_plink_files/EUR \
    --lower 5e-08 \
    --missing MEAN_IMPUTE \
    --model add \
    --out test_uc_std \
    --pheno-col response \
    --pheno-file phenoFile \
    --pvalue P.value \
    --score std \
    --seed 1395400955 \
    --snp RSID \
    --stat Effect \
    --target targetFile \
    --thread 1 \
    --upper 0.5

**Comment by choishingwan** [comment]
can you check if your file is corrupted? As the error occurs after 3% of
the read has been read, and you are not using a multiple chromosome input,
it is likely that PRSice failed to access the file either because of file
lock or corrupted file. Can you try again? Or maybe try 2.2.1, where I
slightly change the order of file read.

**Comment by eshaikho** [comment]
Hi Sam,
Thank you very much for the prompt response.
The file was not corrupted and I was not using multiple chromosomes. The order was the issue between the two version. 2.2.1 is working just fine.

Thank you very much for your time and consideration.
All the best in your science endeavors.


Best,
Elmutaz
