### ISSUE TITLE
Errors in plotting

### ISSUE THREAD

**Issue by michellekee** [choishingwan/PRSice#116]
Hi, 

I've received an error while PRSice was trying to plot the bar graphs.

> Begin plotting
Current Rscript version = 2.2.0
Warning messages:
1: In as.numeric(as.character(covariance.base[, i])) :
  NAs introduced by coercion
2: In as.numeric(as.character(covariance.base[, i])) :
  NAs introduced by coercion
Plotting Bar Plot
Error in expand_scale(mult = c(0, 0.15)) : 
  could not find function "expand_scale"
Calls: process_plot ... plot.bar -> scale_y_continuous -> continuous_scale -> ggproto
Execution halted

My commands are as follows:
`Rscript PRSice.R --dir . \
--prsice ./PRSice \
--base /home/michelle/GWAS_NEUR_full.txt \
--target plink_binaryFile \
--thread 8 \
--stat BETA \
--beta \
--binary-target F \
 --snp MarkerName --chr CHR --bp POS --A1 A1 --A2 A2 --stat Beta --pvalue Pval \
--clump-p 1 --clump-kb 500 --clump-r2 0.2 \
--pheno NEUR.pheno \
--cov NEUR.cov \
--cov-col PC1,PC2 \
--all-score  \
 --out output_$(date +%y%m%d)`

Please advise.

Thank you so much!

Cheers,
Michelle

**Comment by choishingwan** [comment]
Hi, it seems like you have an old version of ggplot2 installed. Could you please check? expand_scale should be part of the ggplot2 package

**Comment by choishingwan** [comment]
Just in case, you can add 
```

expand_scale = function(mult = 0, add = 0) {
  stopifnot(is.numeric(mult) && is.numeric(add))
  stopifnot((length(mult) %in% 1:2) && (length(add) %in% 1:2))

  mult <- rep(mult, length.out = 2)
  add <- rep(add, length.out = 2)
  c(mult[1], add[1], mult[2], add[2])
}
```

Somewhere in PRSice.R (maybe below Helper functions) to enable the function.
