### ISSUE TITLE
List of SNPs included in best risk score

### ISSUE THREAD

**Issue by bechelsie** [choishingwan/PRSice#117]
Hi there,
I'm trying to get a list of all of the variants that went into the best fitting risk score. I do not see a column in any of the output files that would include this information. 
When we try to recreate the results just using plink (rather than PRSice), we get a similar, but different number of SNPs. 
Thanks,
Chelsie

**Comment by choishingwan** [comment]
If you are using PRSice-2, you can use the `--print-snp` option to print out all the post clumping SNPs, of which you can then filter them according to their p-values. 

If you are using PRSice-1.25, this is a known bug that the number of SNPs reported is different to the number of SNPs actually used in the model (PRSice-1.25 use an exclusive end, e.g p-threshold of 0.5 will exclude SNPs with p-value exactly at 0.5, whereas PRSice-2 and PLINK both use an inclusive end, e.g. SNPs with p-value of 0.5 will be included in the threshold of 0.5)

As I am not sure how you use PLINK, one possible reason for the difference in number of SNPs might be with the flipping and ambiguous SNPs removal, which I don't think PLINK will do automatically.

**Comment by bechelsie** [comment]
Thanks for the quick reply. The --print-snp flag worked!
