### ISSUE TITLE
missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by jystatistics** [choishingwan/PRSice#121]
Hi,

Thank you for creating this files. Recently, I tried to calculate poly generic risk score for my target data set. I received the error message as shown below. 

Error in if (levels(as.factor(prof$PHENO))[1] == "1" & levels(as.factor(prof$PHENO))[2] ==  :
  missing value where TRUE/FALSE needed
Execution halted

I know that this issue has been updated in this link, [https://www.biostars.org/p/206740/]. I tired with the dummy phenotype files. However, I received this error message. 

Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  line 3 did not have 25 elements
Calls: read.table -> scan
Execution halted

Here is my command to run the file. 

 R --file=PRSice_v1.25.R -q --args \
plink PRSice_v1.25/plink_1.9_linux_160914\
base SNP_63_Summary.assoc \ 
target total-updated \ 
slower 0 \ 
sinc 0.01 \ 
supper 0.5 \ 
report.best.score.only F \
no.regression T \
report.individual.scores T \
covary F \
pheno-col randomphenotypes.txt

Thank you for your help!

**Comment by choishingwan** [comment]
Hi there, could you please use PRSice-2 instead? It should provide a more comprehensive error message and should inform you of the problem.

**Comment by jystatistics** [comment]
Hi,

I downloaded PRSice-2 (Unix) in my server and tried to install package. But I have the error message as below. Could you help on this?

Rscript PRSice.R --dir /data1/home/jungj7/00_Pipeline/08_GRS/PRSice
Error: Cannot run PRSice without the PRSice binary file

Thank you.

**Comment by choishingwan** [comment]
Unfortunately, our manual page is currently offline (we are trying to do a
domain transfer)

You will need to do


Rscript PRSice.R --dir /data1/home/jungj7/00_Pipeline/08_GRS/PRSice
--prsice PRSice_linux --base XXXX --target XXX

For PRSice to run

**Comment by jystatistics** [comment]
Thank you for your comment. Now PRSice is working. I have another question about the phenotype file. 

Here is the output of my command in PRSice. 


./PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base SNP_63_Summary.assoc \
    --beta  \
    --binary-target T \
    --bp BP \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --ignore-fid  \
    --interval 5e-05 \
    --lower 5e-08 \
    --missing MEAN_IMPUTE \
    --model add \
    --out PRSice \
    --pheno-col IID,age,gender,race,height,weight,exercise_yesno,exercise_times_weekly,exercise_type,smoke_yesno,smoke_num_of_packs_per_day,smoke_highest_num_packs_per_day,smoke_start_age,smoke_quit_age,alcohol_yesno,alcohol_drinks_per_week,hip_total_bmd,spine_total_bmd \
    --pheno-file phenotypes.txt \
    --pvalue P \
    --score avg \
    --seed 87202878 \
    --snp SNP \
    --stat BETA \
    --target total-updated-chr# \
    --thread 1 \
    --upper 0.5


Error: Number of target phenotypes doesn't match
       information of binary target! You must indicate
       whether the phenotype is binary using
       --binary-target


Error:
Execution halted

I entered the column name of my phenotype files in the option of --pheno-col and --binary-target T. 

How can I solve this error message?

Thank you.

**Comment by choishingwan** [comment]
Could you please try and read our manual page (it is now live).

It seems like you are trying to use all the columns in your phenotype file (including the IID) as a phenotype of interest which seems weird to me. Are you trying to include some of those as  a covariate instead? If so, you need to also use `--cov` to include the covariate file and `--cov-col` to indicate the covariates (did you also missed the PCs?). 

Your error occurs because `--binary-target` must be stated for each and every single one of your phenotype so that we can tell whether to use linear or logistic regression for the analysis.

**Comment by jystatistics** [comment]
Thank you for your answer.
I figured out the problem of phenotype with --binary-target F.

I have another question for you with --cov. 

I'm kind of new to PRSice. How can I create PCs? Do I need to use plink?
Also when I run the --cov with other command, I have the error message of 

Error: Malformed covariate file, should have at least 18
       columns
Is it due to the missing of PCs?

Thank you for your help.

**Comment by choishingwan** [comment]
You'll need to use plink to generate PCs (or if you have large sample size,
flashPCA)

I'd suggest you look up how to calculate PCs as you will need to do some
additional pre-processing before you can calculate PCs

When you have the malformed error, it suggestt that your file isn't well
formed. Likely in one of your row, you have less than expected number of
columns

Dr Shing Wan Choi
Postdoctoral Fellow
Genetics and Genomic Sciences
Icahn School of Medicine, Mount Sinai, NYC

**Comment by jystatistics** [comment]
Hi Sam,

I was able to run the cov file after adding PCs and removing the columns where contains the missing values. 

I have another question about the interpretation of PRSice.best file and PRSice.all.score file. 

Here is my command and result. 

./PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --all-score  \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base BMD_v3_SumStats.assoc \
    --beta  \
    --binary-target F \
    --bp BP \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov-file phenotypes.txt \
    --extract PRSice.valid \
    --ignore-fid  \
    --interval 5e-05 \
    --lower 5e-08 \
    --missing MEAN_IMPUTE \
    --model add \
    --out PRSice \
    --pheno-file pheno.txt \
    --pvalue P \
    --score sum \
    --seed 1497645643 \
    --snp SNP \
    --stat BETA \
    --target chr#-markers \
    --thread 1 \
    --upper 0.5


Initializing Genotype file: chr#-markers (bed)


Start processing BMD_v3_SumStats
==================================================

Reading 100.00%
Base file: BMD_v3_SumStats.assoc
20259826 variant(s) observed in base file, with:
34353 duplicated variant(s)
2836093 ambiguous variant(s) excluded
781134 variant(s) located on haploid chromosome
16719443 total variant(s) included from base file



Loading Genotype info from target
==================================================

1209 people (0 male(s), 0 female(s)) observed
1209 founder(s) included

SNP extraction/exclusion list contains 5 columns, will
assume first column contains the SNP ID

519 variant(s) included


Start processing gene set information
==================================================

1 region included

Check Phenotype file: pheno.txt
Column Name of Sample ID: IID
Note: If the phenotype file does not contain a header, the
column name will be displayed as the Sample ID which is ok.
Phenotype Name: hip_total_bmd
There are a total of 1 phenotype to process


Start performing clumping

1031771 MB RAM detected; reserving 1 MB for clumping
Allocated 1 MB successfully

Clumping Progress: 100.00%

Number of variant(s) after clumping : 504

Processing the 1 th phenotype
Phenotype is a continuous phenotype
1209 sample(s) with valid phenotype


Include Covariates:
Name    Missing Number of levels
age     0       -
height  0       -
weight  0       -
PC1     0       -
PC2     0       -
PC3     0       -
PC4     0       -
PC5     0       -
PC6     0       -
PC7     0       -
PC8     0       -
PC9     0       -
PC10    0       -
PC11    0       -
PC12    0       -
PC13    0       -
PC14    0       -
PC15    0       -
PC16    0       -
PC17    0       -
PC18    0       -
PC19    0       -
PC20    0       -


Processing the covariate file: phenotypes.txt
==============================


After reading the covariate file, 1209 sample(s) included
in the analysis


Preparing Output Files

Start Processing
Processing 100.00%
There are 1 region(s) with p-value less than 1e-5. Please
note that these results are inflated due to the overfitting
inherent in finding the best-fit PRS (but it's still best
to find the best-fit PRS!).
You can use the --perm option (see manual) to calculate an
empirical P-value.

In my PRSice.best file, I have the number of, 

FID IID In_Regression PRS
709306 709306 Yes -0.5317481                         
709475 709475 Yes -0.0992664                         
709813 709813 Yes -0.1587764                         
709982 709982 Yes 0.2521247                          
710996 710996 Yes -0.468141                          
712179 712179 Yes 0.1394513                          
712517 712517 Yes -0.8393767                         
713362 713362 Yes -0.4988563                         
713531 713531 Yes -0.5875991                         
713700 713700 Yes -0.2949167                         
713869 713869 Yes -0.1976322 

And in the output of PRSice.all.score, I have the number of,

![1](https://user-images.githubusercontent.com/39386861/61008414-3ed7f000-a324-11e9-80f7-1b489720d7af.PNG)

My questions are

1) I entered three columns (including the first column of IID) to run the phenotype. However, only my second column after IID, run through this. So, when PRSice.best score is calculated, how is it calculated?

2) And also I tried to calculate all PRS score for each covariate column in PRSice.all.score. However, the PRS is not same with PRSice.best for the phenotype column. I was wondering, why the PRS is different?

3) I'm seeing that there is missing phenotype column in the PRSice.summary file. Why the phenotype column is missing? And there is a coefficient for this model. Is coefficient for which covariate? Is it for PRS?

![1](https://user-images.githubusercontent.com/39386861/61008903-bf4b2080-a325-11e9-9ce4-f50453a1139a.PNG)

Thank you again for your help.

**Comment by choishingwan** [comment]
1. As you didn't provide the --pheno-col information, we will use the third
column of your phenotype file (or second, if --ignore-fid is set).
3. Similarly, we don't write out the phenotype name to the summary file as
there's only one phenotype

2. I am not sure what you are trying to do. Calculated PRS should be
unaffected by the covariate used (it's just genotype * effect size)

**Comment by segunfatumo** [comment]
Hi,
I have used PRSice successfully in the past week (PRSice 231e) on mac. Now PRSice is complaining of phenotype file. I created the phenotype file the same as other traits which ran successfully. 
My phenotype file has 3 columns but PRSice seems to be seeing only 2 columns. Please see the error message and the header of my phenotype file below. Thanks

Clumping Progress: 100.00%
Number of variant(s) after clumping : 2824046 

Processing the 1 th phenotype 

Malformed pheno file, should contain at least 3 columns. 2 
observed. Have you use the --ignore-fid option? 

Error: 
Execution halted


Seguns-MBP:Uganda segunfatumo$ head withHeader_ordered_UgandaRawphenoDBP.txt
FID	IID 	 Pheno
APP5117317 APP5117317 51
APP5117318 APP5117318 70.5
APP5117319 APP5117319 76.5
APP5117321 APP5117321 67
APP5117322 APP5117322 92
APP5117327 APP5117327 69
APP5117332 APP5117332 86
APP5117333 APP5117333 84
APP5117337 APP5117337 82

**Comment by choishingwan** [comment]
Mind sending me the first 10 lines of your phenotype file as an attachment
to me instead?
