### ISSUE TITLE
No Phenotype Calculation of PRS in PRSice-2

### ISSUE THREAD

**Issue by jystatistics** [choishingwan/PRSice#126]
Hi,

I have noticed that there is a way to calculate PRS in LDpred by using the option of --only-score in Step 3 as reference by [here ](https://github.com/bvilhjal/ldpred).

According to the help file in LDpred.py score --help,

**_--only-score: only ouput scores, and do not validate predictions, No phenotypes or covariates will be parsed._** 

I was wondering, is there any way I can calculate PRS in PRSice-2 without having a phenotype variable?

Thank you.

**Comment by choishingwan** [comment]
`--no-regress` is the option that you are looking for
