### ISSUE TITLE
exclude

### ISSUE THREAD

**Issue by sarasaezALS** [choishingwan/PRSice#129]
Hi Sam,
I would like to exclude a genomic region from both TARGET and REFERENCE. how should I specify this?
thanks

**Comment by choishingwan** [comment]
We've a function call `--x-range` which do exactly that. 



`--x-range`
Range of SNPs to be excluded from the whole analysis. It can either be a single bed file or a comma seperated list of range. Range must be in the format of *chr:start-end* or *chr:coordinate*
