### ISSUE TITLE
Question about InDels

### ISSUE THREAD

**Issue by jcfoo** [choishingwan/PRSice#130]
Hi,  
I've used PRSice to calculate some PRS and have found that there was a warning about possible mismatched variants:

237171 mismatched variant(s) excluded 
.... 
Warning: Mismatched SNPs detected between base and 
         target!You should check the files are based on the same 
         genome build, or that can just be InDels 
 
I checked the mismatch file and it turns out that all of the mismatches appear to be 'indels', not a build difference.

As the warning message says "that can just be InDels", would I be correct in assuming that InDel information wouldn't be important to calculating the results?  Is it ok to ignore them/this warning in this case?

Thanks in advance for your help!

**Comment by choishingwan** [comment]
That should be fine as long as you still have large number of SNPs remaining. If you still have sufficient SNPs remaining, then it should be fine to ignore the InDels. If not, then you might want to manually curate the InDels so that they match between the base and target file.
