### ISSUE TITLE
general question

### ISSUE THREAD

**Issue by sarasaezALS** [choishingwan/PRSice#132]
Hi Sam,
I have a question, 
I am using:
--quantile 4 --no-full --bar-levels 5E-2 --fastscore
in my pathway analysis I have decide to include all snps with pvalue greater than 0.05. I am doing a only one  threshold at 5E-2. It is ok to add --quantile 4 or not?
what file it is the one to see how good the model is (are under the curve)?
Thanks

**Comment by choishingwan** [comment]
So you are trying to ignore any SNPs with P-value less than 0.05? If that's the case, you might need to use 

```
--non-cumulate --bar-levels 5e-2 --fastscore
```
which will generate 2 PRS, one using SNPs with p-value from 0 to 0.05, and one using SNPs with p-value from 0.05 to 1 (not included those in 0.05). 

`--quantile 4` is there to ask PRSice to generate the quantile plot

We currently don't generate the AUC (area under curve) metric. The only metric we have for now is the R2 in the summary file.

**Comment by sarasaezALS** [comment]
so what does --no-full does?

--no-full --bar-levels 5E-2 --fastscore

**Comment by choishingwan** [comment]
`--no-full` tells PRSice not to include the p-value threshold of 1 by default. 

So if you specify `--barlevels 0.05`, the difference will be

without `--no-full` actual bar-levels will be
`--barlevels 0.05,1`

with `--no-full` actual bar-levels will be 
`--barlevels 0.05`

**Comment by sarasaezALS** [comment]
Ok, I see. I actually I don't want to include p-value threshold of 1. I only want to include 1 bar level and p-value threshold of 0.05 (with all the SNPs in my summary with a pvalue =< 0.05), is that what I did using: 
--no-full --bar-levels 5E-2 --fastscore
(thanks for your help)

**Comment by choishingwan** [comment]
If you only want to include SNPs with p-value <= 0.05, then your command is correct.

**Comment by sarasaezALS** [comment]
Thanks for your quick response!
