### ISSUE TITLE
hard calls versus soft calls

### ISSUE THREAD

**Issue by sarasaezALS** [choishingwan/PRSice#133]
for the target/replication (binary files), I have used Hard calls. it is recommended to use hard/forf calls for imputed date?

**Comment by choishingwan** [comment]
Dosage will give you slightly higher power. Speed wise, they are similar. As a result of that, I usually prefer dosage instead of hard call.

**Comment by sarasaezALS** [comment]
I see, any of them can be used with similar results, true?

**Comment by choishingwan** [comment]
Not sure if I get your question. If you are asking if they are both valid, then yes. You can checkout our paper https://academic.oup.com/gigascience/article/8/7/giz082/5532407#137685593, where we perfromed a simple analysis to compare the performance of dosage and hard score and also discuss the reason for the difference

**Comment by sarasaezALS** [comment]
perfect!
thanks for your quick response
