### ISSUE TITLE
How does PRSice adjust for ascertainment?

### ISSUE THREAD

**Issue by JudGarcGonz** [choishingwan/PRSice#134]
Two questions regarding ascertainment adjustment:

1. How and at what stage of the analysis does PRSice adjust for ascertainment?
2. When ussing the option "no-regress", are the PRS generated adjusted for ascertainment?

Thanks!

**Comment by choishingwan** [comment]
Do you mean the acertainment bias in terms of the final R2 estimate? We only perform the adjustment at the very end of the analysis, where we simply transform the R2 using the Lee's algorithm. 

If you use `--no-regress`, we don't need the adjustment because you don't perform the ascertainment.
