### ISSUE TITLE
[PRSice 2.2.6] on bgen data. Core damped --*** glibc detected *** ./PRSice_linux: free(): invalid pointer: 0x000000000ce4cc20 ***

### ISSUE THREAD

**Issue by kejia01** [choishingwan/PRSice#137]
Hi,

I am running PRSice 2.2.6. on the imputed data (bgen).

I have a problem with PRSice 2.2.6 crashing when the program reaches the part " clumping 100%, then core damped". 

To solve this potential memory issue,  I used cluster, get 100G memory from cluster, set PRSice memory to 80G, thread=10,and set more filter for target data(MAF, INFO)

 Below is the log and error message I get. Any idea of what is going wrong?

Best regards,
Kejia

Log:
2019-08-09 15:49:14
./PRSice_linux \
    --A1 alleleA \
    --A2 alleleB \
    --allow-inter  \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base snptest_ea.imputed_GWAS_combined_chr1_whole_15 \
    --base-info all_impute_info,0.7 \
    --beta  \
    --binary-target T \
    --bp position \
    --chr chromosome \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --exclude Chr1_exclude_unique.txt \
    --hard-thres 0.500000 \
    --info 0.7 \
    --interval 5e-05 \
    --ld-hard-thres 0.5 \
    --ld-info 0.7 \
    --ld-type bgen \
    --lower 5e-08 \
    --maf 0.002 \
    --memory 80G \
    --missing MEAN_IMPUTE \
    --model add \
    --out PRSice4 \
    --pvalue frequentist_add_lrt_pvalue \
    --score avg \
    --seed 3208675037 \
    --snp rsid \
    --stat frequentist_add_beta_1:add/sle=1 \
    --target /mnt/lustre/users/k1074540/data/gwas/eur/vyse/imputed/1kg_phase_3/chr1/eur_chr1_imputed_genotypes_complete.chiamo,xab \
    --thread 10 \
    --type bgen \
    --upper 0.5

Initializing Genotype file: 
/mnt/lustre/users/k1074540/data/gwas/eur/vyse/imputed/1kg_phase_3/chr1/eur_chr1_imputed_genotypes_complete.chiamo 
(bgen) 
With external fam file: xab 
 

Start processing snptest_ea 
================================================== 

Only one column detected, will assume only SNP ID is 
provided 

Reading 100.00%
Base file: snptest_ea.imputed_GWAS_combined_chr1_whole_15 
723994 variant(s) observed in base file, with: 
2 variant(s) excluded based on user input 
645976 variant(s) with INFO score less than 0.700000 
124 NA stat/p-value observed 
67802 total variant(s) included from base file 
 
 

Loading Genotype info from target 
================================================== 

We assume the following line is not a header:
012856@0095500159 012856@0095500159 0.00 -0.0066 0.0048 -0.0027 -0.0037 2 0
(first column isn't FID or IID)
5497 people (0 male(s), 0 female(s)) observed 
5497 founder(s) included 

6479K SNPs processed in /mnt/lustre/users/k1074540/data/gwas/eur/vyse/imputed/1kg_phase_3/chr1/eur_chr1_imputed_genotypes_complete.chiamo.bgen
6413470 variant(s) not found in previous data 
937665 ambiguous variant(s) excluded 
66092 variant(s) included 
 

Calculate MAF and perform filtering on target SNPs 
================================================== 

Calculating allele frequencies: 100.00%
18494 variant(s) excluded based on MAF threshold 
33 variant(s) excluded based on INFO score threshold 
66092 variant(s) included 

Start processing gene set information 
================================================== 

1 region included 

There are a total of 1 phenotype to process 
 

Start performing clumping 

193458 MB RAM detected; reserving 3 MB for clumping 
Allocated 3 MB successfully 

Clumping Progress: 100.00%

*** glibc detected *** ./PRSice_linux: free(): invalid pointer: 0x000000000ce4cc20 ***
======= Backtrace: =========
[0x5cb5e2]
[0x42b2b0]
[0x420f70]
[0x402839]
[0x5ab356]
[0x4039f5]
======= Memory map: ========
00400000-006bb000 r-xp 00000000 4f9:2c566 144122894321002143             /mnt/lustre/users/k1898113/gwasSNP/davidexample/script_meta_dataset_conditiona/PRSic_kejia/PRSice_linux
008bb000-008c5000 rw-p 002bb000 4f9:2c566 144122894321002143             /mnt/lustre/users/k1898113/gwasSNP/davidexample/script_meta_dataset_conditiona/PRSic_kejia/PRSice_linux
008c5000-00950000 rw-p 00000000 00:00 0 
01d7a000-0cf28000 rw-p 00000000 00:00 0                                  [heap]
2b9e4c620000-2b9e4d67e000 rw-p 00000000 00:00 0 
7fffb93c6000-7fffb93dc000 rw-p 00000000 00:00 0                          [stack]
7fffb93ff000-7fffb9400000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)

**Comment by choishingwan** [comment]
This might be related to #128 

I saw that you are using 1000g data as your target. Do you mind sharing that with me (If chr22 also reproduce the same problem, that'd be ideal) so that I can tackle this problem? The bgen file I've got (UKBB) cannot reproduce any of these problem.

**Comment by kejia01** [comment]
Thank you so much for your reply.The data we collected are from our patients. we are only allowed to send with signing an agreement.

Yes ,Chr22, also has this same problem. Is there any other way we could figure out what happened?

Yours
Kejia

**Comment by choishingwan** [comment]
If you can, could you please try and compile the program yourself on your server using the following script:

```
git clone https://github.com/choishingwan/PRSice.git
cd PRSice
g++ -std=c++11 -g -isystem lib -I inc src/*.cpp -lpthread -lz -o PRSice
```

And then run the program again with the new PRSice executable. 

Once you hit the error, you should be able to find a core.XXXX file in your directory (you will have to remove previous core.XXXX files though). This file should contain some information of where and why the Program die, though that information isn't always helpful. Hopefully, the information is enough for me to figure out where the problem lies

**Comment by kejia01** [comment]
Thank you so much for your link.
I follow the instruction, compile the program and try to run the program.

--- Very basic computer problem is
      if I can use     PRSice command to run, only get log file, no  core.XXXX files though
      I can not use PRSice command in the shell script or as interactive job. (-bash: PRSice: command not found) 

----below is my log file
 Maybe I should module add R? then Rscript  PRSice.R as an interactive Job?

Thank you so much.


PRSice 2.1.0.beta (14 Feb 2018)
https://github.com/choishingwan/PRSice
(C) 2016-2017 Shing Wan (Sam) Choi, Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Jack Euesden Cathryn M. Lewis Paul F. O'Reilly (2015)
PRSice: Polygenic Risk Score software.
Bioinformatics 31 (9): 1466-1468

2019-08-12 17:50:55
PRSice \
    --A1 alleleA \
    --A2 alleleB \
    --bar-levels 0.001000,0.050000,0.100000,0.200000,0.300000,0.400000,0.500000,1.000000 \
    --base a_snptest_phil_ea.imputed_GWAS_combined_chr22_whole_15_modified.txt \
    --beta  \
    --binary-target T \
    --bp POS \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --exclude Chr22_exclude_unique.txt \
    --hard-thres 0.900000 \
    --info-base INFO,0.9 \
    --interval 0.000050 \
    --ld-type bgen \
    --lower 0.000100 \
    --model add \
    --out PRSice11 \
    --pvalue P \
    --seed 2749222332 \
    --snp SNP \
    --stat BETA \
    --target /mnt/lustre/users/k1074540/data/gwas/eur/vyse/imputed/1kg_phase_3/chr22/eur_chr22_imputed_genotypes_complete.chiamo,xab \
    --thread 1 \
    --type bgen \
--upper 0.500000


Loading Genotype file:
/mnt/lustre/users/k1074540/data/gwas/eur/vyse/imputed/1kg_phase_3/chr22/eur_chr22_imputed_genotypes_complete.chiamo
(bgen)
With sample file: xab


5497 people (0 male(s), 0 female(s)) observed
5497 founder(s) included


155092 ambiguous variant(s) excluded
955121 variant(s) included


1 region included

Start processing
a_snptest_phil_ea.imputed_GWAS_combined_chr22_whole_15_modified
==============================


Base file:
a_snptest_phil_ea.imputed_GWAS_combined_chr22_whole_15_modified.txt
710998 variant(s) observed in base file, with:
101782 variant(s) not found in target file
139573 NA stat/p-value observed
595563 variant(s) with INFO score less than 0.900000
13651 total variant(s) included from base file



Start performing clumping

64312 MB RAM detected; reserving 32156 MB for clumping

vector::_M_range_check: __n (which is 5497) >= this->size()
(which is 5497)

**Comment by choishingwan** [comment]
Hi, that's strange. If you follow the command I typed, you should be able to get version 2.2.6, instead of 2.1.0 beta (it is almost 17 version behind). Could you please double check if you've got the correct version downloaded?

**Comment by kejia01** [comment]
Thank you so much for your reply, and sorry for this delayed reply.

I actually did little modifications for your script as follows
because of error message like (cc1plus: error: unrecognized command line option **"-std=c++11")**

git clone git://github.com/choishingwan/PRSice.git
cd PRSice
g++ -std=**c++0x** -g -isystem lib -I inc src/*.cpp -lpthread -lz -o PRSice

which gives me more error..
I then download PRSice version 2.2.6 from your website, and upload to the cluster.
Run it and get core file (588M Aug 15 01:02 core.31575), log file (2.4K Aug 15 00:57 PRSice10.log) and PRsice file(683K Aug 15 01:02 PRSice.o4643884).

Below is my PRSice.o4643884, do you need my core file too to figure out what happened on the chromosome22 bgen file?

Thank you so much for your help
Yours
Kejia

----------------------------

RSice 2.2.6 (2019-08-05)
https://github.com/choishingwan/PRSice
(C) 2016-2019 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)

2019-08-15 00:56:54
./PRSice_linux \
    --A1 alleleA \
    --A2 alleleB \
    --allow-inter  \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base a_snptest_phil_ea.imputed_GWAS_combined_chr22_whole_15_modified.txt \
    --base-info all_impute_info,0.7 \
    --beta  \
    --binary-target T \
    --bp POS \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --exclude Chr22_exclude_unique.txt \
    --hard-thres 0.500000 \
    --info 0.7 \
    --interval 5e-05 \
    --ld-hard-thres 0.5 \
    --ld-info 0.7 \
    --ld-type bgen \
    --lower 5e-08 \
    --maf 0.002 \
    --memory 80G \
    --missing MEAN_IMPUTE \
    --model add \
    --out PRSice10 \
    --pvalue P \
    --score avg \
    --seed 2054820972 \
    --snp SNP \
    --stat BETA \
    --target /mnt/lustre/users/k1074540/data/gwas/eur/vyse/imputed/1kg_phase_3/chr22/eur_chr22_imputed_genotypes_complete.chiamo,xab \
    --thread 10 \
    --type bgen \
    --upper 0.5


^[[1;33mWarning: INFO field not found in base file,will ignore INFO
         filtering ^[[0m

                   Initializing Genotype file:
/mnt/lustre/users/k1074540/data/gwas/eur/vyse/imputed/1kg_phase_3/chr22/eur_chr22_imputed_genotypes_complete.chiamo
(bgen)
With external fam file: xab


Start processing
a_snptest_phil_ea.imputed_GWAS_combined_chr22_whole_15_modified
==================================================

Only one column detected, will assume only SNP ID is

Base file:
a_snptest_phil_ea.imputed_GWAS_combined_chr22_whole_15_modified.txt
710998 variant(s) observed in base file, with:
87656 NA stat/p-value observed
536095 total variant(s) included from base file



Loading Genotype info from target
==================================================

We assume the following line is not a header:
012856@0095500159 012856@0095500159 0.00 -0.0066 0.0048 -0.0027 -0.0037 2 0
(first column isn't FID or IID)
5497 people (0 male(s), 0 female(s)) observed
5497 founder(s) included

575604 variant(s) not found in previous data
155092 ambiguous variant(s) excluded
534614 variant(s) included


Calculate MAF and perform filtering on target SNPs
==================================================

@                                         *** glibc detected *** ./PRSice_linux: free(): invalid pointer: 0x00000000096b54c0 ***
======= Backtrace: =========
[0x5cb5e2]
[0x4641dd]
[0x4164ff]
[0x472740]
[0x41a5d1]
[0x40123d]
[0x5ab356]
[0x4039f5]
======= Memory map: ========
00400000-006bb000 r-xp 00000000 4f9:2c566 144122894321002143             /mnt/lustre/users/k1898113/gwasSNP/davidexample/script_meta_dataset_conditiona/PRSic_kejia/PRSice_linux
008bb000-008c5000 rw-p 002bb000 4f9:2c566 144122894321002143             /mnt/lustre/users/k1898113/gwasSNP/davidexample/script_meta_dataset_conditiona/PRSic_kejia/PRSice_linux
008c5000-00950000 rw-p 00000000 00:00 0
00b57000-19a50000 rw-p 00000000 00:00 0                                  [heap]
2aed1cd70000-2aed28910000 rw-p 00000000 00:00 0
7fffe17fc000-7fffe1812000 rw-p 00000000 00:00 0                          [stack]
7fffe1883000-7fffe1884000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
/var/spool/gridscheduler/execd/nodec08/job_scripts/4643884: line 16: 31575 Aborted                 (core dumped) ./PRSice_linux --base a_snptest_phil_ea.imputed_GWAS_combined_chr22_whole_15_modified.txt --target /mnt/lustre/users/k1074540/data/gwas/eur/vyse/imputed/1kg_phase_3/chr22/eur_chr22_imputed_genotypes_complete.chiamo,xab --type bgen --ld-type bgen --beta --out PRSice10 --binary-target T --thread 10 --info 0.7 --maf 0.002 --ld-hard-thres 0.5 --ld-info 0.7 --base-info all_impute_info,0.7 --hard-thres 0.5 --exclude Chr22_exclude_unique.txt --memory 80G --allow-inter --snp SNP --chr CHR --bp POS --A1 alleleA --A2 alleleB --stat BETA --pvalue P
~                                                                                                                                                
~
