### ISSUE TITLE
Why command --print-snp outputs more SNPs than those in PRSice.best? 

### ISSUE THREAD

**Issue by gmgaous** [choishingwan/PRSice#138]
In the results of my data analysis, the number of SNPs used in the best score (in PRSice.best) was 770870. I wanted to output these SNPs. However, when I used command --print-snp, it outputted 948481 SNPs in the file PRSice.snp. How can I get the 770870 SNPs corresponding to the best score?

**Comment by choishingwan** [comment]
`--print-snp` print out all the SNPs included in the PRSice analysis after clumping, together with their p-value. As a result of that, you can simply filter out the SNPs with pvalue less than or equal to the best threshold, then you will get the corresponding SNPs. 

The reason for that is for us to have a nicer output format for PRSet.

**Comment by gmgaous** [comment]
Thanks a lot for your quick response.
Guimin

**Comment by gmgaous** [comment]
If possible, please revise the command  “--print-snp             Print all SNPs used to construct the best PRS” (in the –help list, Rscript PRSice.R -h)
into
 “--print-snp print out all the SNPs included in the PRSice analysis after clumping, together with their p-value. ….”
Thanks.
Guimin

**Comment by choishingwan** [comment]
Ya, I agree, should’ve updated that long ago
-- 
Dr Shing Wan Choi
Postdoctoral Fellow
Genetics and Genomic Sciences
Icahn School of Medicine, Mount Sinai, NYC

**Comment by gmgaous** [comment]
Hi Dr. Choi,
I am running PRSice with imputed data including indels. It showed:
Error: OR not found in base file
Error: No statistic column (OR) in file!
I want to check if PRSice can handle indels. Thank you.
Below is some output from my data analysis for your convenience. Any advice should be appreciated.

2019-08-22 18:19:19
./PRSice_linux \
    --A1 a1 \
    --A2 a2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base /gpfs/data/huo-lab/BCAC/Zhaohui/Gao/meta_SE-time-n-BCAC-white_4AAs-no-ROOT/meta_SE-time-4d21-BCAC-white_4AAs-no-ROOT/convert_to_sumstats/GWAS_sumstats_all_common_uniq.txt \
    --binary-target T \
    --bp bp \
    --chr hG19ChrC \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --interval 5e-05 \
    --lower 5e-08 \
    --missing MEAN_IMPUTE \
    --model add \
    --or  \
    --out /gpfs/data/biostat-lab/PRSice/results/results_4d21SE_white_4AAs_val_ROOT_indel/white_4d21_4AAs \
    --print-snp  \
    --pvalue p \
    --score avg \
    --seed 4034040374 \
    --snp snpid \
    --stat OR \
    --target /gpfs/data/huo-lab/ROOT/wgs/imputed_data_filtered/Gao_add_chr_NO/imputed_data_in_plink_format/plink_subset_common_SUMstat_white_4.21SE_4AAs/Olopade_chr_all.imputed_common_SUMstat_newID \
    --thread 1 \
    --upper 0.5

Best wishes,
Guimin


Guimin Gao Ph.D.
Research Associate Professor
Department of Public Health Sciences
The University of Chicago Biological Sciences
5841 S. Maryland Ave. | Room R321, MC2000 | Chicago, IL  60637
Office: 773-795-1707
Email: ggao@health.bsd.uchicago.edu

**Comment by gmgaous** [comment]
Hi Dr. Choi,
I am running PRSice with imputed data including indels. It showed:
Error: OR not found in base file
Error: No statistic column (OR) in file!
I want to check if PRSice can handle indels. Thank you.
Below is some output from my data analysis for your convenience. Any advice should be appreciated.

2019-08-22 18:19:19
./PRSice_linux \
    --A1 a1 \
    --A2 a2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base /gpfs/data/huo-lab/BCAC/Zhaohui/Gao/meta_SE-time-n-BCAC-white_4AAs-no-ROOT/meta_SE-time-4d21-BCAC-white_4AAs-no-ROOT/convert_to_sumstats/GWAS_sumstats_all_common_uniq.txt \
    --binary-target T \
    --bp bp \
    --chr hG19ChrC \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --interval 5e-05 \
    --lower 5e-08 \
    --missing MEAN_IMPUTE \
    --model add \
    --or  \
    --out /gpfs/data/biostat-lab/PRSice/results/results_4d21SE_white_4AAs_val_ROOT_indel/white_4d21_4AAs \
    --print-snp  \
    --pvalue p \
    --score avg \
    --seed 4034040374 \
    --snp snpid \
    --stat OR \
    --target /gpfs/data/huo-lab/ROOT/wgs/imputed_data_filtered/Gao_add_chr_NO/imputed_data_in_plink_format/plink_subset_common_SUMstat_white_4.21SE_4AAs/Olopade_chr_all.imputed_common_SUMstat_newID \
    --thread 1 \
    --upper 0.5

Best wishes,
Guimin


Guimin Gao Ph.D.
Research Associate Professor
Department of Public Health Sciences
The University of Chicago Biological Sciences
5841 S. Maryland Ave. | Room R321, MC2000 | Chicago, IL  60637
Office: 773-795-1707
Email: ggao@health.bsd.uchicago.edu<mailto:ggao@health.bsd.uchicago.edu>

**Comment by choishingwan** [comment]
Might be best if you start a new issue. 

1. Your base file does not contain a column called OR (exactly as what the error message said)
2. As long as the allele is represented exactly the same between the base and target, then we can "sort of" handle indel. However, we haven't developed any specific algorithm to take care of indels

**Comment by gmgaous** [comment]
Hi Dr. Choi,
Thanks a lot. I made mistake to specify –stat.
I will put my questions at new issues at github of PRSice.
Best wishes,
Guimin
