### ISSUE TITLE
Covariates

### ISSUE THREAD

**Issue by SaraBandres** [choishingwan/PRSice#139]
Dear Shing,

I have tried to apply PRSice adjusting by covariates using the --cov-file option. 
As highlighted in the tutorial, I include FID, IID + my covs.
When adjusting only by PCs everything works fine. However, if I incorporate sex or age, or both (even I have no missingness), I keep getting this error:
Thanks a lot for your help and this wonderful tool.

Include Covariates: 
Name	Missing	Number of levels 
AGE	0	- 
PC1	0	- 
PC2	0	- 
PC3	0	- 
PC4	0	- 
PC5	0	- 
PC6	0	- 
PC7	0	- 
PC8	0	- 
PC9	0	- 
PC10	0	- 
PC11	0	- 
PC12	0	- 
PC13	0	- 
PC14	0	- 
PC15	0	- 
PC16	0	- 
PC17	0	- 
PC18	0	- 
PC19	0	- 
PC20	0	- 
 

8512 sample(s) with invalid covariate: 
 
 

Error: All samples removed due to missingness in covariate 
       file!

**Comment by choishingwan** [comment]
How did you code the sex and age? What command did you use?

**Comment by SaraBandres** [comment]
Sex is coded as 1 and 2 as plink. Age is all continuous without -9 or NAs

**Comment by choishingwan** [comment]
Could you please attach the full log generated from PRSice?
-- 
Dr Shing Wan Choi
Postdoctoral Fellow
Genetics and Genomic Sciences
Icahn School of Medicine, Mount Sinai, NYC

**Comment by SaraBandres** [comment]
Thanks a lot.

PRSice 2.2.6 (2019-08-05) 
https://github.com/choishingwan/PRSice
(C) 2016-2019 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)

2019-08-09 20:17:42
/data/LNG/saraB/PATHWAYS/PRSice_linux/PRSice_linux \
    --A1 Allele1 \
    --A2 Allele2 \
    --bar-levels 0.05 \
    --base nochr_METAANALYSIS_PdGeneAnd23AndMe1_Chang2017.tbl \
    --beta  \
    --binary-target T \
    --clump-kb 1000 \
    --clump-p 1.000000 \
    --clump-r2 0.300000 \
    --cov-file covs_PD_nomissing.txt \
    --fastscore  \
    --feature exon,gene,protein_coding,CDS \
    --gtf /data/LNG/ALS_PATHWAYS/Homo_sapiens.GRCh37.75.gtf \
    --ld /data/LNG/pdMeta5v2/cojoRef/binaryForCojo \
    --maf 0.01 \
    --missing MEAN_IMPUTE \
    --model add \
    --msigdb /data/LNG/ALS_PATHWAYS/c2.cp.v6.2.symbols.gmt.txt \
    --no-full  \
    --out /data/LNG/saraB/PATHWAYS/CURATED/CURATED_SOFTCALLS_CLUMPING_r2_0.3_ALLCOVS \
    --prevalence 0.005 \
    --print-snp  \
    --pvalue P-value \
    --score std \
    --seed 607471200 \
    --set-perm 1000 \
    --snp MarkerName \
    --stat Effect \
    --target SEVENTY_SOFTCALLS_PD_unfiltered_no_duplicates_geno0.15_MAF0.05 \
    --thread 12 \
    --wind-3 0bp \
    --wind-5 0bp


Initializing Genotype file: 
SEVENTY_SOFTCALLS_PD_unfiltered_no_duplicates_geno0.15_MAF0.05 
(bed) 
 

Start processing 
nochr_METAANALYSIS_PdGeneAnd23AndMe1_Chang2017 
================================================== 

Base file: 
nochr_METAANALYSIS_PdGeneAnd23AndMe1_Chang2017.tbl 
7909452 variant(s) observed in base file, with: 
7433478 variant(s) excluded due to p-value threshold 
406035 total variant(s) included from base file 
 
 

Loading Genotype info from target 
================================================== 

12159 people (6691 male(s), 5468 female(s)) observed 
12159 founder(s) included 

2198655 variant(s) not found in previous data 
1 ambiguous variant(s) excluded 
152823 variant(s) included 
 

Start processing reference 
 

Initializing Genotype file: 
/data/LNG/pdMeta5v2/cojoRef/binaryForCojo (bed) 
 

Loading Genotype info from reference 
================================================== 

40063 people (22034 male(s), 18029 female(s)) observed 
40063 founder(s) included 

11305001 variant(s) not found in previous data 
142794 variant(s) remained 
 

Calculate MAF and perform filtering on target SNPs 
================================================== 

152823 variant(s) included 

Start processing gene set information 
================================================== 

Loading /data/LNG/ALS_PATHWAYS/c2.cp.v6.2.symbols.gmt.txt 
(MSigDB) 

Loading GTF file: 
/data/LNG/ALS_PATHWAYS/Homo_sapiens.GRCh37.75.gtf 

A total of 589389 entries removed due to feature selection 
A total of 328080 entries removed as they are not on 
autosomal chromosome 
 

A total of 1329 regions plus the base region are included 

There are a total of 1 phenotype to process 
 

Start performing clumping 

3096000 MB RAM detected; reserving 27 MB for clumping 
Allocated 27 MB successfully 

Number of variant(s) after clumping : 12152 

Phenotype is a binary phenotype 
5148 control(s) 
7011 case(s) 
 

Include Covariates: 
Name	Missing	Number of levels 
2	0	- 
91	0	- 
-0.00284846	0	- 
-0.00476629	0	- 
0.00392423	0	- 
0.00365819	0	- 
0.000910962	0	- 
0.00332572	0	- 
0.00251763	0	- 
0.00168476	0	- 
0.00206178	0	- 
0.00448515	0	- 
-0.000622383	0	- 
-0.000871464	0	- 
-0.00429503	0	- 
-0.00763202	0	- 
0.00427019	0	- 
0.00797001	0	- 
-0.00583093	0	- 
0.00183312	0	- 
0.00416008	0	- 
-0.00624218	0	- 
 

8592 sample(s) with invalid covariate: 
 
Warning: More than 70.663706% of your samples were removed! 
         You should check if your covariate file is correct 
 

Processing the covariate file: covs_PD_nomissing.txt 
============================== 
 

After reading the covariate file, 3567 sample(s) included 
in the analysis 
 

There are 1316 region(s)/phenotype(s) with p-value > 0.1 
(not significant); and 1 region(s) with p-value 
between 0.1 and 1e-5 (may not be significant);

**Comment by choishingwan** [comment]
Log suggested that it run with the covariates without any problem
-- 
Dr Shing Wan Choi
Postdoctoral Fellow
Genetics and Genomic Sciences
Icahn School of Medicine, Mount Sinai, NYC

**Comment by SaraBandres** [comment]
Yes, although it is said"

 "8592 sample(s) with invalid covariate:

Warning: More than 70.663706% of your samples were removed!
You should check if your covariate file is correct

**Comment by SaraBandres** [comment]
Oh yes, I see now. Thanks a lot!
