### ISSUE TITLE
p-competitive

### ISSUE THREAD

**Issue by sarasaezALS** [choishingwan/PRSice#140]
Hi Sam,
thanks for you labor. PRSice2 v2.6 is running pretty well.
Related to the pathway enrichment:
In the .summary file, when the competitive p-value is calculated and the goal is to know the pathway enrichment, I assumed that the enrichment is only calculated by the competitive p value and the beta and se refers to the association with the disease. Is there any numerical value to know quantitatively the enrichment (besides the competitive p-value)

**Comment by choishingwan** [comment]
You mean to rank the gene sets? So far, the most “valid” way is the competitive p-value. However, we also found that R2/ number of post clump SNPs works ok, with the caviar that the resulting R2 will be bias against larger gene sets.
