### ISSUE TITLE
Execution halted

### ISSUE THREAD

**Issue by SaraBandres** [choishingwan/PRSice#141]
Dear helper,

I have found an "execution halted" error when trying to run the following script. I do have enough memory to run it. Do you have any idea why this could happen?
Thanks for your patience

PRSice 2.2.6 (2019-08-05) 
https://github.com/choishingwan/PRSice
(C) 2016-2019 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)

2019-08-14 12:21:11
/data/LNG/saraB/PATHWAYS/PRSice_linux/PRSice_linux \
    --A1 Allele1 \
    --A2 Allele2 \
    --bar-levels 1 \
    --base nochr_AAO_GWAS_META_NO_SPAIN31.tbl \
    --beta  \
    --binary-target F \
    --clump-kb 1000 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov-file COVS_toAAO.txt \
    --fastscore  \
    --feature exon,gene,protein_coding,CDS \
    --gtf /data/LNG/ALS_PATHWAYS/Homo_sapiens.GRCh37.75.gtf \
    --ld /data/LNG/pdMeta5v2/cojoRef/binaryForCojo \
    --missing MEAN_IMPUTE \
    --model add \
    --msigdb c2.cp.v6.2.symbols.gmt.txt \
    --out /data/LNG/saraB/PATHWAYS/GOOD/CURATED_AGEATONSET_r20.1_fullback_TRAINING \
    --perm 1000 \
    --pheno-file Pheno_toAAO.txt \
    --print-snp  \
    --pvalue P-value \
    --score std \
    --seed 4002448545 \
    --snp MarkerName \
    --stat Effect \
    --target SPAIN3_SOFTCALLS_PD_unfiltered_no_duplicates_geno0.15_MAF0.05 \
    --thread 48 \
    --wind-3 0bp \
    --wind-5 0bp

Initializing Genotype file: 
SPAIN3_SOFTCALLS_PD_unfiltered_no_duplicates_geno0.15_MAF0.05 
(bed) 
 

Start processing nochr_AAO_GWAS_META_NO_SPAIN31 
================================================== 

Reading 100.00%
Base file: nochr_AAO_GWAS_META_NO_SPAIN31.tbl 
16164460 variant(s) observed in base file, with: 
13709744 total variant(s) included from base file 
 
 

Loading Genotype info from target 
================================================== 

3439 people (1806 male(s), 1633 female(s)) observed 
3439 founder(s) included 

352447 variant(s) not found in previous data 
1999033 variant(s) included 
 

Start processing reference 
 

Initializing Genotype file: 
/data/LNG/pdMeta5v2/cojoRef/binaryForCojo (bed) 
 

Loading Genotype info from reference 
================================================== 

40063 people (22034 male(s), 18029 female(s)) observed 
40063 founder(s) included 

9531983 variant(s) not found in previous data 
1915812 variant(s) remained 
 

Start processing gene set information 
================================================== 

Loading c2.cp.v6.2.symbols.gmt.txt (MSigDB) 

Loading GTF file: 
/data/LNG/ALS_PATHWAYS/Homo_sapiens.GRCh37.75.gtf 

A total of 589389 entries removed due to feature selection 
A total of 328080 entries removed as they are not on 
autosomal chromosome 
 

A total of 1329 regions plus the base region are included 

Check Phenotype file: Pheno_toAAO.txt 
Column Name of Sample ID: FID+IID 
Note: If the phenotype file does not contain a header, the 
column name will be displayed as the Sample ID which is ok. 
Phenotype Name: AGE 
There are a total of 1 phenotype to process 
 

Start performing clumping 

257652 MB RAM detected; reserving 91 MB for clumping 
Allocated 91 MB successfully 

Clumping Progress: 9.52% 
Clumping Progress: 37.31%
Clumping Progress: 45.47%
Clumping Progress: 100.00%

Number of variant(s) after clumping : 47597 

Processing the 1 th phenotype
AGE is a continuous phenotype 
237 sample(s) without phenotype 
3202 sample(s) with valid phenotype 
 

Include Covariates: 
Name	Missing	Number of levels 
1	0	- 
0.000938228	0	- 
-0.00158876	0	- 
-0.0103799	0	- 
-0.000369322	0	- 
0.00196682	0	- 
0.0034346	0	- 
-0.000195672	0	- 
-0.00186794	0	- 
0.000320244	0	- 
0.00371688	0	- 
 

Processing the covariate file: COVS_toAAO.txt 
============================== 
 

After reading the covariate file, 3202 sample(s) included 
in the analysis 
 

Preparing Output Files

Start Processing
Processing 0.00%Error: 
Execution halted

**Comment by choishingwan** [comment]
I  suspect that might have something to do with your covariate file, however, I can’t seems to replicate it using my data. My guess are as follow:


  1.  Your covariate file does not contain a header, PRSice assume there’s a header
  2.  Your covariate file doesn’t seems to contain the family ID and individual ID (or only containing one). In this case, you need the --ignore-fid option and need to format your phenotype file accordingly.
Haven’t figure out other possible cause. Let me know if those are the problems, otherwise, I will need to have another think.

Sam

**Comment by SaraBandres** [comment]
Hello,

It seems that when I run the same script but using the previous version is works fine:

2019-08-17 21:33:17
/data/LNG/pdMeta5v2/leaveOneOutPrsice/PRSice_linux/PRSice_linux \
    --A1 Allele1 \
    --A2 Allele2 \
    --bar-levels 1.000000 \
    --base nochr_AAO_GWAS_META_NO_SPAIN31.tbl \
    --beta  \
    --binary-target F \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov-file COVS_ALL_AAO.txt \
    --fastscore  \
    --feature exon,gene,protein_coding,CDS \
    --gtf /data/LNG/ALS_PATHWAYS/Homo_sapiens.GRCh37.75.gtf \
    --info-base INFO,0.9 \
    --ld /data/LNG/pdMeta5v2/cojoRef/binaryForCojo \
    --maf 0.01 \
    --model add \
    --msigdb c2.cp.v6.2.symbols.gmt.txt \
    --out /data/LNG/saraB/PATHWAYS/TEST2 \
    --perm 1000 \
    --pheno-file Pheno_toAAO.txt \
    --print-snp  \
    --pvalue P-value \
    --score std \
    --seed 3063947437 \
    --snp MarkerName \
    --stat Effect \
    --target SPAIN3_SOFTCALLS_PD_unfiltered_no_duplicates_geno0.15_MAF0.05 \
    --thread 48


Loading Genotype file: 
SPAIN3_SOFTCALLS_PD_unfiltered_no_duplicates_geno0.15_MAF0.05 
(bed) 
 

3439 people (1806 male(s), 1633 female(s)) observed 
3439 founder(s) included 
 

352447 ambiguous variant(s) excluded 
9 variant(s) excluded based on MAF threshold1999024 
variant(s) included 
 

Processing the GTF file
A total of 917469 entries removed due to feature selection
A total of 54849 genes found in the GTF file
A total of 1330 regions are included 

Loading reference panel 
============================== 
 

Loading Genotype file: 
/data/LNG/pdMeta5v2/cojoRef/binaryForCojo (bed) 
 

40063 people (22034 male(s), 18029 female(s)) observed 
40063 founder(s) included 
 

1915803 variant(s) remained 
 

Start processing nochr_AAO_GWAS_META_NO_SPAIN31 
============================== 
 

Reading 100.00%
Base file: nochr_AAO_GWAS_META_NO_SPAIN31.tbl 
16164460 variant(s) observed in base file, with: 
14248657 variant(s) not found in target file 
1915803 total variant(s) included from base file 
 
 

Start performing clumping 

1031832 MB RAM detected; reserving 42 MB for clumping 
 

Clumping Progress: 100.00%

Number of variant(s) after clumping : 48294 
 

Check Phenotype file: Pheno_toAAO.txt 
Column Name of Sample ID: FID+IID 
Note: If the phenotype file does not contain a header, the 
column name will be displayed as the Sample ID which is ok. 
Phenotype Name: AGE 
There are a total of 1 phenotype to process 
 

237 sample(s) without phenotype 
3202 sample(s) with valid phenotype 
 

11 valid covariates included 
 

Processing the covariate file: COVS_ALL_AAO.txt 
============================== 
 

After reading the covariate file, 3202 sample(s) included 
in the analysis 
 

Processing 100.00% of sets
There are 1183 region(s) with p-value > 0.1 (not 
significant); and 147 region(s) with p-value between 
0.1 and 1e-5 (may not be significant); 

geom_path: Each group consists of only one observation. Do you need to adjust
the group aesthetic?
---- COMMAND EXECUTED: ---------------------------------------------------------
(   Rscript /data/LNG/pdMeta5v2/leaveOneOutPrsice/PRSice_linux/PRSice.R --cov-file COVS_ALL_AAO.txt --out /data/LNG/saraB/PATHWAYS/TEST2 -t SPAIN3_SOFTCALLS_PD_unfiltered_no_duplicates_geno0.15_MAF0.05 -b nochr_AAO_GWAS_META_NO_SPAIN31.tbl --beta --pheno-file Pheno_toAAO.txt --snp MarkerName --A1 Allele1 --A2 Allele2 --stat Effect --pvalue P-value --ld /data/LNG/pdMeta5v2/cojoRef/binaryForCojo --print-snp --score std --perm 1000 --prsice /data/LNG/pdMeta5v2/leaveOneOutPrsice/PRSice_linux/PRSice_linux -n 48 --maf 1E-2 --gtf /data/LNG/ALS_PATHWAYS/Homo_sapiens.GRCh37.75.gtf --msigdb c2.cp.v6.2.symbols.gmt.txt --multi-plot 10 --clump-r2 0.1 )
--------------------------------------------------------------------------------

Plotting the high resolution plot
Plotting Bar Plot
Plotting Multi-Plot

**Comment by choishingwan** [comment]
Hi there, thanks for providing the file. Unfortunately, for some unknown reason, I couldn't download it (corrupted).

On the other hand, I have been looking the code of PRSice last week trying to figure out the problem and was able to identify two area of possible memory leak. I have now fixed those and maybe that can solve the problem?

[Here](https://www.dropbox.com/s/diof1hlwi45hetw/PRSice?dl=0) is the updated executable for linux. Please let me know if this solves your problem. 

Sam

**Comment by SaraBandres** [comment]
Thanks a lot! I will run it and will keep you updated :)
