### ISSUE TITLE
missing all score

### ISSUE THREAD

**Issue by jennysjaarda** [choishingwan/PRSice#142]
I am to use PRSice to get a PR risk scores at multiple thresholds (very similar to the question [here](https://github.com/choishingwan/PRSice/issues/53), however my ".all.best" file is not as expected. The first two columns are FID and IID, the third contains a list of PRS (I'm assuming) and the remaining are empty. There are 2003 column headers total. I am trying to load it into R with fread. 

I know this issue was apparently resolved in versions after 2.1, but I am running version 2.2.1. The log file is here, if you need the all.score file let me know. 
[21001_irnt_male.log](https://github.com/choishingwan/PRSice/files/3504588/21001_irnt_male.log)

**Comment by choishingwan** [comment]
This shouldn't be a problem with version 2.2.6, can you check that?

**Comment by jennysjaarda** [comment]
Hello,
Sorry for the late reply (I was away on vacation). I tried with the new
version and I am still having the same problem with the "all.score" file...

Jenny

**Comment by jennysjaarda** [comment]
Hello, 

I attached the most recent log file and a header of the file (first 10 lines). I do get a correct all.score with the toy data. The toy data is with plink data (whereas I am using bgen files), could this have any impact? The only other difference I see is that my association file has already been filtered to only include variants with p< 0.1. However I also tried filtering the ASSOC file in the toy data set and had no issues. 

Thanks for your help, 

Jenny

**Comment by choishingwan** [comment]
Hi Jenny, unfortunately, I can't see the attachments. Could you please send them to me again? Thank you

**Comment by jennysjaarda** [comment]
Sorry about that. Does it work this time?

**Comment by choishingwan** [comment]
Unfortunately, still no luck with it. Mind trying to send this via github? Maybe something funny happened when send via email.

**Comment by jennysjaarda** [comment]
[21001_irnt_male.log](https://github.com/choishingwan/PRSice/files/3560390/21001_irnt_male.log)

[21001_irnt_male.all.score.header.txt](https://github.com/choishingwan/PRSice/files/3560394/21001_irnt_male.all.score.header.txt)

**Comment by choishingwan** [comment]
Got it, perfect. Thank you

**Comment by jennysjaarda** [comment]
Indeed, a problem with sending via email. Let me know if you need anything else!

**Comment by choishingwan** [comment]
How'd your 21001_irnt_male.prsice and 21001_irnt_male.best file look like?

I have just test run the `--all-score` command on my bgen toy data and I still managed to obtain a valid all score file. It's really strange that yours malformed.

**Comment by jennysjaarda** [comment]
These two files both seem completely fine as far as I can tell... Do you
want me to send a header of these results?

I could try running the Toy data but with my bgen data and try and isolate
the problem that way...

**Comment by jennysjaarda** [comment]
Hello,
I think I may have found isolated the problem! My base file has been
filtered and clumped to include a set of pruned variants with p<0.1.

When I modify this file in R as follows:
base=("my_base_data_file_name")
base_data <- read.table(base, header=T)
pvals <- runif(n=dim(base_data)[1], min=1e-12, max=.9100)
base_data$PVAL <- pvals
write.table(base_data, paste0(base, ".temp2"), row.names=F, quote=F,
col.names=T)

And rerun PRSice with the $base.temp2 file, everything works completely
fine. If I use my original I get an malformed file. So either there is
something wrong with my PVAL column in the original file, or the program
doesn't like a filtered file. Could there be a problem with scientific
notation?

**Comment by jennysjaarda** [comment]
Attached is my original base file, in case it's useful. 
[male_GRS_0.1.txt](https://github.com/choishingwan/PRSice/files/3566068/male_GRS_0.1.txt)

**Comment by choishingwan** [comment]
Could you have a try with this and see if this solved the problem?

https://www.dropbox.com/s/diof1hlwi45hetw/PRSice?dl=0

**Comment by jennysjaarda** [comment]
Yes- it seems to be working with this version!

**Comment by choishingwan** [comment]
That's great!

**Comment by jennysjaarda** [comment]
Out of curiousity will this be resolved in the latest release or should I just continue to use this version you provided at the Dropbox link?

**Comment by choishingwan** [comment]
It will be included in the next release (the executable you got is a work in progress). There are still some extra function / features that needed more work before I will release it. However, for now, you can safely use the current version from the dropbox link (the remaining features / functions are all related to speeding up the permutation).

**Comment by jennysjaarda** [comment]
Sounds good, thanks so much for the help!

Jenny

**Comment by jennysjaarda** [comment]
Hello, 

I’m not sure if this is a problem with the version you sent me via dropbox (I suspect not since I am still using the same .R file), but I am now having a problem generating the plots, I get the following error: 

Error: Error: None of the phenotype is identified in phenotype header!
Execution halted

However I loaded in the pheno file as you did in your script: 
‘
header <- read.table(argv$pheno_file, nrows = 1, header = TRUE, check.names=FALSE)
# This will automatically filter out un-used phenos
valid.pheno <- phenos %in% colnames(header)

‘
And the pheno seems to be there… any ideas? 

Thanks, 
Jenny

**Comment by choishingwan** [comment]
Could you please send me the full log? Thanks
-- 
Dr Shing Wan Choi
Postdoctoral Fellow
Genetics and Genomic Sciences
Icahn School of Medicine, Mount Sinai, NYC

**Comment by choishingwan** [comment]
Great! (I've updated your code block so that it shows the escape sequence more clearly)
