### ISSUE TITLE
Should A1 and A2 in base dataset have the same order as in target plink bim file?

### ISSUE THREAD

**Issue by gmgaous** [choishingwan/PRSice#143]
In my Base dataset, at some SNPs, the order of A1 and A2 is different from that in the Target dataset (Plink bim file) while at other SNPs, the order is the same. Do you think PRSice can handle this problem?

My Base dataset (summary stats) has the following format:
hG19ChrC snpid a1 a2 bp or p
Chr1 1:10642:G:A A G 10642 0.704759 0.1517
Chr1 1:11008:C:G C G 11008 0.9757 0.6369
Chr1 1:11063:T:G T G 11063 1.0245 0.9212
Chr1 1:13110:G:A A G 13110 0.951991 0.6723

My Target Plink bim file (from study sample)
1       1:10642:G:A     0       10642   A       G
1       1:11008:C:G     0       11008   G       C
1       1:11063:T:G     0       11063   G       T
1       1:13110:G:A     0       13110   A       G

**Comment by choishingwan** [comment]
PRSice can automatically do the flipping as long as your effective allele is consistently located in either the a1 or a2 column of your base file (and specify the effective allele column using --A1)
