### ISSUE TITLE
Missing scores despite --no-regress

### ISSUE THREAD

**Issue by agilly** [choishingwan/PRSice#145]
When running PRSice 2.2.6 with `--no-regress`, I would expect all scores to be printed in the output file. However, I get only the score for thetop (most stringent) threshold, and all the others are empty. The header is `FID IID` followed by all the thresholds, all of which are empty columns besides the first. My command:

```
PRSice_linux \
    --A1 allele1 \
    --A2 allele0 \
    --all-score  \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base assoc.txt.gz \
    --base-maf af,0.01 \
    --beta  \
    --binary-target F \
    --bp ps \
    --chr '#chr' \
    --clump-kb 2000 \
    --clump-p 0.000100 \
    --clump-r2 0.100000 \
    --extract PRSice.valid \
    --interval 1e-10 \
    --ld 'chr#.ld' \
    --lower 7.45e-11 \
    --missing MEAN_IMPUTE \
    --model add \
    --no-regress  \
    --out test \
    --pvalue p_score \
    --score avg \
    --seed 3041381028 \
    --snp rs \
    --stat beta \
    --target 'input/chr#' \
    --thread 20 \
    --upper 0.0001 \
```

This may be similar to #142 but I am seeing this with `--no-regress` rather than `--all-score`.  My understanding was that `--all-score` was used with a regression/optimisation, whereas `--no-regress` would automatically output all scores. I also see this if  `--all-score` is enabled. Any help appreciated!

Arthur

**Comment by choishingwan** [comment]
Which file do you look at? The result should be in the all.score file

Sam
-- 
Dr Shing Wan Choi
Postdoctoral Fellow
Genetics and Genomic Sciences
Icahn School of Medicine, Mount Sinai, NYC

**Comment by agilly** [comment]
Hi Sam,

yes, that's the file I'm looking at:

`awk '{print NF}' test.all.score | head` gives:
```
394
3
3
3
3
3
3
3
3
3
```
which indicates a header with 394 columns, 391 of which are empty (awk treats consecutive whitespace as a single delimiter).

Cheers,

Arthur

**Comment by agilly** [comment]
I'm running multiple scores with the same target and different base files, with otherwise the exact same command. And I'm seeing arbitrary numbers of scores generated (not only 1 as indicated above). What is also strange is that the number of fields in the header line changes. This represents the number of thresholds + 2, and it should be constant if I have the exact same `--interval`, `--lower`, and `--upper` parameters as is the case here. Below the number of fields in the 1st and second line of a couple of output files:

```
232 232
209 144
187 187
209 130
168 168
173 173
198 198
183 183
230 230
394 3
246 93
388 3
```

If I compare the logs of a run that went well (1st line = 2nd line) with a bad one, I see no major differences :
- good run : 6M variants remaining, 231 after clumping, variants included 2-100, 228 thresholds in the prsice file
- bad run : 6M variants remaining, 467 after clumping, variants included 36-467, 392 thresholds in the prsice file

Looking at the prsice file, could it be that the thresholds with the same number of remaining variants get excluded (not reported)? This would explain why the files have different number of columns in the header.

**Comment by agilly** [comment]
I think I've got it. If I use a smaller number of thresholds (e.g. if I do `--upper 1e-6`), I get my output files. Could it be that the software can't handle too many scores at the same time? From the numbers, I would say around 200 for ~500k individuals.

**Comment by choishingwan** [comment]
This is very useful. I think this might be due to integer overflow, which leads to the all-score problem. Will try to fix it today

**Comment by choishingwan** [comment]
Maybe have a try with this:

https://www.dropbox.com/s/diof1hlwi45hetw/PRSice?dl=0

Hopefully this should help us to get a better output. Though if the problem persists, I'll have to rethink if there are better ways to generate the all score file.

**Comment by agilly** [comment]
This works, thanks!
