### ISSUE TITLE
Long run time in comparison to publication

### ISSUE THREAD

**Issue by HannahVMeyer** [choishingwan/PRSice#146]
Thanks again for a great package!

I've been trying to run a PRSice (PRSice 2.2.7) with:
1. base: 641588 genetic variant effect sizes on a quantitative trait
1. target: qc-ed ukb directly genotyped genotypes of 488377 individuals with 641588 markers
1. keep ids: 18095 individuals

Using the following command:

```{bash}
PRSice \
    --A1 a_0 \
    --A2 a_1 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base prsice_association.txt \
    --beta  \
    --binary-target F \
    --bp pos \
    --chr chr \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov prsice_covariates.txt \
    --cov-factor sex \
    --ignore-fid  \
    --interval 5e-05 \
    --keep eid.csv \
    --lower 5e-08 \
    --memory 15GB \
    --missing MEAN_IMPUTE \
    --model add \
    --out grs \
    --perm 10000 \
    --pheno prsice_pheno.txt \
    --print-snp  \
    --pvalue p \
    --score avg \
    --seed 101 \
    --snp rsid \
    --stat beta \
    --target ukb_cal_chr#_v2,ukb_cal_chr1_v2.fam \
    --thread 8 \
    --type bed \
    --upper 0.5
```
It has been running on an HTC with 15GB memory and 8CPUs and has already taken 430h CPU hours. Checking on the cluster log file: 

```{bash}
Preparing Output Files

Start Processing
Processing 53.58%
```
and resource usage collected:
The CPU time used is 1548751 seconds.
MEM: 337 Mbytes;  SWAP: 1.4 Gbytes;  NTHREAD: 16

Any ideas why this would take so long, especially compared to the runtimes reported in the paper? Did the paper run times not include the permutations maybe? Am I mis-specifying/mis-using any of the options?

Thank you very much for your help!

**Comment by choishingwan** [comment]
There seems to be a huge swap usage which the memory requirement of PRSice is low. Could you check why’s that?

What’s the output of the time command? Do you see a high real but small user and sys time? That might also indicate you have IO block. PRSice did a large number of random access to file, which incur  a large IO cost. It usually does not matter, but when the server experience high fie I/O, then PRSice can slow down significantly (similar to most other software, in fact I am having the same problem with my server at the moment).

In 2.2.7 (which isn’t officially released yet, as I am still trying to fix the –all-score bug), I have added a function call –enable-mmap which use significantly higher amount of memory, but if sufficient memory is provided (e.g. 50~60GB for UKB genotype file), it should, in theory help to speed up PRSice in the event of I/O block (but only slightly)

**Comment by HannahVMeyer** [comment]
thanks for the quick reply. What time command do you mean? I am running this via lsf/bsub.

I have just checked on the jobs again and they are still processing, at about 68% at the moment, so about 15% progress in 22h. 

I also checked the output directory and it has created a very large intermediate file called grs.inter which is 977G! Likely related to the swap, any idea what this file is doing and why it is so large?

Thanks!

**Comment by choishingwan** [comment]
If you are using the lsf system, then you should be able to see the CPU time. If it is much smaller than the actual runtime, then you are facing some kind of IO block. I am having this same problem with the Mount Sinai computer cluster at the moment. 

There shouldn't be a intermediate file. Are you using bgen? (Your log file suggested that you are performing analysis on genotype file, not bgen). If you are working on bgen, then it is expected to be much slower, usually take around 24-48hr for the full uk biobank bgen data to be processed. (The speed information from our paper were based on genotyped data, as both LDpred and lassosum cannot directly process bgen file)

**Comment by HannahVMeyer** [comment]
Yes, apologies, you are right, was just about to comment again. The intermediate file is from my initial attempt to run it on the bgen file. However, after 6 days of running, it was still at 70% of calculating allele frequencies, so I quit that job. 

The times I provided above are CPU times, as from the bjobs -l jobid:
```{bash}
Tue Sep  3 10:31:14: Resource usage collected.
                     The CPU time used is 2078063 seconds.
```
So based on this, it is actual CPU usage not just runtime. 
I am happy to provide additional information, but am not sure what else I could
do to speed this up if it is not an i/o error.

**Comment by choishingwan** [comment]
Can you try and run

```
\time -f "%e %S %U %P %K %I %O %W %M"
PRSice \
    --A1 a_0 \
    --A2 a_1 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base prsice_association.txt \
    --beta  \
    --binary-target F \
    --bp pos \
    --chr chr \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov prsice_covariates.txt \
    --cov-factor sex \
    --ignore-fid  \
    --interval 5e-05 \
    --keep eid.csv \
    --lower 5e-08 \
    --memory 15GB \
    --missing MEAN_IMPUTE \
    --model add \
    --out grs \
    --perm 10000 \
    --pheno prsice_pheno.txt \
    --print-snp  \
    --pvalue p \
    --score avg \
    --seed 101 \
    --snp rsid \
    --stat beta \
    --target ukb_cal_chr#_v2,ukb_cal_chr1_v2.fam \
    --thread 8 \
    --type bed \
    --upper 0.5
```

And do it maybe on chromosome 22 only? Currently, it seems like the main problem is the swap usage. Given the memory requirement of PRSice, you should only need to use minimum amount of memory. Maybe also give 2.2.6 a try? (as mentioned, 2.2.7 is kinda work in progress. Depending on which 2.2.7 you are using (I didn't label it very well, as it's not released, I should've develop new function in a separate branch to be honest, sorry about that), then one of the 2.2.7 actually defaults to the use of mmap, which uses large amount of memory, and might contribute to the swap problem)

**Comment by HannahVMeyer** [comment]
Thanks for the suggestion, I'll give it a go and will update on results.

**Comment by HannahVMeyer** [comment]
Started running on chr22 with 2.2.6 and 2.2.7. After clumping 4070 variants for 18k samples left. 
This is the \time output.

Version 2.2.6 without permutation for chr22:
```{bash}
\time -f "%e %S %U %P %K %I %O %W %M"
104.30 9.90 88.84 94% 0 165792 4312 0 588160
```

Version 2.2.7 without permutation for chr22:
```{bash}
\time -f "%e %S %U %P %K %I %O %W %M"
610.08 9.14 580.44 96% 0 3096 148376 0 413024
```

Running with permutations  takes a lot longer (which seems intuitive), however, monitoring progress, I again suspect it should not take this long. In order to report now and not wait a day before it is done, I stopped it when processing output files was at 4%. This is for version 2.2.6

```{bash}
\time -f "%e %S %U %P %K %I %O %W %M"
5393.21 17.58 1155.86 21% 0 7608 2312 0 588760
```

**Comment by choishingwan** [comment]
Oh, sorry, just realize that you are running permutation. With permutation, you can see it as running PRSice repeatedly for N times, where N is the number of permutation (we did some tricks to speed it up a bit). So if it takes 100 second to run PRSice, running 10,000 permutation will take around 1,000,000 seconds. I'm trying to figure out some other way to speed up the permutations further, but that''d need some rigorous testing before I am comfortable with implementing them.

**Comment by HannahVMeyer** [comment]
I see - so runtimes in the paper are without permutations then?

**Comment by choishingwan** [comment]
Yes. Lassosum and LDpred does not provide a permutation function. It will be unfair to PRSice if we compare PRSice with permutation (which is known to be time consuming), with lassosum and LDpred which does not perform permutation.

**Comment by HannahVMeyer** [comment]
I was surprised to read in the paper that the entire analysis should be that quick - from the text I had read it as if the permutations were conducted. That explains it then. Thanks

**Comment by choishingwan** [comment]
The permutation analysis is something we proposed, which wasn't implemented in the other software (though I guess that shouldn't be too difficult). However, for the most part, it is extremely time consuming, thus people tends to only do it at the very end of their analysis to obtain the empirical p-value. From our experience, if your p-value is less than 1e-5, then it is likely it will show up as significant in the permutation analysis (if your p-value is at range of 1e-100, you can almost be certain that you will get a significant empirical p-value)
