### ISSUE TITLE
SNPs output for different phenotype

### ISSUE THREAD

**Issue by michellekee** [choishingwan/PRSice#148]
Hi, 

I don't quite understand the output from --print-snp flag. I had specified to run a regressions on a few phenotypes, but only 1 list was given. Is it possible to generate the list of SNPs at the best PRS threshold for each phenotype specified?

Please advise.

Thank you!

Cheers,
Michelle

**Comment by choishingwan** [comment]
For anyone who've the same question: the same set of SNPs are used to construct PRS for different phenotype, as a result, only one copy of the .snp file is generated
