### ISSUE TITLE
Not recognize non-numeric phenotypes / covariates

### ISSUE THREAD

**Issue by choishingwan** [choishingwan/PRSice#15]
Might want to automatically change them to numbers (though that might not be the best way to handle this?)

**Comment by JoniColeman** [comment]
If automatically changing to numbers, need to make sure categorical covariates are not treated as continuous.

Joni

**Comment by choishingwan** [comment]
Proper way of dealing with factors for covariate (following how R handle factor as covariates):

1. Find out number of factors (**n**)
2. Use **n-1** column to represent the covariate
3. for the **i**th column, we use 0 or 1 to denote if the covariate == the **i+1** factor

**Comment by choishingwan** [comment]
Found that PLINK doesn't support this either. Should put it low on the development priority

**Comment by choishingwan** [comment]
PLINK 1.9 now support this option. We have also implemented the function to perform the analysis yet this option will not go live until we have extensively test run it

**Comment by choishingwan** [comment]
We will now begin implementing this feature with the following restrictions:

1. We will not do automatic factor detection. Instead, we require user to provide column names of the factor covariates in `--cov-factor`. For example, to include a factor batch / centre covariate for UKBB, the command should include `--cov-col Age,Batch,Centre --cov-factor Batch,Centre`. This force users to conciously determine which covariate is a factor (and makes the implementation slightly easier)

2. As we cannot rule out the possibility that the base factor (usually defined as the first factor for the covariate) is presence in  **all phenotype**, we will re-process the whole covariate file per-phenotype, making the multi-phenotype approach slightly slower. This will be much easier to implement and more memory efficient.

**Comment by choishingwan** [comment]
Now implemented and tested.
