### ISSUE TITLE
PRSice v2.2.8 Mac

### ISSUE THREAD

**Issue by kaitlynmmul** [choishingwan/PRSice#154]
Hi, I have used PRSice v1.25 on my mac for a while now with no problems. I went to install PRSice v2.28 and it is not working. I am new to using the terminal and don't know how to fix this error. Thank you for the help.

Rscript ./PRSice_mac/PRSice.R --dir ./PRSice_mac/ --prsice ./PRSice_mac/PRSice_mac 

Error message:
Trying to install data.table in ./PRSice_mac//lib

  There is a binary version available but the source version is later:
             binary source needs_compilation
data.table 1.10.4-3 1.12.2              TRUE

Trying to install optparse in ./PRSice_mac//lib

  There are binary versions available but the source versions are later:
         binary source needs_compilation
getopt   1.20.1 1.20.3             FALSE
optparse  1.4.4  1.6.4             FALSE

dyld: Library not loaded: /usr/local/lib/libz.1.dylib
  Referenced from: /Users/Contrie/PRSice_mac/./PRSice_mac
  Reason: image not found
Error: 
Execution halted

**Comment by choishingwan** [comment]
Oh, are you using old version of mac? I have turned on some aggressive optimization when compiling the mac binary assuming all Macs are similar. I will try to revert that. For now, you can use the attached. (Note: attached is version 2.2.9)

[PRSice_mac_lite.zip](https://github.com/choishingwan/PRSice/files/3636650/PRSice_mac_lite.zip)

**Comment by kaitlynmmul** [comment]
Hi,


Thank you for your reply. I tried the lite version and I get the same error.


Kaitlyn

________________________________

**Comment by choishingwan** [comment]
Sorry, should have read the error more carefully. You are missing the zlib, which usually ship with mac. Which version of mac do you have? Can you run the following?

```
xcode-select --install
```
This should install the command line developer tools which should include the required library

**Comment by kaitlynmmul** [comment]
I have mac vs 10.9.5. I ran this command and I still do not have the zlib library. Do you think I should compile it myself?

Kaitlyn
________________________________

**Comment by kaitlynmmul** [comment]
Sorry to bother you with this problem. Thank you for your help.


I tried :

brew install zlib


Error:


Warning: You are using macOS 10.9.

We (and Apple) do not provide support for this old version.

You will encounter build failures with some formulae.

Please create pull requests instead of asking for help on Homebrew's GitHub,

Discourse, Twitter or IRC. You are responsible for resolving any issues you

experience while you are running this old version.


==> Downloading https://zlib.net/zlib-1.2.11.tar.gz

######################################################################## 100.0%

==> ./configure --prefix=/usr/local/Cellar/zlib/1.2.11

==> make install

==> Caveats

zlib is keg-only, which means it was not symlinked into /usr/local,

because macOS already provides this software and installing another version in

parallel can cause all kinds of trouble.


For compilers to find zlib you may need to set:

  export LDFLAGS="-L/usr/local/opt/zlib/lib"

  export CPPFLAGS="-I/usr/local/opt/zlib/include"


For pkg-config to find zlib you may need to set:

  export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"


==> Summary

🍺  /usr/local/Cellar/zlib/1.2.11: 12 files, 380.8KB, built in 17 seconds

________________________________

**Comment by choishingwan** [comment]
Ya, your OS version is too slow. Without the zlib, PRSice won't be able to run. Unfortunately, MAC also doesn't allow me to compile a static version, thus the only way for you to use PRSice will be to update your OS and install zlib

**Comment by kaitlynmmul** [comment]
Thank you!

________________________________
