### ISSUE TITLE
Execution halted while trying to open sumstats file

### ISSUE THREAD

**Issue by gythien** [choishingwan/PRSice#157]
I am trying to run PRSice v2.2.8 on GenomeDK, and regardless of the summary statistics file I use (gz and non-gz versions), I get "Error: Execution halted" message while reading the sumstats file. 

Here is my code:
Rscript PRSice.R --dir . \
--prsice PRSice_linux \
--base fin1.gz \
--target genome1to24 \
--snp SNP \
--stat OR \
--pvalue P \
--A1 A1 \
--A2 A2 \
--pheno-file input_3oct2019.txt \
--pheno-col pheno2013 \
--cov-file input_3oct2019.txt \
--cov-col @C[1-10] \
--fastscore \
--binary-target T \
--bar-levels 0.00001,0.001,0.01,0.05,0.1,0.2,0.3,0.4,0.5,1 \
--quantile 5 \
--quant-ref 1 \
--perm 10000 \
--out output_4oct2019

**Comment by choishingwan** [comment]
Did you see the same problem with 2.2.9? And what's the full log generated by PRSice? (it is possible that I have over optimize the compilation, leading to failure on some of the machines)
