### ISSUE TITLE
Tutorial problem

### ISSUE THREAD

**Issue by giupeppefanelli** [choishingwan/PRSice#16]
I'm trying to learn how to use this tool, so I started the tutorial. But I get this error and I don't have at the moment other TARGET dataset to use. I tried to redownload the tutorial files but I get the same error. Could you help me?

 R -q --file=/usr/local/bin/PRSice_v1.25/PRSice_v1.25.R --args \ base TOY_BASE_GWAS.assoc \ target TOY_TARGET_DATA \ slower 0 \ supper 0.5 \ sinc 0.01 \ covary F \ clump.snps F \ plink /usr/local/bin/PRSice_v1.25/plink_1.9_linux_160914 \ figname EXAMPLE_1

> library(batch)

> start.time <- proc.time()[3]

> options(echo = FALSE)

 ################################# 

 # 

 # 

 # 

 # 

 # PRSice: Polygenic Risk Score software 

 # 

 # Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly 2014 

 # 

 # 

 # If you use PRSice in published work, please cite: 

 # 

 # "PRSice: Polygenic Risk Score software" 

 # Euesden, Lewis, O'Reilly, Bioinformatics (2015) 31 (9):1466-1468 

 # 

 # 

 # 

 #  

 ################################# 

 ################################# 

 # 

 #  Read in Command Line Arguments & interpret 

 # 

 ################################# 

$` base`

[1] "TOY_BASE_GWAS.assoc"

$` target`

[1] "TOY_TARGET_DATA"

$` slower`

[1] 0

$` supper`

[1] 0.5

$` sinc`

[1] 0.01

$` covary`

[1] "F"

$` clump.snps`

[1] "F"

$` plink`

[1] "/usr/local/bin/PRSice_v1.25/plink_1.9_linux_160914"

$` figname`

[1] "EXAMPLE_1"

 ################################# 

 # 

 #  Check options match 

 # 

 ################################# 

**[1] "ERROR: Please Supply a TARGET DATA SET"**

**Comment by choishingwan** [comment]
Did you have the target and base file in the same directory as where you run the script?

```bash
R -q --file=/usr/local/bin/PRSice_v1.25/PRSice_v1.25.R --args \
base TOY_BASE_GWAS.assoc \
target TOY_TARGET_DATA \
slower 0 \
supper 0.5 \
sinc 0.01 \
covary F \
clump.snps F \
plink /usr/local/bin/PRSice_v1.25/plink_1.9_linux_160914 \
fig name EXAMPLE_1
```

did direct copy and paste of my above code to your terminal works?

**Comment by giupeppefanelli** [comment]
Yes, I have the target and base file and the script in the same directory. Your code doesn't work, too:

R -q --file=/usr/local/bin/PRSice_v1.25/PRSice_v1.25.R --args \
> base TOY_BASE_GWAS.assoc \
> target TOY_TARGET_DATA \
> slower 0 \
> supper 0.5 \
> sinc 0.01 \
> covary F \
> clump.snps F \
> plink /usr/local/bin/PRSice_v1.25/plink_1.9_linux_160914 \
> fig name EXAMPLE_1

> library(batch)
> start.time <- proc.time()[3]
> options(echo = FALSE)
 ################################# 
 # 
 # 
 # 
 # 
 # PRSice: Polygenic Risk Score software 
 # 
 # Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly 2014 
 # 
 # 
 # If you use PRSice in published work, please cite: 
 # 
 # "PRSice: Polygenic Risk Score software" 
 # Euesden, Lewis, O'Reilly, Bioinformatics (2015) 31 (9):1466-1468 
 # 
 # 
 # 
 #  
 ################################# 
 ################################# 
 # 
 #  Read in Command Line Arguments & interpret 
 # 
 ################################# 
Error in if (substr(value, 1, 2) == "c(") value <- eval(parse(text = args[i +  : 
  missing value where true/false needed 
Calls: parseCommandArgs
Execution halted

**Comment by choishingwan** [comment]
That's strange. The "\" seems to be missing. Maybe try running the script in a single line:

```
R -q --file=/usr/local/bin/PRSice_v1.25/PRSice_v1.25.R --args base TOY_BASE_GWAS.assoc target TOY_TARGET_DATA slower 0 supper 0.5 sinc 0.01 covary F clump.snps F plink /usr/local/bin/PRSice_v1.25/plink_1.9_linux_160914 fig name EXAMPLE_1
```
