### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SaraBandres** [choishingwan/PRSice#163]
Hi Sam,

I am currently writing a manuscript where I ran PRSice 2.2.11 as the starting point for the following analyses. I have just seen that there is a new version called 2.2.11b and I was wondering if it is very different to 2.2.11 and I should repeat the analyses.
Would you like to be an author on our manuscript? Since you are the creator of the platform we feel more confident if you agree with how we performed our analyses.

Thanks!

**Comment by choishingwan** [comment]
If you doesn't use any of the following, then 2.2.11 should be identical to
2.2.11b
--score, --missing and --model


What's your manuscript about? As of now, I don't think I have provide
substantial contribution to your manuscript so in current state I don't
think I am suitable as an author. (But it will be nice if you cite our
paper :) )

Thanks

Sam
