### ISSUE TITLE
question gender and PRS

### ISSUE THREAD

**Issue by sarasaezALS** [choishingwan/PRSice#166]
I would like to run PRS to compare the PRS between males and females. I am using the GWAS sum stats as a reference and as a target, the binary files of males or females. I am not sure if this is the right way to go. Could it be correct?

**Comment by choishingwan** [comment]
Hi Sara,

Sorry, I think I missed your previous email (was in a conference and only
just got back).

I think the easiest way will be to perform PRSice on male and female
together, adjusting for sex, then perform the statistic test between the
male PRS and female PRS. However, if your assumption is that the disease
etiology might be completely different between male and female, and you are
doing thresholding, then maybe it is better to perform the analysis on male
and female separately.

Sam

**Comment by sarasaezALS** [comment]
Thanks!
I did it separately, I wasn’t sure If the predictability of the model could be OK. I mean, the base file contain both gender.

……………………………………
Sara Saez-Atienzar PhD
Postdoctoral Research Fellow
Neuromuscular Diseases Research Section
Laboratory of Neurogenetics, NIA, NIH
35 Convent Drive, Room 1A-108, Bethesda, MD 20892-3707

**Comment by choishingwan** [comment]
I am not sure what you meant by if the predictability of the model. I guess
the more important question is what exactly are you trying to get to? Are
you hypothesizing that different pathways contribute to the disease
etiology in different sex within the same disease? Or that the global
polygenic burden in male and female differs?

If you assume that the phenotype is only subtyped according to sex, then
maybe you can do something like the BUHMBOX
http://software.broadinstitute.org/mpg/buhmbox/ or this recent paper
<https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwi0i4WpsdHlAhXSUt8KHWeID-0QFjABegQIAhAC&url=https%3A%2F%2Fwww.biorxiv.org%2Fcontent%2Fbiorxiv%2Fearly%2F2019%2F11%2F01%2F827162.full.pdf&usg=AOvVaw0Cabe4lTX_kAIssHR8G13D>
and see if there are two subtype maybe?

**Comment by sarasaezALS** [comment]
I see..thanks!
I am just using general PRS to see if there is difference among genders. I will take a look to this
……………………………………
Sara Saez-Atienzar PhD
Postdoctoral Research Fellow
Neuromuscular Diseases Research Section
Laboratory of Neurogenetics, NIA, NIH
35 Convent Drive, Room 1A-108, Bethesda, MD 20892-3707
