### ISSUE TITLE
gen file script

### ISSUE THREAD

**Issue by mxttgen31** [choishingwan/PRSice#17]
Can you please post an example script using a gen genotype file and impute sample file?

**Comment by choishingwan** [comment]
Currently we only support the **bgen** format but not the **gen** format

If it is for the bgen format, then you can run

```bash
Rscript PRSice.R --dir . \
--prsice ./bin/PRSice \
--base TOY_BASE_GWAS.assoc \
--target TOY_TARGET_DATA \
--type begn \
--pheno-file TOY_TARGET_DATA.sample \
--binary-target T \
--thread 1 \
--beta F \
--full \
--fastscore 
```

Assuming the target file's name is _TOY_TARGET_DATA.bgen_ and _TOY_TARGET_DATA.sample_

**Comment by mxttgen31** [comment]
Thank you!

**Comment by choishingwan** [comment]
Please note that the bgen option is currently under beta testing. If you encountered any problem, please let us know.
