### ISSUE TITLE
v2.2.11b

### ISSUE THREAD

**Issue by SaraBandres** [choishingwan/PRSice#171]
Hi Sam,

I have run the last version of the software in my data with the following code and I am getting some weird results. Do you know what could be the issue? Thank you

PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2019-11-24 22:32:33
/data/LNG/saraB/PRSice_linux.nightly/PRSice_linux \
    --A1 Allele1 \
    --A2 Allele2 \
    --bar-levels 0.05 \
    --base /data/LNG/saraB/PATHWAYS/nochr_METAANALYSIS_PdGeneAnd23AndMe1_Chang2017.tbl \
    --beta  \
    --binary-target T \
    --clump-kb 1000 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov noage_toPRSice_phenosAndCovs_renamed.tab \
    --fastscore  \
    --feature exon,gene,protein_coding,CDS \
    --gtf /data/LNG/ALS_PATHWAYS/Homo_sapiens.GRCh37.75.gtf \
    --ld /data/LNG/pdMeta5v2/cojoRef/binaryForCojo \
    --msigdb /data/LNG/saraB/PATHWAYS/c2.cp.v6.2.symbols.gmt.txt \
    --no-full  \
    --out /data/LNG/saraB/WGS/2.2.11B_ALLSAMPLES/version2.2.11B_ALLSAMPLES_TRAINING_PDHITS_goodclumping \
    --prevalence 0.005 \
    --print-snp  \
    --pvalue P-value \
    --score std \
    --seed 4095644710 \
    --set-perm 1000 \
    --snp MarkerName \
    --stat Effect \
    --target unrelatedsamplestokeepnoWGSnoCHANG_SOFTCALLS_PD_unfiltered_no_duplicates_geno0.15_MAF0.01with90PDHITS \
    --thread 48

Initializing Genotype file: 
unrelatedsamplestokeepnoWGSnoCHANG_SOFTCALLS_PD_unfiltered_no_duplicates_geno0.15_MAF0.01with90PDHITS 
(bed) 

Start processing 
nochr_METAANALYSIS_PdGeneAnd23AndMe1_Chang2017 
================================================== 

Reading 100.00%
Base file: 
/data/LNG/saraB/PATHWAYS/nochr_METAANALYSIS_PdGeneAnd23AndMe1_Chang2017.tbl 
7909452 variant(s) observed in base file, with: 
7433478 variant(s) excluded due to p-value threshold 
69939 ambiguous variant(s) excluded 
406035 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

16616 people (8955 male(s), 7661 female(s)) observed 
16616 founder(s) included 

7038656 variant(s) not found in previous data 
1 ambiguous variant(s) excluded 
337978 variant(s) included 

Start processing reference 

Initializing Genotype file: 
/data/LNG/pdMeta5v2/cojoRef/binaryForCojo (bed) 

Loading Genotype info from reference 
================================================== 

40063 people (22034 male(s), 18029 female(s)) observed 
40063 founder(s) included 

11109817 variant(s) not found in previous data 
337978 variant(s) included 

Start processing gene set information 
================================================== 

Loading /data/LNG/saraB/PATHWAYS/c2.cp.v6.2.symbols.gmt.txt 
(MSigDB) 

Loading GTF file: 
/data/LNG/ALS_PATHWAYS/Homo_sapiens.GRCh37.75.gtf 

A total of 666123 entries removed due to feature selection 
A total of 251346 entries removed as they are not on 
autosomal chromosome 

A total of 1329 regions plus the base region are included 

There are a total of 1 phenotype to process 

Start performing clumping 

1547809 MB RAM detected; reserving 30 MB for clumping 

Allocated 30 MB successfully 

Clumping Progress: 100.00%

Number of variant(s) after clumping : 39209 

Processing the 1 th phenotype
Phenotype is a binary phenotype 
9412 control(s) 
7204 case(s) 

Processing the covariate file: 
noage_toPRSice_phenosAndCovs_renamed.tab 
============================== 

Include Covariates: 
Name	Missing	Number of levels 
sex	0	- 
PC1	0	- 
PC2	0	- 
PC3	0	- 
PC4	0	- 
PC5	0	- 
PC6	0	- 
PC7	0	- 
PC8	0	- 
PC9	0	- 
PC10	0	- 
PC11	0	- 
PC12	0	- 
PC13	0	- 
PC14	0	- 
PC15	0	- 
PC16	0	- 
PC17	0	- 
PC18	0	- 
PC19	0	- 
PC20	0	- 

After reading the covariate file, 16616 sample(s) included 
in the analysis 

Preparing Output Files

Start Processing
Processing 0.09%
Start competitive permutation 

Warning: To speed up the permutation, linear regression 
         instead of logistic regression were performed 
         within the permutation, and constructs the null 
         distribution using the absolute z-scores. This is 
         based on the assumption that linear Regression & 
         logistic regression should produce similar 
         absolute z-scores. In addition, the regression 
         equation changed from Phenotype~PRS+Covariates to 
         PRS~Phenotype+Covariate. This two equations should 
         generate simliar z-score for the independent 
         variable and will allow us to perform some 
         optimizations to speed up the permutation 

Running permutation with 48 threads 

Processing 100.00%
There are 1330 region(s)/phenotype(s) with p-value > 0.1 
(not significant);

**Comment by SaraBandres** [comment]
<img width="1147" alt="Screen Shot 2019-11-25 at 10 09 11 AM" src="https://user-images.githubusercontent.com/39712654/69551988-a907cf00-0f6b-11ea-9250-346baa8dd8de.png">

**Comment by SaraBandres** [comment]
It is said "non-significant" which is weird given that my reference file is sum stats from 26,035 cases and 403,190 controls, and my target file contains 7204 cases and 9412 controls, and the disease I'm testing is highly heritable.

**Comment by choishingwan** [comment]
I am more concern with the fact that a lot of the results contains nan
instead of a value. That means something is wrong with PRSice (as by
default we will filter out any nan). I will have a look and see if I can
solve that.

**Comment by SaraBandres** [comment]
Thanks a lot for the prompt response Sam

**Comment by choishingwan** [comment]
When you run the normal PRSice (without the gene sets) with the same
options, do you get the nan? I tried to replicate it with my data and I
can't seems to get the nan.

**Comment by SaraBandres** [comment]
Hi Sam, I am still getting an error. See below 

PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2019-11-25 10:52:29
/data/LNG/saraB/PRSice_linux.nightly/PRSice_linux \
    --A1 Allele1 \
    --A2 Allele2 \
    --bar-levels 0.05 \
    --base /data/LNG/saraB/PATHWAYS/nochr_METAANALYSIS_PdGeneAnd23AndMe1_Chang2017.tbl \
    --beta  \
    --binary-target T \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov noage_toPRSice_phenosAndCovs_renamed.tab \
    --fastscore  \
    --ld /data/LNG/pdMeta5v2/cojoRef/binaryForCojo \
    --no-full  \
    --out /data/LNG/saraB/WGS/2.2.11B_ALLSAMPLES/version2.2.11B_ALLSAMPLES_TRAINING_PDHITS_goodclumping \
    --prevalence 0.005 \
    --print-snp  \
    --pvalue P-value \
    --score std \
    --seed 1146284421 \
    --set-perm 1000 \
    --snp MarkerName \
    --stat Effect \
    --target unrelatedsamplestokeepnoWGSnoCHANG_SOFTCALLS_PD_unfiltered_no_duplicates_geno0.15_MAF0.01with90PDHITS \
    --thread 48

Initializing Genotype file: 
unrelatedsamplestokeepnoWGSnoCHANG_SOFTCALLS_PD_unfiltered_no_duplicates_geno0.15_MAF0.01with90PDHITS 
(bed) 

Start processing 
nochr_METAANALYSIS_PdGeneAnd23AndMe1_Chang2017 
================================================== 

Reading 100.00%
Base file: 
/data/LNG/saraB/PATHWAYS/nochr_METAANALYSIS_PdGeneAnd23AndMe1_Chang2017.tbl 
7909452 variant(s) observed in base file, with: 
7433478 variant(s) excluded due to p-value threshold 
69939 ambiguous variant(s) excluded 
406035 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

16616 people (8955 male(s), 7661 female(s)) observed 
16616 founder(s) included 



7038656 variant(s) not found in previous data 
1 ambiguous variant(s) excluded 
337978 variant(s) included 

Start processing reference 

Initializing Genotype file: 
/data/LNG/pdMeta5v2/cojoRef/binaryForCojo (bed) 

Loading Genotype info from reference 
================================================== 

40063 people (22034 male(s), 18029 female(s)) observed 
40063 founder(s) included 

11109817 variant(s) not found in previous data 
337978 variant(s) included 

There are a total of 1 phenotype to process 

Start performing clumping 

257652 MB RAM detected; reserving 14 MB for clumping 

Allocated 14 MB successfully 

Clumping Progress: 100.00%

Number of variant(s) after clumping : 35055 

Processing the 1 th phenotype
Phenotype is a binary phenotype 
9412 control(s) 
7204 case(s) 

Processing the covariate file: 
noage_toPRSice_phenosAndCovs_renamed.tab 
============================== 

Include Covariates: 
Name	Missing	Number of levels 
sex	0	- 
PC1	0	- 
PC2	0	- 
PC3	0	- 
PC4	0	- 
PC5	0	- 
PC6	0	- 
PC7	0	- 
PC8	0	- 
PC9	0	- 
PC10	0	- 
PC11	0	- 
PC12	0	- 
PC13	0	- 
PC14	0	- 
PC15	0	- 
PC16	0	- 
PC17	0	- 
PC18	0	- 
PC19	0	- 
PC20	0	- 

After reading the covariate file, 16616 sample(s) included 
in the analysis 

Preparing Output Files

Start Processing
Processing 100.00%
There are 1 region(s)/phenotype(s) with p-value > 0.1 (not 
significant); 

Begin plotting
Current Rscript version = 2.2.10
Plotting the quantile plot
WARNING: There are only 1 unique PRS but asked for 4 quantiles
Will not generate the quantile plot for  /data/LNG/saraB/WGS/2.2.11B_ALLSAMPLES/version2.2.11B_ALLSAMPLES_TRAINING_PDHITS_goodclumping
Plotting Bar Plot
Error in if (zero_range(as.numeric(limits))) { : 
  missing value where TRUE/FALSE needed
Calls: process_plot ... <Anonymous> -> f -> <Anonymous> -> f -> <Anonymous> -> f
In addition: Warning message:
Removed 1 rows containing missing values (position_stack).

**Comment by SaraBandres** [comment]
The following was not displayed when running PRSice with gene sets

Error in if (zero_range(as.numeric(limits))) { :
missing value where TRUE/FALSE needed
Calls: process_plot ... -> f -> -> f -> -> f
In addition: Warning message:
Removed 1 rows containing missing values (position_stack).

**Comment by choishingwan** [comment]
Definitely something is wrong (I guess you are getting nan as your PRS). Do
you mind trying this build  (2.2.12
<https://www.dropbox.com/s/51ydin4h7mktfmb/PRSice_linux?dl=0>), this is a
new version that I am sporadically working on. I suspect that might have
something to do with missing data and stuff. Maybe try this and see if the
result changes, if not, I might need a small snappy of your data to test
PRSice out.
