### ISSUE TITLE
How to interpret the negative number from the output of PRSice?

### ISSUE THREAD

**Issue by jystatistics** [choishingwan/PRSice#173]
Hi,

I calculated PRS for my imputed data set with PRSice-2. 

The code is shown below:

`./PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --all-score  \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base SNPs_1104.assoc \
    --beta  \
    --binary-target F \
    --bp BP \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --interval 5e-05 \
    --lower 5e-08 \
    --missing MEAN_IMPUTE \
    --model add \
    --no-regress  \
    --out PRSice \
    --pvalue P \
    --score sum \
    --seed 1696285276 \
    --snp SNP \
    --stat BETA \
    --target HIPFXchr#-updated \
    --thread 1 \
    --upper 0.5
`

I attached the output of my PRS score. I'm seeing that some of the patients have the negative PRS. 

I was wondering, how can I interpret this result? Is it because of the negative effect size in my summary stat?

Thank you.
![1](https://user-images.githubusercontent.com/39386861/70075193-1b526200-15b1-11ea-83ba-45562ae30669.PNG)

**Comment by choishingwan** [comment]
There are a number of discussion on this topic in our google group[ [1]](https://groups.google.com/forum/#!searchin/prsice/negative|sort:date/prsice/hs-6YPYSRQY/ElkiderrAAAJ)[[2]](https://groups.google.com/forum/#!searchin/prsice/negative$20prs|sort:date/prsice/zG6OJKu2RN0/XbgenOpsCAAJ)

Quoting @JoniColeman 

> 
> Negative polygenic scores are potentially valid. The score is the average of all the weighted test allele counts (with missing genotypes imputed as the mean frequency in the target dataset). If the log(ORs) from the base dataset are predominantly negative (i.e. most test alleles are more common in controls than in cases), then the score will tend to be weighted negatively. This isn't really an issue - in a within-trait analysis, we should still expect cases to have higher scores than controls, because they carry fewer protective alleles.
> 
> Check PLINK's score function (on which PRSice is based) to understand further: https://www.cog-genomics.org/plink/1.9/score 
>

**Comment by Spendlove** [comment]
What could be wrong if we have negative PRS scores cases end up having a lower PRS than controls?  I am using the alternate allele as A1.
