### ISSUE TITLE
Error: Require FID and IID for extraction. You can ignore the FID by using the --ignore-fid flag

### ISSUE THREAD

**Issue by JuRaGa** [choishingwan/PRSice#177]
Hi, 
I have tried everything and I don't know why I am getting the above error... This is my log file:

./PRSice_linux \
    --A1 a1 \
    --A2 a2 \
    --allow-inter  \
    --bar-levels 0.087 \
    --base ./Full_stats.txt \
    --beta  \
    --binary-target T \
    --bp BP \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 0.500000 \
    --clump-r2 0.100000 \
    --cov-col x1,x2,x3,x4,x5,x6,@PC[1-10] \
    --cov-factor x1,x2,x3,x4\
    --cov-file ./PRSice_PhenoFile_Eur_Unrelated.txt \
    --fastscore  \
    --interval 5e-05 \
    --keep ./PRSice_PhenoFile_Eur_Unrelated.txt \
    --keep-ambig  \
    --lower 1e-04 \
    --maf-base MAF,0.05 \
    --model add \
    --no-full  \
    --out ./PRSice_out \
    --pheno-col y \
    --pheno-file ./PRSice_PhenoFile_Eur_Unrelated.txt \
    --print-snp  \
    --pvalue pval \
    --se SE \
    --seed 916614979 \
    --snp snpid \
    --stat beta \
    --target ./imp_chr#_EUR_ForPRSice \
    --thread 10 \
    --upper 0.5 \
    --x-range 6:26000000-33000000

Loading Genotype file: 
./imp_chr#_500k_EUR_ForPRSice 
(bed) 
 

[1;31mError: Require FID and IID for extraction. You can ignore 
       the FID by using the --ignore-fid flag [0m

Error: 
Execution halted

Thank you for your help and happy Christmas break!

**Comment by choishingwan** [comment]
Check the format of your PRSice_PhenoFile_Eur_Unrelated.txt file. Maybe you
need the --ignore-fid flag in your script

**Comment by JuRaGa** [comment]
Thank you, it was indeed a problem with the format!!
