### ISSUE TITLE
Interpretation of the quantile plot

### ISSUE THREAD

**Issue by aslam24** [choishingwan/PRSice#178]
Dear developer, 

I have a question concerning the interpretation of the quantile plot. For the quantitative trait: Does the y-axis indicate the change in outcome per quantile compared to the reference or does it indicate the variance explained per change in quantile compared to the reference?

Thank you! Kind regards!

**Comment by choishingwan** [comment]
Y axis indicate the change in outcome for each quantile compared to the reference.  (Beta instead of R2)
