### ISSUE TITLE
PRS very small

### ISSUE THREAD

**Issue by kaitlynmmul** [choishingwan/PRSice#180]
Hi,

I have been a PRSice user for awhile but I noticed even if my base training set is a large GWAS I always get very small (10-4) polygenic risk scores. My target dataset is quite small (N=4400), but I do not have genotype data for any other GWAS to test if the PRS are small because of my target set.

I noticed when I use the test data provided with PRSice I also get small PRS.

Is this normal, does this just mean the risk SNPs are very small effect, or that there is not enough power?

Thanks,
Kaitlyn

**Comment by choishingwan** [comment]
Small PRS is normal, because the calculation of PRS is the sum of genotype
* effect size *divided* by the number of alleles. You can see it as the
"average" effect of all alleles.

**Comment by kaitlynmmul** [comment]
Thank you so much! I found it in the manual. I appreciate the help.

Kaitlyn
________________________________
