### ISSUE TITLE
Error message : Only one phenotype value detected

### ISSUE THREAD

**Issue by innerpyg-bi** [choishingwan/PRSice#181]
Hi,

I have a base file that contains beta and p values.
There is also a target plink file.
So I calculated the PRS using PRSice.
However, the following error occurs in the target plink file:

Processing the 1 th phenotype
Phenotype is a continuous phenotype
Only one phenotype value detected
Not enough valid phenotype
Error:
Execution halted

The target plink file include only one phenotype such as control.
PRS calculations work well when the plink file phenotype consists of case and control.
Actually, PRS is calculated by multiplying the sum of number of risk alleles by the weighted by SNP effect sizes.
In this situation, should I distinguish the phenotypes?

Thanks

**Comment by innerpyg-bi** [comment]
Hi,

The previous question about case control was confirmed because PRSice kindly checks the model fit.

By the way, There is something strange.
Although the same sample and SNP have been configured, the PRS value for some samples depends on the target same size.
![PRS_Capture](https://user-images.githubusercontent.com/57429465/74794393-68b7b300-5306-11ea-83fb-049c1a1e11d0.PNG)
The left side is the PRS value with the target size is 1050ea, and the right side is the value with the target size is only 24ea.
How can this possible?

Thanks

**Comment by choishingwan** [comment]
In this case, you will need to use `--no-regress` option. Do make sure you know which p-value threshold to use.
As per your second question, it looks like you are using a relatively old version of PRSice. Could you please let me know which version are you using?

Sam

**Comment by innerpyg-bi** [comment]
Hi Sam,

Thank you for your help. Very clear now.

When i check the PRSice.R, the version is 2.2.10.

Thanks

**Comment by choishingwan** [comment]
You'd like to check the version for the executable. E.g. PRSice_linux -v

**Comment by innerpyg-bi** [comment]
The PRSice_linux version is 2.2.11.b (2019-10-16).

Thanks

**Comment by choishingwan** [comment]
Oh, sorry, I was confused with the picture.  That is definitely possible
because when you have missing genotype, we "impute" the missing genotype
using the MAF of the population. As a result of that, when you have
different samples, the MAF might differ slightly, thus lead to small
differences in the PRS calculated.

**Comment by innerpyg-bi** [comment]
I understood.

Thank you very much.
