### ISSUE TITLE
Efficiency issue

### ISSUE THREAD

**Issue by GuoanQi1996** [choishingwan/PRSice#182]
Dear developer,
  Greetings! I applied PRSice on a base/target consists 6000 individuals and 1000 markers of interests in Win10 by following commands
**Rscript PRSice.R --dir . --prsice PRSice_win64.exe --base ..\R5_target_loci_rgrsion.assoc.logistic --target PRS_D12_plinkRes --stat or --binary-target T --cov ..\first5pc.eigenvec**,
while logistic binary phenotype codes as 1 and 2.
  Not sure whether the issue was something wrong with my command or data structure, or it was just normal, it took more than 10 hours till now and the results is still in process. And only information showed in command line was 
**PRSice 2.2.11.b (2019-10-16)**.
  I am aware that PRSice is developed in R and C++, so I think there should be no problem in efficiency, could you please give me some hints on this?
  Much appreciate.

**Comment by GuoanQi1996** [comment]
By the way, the PRSice is running on my PC with i7-7700HQ and 8Gb memory. 
Thank you.

**Comment by choishingwan** [comment]
The window executable is currently dead ( cannot run) and I have yet figure
out the reason. This will take me substantial amount of time and are
currently at the bottom of my to do list. Will try to update you once that
is solved, but for now, it is best to use PRSice on linux or Mac

Sorry about that.

Sam

**Comment by GuoanQi1996** [comment]
Appreciate your prompt reply, and I'll use it on other OS.

Thank you.
