### ISSUE TITLE
Error: no valid variant remaining (again)

### ISSUE THREAD

**Issue by tpillinger** [choishingwan/PRSice#184]
Hi Sam

I am trying to use PRSice-2 (July  1, 2019) using the PGC2 GWAS data as a base, and my own sample as a target. I am however getting an error (described below), any ideas why this is the case?

Using the following command: 

Rscript PRSice.R --dir . \
    --prsice ./PRSice \
    --base /rds/general/user/tpilling/home/toby_ukbb/PGC2_BASE_GWAS.assoc \
    --target /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr#.plink.bgen \
--type bgen \
    --pheno phenotype_LVM.pheno \
    --thread 1 \
    --stat BETA \
    --beta \
    --binary-target F 

I get the following error message:
 
9444230 variant(s) observed in base file, with:
944230 NA stat/p-value observed
0 total variant(s) included from base file
Error: no valid variant remaining 
 
I looked at the previous question raised by jpouget: https://github.com/choishingwan/PRSice/issues/167

And I thought it might be due to non-numeric characters in the P value column of the base data so have read this into python and re-written it. Unfortunately with this new base data file I still get the same error message.
 
Thanks in advance for your help

Toby

**Comment by choishingwan** [comment]
Could you check if this is still a problem in 2.2.12? Sometimes, when there
are special characters in your file, PRSice will fail to parse the string,
leading to the NA problem.

**Comment by tpillinger** [comment]
Thanks for getting back to me Sam.

When I run the same command using 2.2.12 I just get: 

Error:
Execution halted  

I then tried with a different base file (that other people have used successfully with PRSice) and unfortunately still get the same message (Error: Execution halted).

**Comment by choishingwan** [comment]
Mind trying this out?

https://www.dropbox.com/s/kaiopjzdjyj89yk/PRSice_linux?dl=0

I am trying to figure out if it is because of the memory leak identified
from the other thread, or the way I compile the program (I no longer have
access to the old server which I used for compilation) that caused such
errors.

Sam

**Comment by tpillinger** [comment]
Thanks Sam for your help - still getting the same error with 2.2.13 I'm afraid ('Error: Execution halted')

**Comment by choishingwan** [comment]
ok, then it is highly likely th
at my current settings of compilation doesn't match those from my previous
server.

If you can compile PRSice yourself, then maybe you can try that and see if
that solves the problem

(if you have cmake, then, within the PRSice folder, it is

mkdir build
cd build
cmake ../
make
)

**Comment by choishingwan** [comment]
Or if you haven't already compile it, try this experimental build
PRSice_linux.zip
Open link on Dropbox
<https://www.dropbox.com/s/nl21wyn5a170jx6/PRSice_linux.zip?dl=0>

**Comment by tpillinger** [comment]
Thanks Sam,
I’ve tried the experimental build but still get the same error message (Error: execution halted). 
I can’t compile yet because have only got v2 of cmake (have asked for the new version to be installed on our cluster)
Do you have any other suggestions?
Thanks again for all your help.
Toby

**Comment by choishingwan** [comment]
Mind doing a super quick test on this version? And if possible, could you
send me the full error log?

PRSice_linux.zip
Open link on Dropbox
<https://www.dropbox.com/s/z4dglz2rkrzu96o/PRSice_linux.zip?dl=0>

**Comment by tpillinger** [comment]
Hi Sam, still have the same issue with the new version. Error log as follows (sorry as screen shot as can't copy/paste from my cluster):

![Screen Shot 2020-03-05 at 18 04 07](https://user-images.githubusercontent.com/61508703/76011069-dfaa9980-5f0b-11ea-989d-4a69cbcd70d9.png)

**Comment by choishingwan** [comment]
What if you do

./PRSice_linux_6 --base XXX --target XXXX

without using the RScript?

What computer are you working on? e.g. Mac? Linux? (Ubuntu? Fedora?)

**Comment by tpillinger** [comment]
Thanks Sam, I am running everything in Unix (CentOS) via Imperial College London cluster. 

I think we are getting somewhere by removing the Rscript line. 

Using the following command:

./PRSice_linux-6/PRSice_linux_6 \
--base /rds/general/user/tpilling/home/toby_ukbb/PGC2_BASE_GWAS.assoc \
--target /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr#.plink \
--type bgen \
--pheno phenotype_LVM_6.pheno \
--thread 1 \
--stat BETA \

The PGC2 base data is processed fine, however now I am having a problem with PRSice matching the BGEN and phenotype data. The phenotype data is just 2 columns (IID and phenotype value (LVM), see picture attached). It initially gave this error message: 

Error: Sample mismatch between bgen and phenotype file!
       Name in BGEN file is :3111596_3111596 and in
       phentoype file is: 3111596 3111596. Please note that
       PRSice require the bgen file and the .sample (or
       phenotype file if sample file is not provided) to
       have sample in the same order. (We might be able to
       losen this requirement in future when we have more
       time)

So I edited the pheno file to concatenate the FID and IID wih an underscore so that it would match with the bgen. However I then got the following error:

We assume the following line is not a header:
"IID"   "LVM"
(first column isn't FID or IID)

26203 people (0 male(s), 0 female(s)) observed
26203 founder(s) included

Error: Sample mismatch between bgen and phenotype file!
       Name in BGEN file is :3111596_3111596 and in
       phentoype file is: "IID" "LVM". Please note that
       PRSice require the bgen file and the .sample (or
       phenotype file if sample file is not provided) to
       have sample in the same order. (We might be able to
       losen this requirement in future when we have more
       time)

So I removed the IID/LVM header from the phenotype file, but now it looks like the pheno files columns are not being read individually as I get the following error:


We assume the following line is not a header:
3111596_3111596 70.19574413
(first column isn't FID or IID)

26202 people (0 male(s), 0 female(s)) observed
26202 founder(s) included

Error: Sample mismatch between bgen and phenotype file!
       Name in BGEN file is :3111596_3111596 and in
       phentoype file is: 3111596_3111596 70.19574413.
       Please note that PRSice require the bgen file and
       the .sample (or phenotype file if sample file is not
       provided) to have sample in the same order. (We
       might be able to losen this requirement in future
       when we have more time)
 
The phenotype file was is tab delimited, created in r.

Any ideas how to sort this out? 

Thanks again for your help. Toby

![Pheno_top](https://user-images.githubusercontent.com/61508703/76091887-556b3f80-5fb6-11ea-88c8-2f8aa845f183.JPG)

**Comment by choishingwan** [comment]
What you need is either --id-delim which determine how the FID and IID is
appended to generate the sample ID (you can use --id-delim _)

Or in your second case, you need --ignore-fid to tell PRSice that your
phenotype file only contains the IID

**Comment by tpillinger** [comment]
Thanks!

Using --ignore-fid I am able to process the SNPs for each individual chromosome however I now get an error message regarding duplicated SNPs, advising me to use --extract PRSice.valid, I can't seem to find anything from githib or PRSice.info on how to use this as part of the code. Any pointers/links?



bash-4.2$ ./PRSice_linux-6/PRSice_linux_6 \
> --base /rds/general/user/tpilling/home/toby_ukbb/PGC2_BASE_GWAS.assoc \
> --target /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr#.plink \
> --type bgen \
> --pheno phenotype_LVM_6.pheno \
> --ignore-fid
PRSice 2.2.13 (2020-03-04)
https://github.com/choishingwan/PRSice
(C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2020-03-06 15:09:40
./PRSice_linux-6/PRSice_linux_6 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base /rds/general/user/tpilling/home/toby_ukbb/PGC2_BASE_GWAS.assoc \
    --binary-target T \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --ignore-fid  \
    --interval 5e-05 \
    --lower 5e-08 \
    --num-auto 22 \
    --out PRSice \
    --pheno phenotype_LVM_6.pheno \
    --seed 576644381 \
    --target /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr#.plink \
    --thread 1 \
    --type bgen \
    --upper 0.5

Initializing Genotype file:
/rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr#.plink
(bgen)

Start processing PGC2_BASE_GWAS
==================================================

Reading 100.00%
Base file:
/rds/general/user/tpilling/home/toby_ukbb/PGC2_BASE_GWAS.assoc
9444230 variant(s) observed in base file, with:
1333477 ambiguous variant(s) excluded
8110753 total variant(s) included from base file

Loading Genotype info from target
==================================================

We assume the following line is not a header:
3111596_3111596 70.19574413
(first column isn't FID or IID)

26202 people (0 male(s), 0 female(s)) observed
26202 founder(s) included

7402K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr1.plink.bgen
8129K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr2.plink.bgen
6696K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr3.plink.bgen
6555K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr4.plink.bgen
6070K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr5.plink.bgen
5751K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr6.plink.bgen
5405K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr7.plink.bgen
5282K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr8.plink.bgen
4066K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr9.plink.bgen
4562K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr10.plink.bgen
4628K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr11.plink.bgen
4431K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr12.plink.bgen
3270K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr13.plink.bgen
3037K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr14.plink.bgen
2767K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr15.plink.bgen
3089K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr16.plink.bgen
2660K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr17.plink.bgen
2599K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr18.plink.bgen
2087K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr19.plink.bgen
2082K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr20.plink.bgen
1261K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr21.plink.bgen
1255K SNPs processed in /rds/general/user/tpilling/projects/francis_ukbb/live/raw_geno/full_imaging/imaging_only_chr22.plink.bgen
Error: A total of 10544 duplicated SNP ID detected out of
       6825134 input SNPs! Valid SNP ID (post --extract /
       --exclude, non-duplicated SNPs) stored at
       PRSice.valid. You can avoid this error by using
       --extract PRSice.valid

**Comment by choishingwan** [comment]
Just add --extract PRSice.valid at the end of your command
