### ISSUE TITLE
Chr:Pos

### ISSUE THREAD

**Issue by jPontix** [choishingwan/PRSice#187]
Hi,

In my base and target files, I do not have the SNPs ID but I have the chr and the position in this format chr:pos. How can I run PRSice with only this information?

**Comment by choishingwan** [comment]
If both your base and target contain a column with something like chr:pos,
then you can simply provide that column name to PRSice and PRSice should be
able to match those. If the SNP ID are only coded as chr:pos in either your
base or your target, then you will want to manually construct a column
containing this info

**Comment by jPontix** [comment]
So I have to use dbSNP to obtain the SNPs id? there is no way to use only chr:pos information? The genotyping file is very big and this operation can be time-consuming.

Thanks for reply

**Comment by choishingwan** [comment]
You can just use the chr:pos if those are included. If not then I'm afraid
as of now, there isn't a way to automatically do it.

**Comment by jPontix** [comment]
If I use chr:pos information (that is included in base and target data) I get the following error: "Error: No SNP name column (SNP) in file!" What do you suggest to do?

**Comment by jPontix** [comment]
And which command I have to use to specify that?

Il giorno gio 5 mar 2020 alle ore 15:32 Shing Wan Choi <
notifications@github.com> ha scritto:

**Comment by jPontix** [comment]
And which command I have to use to specify chr:pos?

**Comment by choishingwan** [comment]
If your base file has a column name ID which contain the chr:pos info, then
you can use
./PRSice --snp ID

to specify the ID

More information can be find in our website
http://www.prsice.info/step_by_step/

**Comment by jPontix** [comment]
I already did this command but I got the following error:

>  Error: No SNP name column (SNP) in file!

**Comment by choishingwan** [comment]
Please send me the full log for me to determine the problem. Thank you

**Comment by jPontix** [comment]
This is my log file. Thank you!

Il giorno ven 6 mar 2020 alle ore 15:49 Shing Wan Choi <
notifications@github.com> ha scritto:

> Please send me the full log for me to determine the problem. Thank you
>

**Comment by choishingwan** [comment]
Hi, sorry, I don't see the log file, could you please make sure it is attached? Thanks

**Comment by jPontix** [comment]
[af.gws.log](https://github.com/choishingwan/PRSice/files/4307063/af.gws.log)

Thanks

**Comment by choishingwan** [comment]
You didn't use the `--snp` option with an input. You need to specify the column name instead of just using `--snp`. I am surprise that PRSice didn't error out earlier. 

In addition, you are using a very old version of PRSice. You can try [this version](https://www.dropbox.com/s/z4dglz2rkrzu96o/PRSice_linux.zip?dl=0) which will be released soon.

**Comment by jPontix** [comment]
This is very strange because in my command line I specified the --snp: --snp MarkerName (which I have the chr:pos information). This was the command that I used:

`/usr/local/bin/PRSice --base /home/atrial_fibrillation/sum_stat_OR.txt --target /home/atrial_fibrillation/genotyping/out-6884643\ --snp MarkerName --A1 A1 --A2 A2 --stat OR --or --pvalue Pvalue --pheno /home/atrial_fibrillation/genotyping/AF_trait.txt --binary-target T --bar-levels 5e-8 --no-full --fastscore --out /home/atrial_fibrillation/genotyping/PRS/af.gws`

I will use the new version. If I will have some trouble I am going to contact you again.
Thanks

**Comment by choishingwan** [comment]
The reason it doesn't work is because of the \ before the space of `--snp`,
which cause means you are saying your target is having the name of
"/home/atrial_fibrillation/genotyping/out-6884643 --snp" (note that --snp
now become part of the file name)

**Comment by jPontix** [comment]
Many thanks
