### ISSUE TITLE
PRS only using summary stats as target data

### ISSUE THREAD

**Issue by SaraBandres** [choishingwan/PRSice#188]
Dear Sam,

I was wondering if the option of using GWAS summary stats for your base and target datasets is implemented in PRSice. I do not see such an option but just wanted to double check.
This can be important when i.e exploring shared genetic effects between two different phenotypes for which we do not have individual level data.

Thanks

**Comment by choishingwan** [comment]
This isn't implemented and I don't think we will ever implemented that as I believe a better analysis in this situation is to use LDSC or LDAK to calculate the genetic correlation instead
