### ISSUE TITLE
No variant remained

### ISSUE THREAD

**Issue by annalexj** [choishingwan/PRSice#189]
Hi, 
I am new to PRSice.  My base file is a summary statistic from a paper. My target is imputed genotype file from plink. All are control samples. When I try running PRSice I get an error "variants not found in previous data 0 variants included". Could you please help me with this. 
PRSice 2.2.5 (30 July 2019) 
https://github.com/choishingwan/PRSice
(C) 2016-2019 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)

2020-03-18 10:31:44
./PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base Base_T_men.prn \
    --beta  \
    --binary-target F \
    --bp BP \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --interval 5e-05 \
    --lower 5e-08 \
    --missing MEAN_IMPUTE \
    --model add \
    --out PRSice \
    --pvalue P \
    --score avg \
    --seed 2837787525 \
    --snp SNP \
    --stat BETA \
    --target 1000G_chrA_both_qc \
    --thread 1 \
    --upper 0.5

Initializing Genotype file: 1000G_chrA_both_qc (bed) 
 

Start processing Base_T_men 
================================================== 

Base file: Base_T_men.prn 
200 variant(s) observed in base file, with: 
166 total variant(s) included from base file 
 
 

Loading Genotype info from target 
================================================== 

770 people (0 male(s), 0 female(s)) observed 
770 founder(s) included 

9306283 variant(s) not found in previous data 
0 variant(s) included 
 

Error: No vairant remained! 

Thanks...

**Comment by choishingwan** [comment]
it is likely that your base and target data has different encoding for SNPs. You will need to check that.

**Comment by annalexj** [comment]
I tried the same using PRSice_v1.25. I got PRS_AT_ALL_THRESHOLDS. Could you help me on how to check whether the base and target have different encoding ?
Any help is much appreciated.

**Comment by choishingwan** [comment]
So it worked on PRSice_v1.25?

If so, please show me the first few line of your bim and base file.

**Comment by annalexj** [comment]
Hi, These are the first few lines of my base and bim file. 
Base File
      SNP          CHR             BP             A1      A2     MAF     INFO    BETA     SE      P
    rs36086195        1          16,510,894         T       C     0.579   0.997   0.019   0.003  1.70E-09
    rs66844552        1          25,802,056         A       G     0.598   0.926   0.017   0.003  3.30E-08
    rs114165349       1          27,021,913         G       C     0.977   0.985   0.148    0.01  6.70E-51
     rs3768321        1          40,035,928         G       T     0.803   0.997   0.031   0.004  5.40E-15
     rs9970140        1          61,684,288         G       A     0.076   0.982    0.04   0.006  6.80E-12
    rs141509569       1          65,973,220         G      GTA    0.381   0.913    0.02   0.003  2.90E-12
     rs6676846        1          92,942,352         A       G     0.794   0.992    0.03   0.004  1.20E-15
    rs12406721        1         107,563,243         T       G     0.343   0.992   0.033   0.003  2.30E-28
     rs267733         1         150,958,836         A       G     0.839     1     0.023   0.004  1.80E-08

Bim file

1       rs143225517     0       751756  C       T
1       rs3094315       0       752566  G       A
1       rs3131972       0       752721  A       G
1       rs3131971       0       752894  T       C
1       rs61770173      0       753405  C       A
1       rs2073814       0       753474  C       G
1       rs2073813       0       753541  A       G

Thanks

**Comment by choishingwan** [comment]
The comma in your bp column will lead to the SNPs being discarded (as they
are not in a "numeric" format recognisable by PRSice). Try using --bp XXX
or --no-default to invalidate the BP column in base and see if that will
work

**Comment by annalexj** [comment]
HI, 
It worked. Thank you so much for the prompt responses.

**Comment by michellekee** [comment]
Hi, sorry to hijack this.

I am having the same issue. Both my GWAS and genotype is from the same build, so I used a non-existent bp and chr column. However, no variants were found.. I checked internally and the variants were found. Could you please advise? I'm attaching the .log file here too. Thank you! 
[PRS.log](https://github.com/choishingwan/PRSice/files/4529484/PRS.log)
