### ISSUE TITLE
Specify .bed, .bim, .fam separately

### ISSUE THREAD

**Issue by JoniColeman** [choishingwan/PRSice#19]
Particularly in view of UKBiobank work (where separate .fam files are passed to shared .bed and .bim files), it would be valuable for PRSice to have the option to specify the components of the target binary file separately.

**Comment by choishingwan** [comment]
This is now implemented in 52de5cf887f87695c5f88fcd0eda85d1959aaf88 and will be included in the next release.

To use this function, simply do:
--target \<bfile Prefix\>**,**\<fam file\>

Note: No space

**Comment by JoniColeman** [comment]
This doesn't work in the current build (see output below):

`PRSice 2.0.10.beta (26 September 2017)
https://github.com/choishingwan/PRSice
(C) 2016-2017 Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly, Sam Choi
GNU General Public License v3

Thu Sep 28 09:41:24 2017

/mnt/lustre/groups/ukbiobank/usr/KCL_Data_Analyses/PRSice \
    --base /mnt/lustre/groups/ukbiobank/Edinburgh_Data/Resources/PRS/Summary_stats/GIANT_LOCKE_2015_FOR_PRSice.txt \
    --target /mnt/lustre/datasets/ukbiobank/June2017/Genotypes/ukb_binary_v2,/mnt/lustre/groups/ukbiobank/KCL_Data/Genotypes/ukb1657_cal_chr1_v2_s488374.fam \
    --type bed \
    --binary-target F \
    --out /mnt/lustre/groups/ukbiobank/usr/KCL_Data_Analyses/Internalising/PRSice_Output/Trauma.All.Cases\
    --thread 4 \
    --keep /mnt/lustre/groups/ukbiobank/usr/KCL_Data_Analyses/Internalising/Trauma.All.Cases_Keeps_For_PRSice.txt \
    --bar-levels 0.05,1 \
    --pheno-file /mnt/lustre/groups/ukbiobank/usr/KCL_Data_Analyses/Internalising/Trauma.All.Cases_For_PRSice_Pheno.txt \
    --clump-kb 250 \
    --clump-p 1 \
    --clump-r2 0.1 \
    --extract /mnt/lustre/groups/ukbiobank/usr/KCL_Data_Analyses/Internalising/MDD_BMI_PRSice_Includes.txt \
    --stat BETA \
    --chr CHR \
    --A1 A1 \
    --A2 A2 \
    --snp SNP \
    --bp BP \
    --se SE \
    --pvalue P \
    --beta \
    --fastscore

Loading Genotype file: /mnt/lustre/datasets/ukbiobank/June2017/Genotypes/ukb_binary_v2 (bed)
With external fam file: /mnt/lustre/groups/ukbiobank/KCL_Data/Genotypes/ukb1657_cal_chr1_v2_s488374.fam
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: Cannot open bim file: /mnt/lustre/datasets/ukbiobank/June2017/Genotypes/ukb_binary_v2,/mnt/lustre/groups/ukbiobank/KCL_Data/Genotypes/ukb1657_cal_chr1_v2_s488374.fam.bim
./MDD_BMI_PRSice.sh: line 46: 56047 Aborted                 (core dumped) /mnt/lustre/groups/ukbiobank/usr/KCL_Data_Analyses/PRSice -b /mnt/lustre/groups/ukbiobank/Edinburgh_Data/Resources/PRS/Summary_stats/GIANT_LOCKE_2015_FOR_PRSice.txt /mnt/lustre/groups/ukbiobank/Edinburgh_Data/Resources/PRS/Summary_stats/daner_pgc_mdd_meta_no23andMe_noUKBB -t /mnt/lustre/datasets/ukbiobank/June2017/Genotypes/ukb_binary_v2,/mnt/lustre/groups/ukbiobank/KCL_Data/Genotypes/ukb1657_cal_chr1_v2_s488374.fam --type bed --binary-target F --beta F,T -o /mnt/lustre/groups/ukbiobank/usr/KCL_Data_Analyses/Internalising/PRSice_Output/Trauma.All.Cases -n 4 --keep /mnt/lustre/groups/ukbiobank/usr/KCL_Data_Analyses/Internalising/Trauma.All.Cases_Keeps_For_PRSice.txt --fastscore --bar-levels 0.05,1 -f /mnt/lustre/groups/ukbiobank/usr/KCL_Data_Analyses/Internalising/Trauma.All.Cases_For_PRSice_Pheno.txt --clump-kb 250 --clump-p 1 --clump-r2 0.1 --extract /mnt/lustre/groups/ukbiobank/usr/KCL_Data_Analyses/Internalising/MDD_BMI_PRSice_Includes.txt
`

This can be worked around by creating a symbolic link to the different components with a shared prefix

**Comment by choishingwan** [comment]
The update b22610e5af96dd5d6f48cec3e1e9fea649de7da has now solve this problem. In addition, that should no longer complain about size of bed file when sex chromosome stuff is included (Haven't got an example file for me to test that though...)
