### ISSUE TITLE
Mismatch variants

### ISSUE THREAD

**Issue by zqsha** [choishingwan/PRSice#190]
Hi there,

Recently, I've been using PRSice to run polygenetic scores. I am sure we are using the same genome build between the base and target files (we use bfiles, rather than bgen files). But, there are still lots of mismatches (e.g. for some traits, it could be 100-5000 SNPs mismatch. For other traits, it could be 500000 SNPs). I tried to use non-existing name with --A2. I found it's worse and more mismatches. I guess it's because that if it does not know the name of A2, it could not check the coding and non-coding alleles first, which caused more mismatches. Do you have any suggestions?

Best,
Zhiqiang

**Comment by choishingwan** [comment]
You can always check the *.mismatch file to know the reason of mismatch

And yes, when --a2 isn't provided, then PRSice will have more difficulties to match the variant between the base and target as it will be more difficult for us to do the flipping

**Comment by zqsha** [comment]
OK, thanks for your reply. If an allele is more than 10 letters, for example AAGTTACTTATT, then this toolbox will not match, and then it just showed AAGTTACTTA+2 in the *.mismatch file. I checked, for these kinds of SNPs, they are matched with these in the base files, only because of the longer names. But why does it say it's not matched.
I guess if an allele has more than 10 letters, they will just recognize the first 10 letters. Is it right?

**Comment by choishingwan** [comment]
You mean you see the exact same sequence in both base and target and PRSice
still flag that as mismatch??

As long as they are identical, then that should still work alright.

**Comment by zqsha** [comment]
Yes, let me show you this example in the mismatch file,
File_Type	RS_ID	CHR_Target	CHR_File	BP_Target	BP_File	A1_Target	A1_File	A2_Target	A2_File
Base	rs151261418	22	22	45681511	-	G	GAGGGTGTTTTTA+2	GAGGGTGTTTTTACT	G

When I extend this GAGGGTGTTTTTA+2, I saw the full name is GAGGGTGTTTTTACT, which is the same with that in the base file. But why is it in the mismatch file? Thanks

**Comment by choishingwan** [comment]
Can you show me the output of 

`grep rs151261418 <base file  name>`

I suspect the allele is coded as GAGGGTGTTTTTA+2 in the base file instead of GAGGGTGTTTTTACT as PRSice doesn't really do any shortening of allele

**Comment by zqsha** [comment]
OK. I checked the rsid in the base file. It's indeed the GAGGGTGTTTTTA+2, there is something wrong in the GWAS summary statistic base file. Thank you so much for your help. I really appreciate.
