### ISSUE TITLE
Quick Start fails to run

### ISSUE THREAD

**Issue by joshstolz** [choishingwan/PRSice#192]
Rscript /jhpce/shared/jhpce/libd/PRSice-2/v2.2.13/PRSice.R --prsice /jhpce/shared/jhpce/libd/PRSice-2/v2.2.13/PRSice_linux     --base TOY_BASE_GWAS.assoc --target TOY_TARGET_DATA --thread 1  --stat OR     --binary-target T

Error: 
Execution halted

I am running this on a linux based cluster and it is probably something on my end but difficult to debug given the generic error message. Any help would be appreciated.

**Comment by choishingwan** [comment]
If you run 

` /jhpce/shared/jhpce/libd/PRSice-2/v2.2.13/PRSice_linux --base TOY_BASE_GWAS.assoc --target TOY_TARGET_DATA`

What do you see?

**Comment by joshstolz** [comment]
Nothing it just executes.

**Comment by choishingwan** [comment]
So it just finished with nothing on screen? Not even a log on what parameters were used nor anything related to execution halt?

**Comment by joshstolz** [comment]
`[compute-104 /users/jstolz]$ /jhpce/shared/jhpce/libd/PRSice-2/v2.2.13/PRSice_linux --base TOY_BASE_GWAS.assoc --target TOY_TARGET_DATA
[compute-104 /users/jstolz]$ `

Yeah that's it

**Comment by choishingwan** [comment]
That is very abnormal. Do you have enough disk space? That's the only possible reason I can think of. What's your system's configuration?

**Comment by joshstolz** [comment]
I'm running this on a cluster. So space isn't the issue.

**Comment by choishingwan** [comment]
If you have enough space quota (a cluster can have a lot of space, but you can run out of quota), and you have the correct permission to the folder and file, then I have no idea why there isn't even an error message from PRSice.

What's your system's configuration?
What's the output if you type

`/jhpce/shared/jhpce/libd/PRSice-2/v2.2.13/PRSice_linux 0--help`

**Comment by joshstolz** [comment]
That also shows nothing. I uninstalled and reinstalled with
`curl https://codeload.github.com/choishingwan/PRSice/tar.gz/2.2.8 > PRSice.tar.gz`
And now it works. I think I may have had the wrong version or configured it wrong. I appreciate your help.
