### ISSUE TITLE
[Problem] Error: SNP with non-numeric corrdinate:

### ISSUE THREAD

**Issue by ddlinh** [choishingwan/PRSice#193]
Hi, I have just used PRSice to analyse PRS and my command line showed:
![image](https://user-images.githubusercontent.com/60208884/79493849-43b49780-804c-11ea-94e6-cc2cc2fd6298.png)

I have found in all my files and there are no "rs4075116:1003629.0" existed. What happened? ;( 

I'm looking forward for your response.
My sincerely

**Comment by choishingwan** [comment]
The SNP is rs4075116 and the coordinates is 1003629.0

wonder why the .0 happens but basically we are expecting an integer not a
double, thus the conversion failed.

**Comment by ddlinh** [comment]
I think it's related to Python numeric processing. Anw, thank you so much!

**Comment by choishingwan** [comment]
In theory, we should be able to handle that too. I will see if we can handle the .0 if needed in the future
