### ISSUE TITLE
Issue PRSice2 ( 2.2.13 ) error with bgen type - excution halted 

### ISSUE THREAD

**Issue by helenhpcsupport** [choishingwan/PRSice#196]
**Describe the bug*
Centos 7.x, PRSice 2.2.13 with R3.5.2, bgen type cause execution halted issue. I checked the old issue report, but unable to fix it from the previous suggestion. 

**Error Log**
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2020-05-17 17:57:36
./PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base AUDIT_C_CLEAN.txt \
    --beta  \
    --binary-target F \
    --bp BP \
    --chr CHR \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov alspac_pcs.dat \
    --cov-col sex,@PC[1-10] \
    --ignore-fid  \
    --interval 5e-05 \
    --ld-dose-thres 0.000000 \
    --ld-hard-thres 0.100000 \
    --ld-type bgen \
    --lower 5e-08 \
    --num-auto 22 \
    --out auditc \
    --pheno MergedALSPAC.dat \
    --pheno-col tf5_audit_c \
    --pvalue P \
    --score avg \
    --seed 4010359512 \
    --snp snpid \
    --stat beta \
    --target data_#.bgen \
    --thread 1 \
    --upper 0.5

Error:
Execution halted

**To Reproduce**
If possible, provide a minimum working example for me to reproduce the problem. This can usually speed up the debugging process. 

**Additional context**

**Comment by choishingwan** [comment]
Ya that... Bug in 2.2.13 means it doesn't report the error log. Try this:


https://www.dropbox.com/s/s8ycohvlqcrkj6s/PRSice_linux?dl=0

**Comment by choishingwan** [comment]
[2.3.0 ](https://github.com/choishingwan/PRSice/releases/tag/2.3.0)is out. You can try that.

**Comment by helenhpcsupport** [comment]
Thanks for your quick response. I am unable to open the dropbox. ..

**Comment by helenhpcsupport** [comment]
I tried version 2.3 and this is what the error message showed after rerun. Looks like the P value is not taken.. please advise.

Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2020-05-18 14:24:04
./PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base AUDIT_C_CLEAN.txt \
    --beta  \
    --binary-target F \
    --bp BP \
    --chr CHR \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov alspac_pcs.dat \
    --cov-col sex,@PC[1-10] \
    --ignore-fid  \
    --interval 5e-05 \
    --lower 5e-08 \
    --num-auto 22 \
    --out auditc \
    --pheno MergedALSPAC.dat \
    --pheno-col tf5_audit_c \
    --pvalue P \
    --score avg \
    --seed 3613760682 \
    --snp snpid \
    --stat beta \
    --target data_#.bgen \
    --thread 1 \
    --type bgen \
    --upper 0.5

Error: P not found in base file
Error: Column for the P-value must be provided!

Error:
Execution halted

**Comment by choishingwan** [comment]
You can just use the 2.3.0 now as I have released it

**Comment by jPontix** [comment]
It works! Great, thanks a lot. 
Just another question... If I add --plot to generate the quantile plot using the following command:

 ```
Rscript PRSice.R --prsice ./PRSice_linux --A1 A1 --A2 A2 --base /home/atrial_fibrillation/af.cleaning.txt --binary-target T --ignore-fid --or --pheno /home/EUR_9919orderFam.af.tab.txt --pheno-col AF --nonfounders --pvalue Pvalue --snp MarkerName --stat OR --target /home/HRC_imputed/filtered --cov /home/Cov_9919orderFam.af.txt --quantile 10 --plot --out af.help
Begin plotting
Current Rscript version = 2.3.0
Plotting the quantile plot
WARNING: There are only 0 unique PRS but asked for 10 quantiles
Will not generate the quantile plot for  af.help
Plotting Bar Plot
Plotting the high resolution plot
Warning messages:
1: In fread(paste0(prefix, ".best"), data.table = F, colClasses = c(FID = "character",  :
  Detected 4 column names but the data has 3 columns. Filling rows automatically. Set fill=TRUE explicitly to avoid this warning.
2: In max(pheno$Pheno) : no non-missing arguments to max; returning -Inf
```

I don't understand this line:

> WARNING: There are only 0 unique PRS but asked for 10 quantiles

Why does it happen?

**Comment by choishingwan** [comment]
YOu are likely using an older version of the Rscript. Try using the version
that comes with 2.3.0.a

**Comment by choishingwan** [comment]
The error is from the executable. Could you please check the header of your
base file to make sure the p-value column P is there?

**Comment by helenhpcsupport** [comment]
Yes, it is working now, the pvalue in base file should be “p” not “P”, I have changed it and now it is processing. Thank you so much for your efforts.

Helen
