### ISSUE TITLE
[BUG] all_score output rows mixed and FID present

### ISSUE THREAD

**Issue by ukuvainik** [choishingwan/PRSice#198]
**Describe the bug**
I run the latest PRSice2.30b. When I extract PGS-s from .all_score, then two things happen:

First, the second line is not separated from the first line. 
Second, there is an FID column, although I set --ignore-fid =T. This makes data extraction bit difficult, as there are more names than columns

**Error Log**
![image](https://user-images.githubusercontent.com/6614391/82447912-9e10a000-9ab1-11ea-9e2e-3a6a3825e4d2.png)

**To Reproduce**
[ea3.log](https://github.com/choishingwan/PRSice/files/4656921/ea3.log)

**Comment by choishingwan** [comment]
This is a format bug. Have just fixed it in 2.3.0.c. Thanks
