### ISSUE TITLE
PRSice (v2.3.0) will not generate 'all_score' file unless phenotype is present

### ISSUE THREAD

**Issue by dfelsky** [choishingwan/PRSice#199]
Using PRSice v2.3.0, I am attempting a very basic operation, which is just the calculation and output of PRS at multiple thresholds (--bar-levels) for a set of genotype data. No further analysis or plotting. The code is as follows and runs without error:

```bash
PRSice_linux --stat OR \
--snp snp \
--pvalue P \
--or \
--all-score \
--bar-levels 5e-08,1e-06,1e-05 \
--fastscore \
--no-regress \
--print-snp \
--out test \
-b sumstats.txt \
-t merged_geno
```
The log from this code is as follows:
![image](https://user-images.githubusercontent.com/9359659/82454813-3beb7700-9a80-11ea-8c13-c60e5205fc71.png)

Despite --all-score and --no-regress options, the only output files that are generated are:

![image](https://user-images.githubusercontent.com/9359659/82454999-73f2ba00-9a80-11ea-92b6-07f2187d3cb9.png)

However. When I replace the target fileset .fam file's 6th column (which is all -9 in the above example) with simulated case-control status (1,2), the same code runs and generates the test.all_score file successfully. With this log:

![image](https://user-images.githubusercontent.com/9359659/82460268-f5e5e180-9a86-11ea-8609-15773c616438.png)

Must there be some phenotype values present for the program to calculate scores? I have attempted many versions of the code, with -9 in the .fam's file 6th column, adding and removing options. In all cases, the all_score file is not generated.

**Comment by choishingwan** [comment]
That's a bug introduced because I want to allow people to use `--score con-std` with `--no-regress`. It is now fixed with 2.3.0.c. Thanks
