### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by stephensonm2** [choishingwan/PRSice#200]
**Describe the bug**
I am receiving an error message that states: "Not enough column in phenotype file. If the phenotype does not contain the FID, use --ignore-fid." However, I have already included --ignore-fid in my script. I am using PRSice version 2.3.

**Error Log**
[auditc.log](https://github.com/choishingwan/PRSice/files/4678907/auditc.log)

**To Reproduce**
Script: Rscript ./PRSice.R --dir . --prsice ./PRSice_linux --base AUDIT_C_CLEAN_REV2.txt --snp CHR:BP --chr CHR --bp BP --A1 A1 --A2 A2 --stat beta --pvalue p --extract auditc.valid --pheno ALSPAC_AUDITC_PRSice.dat --ignore-fid --binary-target F --type bgen --target data_# --cov alspac_pcs_genoIDs.dat --cov-col sex1,@PC[1-10] --score avg --out auditc

**Comment by choishingwan** [comment]
Can you do this?

awk 'NF < 2 {print NR,$0}' ALSPAC_AUDITC_PRSice.dat

This should show any line with less than 2 column

**Comment by stephensonm2** [comment]
This command helped me to identify and solve the issue - thanks so much!
