### ISSUE TITLE
Question on covariate bug-fix 

### ISSUE THREAD

**Issue by nannabarnkob** [choishingwan/PRSice#201]
Hi Sam 

I had a number of very weird results using v.2.3.1 with extremely high-performing PRSs (70%). Including covariates, we "reached" ~90% in full R2. Because R2 is often overestimated if you do not include an intercept in the R2 calculation, I tried to manually add it to my covariates file with a column of 1s. This completely diminished the performance of both the full model and PRS to almost 0.5% and practically 0%. 
Today I redid my experiments with the newest version v2.3.1.d and I found no difference in adding the intercept manually or not, also my results were more realistic. Do you think you can help me by confirming that my weird results were most likely do to a bug that should be fixed in v2.3.1.c (Fix problem with missing covariate)? 

Thank you! 
Best 
Nanna

**Comment by choishingwan** [comment]
yes, that is likely the case. Coz by default, PRSice always include the
intercept when performing the regression.

When there're missing covariate, previous version (e.g. 2.3.x+ but before
2.3.1.c) misplace the covariate on the matrix, which can lead to some crazy
downstream result. That should be fixed now. If you are worry, you can try
and repeat the analysis in R using the best PRS  and see if the result from
the manual regression is the same as PRSice (which should be the case)

Sam

**Comment by nannabarnkob** [comment]
Great to hear, thank you for the super quick reply as always :) 
I just redid the R2 estimates in python statsmodels and got exactly the same as PRSIce so everything should be good.
