### ISSUE TITLE
Question: Print Ambiguous SNPs

### ISSUE THREAD

**Issue by michellekee** [choishingwan/PRSice#202]
Hi, 

Is there a way for us to print the ambiguous variants that have been removed? So that we can head back to the GWAS and check?

Thank you so much! 

P/S: It's not a bug but the label was added accidentally and unfortunately, I'm tried to remove the label but failed. Sincere apologies for that..

**Comment by choishingwan** [comment]
Nope. We don't output the ambiguous SNPs. You can check that by looking at the reference and alternative allele. If they are A/T or G/C then you have an ambiguous SNP
