### ISSUE TITLE
" " is not a valid option, or does not support an argument

### ISSUE THREAD

**Issue by jessica-agnewblais** [choishingwan/PRSice#204]
Hi,
I am getting the error:
Error in getopt_options(object, args) : 
  Error in getopt(spec = spec, opt = args) : 
  " " is not a valid option, or does not support an argument
Calls: parse_args -> parse_options -> getopt_options
Execution halted

My code is below. I am running the code on rosalind, so I'm not sure if it's something to do with that.

module add apps/R/3.6.0
module add apps/prsice/2.2.12 
module add apps/plink/1.9.0b6.10

Rscript /users/k1469373/brc_scratch/software/PRSice.R \
--dir . \
--prsice /users/k1469373/brc_scratch/software/PRSice_linux \
--base /users/k1469373/brc_scratch/data/adhd_jul2017 \
--target /users/k1469373/brc_scratch/pelotas/chr# \
--chr CHR \
--snp SNP \
--A1 A1 \ 
--A2 A2 \
--stat OR \ 
--pvalue P \
--ld /users/k1469373/brc_scratch/software/PRScs/ldblk_1kg_eur \
--out /users/k1469373/brc_scratch/pelotas/pelotas_prs

The full log is below as well. Thanks!! Jess
[k1469373@noded18 [rosalind] data]$ Rscript /users/k1469373/brc_scratch/software/PRSice.R \
> --dir . \
> --prsice /users/k1469373/brc_scratch/software/PRSice_linux \
> --base /users/k1469373/brc_scratch/data/adhd_jul2017 \
> --target /users/k1469373/brc_scratch/pelotas/chr# \
> --chr CHR \
> --snp SNP \
> --A1 A1 \ 
Error in getopt_options(object, args) : 
  Error in getopt(spec = spec, opt = args) : 
  " " is not a valid option, or does not support an argument
Calls: parse_args -> parse_options -> getopt_options
Execution halted
[k1469373@noded18 [rosalind] data]$ --A2 A2 \
> --stat OR \ 
bash: --A2: command not found
[k1469373@noded18 [rosalind] data]$ --pvalue P \
> --ld /users/k1469373/brc_scratch/software/PRScs/ldblk_1kg_eur \
> --out /users/k1469373/brc_scratch/pelotas/pelotas_prs

**Comment by choishingwan** [comment]
Most likely this is an error caused by missing out some \
```
Rscript /users/k1469373/brc_scratch/software/PRSice.R \
--dir . \
--prsice /users/k1469373/brc_scratch/software/PRSice_linux \
--base /users/k1469373/brc_scratch/data/adhd_jul2017 \
--target /users/k1469373/brc_scratch/pelotas/chr# \
--chr CHR \
--snp SNP \
--A1 A1 \
--A2 A2 \
--stat OR \
--pvalue P \
--ld /users/k1469373/brc_scratch/software/PRScs/ldblk_1kg_eur \
--out /users/k1469373/brc_scratch/pelotas/pelotas_prs \
```

Also, think Rosalind contains the latest PRSice module, you might be able to use that by doing module load (haven't used rosalind for sometime now, so I might be wrong.)
