### ISSUE TITLE
most p-value thresholds have 0 p-values

### ISSUE THREAD

**Issue by Mary-mufford** [choishingwan/PRSice#205]
![whole_amygdala_BARPLOT_2020-06-08](https://user-images.githubusercontent.com/66270009/85312312-f672fd00-b4b6-11ea-84d3-16a3b9067ab6.png)
![whole_amygdala_HIGH-RES_PLOT_2020-06-08](https://user-images.githubusercontent.com/66270009/85312328-f96ded80-b4b6-11ea-92f7-d5c2592f94dd.png)
Hi there,

For some reason, many of the PRS that were generated for most of the thresholds have a p-value of 0.  See attached the plots. Please could you explain why this has happened?

**Comment by catlisboa** [comment]
I'm having the same problem
<img width="667" alt="Screen Shot 2020-06-22 at 2 12 12 PM" src="https://user-images.githubusercontent.com/37371744/85321361-966a5f80-b492-11ea-95d8-8d65951f1e87.png">

**Comment by choishingwan** [comment]
Did you use the same data set for generating the GWAS and use it for PRS
calculation?

**Comment by catlisboa** [comment]
No, but I was trying to use snps in common - can that be the reason? 
I'm also getting only a few snps after the "clumping process" - could it be due to the same?

Thank you

**Comment by choishingwan** [comment]
What's your sample size? And are there any samples in your target that can
be found in the base GWAS?

A high R2 (which doesn't seem to be the problem for both of you) usually
indicates some form of sample overlap between the base and the target.
Whereas a small P-value is definitely possible, especially when you have
large sample size.

**Comment by Mary-mufford** [comment]
Hi there,

In my case they are two different datasets of the same continuous trait. There is some sample overlap. My target has 31k samples (using raw genotypes) and the discovery has 34k (using sumstats, of which ~8k may be in common)


Kind regards

Mary


________________________________

**Comment by Mary-mufford** [comment]
So if the sample size is fairly large, and the p-values are very small. How do I know which is the best PRS if all except one have the same p-value of 0? I am just struggling to make sense of what I am seeing. Based on the manhattan plots I would expect that datasets to have very similar results. Attached is my log file


Kind regards

Mary


________________________________

**Comment by choishingwan** [comment]
With sample overlap, you are bound to see extreme p-value in addition to an
inflation in R2. You should make sure none of your samples in the target
data are presented in the base.

The way we select the "best" threshold is actually by R2 (preciously
because p-value has a bounding issue)

Sam
