### ISSUE TITLE
Clumping is filtering out too many snps

### ISSUE THREAD

**Issue by catlisboa** [choishingwan/PRSice#206]
Hi, I'm trying to understand why the clumping step is filtering out so many snps. Could you explain me a bit better how this step is performed? 
Thank you so much.

Here is my log file:
(This is just one chr, but when I scale up for all chr the same is happening)

Reading 100.00%
8150754 variant(s) observed in base file, with: 
7837619 variant(s) excluded based on user input 
313135 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

425843 people (196188 male(s), 229655 female(s)) observed 
425843 founder(s) included 

818 variant(s) not found in previous data 
4193 variant(s) included 

There are a total of 1 phenotype to process 

Start performing clumping 

Clumping Progress: 100.00%
Number of variant(s) after clumping : 467 

Processing the 1 th phenotype 

Phenotype is a binary phenotype 
352294 control(s) 
73549 case(s) 

Start Processing
Processing 100.00%
There are 1 region(s) with p-value between 0.1 and 1e-5 
(may not be significant). 

Begin plotting
Current Rscript version = 2.3.1.c
Plotting the quantile plot
Plotting Bar Plot
Plotting the high resolution plot

**Comment by choishingwan** [comment]
If those 4193 SNPs all lie within a small region, or are in high LD with
each other, then it is not surprising for you to only have 467 SNPs
remaining.
