### ISSUE TITLE
how to use chr-id flag when file has no rsid?

### ISSUE THREAD

**Issue by ukuvainik** [choishingwan/PRSice#207]
**Describe the bug**
I have a gwas without rsid. The file is from Nalls 2019 Lancet Neurology and reads as:

SNP	A1	A2	freq	b	se	p	N_cases	N_controls
chr11:88249377	T	C	0.9931	0.1575	0.1783	0.3771	7161	5356
chr1:60320992	A	G	0.9336	0.0605	0.0456	0.1846	26421	442271

here is the full file: https://drive.google.com/drive/folders/10bGj6HfAXgl-JslpI9ZJIL_JIgZyktxn

I am trying to use the chr-id flag to read in the SNP column and reconstruct the rsid, but I am unsure, how to do it

Could you provide an example syntax, how to tell chr-id that it needs to look up column SNP, and then use the format c:L ?

Thank you!

Uku

**Error Log**
PRSice 2.3.1.e (2020-05-30) 
https://github.com/choishingwan/PRSice
(C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2020-06-25 10:53:14
/home/a40950/programs/prsice231e/PRSice_linux \
    --a1 A1 \
    --a2 A2 \
    --all-score  \
    --bar-levels 5e-08,1e-07,1e-06,1e-05,0.0001,0.001,0.01,0.05,0.1,0.5,1 \
    --base /home/a40950/gwas_base/pd_2019_nalls/pd1st50k.txt \
    --base-maf freq:.90 \
    --beta  \
    --binary-target F \
    --chr-id SNP:c:L \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --fastscore  \
    --ignore-fid  \
    --num-auto 22 \
    --out /home/a40950/gv_uku/pgs/out/mdd_pcg_ukb \
    --pheno /home/a40950/gv_uku/pgs/sample/gv_phens.tsv \
    --pheno-col Nx \
    --pvalue p \
    --seed 163121775 \
    --snp SNP \
    --stat b \
    --target /home/a40950/gv_uku/snp/bed_neopi_filt/chr# \
    --thread 11 \
    --upper 1

Initializing Genotype file: 
/home/a40950/gv_uku/snp/bed_neopi_filt/chr# (bed) 

Start processing pd1st50k 
================================================== 

Base file: 
/home/a40950/gwas_base/pd_2019_nalls/pd1st50k.txt 
Header of file is: 
SNP	A1	A2	freq	b	se	p	N_cases	N_controls 

Reading 100.00%
49999 variant(s) observed in base file, with: 
34467 variant(s) excluded due to MAF threshold 
2790 ambiguous variant(s) excluded 
12742 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

3606 people (1430 male(s), 2122 female(s)) observed 
3606 founder(s) included 

5234720 variant(s) not found in previous data 
0 variant(s) included 

Error: No vairant remained! 

Error: 
Execution halted

**To Reproduce**
If possible, provide a minimum working example for me to reproduce the problem. This can usually speed up the debugging process. 

**Additional context**

**Comment by choishingwan** [comment]
The default of PRSice is to honor the --snp parameter. So in your use case,
you might want to do

--snp SNP --chr-id c:l

(though currently, there isn't anyway to do it if your bim file doesn't
contain the chr header, I might need to think of a better way to handle
that)

Sam

**Comment by ukuvainik** [comment]
Hi Sam!

Thank you for your clarification. I have a chr header in the bim files. Still, the script below ends up having no variants remaining. Could the reason be that I have separate files per each chromosome?

Another Q - how to rebuild the rsid from CHR and BP number on my own? 

Thanks!

Uku


PRSice 2.3.1.e (2020-05-30) 
https://github.com/choishingwan/PRSice
(C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2020-06-28 11:26:14
/home/a40950/programs/prsice231e/PRSice_linux \
    --a1 A1 \
    --a2 A2 \
    --all-score  \
    --bar-levels 5e-08,1e-07,1e-06,1e-05,0.0001,0.001,0.01,0.05,0.1,0.5,1 \
    --base /home/a40950/gwas_base/pd_2019_nalls/nallsEtAl2019_excluding23andMe_allVariants.tab \
    --base-maf freq:.90 \
    --beta  \
    --binary-target F \
    --chr-id c:l \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --fastscore  \
    --ignore-fid  \
    --num-auto 22 \
    --out /home/a40950/gv_uku/pgs/out//pd \
    --pheno /home/a40950/gv_uku/pgs/sample/gv_phens.tsv \
    --pheno-col Nx \
    --pvalue p \
    --seed 3578709927 \
    --snp SNP \
    --stat b \
    --target /home/a40950/gv_uku/snp/bed_neopi_filt/chr# \
    --thread 11 \
    --upper 1

Initializing Genotype file: 
/home/a40950/gv_uku/snp/bed_neopi_filt/chr# (bed) 

Start processing nallsEtAl2019_excluding23andMe_allVariants 
================================================== 

Base file: 
/home/a40950/gwas_base/pd_2019_nalls/nallsEtAl2019_excluding23andMe_allVariants.tab 
Header of file is: 
SNP	A1	A2	freq	b	se	p	N_cases	N_controls 

Reading 100.00%
17510617 variant(s) observed in base file, with: 
12065111 variant(s) excluded due to MAF threshold 
987751 ambiguous variant(s) excluded 
4457755 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

3606 people (1430 male(s), 2122 female(s)) observed 
3606 founder(s) included 

5234720 variant(s) not found in previous data 
0 variant(s) included 

Error: No vairant remained! 

Error: 
Execution halted

**Comment by choishingwan** [comment]
Try doing it again without giving the --snp parameter and see if that
works? If that doesn't, then it is possible that your base and target are
from different genome build, so the position doesn't match.

It is not easy to get rsid from chr and position. Guess you can use some
resources like the dbSNP?

**Comment by ukuvainik** [comment]
when there is no --snp parameter, forced with --no-default,  PRSice gives the following error:

Error: Required column for chr id construction not found in 
       base file! 

to bad about the rebuilding not being straightforward. I imagine there being a giant lookup table for CHR nr and BP

**Comment by ukuvainik** [comment]
I have solved this issue by using an external reference panel. Since Nalls et al use UKB, I also used ukb chr/ bp data, as provided by neale lab variants.tsv.gz 

https://docs.google.com/spreadsheets/d/1kvPoupSzsSFBNSztMzl04xMoSC3Kcx3CrjVf4yBmESU/edit?ts=5b5f17db#gid=227859291

I then merge the GWAS and extracted variants.tsv in R using dtplyr, that is faster.

library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)
pd=vroom::vroom("nallsEtAl2019_excluding23andMe_allVariants.tab")

ref=vroom::vroom("ukb_neale_variants.tsv")
snps=select(ref,variant,chr,pos,rsid,info,ref,alt,minor_AF)

snpslazy=lazy_dt(snps)
pdlazy=lazy_dt(pd)

snpsprep=snpslazy %>% mutate(
  SNP=paste0("chr",chr,":",pos)
)
pdrsid=left_join(pdlazy,snpsprep) 

prsid_out=pdrsid %>% as_tibble()

vroom::vroom_write(prsid_out,path = "nalls_ukbrsid.tsv")

**Comment by choishingwan** [comment]
When you use --no-default, you need to give the --chr and --bp column for
PRSice to work on (which is why there's the error). Glad that you have your
problem solved.

**Comment by saloni-nd** [comment]
Hi @choishingwan , I'm having a similar problem as the one mentioned above.

My base file has these headers, and has rsIDs for the SNP column.

CHR	SNP	BP	A1	A2	MAF_a	MAF_b	INFO	OR	SE	P	ngt	Direction	HetISqt	HetDf	HetPVa	Nca	Nco	Neff 


My target file has this BIM format (no header), and doesn't have rsIDs for the SNP column.

1	1_49298_T_C	0	49298	T	C
1	1_54676_C_T	0	54676	T	C
1	1_86028_T_C	0	86028	C	T


So I've used these commands on PRSice 2.3.3:

Rscript /scratch/users/k1754887/software/PRSice.R \
    --prsice PRSice_linux \
    --base MDD2018_ex23andMe.QC1 \
    --target GS21410_GWAS_merged.QC_1 \
    --binary-target T \
    --pheno phenotype.tsv \
    --cov GS21410_GWAS_merged.PC \
    --base-maf MAF_a:0.01,MAF_b:0.01 \
    --base-info INFO:0.8 \
    --chr-id c_l_a_b \
    --or \
    --out GS21410_GWAS_prsice

But this gives me the error `Error: No vairant remained!`

When I add a header to the BIM file to name the columns "CHR", "SNP", "X", "BP", "A1", "A2", then it gives me a different error which says `Error: Invalid .bed file size for GS21410_GWAS_merged.QC_1.bed`

Is there another way I should use the --chr-id flag to allow it to recognise the variants without rsIDs?

Thank you :)

**Comment by choishingwan** [comment]
bim file should not contain a header.

chr-id is also very funky (as mentioned). If you try manually matching the
two files using chr id e.g. using R, do you manage to find any overlap
variants?

**Comment by saloni-nd** [comment]
Thanks! 

I tried earlier by mapping some of the variants in my target file to rsIDs, and used PRSice with that, which led to an overlap of around 700k variants. 

But I only had a map file with the genomic position, rather than the base change, so I think it's not ideal because there are a lot of variants at the same position but different changes.

Maybe I could use the base file to assign rsIDs to the target file variants, if there aren't any other ways to do it?

**Comment by saloni-nd** [comment]
Just tried that – it worked! Thanks @choishingwan :) 

Related to this (maybe I should make a new issue), is there a way to incorporate GRMs in PRSice, to adjust for genetic relatedness, during the PRS calculation? I've tried a few other packages like glmkin and relmatglmmer but haven't had much success unfortunately.

**Comment by choishingwan** [comment]
Nope. Not that I am aware of.

**Comment by jamesjin63** [comment]
In this Per-phenotype files, they give the introduction of Per-phenotype files 'read_delim(gzfile('file.tsv.bgz'), delim='\t')'
and also list the Variant manifest file:
Variant manifest file[#](https://pan-dev.ukbb.broadinstitute.org/docs/per-phenotype-files/index.html#variant-manifest-file)
Variant manifest (download from [Amazon AWS](https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_release/full_variant_qc_metrics.txt.bgz))

Variant manifest files have RSID inside, we could use variant in bgz file to get RSID

**Comment by saloni-nd** [comment]
Hi @pbchandr, unfortunately I can't remember exactly what I did –

But I checked my changelogs and it looks like I just removed the variants in the target file that weren't in the base file, and then removed the --chr-id flag.

If it helps, here's a link to my script:  https://osf.io/mcrxs

The relevant section starts with the line:
> message("Match rsIDs with BIM file")
