### ISSUE TITLE
Number of sample in phenotype file does not match         number of samples specified in bgen file. Please     check you have the correct phenotype file input.         Note: Phenotype file should have the same number of samples as the bgen file and they should appear in  the same order[BUG]

### ISSUE THREAD

**Issue by MiaoranZhang** [choishingwan/PRSice#208]
**Describe the bug**
the order and number of samples in my phenotype files are the same as my bgen file. however the software consistently reports the error that I have different order or number.
**Error Log**
Please always include the log file generated by PRSice. 
PRSice 2.3.1.e (2020-05-30) 
https://github.com/choishingwan/PRSice
(C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2020-06-30 00:02:56
./PRSice_linux \
    --a1 A1 \
    --a2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base /data/zhangmr/gwas/PRS/iv_base_asso \
    --beta  \
    --binary-target T \
    --bp BP \
    --chr CHR \
    --interval 5e-05 \
    --lower 5e-08 \
    --no-clump  \
    --num-auto 22 \
    --out salt2 \
    --pheno salt_raw.pheno \
    --pvalue P \
    --seed 1768749779 \
    --snp SNP \
    --stat BETA \
    --target-list bgen.txt \
    --thread 10 \
    --type bgen \
    --upper 0.5

Initializing Genotype info from file: bgen.txt (bgen) 

Start processing iv_base_asso 
================================================== 

Base file: /data/zhangmr/gwas/PRS/iv_base_asso 
Header of file is: 
SNP CHR BP A1 A2 BETA SE P 

3 variant(s) observed in base file, with: 
3 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

Error: Number of sample in phenotype file does not match 
       number of samples specified in bgen file. Please 
       check you have the correct phenotype file input. 
       Note: Phenotype file should have the same number of 
       samples as the bgen file and they should appear in 
       the same order 

**To Reproduce**
If possible, provide a minimum working example for me to reproduce the problem. This can usually speed up the debugging process. 

**Additional context**

**Comment by choishingwan** [comment]
Could you please use QCtools or PLINK 2 to check how many samples are there
in your bgen file? PRSice does require the sample names and sample number
to match exactly with those in the bgen file. Sometimes, the --delim
parameter might be helpful for ID matching.

Last but not least, PRS with only 3 SNPs are less likely to be informative
unless they have huge effect sizes.

Sam
