### ISSUE TITLE
"Execution halted" while summary stats file being read

### ISSUE THREAD

**Issue by jessica-agnewblais** [choishingwan/PRSice#209]
Hello,

I am getting the message "Error: execution halted" when I am about a quarter of the way through reading the summary stats file. I'm not sure what the error is here? The log with the error message is below followed by my code in full. 

Many thanks!
Jess

Base file: 
/users/k1469373/brc_scratch/data/adhd_jul2017_2020 
Header of file is: 
CHR	SNP	BP	A1	A2	INFO	OR	SE	P 

Reading 26.62%Error: 
Execution halted

code:

Rscript /users/k1469373/brc_scratch/software/PRSice.R \
--dir . \
--prsice /users/k1469373/brc_scratch/software/PRSice_linux \
--base /users/k1469373/brc_scratch/data/adhd_jul2017_2020 \
--target /users/k1469373/brc_scratch/pelotas/chr# \
--chr CHR \
--snp SNP \
--A1 A1 \
--A2 A2 \
--stat OR \
--pvalue P \
--ld /users/k1469373/brc_scratch/software/PRScs/ldblk_1kg_eur \
--out /users/k1469373/brc_scratch/pelotas/pelotas_prs

**Comment by choishingwan** [comment]
Which version are you using?

Also, how much memory did you give PRSice? For UK Bobank level data, you
will need around 40GB

**Comment by jessica-agnewblais** [comment]
Yes increasing the memory fixed it!

Sorry to bother you again, I am now getting stuck with the ld reference file. I am using 1000 genomes as a reference for ld, but it’s having trouble opening the fam file I think? Currently the 1000 genomes files are divided by chromosome and are hdf5 files. It seems to read the bed file ok but get stuck on the fam?  I get the error:

Initializing Genotype file:
/users/k1469373/brc_scratch/software/PRScs/ldblk_1kg_eur/ldblk_1kg_chr#
(bed)

Loading Genotype info from reference
==================================================

[1;31mError: Cannot open file:
       /users/k1469373/brc_scratch/software/PRScs/ldblk_1kg_eur/ldblk_1kg_chr1.fam[0m

Error:
Execution halted

My code is below. Thank you!!!

Rscript /users/k1469373/brc_scratch/software/PRSice.R \
--dir . \
--prsice /users/k1469373/brc_scratch/software/PRSice_linux \
--base /users/k1469373/brc_scratch/data/adhd_jul2017_2020 \
--target /users/k1469373/brc_scratch/pelotas/chr# \
--chr CHR \
--snp SNP \
--A1 A1 \
--A2 A2 \
--stat OR \
--pvalue P \
--ld /users/k1469373/brc_scratch/software/PRScs/ldblk_1kg_eur/ldblk_1kg_chr# \
--out /users/k1469373/brc_scratch/pelotas/pelotas_prs

**Comment by choishingwan** [comment]
So they are not binary plink format? If it is indeed in hd5 format, then
PRSice won't be able to work with it. We can only handle bgen or binary
plink formats.
Dr Shing Wan Choi
Postdoctoral Fellow
Genetics and Genomic Sciences
Icahn School of Medicine, Mount Sinai, NYC

**Comment by jessica-agnewblais** [comment]
Ah ok, that would explain it then! I will find the 1000 genomes files in the correct format and try it again.

Thanks so much!!!
Jess
