### ISSUE TITLE
Base Data Set Format

### ISSUE THREAD

**Issue by Philippa36** [choishingwan/PRSice#21]
This is quite a simple question, but please can you tell me how I can save my Excel spreadsheet of summary stats (the base file) as a whitespace tab delimited file as specified for the input?

**Comment by choishingwan** [comment]
Go to file -> save as -> Choose file format as tab delimited text

**Comment by Philippa36** [comment]
Thank you for the quick response! I had done that right as it turns out, there must be a different reason my script doesn't work.
