### ISSUE TITLE
PRSice2 --base-maf and --base-info flag issue

### ISSUE THREAD

**Issue by charlisech** [choishingwan/PRSice#210]
**Describe the bug**
When following the [PRS tutorial](https://choishingwan.github.io/PRS-Tutorial/prsice/), the flags `--base-maf` and `--base-info` can not recognize the input and cannot find corresponding columns in the base file.

**Error Log**
```
2020-07-03 13:17:40
./PRSice_mac \
    --A1 A1 \
    --A2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base height.QC \
    --base-info INFO:0.8 \
    --base-maf MAF:0.01 \
    --binary-target F \
    --bp BP \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov-file EUR.cov \
    --interval 5e-05 \
    --lower 5e-08 \
    --missing MEAN_IMPUTE \
    --model add \
    --or  \
    --out EUR \
    --pheno-file EUR.height \
    --pvalue P \
    --score avg \
    --seed 86459283 \
    --snp SNP \
    --stat OR \
    --target EUR.QC \
    --thread 1 \
    --upper 0.5

Warning: INFO field not found in base file,will ignore INFO filtering 
Error: Invalid argument passed to --base-maf: MAF:0.01! Threshold must be numeric 
```
 
**To Reproduce**
The code used is straight from the tutorial.
```
Rscript PRSice.R \
    --prsice PRSice_mac \
    --base Height.QC.gz \
    --target EUR.QC \
    --binary-target F \
    --pheno EUR.height \
    --cov EUR.cov \
    --base-maf MAF:0.01 \
    --base-info INFO:0.8 \
    --stat OR \
    --or \
    --out EUR
```
**Additional context**
All the files used are from the tutorial. In the base file, there are MAF and INFO columns, not sure why PRsice wasn't able to detect them. Below is the first couple lines of the base file, where you can see the MAF and INFO column. 
![Screen Shot 2020-07-03 at 1 19 23 PM](https://user-images.githubusercontent.com/67753577/86488684-dac9eb00-bd2f-11ea-9e7c-f8b642934421.png)

**Comment by echoheqian** [comment]
Hi, are you figure out this problem?

**Comment by choishingwan** [comment]
Have you got similar problem? If so, please send me the full log and command use. Preferably also include the header of your summary statistic file.

**Comment by choishingwan** [comment]
2 2.11b is I so old,  please use the latest version

**Comment by Hybert9108** [comment]
> 
Perfect！Thanks a lot！
