### ISSUE TITLE
Calculating OR for the bar graphs

### ISSUE THREAD

**Issue by LindsayMB** [choishingwan/PRSice#211]
Hi,

I was just wondering if there was a way to calculate the OR of the various bars on the bar graph generated by PRSice? I'm hoping to calculate the OR without running a quantile analysis. 

Thank you!

**Comment by choishingwan** [comment]
Our bar graph reports the R2, not sure if there are any direct translation between the two metric. Why don't you just run the quantile analysis? That should take seconds.
