### ISSUE TITLE
[BUG] dyld symbol not found

### ISSUE THREAD

**Issue by kylec1729** [choishingwan/PRSice#212]
**Describe the bug**
I'm trying to run PRSice, but I'm getting the following error:
Error: Execution halted
The full log is given below.

**Error Log**
PRSice 2.3.1.e (2020-05-30) 
https://github.com/choishingwan/PRSice
(C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2020-07-06 22:41:37
./PRSice_mac \
    --a1 A1 \
    --a2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base TOY_BASE_GWAS.assoc \
    --binary-target T \
    --bp BP \
    --chr CHR \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --interval 5e-05 \
    --lower 5e-08 \
    --num-auto 22 \
    --or  \
    --out PRSice \
    --pvalue P \
    --seed 3339972190 \
    --snp SNP \
    --stat OR \
    --target TOY_TARGET_DATA \
    --thread 1 \
    --upper 0.5

Initializing Genotype file: TOY_TARGET_DATA (bed) 

Start processing TOY_BASE_GWAS 
================================================== 

Base file: TOY_BASE_GWAS.assoc 
Header of file is: 
SNP CHR BP A1 A2 P OR 

91062 variant(s) observed in base file, with: 
2226 variant(s) located on haploid chromosome 
88836 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

2000 people (1024 male(s), 976 female(s)) observed 
2000 founder(s) included 

Warning: Currently not support haploid chromosome and sex 
         chromosomes 

88836 variant(s) included 

There are a total of 1 phenotype to process 

Start performing clumping 

Number of variant(s) after clumping : 88836 

Processing the 1 th phenotype 

Phenotype is a binary phenotype 
1000 control(s) 
1000 case(s) 

Start Processing
Processing 100.00%dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Volumes/My Passport for Mac/Research/Comparison/jun19/./PRSice_mac
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Volumes/My Passport for Mac/Research/Comparison/jun19/./PRSice_mac
  Expected in: /usr/lib/libSystem.B.dylib

**Additional context**
I'm using a Mac on El Capitan (post-Mountain Lion version).

**Comment by choishingwan** [comment]
It might be due to the version of your mac. You can try compiling the
software yourself and see if it works.

in PRSice directory, do

g++ -std=c++17 -O3 -DNDEBUG -isystem lib/ -isystem lib/eigen -I inc src/*
-lpthread -lz -o PRSice

If you don't have the lib/eigen, then you might get it with git submodule
update --init -- lib/eigen/

And if you can't compile it, then it is likely that your system OS is
simply too old (or you need to update your g++, though more likely than not
that your OS is the problem)

(If you have cmake install, do

mkdir build
cd build
cmake ../
make
)

**Comment by kylec1729** [comment]
> It might be due to the version of your mac. You can try compiling the software yourself and see if it works. in PRSice directory, do g++ -std=c++17 -O3 -DNDEBUG -isystem lib/ -isystem lib/eigen -I inc src/* -lpthread -lz -o PRSice If you don't have the lib/eigen, then you might get it with git submodule update --init -- lib/eigen/ And if you can't compile it, then it is likely that your system OS is simply too old (or you need to update your g++, though more likely than not that your OS is the problem) (If you have cmake install, do mkdir build cd build cmake ../ make )

Thanks - it looks like my compiler is too old (need to update OS). Is there any other software that I can use to make those beautiful quantile plots that you have in PRSice?

**Comment by choishingwan** [comment]
If you have the PRS (possibly calculated from plink), then you should be
able to use some of the scripts within the PRSice Rscript to generate the
quantile plot. If you open the PRSice Rscript in Rstudio, you should be
able to find a section of code called Quantile Plots, which contains all
the scripts related to quantile plot generation. I also found a script
called quantile.R which was used in our previous summer school, which is a
tone downed version of the script used in PRSice. Maybe that'd help

Good luck

**Comment by kylec1729** [comment]
Thanks again. In case I can't figure out how to work the quantile script given in PRSice.R, where would I be able to find the simpler version quantile.R?

**Comment by choishingwan** [comment]
Always forgot github automatically remove any attached scripts for security reasons. Here is the link to the script 

https://www.dropbox.com/s/3vink0uaskao2r4/Quantile.R?dl=0

It s still rather complex and I wasn't doing a whole lot of commenting there. Do feel free to ask if you need any help.
