### ISSUE TITLE
Quantiles OR range 0 to Inf

### ISSUE THREAD

**Issue by bhuwankhatri11** [choishingwan/PRSice#215]
Hi,

I am getting OR range for quantile plot from 0 to Inf. Will you please help me to figure out what might have happened?

Quantile	OR	CI.U	CI.L	Group	N
1	1	1	1	0	1989
2	0.993374081719368	Inf	0	0	1989
3	0.981192113077211	Inf	0	0	1989
4	1.00717252018387	Inf	0	0	1989
5	1.00346804952161	Inf	0	0	1989
6	1.00830854369736	Inf	0	0	1989
7	1.00703476727274	Inf	0	0	1989
8	1.04670954700994	Inf	0	0	1989
9	4162685678.69933	Inf	0	0	1989
10	4.5464487912356e+19	Inf	0	0	1989

My code look like this:
./PRSice_linux \
    --a1 A1 \
    --a2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base test_re.assoc \
    --binary-target T \
    --bp BP \
    --chr CHR \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov covars.txt \
    --cov-col @PC[1-4] \
    --exclude exlcude_SNPs.list \
    --interval 5e-05 \
    --lower 5e-08 \
    --num-auto 22 \
    --or  \
    --out test_re_nonambig_match_quantiles_ref1_exlcudeInversion \
    --pvalue P \
    --seed 2701661039 \
    --snp SNP \
    --stat OR \
    --target test_re \
    --thread 1 \
    --upper 0.5

I will appreciate your help.
Thanks!

BK

**Comment by choishingwan** [comment]
Likely the SD is too high. What's your sample size, and how does your other
graph looks like?

**Comment by bhuwankhatri11** [comment]
Thank you for quick response.

Barplot 
![image](https://user-images.githubusercontent.com/18176881/87703059-d9e97e00-c75f-11ea-89df-06312ba8dc56.png)

High Resolution plot
![image](https://user-images.githubusercontent.com/18176881/87703141-f7b6e300-c75f-11ea-8a20-754a07344ac9.png)

I generated base data from target data. Is it due to that reason?

**Comment by choishingwan** [comment]
Yes, using the same data for both base and target will lead to invalid
results.

**Comment by bhuwankhatri11** [comment]
Hi,
What can be done in my case where the base data was generated using target data and I am more interested in finding proportion of variance of the disease case-control status explained by PRS? Is there any way PRSice can handle it?
Thanks

**Comment by choishingwan** [comment]
You cannot run a PRS analysis if you use the same data to generate both base and target. The only way to do it is to find an external GWAS summary statistics
