### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sandyyy123** [choishingwan/PRSice#216]
Hi,

The PRSice is unable to recognize my covariate file column headings. Please help.

PRSice 2.2.11.b (2019-10-16) 
https://github.com/choishingwan/PRSice
(C) 2016-2019 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2020-07-24 14:16:46
./PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base prs_base_courage_pooled.assoc \
    --binary-target T \
    --bp bp \
    --chr chr \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov prs_cov_pooled.csv \
    --cov-col PC4,PC2,PC3,PC1,SEX \
    --interval 5e-05 \
    --lower 5e-08 \
    --or  \
    --out PRSice \
    --perm 10000 \
    --pheno prs_phenotype_pooled.csv \
    --pheno-col PHENOTYPE \
    --pvalue pvalue \
    --score sum \
    --seed 718817049 \
    --snp snp \
    --stat OR \
    --target for_combined \
    --thread 1 \
    --upper 0.5

Warning: Covariate(s) missing from file: 
         PC4,PC2,PC3,SEX,PC1. Header of file is: 
         PC4,PC2,PC3,SEX,PC1 
Error: No valid Covariate!

**Comment by choishingwan** [comment]
Unfortunately, we don't currently accept CSV. Your file needs to be tab
delimited for PRSice to work. Sorry about that.

**Comment by Sandyyy123** [comment]
Thanks for clarifying the same. I am unfortunately landing with another issue.
PRSice 2.2.11.b (2019-10-16) 
https://github.com/choishingwan/PRSice
(C) 2016-2019 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2020-07-24 15:02:39
./PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base prs_base_courage_pooled.assoc \
    --binary-target T \
    --bp bp \
    --chr chr \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov prs_cov_pooled.txt \
    --cov-col PC4,PC2,PC3,PC1,SEX \
    --ignore-fid  \
    --interval 5e-05 \
    --lower 5e-08 \
    --or  \
    --out PRSice \
    --perm 10000 \
    --pheno prs_phenotype_pooled.txt \
    --pheno-col PHENOTYPE \
    --pvalue pvalue \
    --score sum \
    --seed 2379389198 \
    --snp snp \
    --stat OR \
    --target for_combined \
    --thread 1 \
    --upper 0.5

Initializing Genotype file: for_combined (bed) 

Start processing prs_base_courage_pooled 
================================================== 

Base file: prs_base_courage_pooled.assoc 
6 variant(s) observed in base file, with: 
6 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

23746 people (12826 male(s), 10920 female(s)) observed 
23746 founder(s) included 

6 variant(s) included 

Check Phenotype file: prs_phenotype_pooled.txt 
Column Name of Sample ID: IID 
Note: If the phenotype file does not contain a header, the 
column name will be displayed as the Sample ID which is ok. 
There are a total of 1 phenotype to process 

Start performing clumping 

32598 MB RAM detected; reserving 1 MB for clumping 

Allocated 1 MB successfully 

Number of variant(s) after clumping : 6 

PHENOTYPE is a binary phenotype 
10413 control(s) 
13333 case(s) 

Processing the covariate file: prs_cov_pooled.txt 
============================== 

Include Covariates: 
Name	Missing	Number of levels 
PC4	0	- 
PC2	0	- 
PC3	0	- 
SEX	0	- 
PC1	0	- 

23746 sample(s) with invalid covariate: 

Error: All samples removed due to missingness in covariate 
       file!

**Comment by choishingwan** [comment]
Can you check if your covariate file is valid? (Did you code sex as M / F
or 1 /2?) If you sex coding is M/F, you will need to add --cov-factor SEX
in your command so that PRSice will parse the M / F correctly.

Sam

**Comment by Sandyyy123** [comment]
Sex is already 1 and 2 and PCs are positive and negative intergers

**Comment by choishingwan** [comment]
Mind sending me the first few line of your covariate file so that I can
check?

**Comment by Sandyyy123** [comment]
PC4	PC2	PC3	SEX	PC1
-0.0125841	-0.00407448	0.000559757	1	-0.000204557
0.000476067	-0.00251433	0.00707994	1	0.000817135
0.00167305	0.0189565	0.00335686	2	0.0141195

**Comment by choishingwan** [comment]
You need FID and IID in your covariate file. Otherwise, PRSice wouldn't be
able to match your covariates to your genotype data. Might also want to use
the later version of PRSice. We are currently at 2.3.2.

Sam

**Comment by Sandyyy123** [comment]
Great. Thanks. It worked. Sorry for the trouble.

**Comment by choishingwan** [comment]
Glad it works.

**Comment by Sandyyy123** [comment]
One quick question: I specified Phenotype as 1 and 2 as opposed to case and control in the phenotype file. Is it correct? Earlier I had the impression phenotype file should contain covariates. But after reading your earlier github issues, I moved them to covariate files.

**Comment by choishingwan** [comment]
Yes, 1 and 2 is fine. It's ok for your covariates to be within the same
file as the covariate as long as you also put the phenotype file to the
--cov command.

**Comment by Sandyyy123** [comment]
Thanks
