### ISSUE TITLE
[BUG]'Execution halted' during processing 

### ISSUE THREAD

**Issue by charlisech** [choishingwan/PRSice#218]
**Describe the bug**
When running prcise2, all the input files were read in correctly, however error occurs at the processing stage. NOTE: I have run this exact same job but without the --keep flag, and it was able to finish processing, the problem seem to only occur when I added the keep flag.

**Error Log**
PRSice 2.3.2 (2020-07-10) 
https://github.com/choishingwan/PRSice
(C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2020-08-04 00:16:10
./PRSice_linux \
    --a1 ALLELE1 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base chronic_pain-bgen.stats.gz \
    --base-info INFO:0.9 \
    --beta  \
    --binary-target T \
    --bp BP \
    --chr CHR \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov full_pc.txt \
    --extract johnston-pain8_v2.valid \
    --ignore-fid  \
    --interval 5e-05 \
    --keep pain_8_w_random_control_keep \
    --lower 5e-08 \
    --num-auto 22 \
    --out johnston-pain8_21_3_random \
    --pheno pain_8_pheno_new \
    --pvalue P_BOLT_LMM \
    --seed 4087242625 \
    --snp SNP \
    --stat BETA \
    --target /home/charlise/scratch/21 \
    --thread 1 \
    --type bgen \
    --upper 0.5

Initializing Genotype file: /home/charlise/scratch/21 
(bgen) 

Start processing chronic_pain-bgen.stats 
================================================== 

SNP extraction/exclusion list contains 5 columns, will 
assume first column contains the SNP ID 

Base file: chronic_pain-bgen.stats.gz 
GZ file detected. Header of file is: 

SNP	CHR	BP	GENPOS	ALLELE1	ALLELE0	A1FREQ	INFO	CHISQ_LINREG	P_LINREG	BETA	SE	CHISQ_BOLT_LMM_INF	P_BOLT_LMM_INF	CHISQ_BOLT_LMM	P_BOLT_LMM 

Reading 100.00%
9926106 variant(s) observed in base file, with: 
9818551 variant(s) excluded based on user input 
107555 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

487409 people (0 male(s), 0 female(s)) observed 
106815 founder(s) included 

1261K SNPs processed in /home/charlise/scratch/21.bgen   
1153544 variant(s) not found in previous data 
2 variant(s) with mismatch information 
57 ambiguous variant(s) excluded 
107555 variant(s) included 

Phenotype file: pain_8_pheno_new 
Column Name of Sample ID: 4287785 
Note: If the phenotype file does not contain a header, the 
column name will be displayed as the Sample ID which is 
expected. 

There are a total of 1 phenotype to process 

Start performing clumping 

Clumping Progress: 100.00%
Number of variant(s) after clumping : 5088 

Processing the 1 th phenotype 

Phenotype is a binary phenotype 
100000 control(s) 
6815 case(s) 

Processing the covariate file: full_pc.txt 
============================== 

Include Covariates: 
Name	Missing	Number of levels 
Genetic_sex	0	- 
PC_1	0	- 
PC_2	0	- 
PC_3	0	- 
PC_4	0	- 
PC_5	0	- 
PC_6	0	- 
PC_7	0	- 
PC_8	0	- 
PC_9	0	- 
PC_10	0	- 
PC_11	0	- 
PC_12	0	- 
PC_13	0	- 
PC_14	0	- 
PC_15	0	- 
PC_16	0	- 
PC_17	0	- 
PC_18	0	- 
PC_19	0	- 
PC_20	0	- 
PC_21	0	- 
PC_22	0	- 
PC_23	0	- 
PC_24	0	- 
PC_25	0	- 
PC_26	0	- 
PC_27	0	- 
PC_28	0	- 
PC_29	0	- 
PC_30	0	- 
PC_31	0	- 
PC_32	0	- 
PC_33	0	- 
PC_34	0	- 
PC_35	0	- 
PC_36	0	- 
PC_37	0	- 
PC_38	0	- 
PC_39	0	- 
PC_40	0	- 

After reading the covariate file, 106815 sample(s) included 
in the analysis 

Start Processing
Processing 0.43%Error: 
Execution halted

**To Reproduce**
If possible, provide a minimum working example for me to reproduce the problem. This can usually speed up the debugging process. 

**Additional context**
the --keep flag used decreased the control number from around 180000 to 100000.

**Comment by choishingwan** [comment]
There seems to be some persistent problem with bgen. Will have to double
check the code but your information are very helpful. I will start looking
into it once I have the time.

Thanks

Sam

**Comment by choishingwan** [comment]
Thanks to your report, I am able to pinpoint the bug and have it fixed in 2.3.3. Thank you.
