### ISSUE TITLE
Receiving error messages regarding base file, despite changing target bim file

### ISSUE THREAD

**Issue by ArcadiaMerlot** [choishingwan/PRSice#219]
When trying to run PRS, I have encountered the following errors:

> Warning, CHR not found in basefile

> Warning A2 not found in basefile

> Warning BP not found in basefile

> Error A1 not found in basefile

> Error P not found in basefile

> Error Column for the P value must be provided!

I spoke to my supervisor to which he said editing the bim file of the target file is a way to correct for this without editing the basefile. As a result, he sent a series of commands to correct for this, but as seen in the error messages above, it didn't work. Data is from the Ben Neale biobank. Should I go to reverting the basefile rather than the bim target? If so, how can I do this?

**Comment by choishingwan** [comment]
Hi,

The log file is rather clear, you must have the A1 and P column in your
base file for PRSice to run.

Sam
