### ISSUE TITLE
Target Data Set

### ISSUE THREAD

**Issue by Philippa36** [choishingwan/PRSice#22]
I have my target data set in separate files by chromosome, named chr1-geno.qc.bed, chr1-geno.qc.bim, chr1-geno.qc.fam,  for each chromosome. I've used geno as list T in the arguements in the script, but I'm not sure how to direct to the target data set.

Im also not sure how to successfully run the alternative option of merging the plink files to make a single target data file.

Thank you

**Comment by choishingwan** [comment]
If you are using PRSiceV1.25

geno.as.list T target chrCHRNUM-geno.qc

will do

If you are using the latest PRSice (the one you download from release in this github)

--target chr#-geno.qc

is enough

**Comment by Philippa36** [comment]
That's great - thank you very much.
