### ISSUE TITLE
Getting All the Same PRS in PRS.best 

### ISSUE THREAD

**Issue by HannahR1** [choishingwan/PRSice#220]
Hi Sam,

So I have run PRSice on a sample of 106 individuals, 53 which are controls and 53 which are test cases. When running PRSice I seem to be getting all the same PRS for each individual.

PRSice.R --dir . --./PRSice_linux --base basefile --target mergedGenomeLNKAnc --thread 1 --a1 ALT --a2 REF --snp SNP --beta --stat all_inv_var_meta_beta --binary-target T --pvalue all_inv_var_meta_p

Here is what the PRSice .best file looks like:
d54f4d2c-9b1e-4a4f-a21a-59ab07425a93 d54f4d2c-9b1e-4a4f-a21a-59ab07425a93 Yes -0.062335
6c531200-d09a-4b6d-a30d-dd3d9ca4cbf0 6c531200-d09a-4b6d-a30d-dd3d9ca4cbf0 Yes -0.062335
922f420d-dbf2-40af-a712-6da062cec326 922f420d-dbf2-40af-a712-6da062cec326 Yes -0.062335
4622feae-5216-466a-90a6-704da2dd0e7c 4622feae-5216-466a-90a6-704da2dd0e7c Yes -0.062335
4d6eae1d-18e1-4183-ad80-c393c1c943aa 4d6eae1d-18e1-4183-ad80-c393c1c943aa Yes -0.062335
88b639cd-f358-4684-882c-7881162d5e51 88b639cd-f358-4684-882c-7881162d5e51 Yes -0.062335
2556ca53-88f0-4ac3-b3be-d124b0ec73aa 2556ca53-88f0-4ac3-b3be-d124b0ec73aa Yes -0.062335
6a1b8d2f-474a-4896-a9b2-e1d934021f90 6a1b8d2f-474a-4896-a9b2-e1d934021f90 Yes -0.062335
382f8f34-c91e-4d95-934a-2a81991dd74a 382f8f34-c91e-4d95-934a-2a81991dd74a Yes -0.062335
9d6bdebb-26d8-4848-b2cd-81c2f342d256 9d6bdebb-26d8-4848-b2cd-81c2f342d256 Yes -0.062335
9dd07cc4-d6cd-40c4-8b11-9c0992e242f5 9dd07cc4-d6cd-40c4-8b11-9c0992e242f5 Yes -0.062335

Do you know possible reasons for why this could be?
Thanks!

**Comment by choishingwan** [comment]
Which version? Also what does the summary file look like?
