### ISSUE TITLE
Viewing quantile specific IIDs

### ISSUE THREAD

**Issue by ssharma08** [choishingwan/PRSice#223]
Hi,

I was wondering how I could view the sample IIDs within each specific quantile? I know the quantile.txt output shows you the number of samples within each quantile but can I view which samples they are? For example, if I wanted to make a file with all the sample IIDs and polygenic risk scores just from quantile 5 - how could I do that?

Thank you!

**Comment by choishingwan** [comment]
As of now, that information wasn't available. You can maybe modify the
Rscript to generate that. I think you might be able to get an output call
in line 994 to output the pheno.merge object. That should in theory contain
both the quantile information and the sample ID.

**Comment by ssharma08** [comment]
I see - thank you!
