### ISSUE TITLE
Error: Invalid .bed file size

### ISSUE THREAD

**Issue by Qiaolan** [choishingwan/PRSice#226]
**Describe the bug**
I got an error about bed file. It shows "Error: Invalid .bed file size for ...".

**Error Log**

PRSice 2.3.3 (2020-08-05) 
https://github.com/choishingwan/PRSice
(C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2020-09-08 19:48:06
/fs/ess/PAS1501/gaolab/software/PRSice_2.3.3/PRSice_linux \
    --a1 A1 \
    --a2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base /fs/ess/PAS1501/gaolab/qldeng/AD_Eden_PRS/plink_casecontrol/mtv/base/base_sumstat_qc_OR_mtv \
    --binary-target T \
    --bp BP \
    --chr CHR \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov /fs/ess/PAS1501/gaolab/qldeng/AD_Eden_PRS/pheno/pheno.mtv \
    --cov-col sex,aaoaae \
    --cov-factor sex \
    --interval 5e-05 \
    --lower 5e-08 \
    --num-auto 22 \
    --or  \
    --out /fs/ess/PAS1501/gaolab/qldeng/AD_Eden_PRS/plink_casecontrol/mtv/prs/prs_meta_leav1out_casecontrol_mtv \
    --perm 10000 \
    --pheno /fs/ess/PAS1501/gaolab/qldeng/AD_Eden_PRS/pheno/pheno.mtv \
    --pheno-col status \
    --print-snp  \
    --pvalue P \
    --seed 1870649734 \
    --snp SNP \
    --stat OR \
    --target /fs/ess/PAS1501/gaolab/qldeng/AD_Eden_PRS/plink_casecontrol/mtv/target/target_geno_mtv_chr# \
    --thread 1 \
    --upper 0.5

Initializing Genotype file: 
/fs/ess/PAS1501/gaolab/qldeng/AD_Eden_PRS/plink_casecontrol/mtv/target/target_geno_mtv_chr# 
(bed) 

Start processing base_sumstat_qc_OR_mtv 
================================================== 

Base file: 
/fs/ess/PAS1501/gaolab/qldeng/AD_Eden_PRS/plink_casecontrol/mtv/base/base_sumstat_qc_OR_mtv 
Header of file is: 
SNP A1 A2 P OR CHR BP 

7851932 variant(s) observed in base file, with: 
1185823 ambiguous variant(s) excluded 
6666109 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

535 people (182 male(s), 261 female(s)) observed 
535 founder(s) included 

Error: Invalid .bed file size for 
       /fs/ess/PAS1501/gaolab/qldeng/AD_Eden_PRS/plink_casecontrol/mtv/target/target_geno_mtv_chr2.bed 

**To Reproduce**
If possible, provide a minimum working example for me to reproduce the problem. This can usually speed up the debugging process. 

**Additional context**

prs still runs successfully if I replace the "#" with the chromosome number of error, e.g. chr2 here.

Thanks!

**Comment by choishingwan** [comment]
Do you mind checking if all your bed files have the same sample size?
PRSice assumes all your files to have the same sample size and uses that to
estimate the bed size. So if your chr1 and chr2 file contain different
numbers of samples, you will see the invalid bed size error.

**Comment by Qiaolan** [comment]
> Do you mind checking if all your bed files have the same sample size? PRSice assumes all your files to have the same sample size and uses that to estimate the bed size. So if your chr1 and chr2 file contain different numbers of samples, you will see the invalid bed size error.

Thanks for your reply! I think this makes sense, because each chr was filtered in plink by --mind 0.02 leading to possible different sample sizes. I will keep the same sample size and try again. Thanks!

**Comment by choishingwan** [comment]
That's why then. When doing mind, you should really do it genome wide. As
your input breaks our assumptions on how bed bim fam files behave, it
breaks the program.

Sam
