### ISSUE TITLE
Error in plotting

### ISSUE THREAD

**Issue by jessica-agnewblais** [choishingwan/PRSice#227]
Hi,
I am running PRSice on the Rosalind cluster, but I am having a problem creating the figures. I get the error below:

Begin plotting
Current Rscript version = 2.3.1.c
Plotting Bar Plot
Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  : 
  unable to start device PNG
Calls: process_plot ... bar_plot -> plot.bar -> ggsave -> dev -> <Anonymous>
In addition: Warning message:
In grDevices::png(..., res = dpi, units = "in") :
  unable to open connection to X11 display ''
Execution halted

The code I am using is below. Any advice would be much appreciated!
module add apps/prsice/2.2.12 
module add apps/plink/1.9.0b6.10
module add apps/R/3.6.0

Rscript /users/k1469373/brc_scratch/software/PRSice.R \
--dir . \
--prsice /users/k1469373/brc_scratch/software/PRSice_linux \
--base /users/k1469373/brc_scratch/data/adhd_jul2017_2020 \
--target /users/k1469373/brc_scratch/pelotas/chr# \
--chr CHR \
--snp SNP \
--A1 A1 \
--A2 A2 \
--stat OR \
--pvalue P \
--ld /users/k1469373/brc_scratch/data/1000G_EUR_Phase3_plink/1000G.EUR.QC.chr# \
--quantile 10 \
--quant-ref 5 \
--pheno /users/k1469373/brc_scratch/data/pelotas_pheno_excl.txt \
--ignore-fid \
--pheno-col age11 \
--bar-levels 1,0.5,0.1,0.05,0.001 \
--all-score \
--fastscore \
--out /users/k1469373/brc_scratch/pelotas/prs_child_lev

**Comment by choishingwan** [comment]
It's likely the x11 plotting system, which R depends on, are missing.

By Rosalind, do you mean the rosalind server of King's College London?

Did you do module load apps/R/3.6.0 before you run PRSice? If that doesn't
help, then maybe also do module load libs/png/1.6.37


Sam

**Comment by jessica-agnewblais** [comment]
Thanks for your quick reply! Yes, I am running on King’s Rosalind server. I did load R but I will try with libs/png/1.6.37 as well right now.

Many thanks,
Jess

**Comment by jessica-agnewblais** [comment]
Hmm I added in module load libs/png/1.6.37 but I am still getting the same error. Code below:

#!/bin/bash
#SBATCH -p shared
#SBATCH -J Test
#SBATCH --mem 20G
#SBATCH -n 1


module add apps/prsice/2.2.12
module add apps/plink/1.9.0b6.10
module add apps/R/3.6.0
module add libs/png/1.6.37


Rscript /users/k1469373/brc_scratch/software/PRSice.R \
--dir . \
--prsice /users/k1469373/brc_scratch/software/PRSice_linux \
--base /users/k1469373/brc_scratch/data/adhd_jul2017_2020 \
--target /users/k1469373/brc_scratch/pelotas/chr# \
--chr CHR \
--snp SNP \
--A1 A1 \
--A2 A2 \
--stat OR \
--pvalue P \
--ld /users/k1469373/brc_scratch/data/1000G_EUR_Phase3_plink/1000G.EUR.QC.chr# \
--quantile 10 \
--bar-levels 1,0.5,0.1,0.05,0.001 \
--all-score \
--fastscore \
--out /users/k1469373/brc_scratch/pelotas/prs_child_lev

**Comment by choishingwan** [comment]
Try and see if this works:


library(ggplot2)
dat <- data.table(x=rnorm(1000), y=rnorm(1000))
x <- ggplot(dat, aes(x,y))+geom_point()
ggsave("test.png", x)

Do you see the same error?

I just tried to do some plotting on rosalind and didn't encounter the error
message. If this persists, you might need to contact rosalind support.

**Comment by jessica-agnewblais** [comment]
Yes, I am getting the same error when I run that code. Does that suggest I should contact Rosalind support?

Thanks again,
Jess

**Comment by choishingwan** [comment]
Yes, my test code was basically testing if the R plotting function is
working. And from what you see, it seems like for some reason, the R
plotting doesn't seems to work on your account. I don't really know why as
I have checked that the plotting on rosalind should in theory work.
