### ISSUE TITLE
Is AUC available in PRSice?

### ISSUE THREAD

**Issue by Qiaolan** [choishingwan/PRSice#228]
Hi!

I am wondering if it is available to plot AUC in PRSice? Also, is there any measure of goodness of fit specifically for binary traits?

Thanks!

**Comment by choishingwan** [comment]
It was requested, but I haven't got time to implement it as of now.

**Comment by sariya** [comment]
Sorry for revamping this. Is there a way I can calculate AUC/ROC from the PRS generated for the individuals provided?

**Comment by sariya** [comment]
https://www.rdocumentation.org/packages/pROC/versions/1.16.2/topics/auc
this maybe of help to someone in future.

**Comment by Qiaolan** [comment]
> https://www.rdocumentation.org/packages/pROC/versions/1.16.2/topics/auc
> this maybe of help to someone in future.

Excuse me for another question. I am also using LDpred2 and wondering if AUC is available in LDpred2. Thanks!

**Comment by sariya** [comment]
Yes, LDpred2 tutorial walks through steps to create AUC.
