### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Philippa36** [choishingwan/PRSice#23]
Hi,

I'm getting the following error message:
 #  Read in Command Line Arguments & interpret 
 # 
 ################################# 
Error in assign(args[i], value, inherits = TRUE) : 
  cannot change value of locked binding for 'T'
Calls: parseCommandArgs -> assign
Execution halted

Please help?

**Comment by choishingwan** [comment]
could you please post your full command?

**Comment by Philippa36** [comment]
R --file= PRSice_v1.25.R-q --args \
plink \
base/gpfs/home/wellsp/PRS_All.Files/PRS_SumStats.prn \
target chrCHRNUM-geno.qc \
slower 0 \
sinc 0.02 \
supper 0.3 \
clump.snps T \
geno.as.list T \
no.regression T \
covary F \
best.thresh.on.bar F \
report.individual.scores T

**Comment by Philippa36** [comment]
R --file= PRSice_v1.25.R-q --args \
plink \
base/gpfs/home/wellsp/PRS_All.Files/PRS_SumStats.prn \
target chrCHRNUM-geno.qc \
slower 0 \
sinc 0.02 \
supper 0.3 \
clump.snps T \
geno.as.list T \
no.regression T \
covary F \
best.thresh.on.bar F \
report.individual.scores T

**Comment by Philippa36** [comment]
The back slashes aren't showing up when I post but I have used these at the end of every line

**Comment by Philippa36** [comment]
edit - I have a space after base beforte specifying the file.

Thank you

**Comment by choishingwan** [comment]
you have forgot to provide an argument for plink. you need to provide the plink binary for PRSice to work

**Comment by Philippa36** [comment]
Thanks for the quick response, I thought I didn't need to specify the location, but amended the code to include this(below) and still get the same error message


R --file=PRSice_v1.25.R -q --args \
plink ./plink_1.903bx_mac_160914 \
base /gpfs/home/wellsp/PRS_All.Files/PRS_SumStats.prn \
target target chrCHRNUM-geno.qc \
slower 0 \
sinc 0.02 \
supper 0.3 \
geno.as.list T \
no.regression T \
covary F \
best.thresh.on.bar F \
report.individual.scores T \
clump.snps T

**Comment by Philippa36** [comment]
I've now tried 

plink plink_1.903b3x \

I get the same error message still. 
Any suggestions appreciated! Thank you again

**Comment by choishingwan** [comment]
you've got two target: 
**target target** chrCHRNUM-geno.qc 
Also, it is usually worth trying to run the script on the same line, that avoid some problem with the \\

**Comment by Philippa36** [comment]
Thank you, I'm not sure how I missed that! I've run it again but now get a different error message - 
# 
 #  Check options match 
 # 
 ################################# 
[1] "Using current directory as working directory"
 ################################# 
 # 
 #  Check base input format 
 # 
 ################################# 
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 10 elements
Calls: read.table -> scan
Execution halted

**Comment by Philippa36** [comment]
My code is now on 1 line: 
R --file=PRSice_v1.25.R -q --args plink plink_1.903b3x base /gpfs/home/wellsp/PRS_All.Files/PRS_SumStats.prn target chrCHRNUM-geno.qc slower 0 sinc 0.02 supper 0.3 geno.as.list T no.regression T covary F best.thresh.on.bar F report.individual.scores T clump.snps T

Please also see this PDF copy of base data set,please could you check the format?

[PRS_SumStats.pdf](https://github.com/choishingwan/PRSice/files/1340267/PRS_SumStats.pdf)

Thank you for your patience

**Comment by Philippa36** [comment]
I'm now getting this mesage:

 #  Check options match 
 # 
 ################################# 
[1] "Using current directory as working directory"
 ################################# 
 # 
 #  Check base input format 
 # 
 ################################# 
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 12 elements
Calls: read.table -> scan
Execution halted

**Comment by choishingwan** [comment]
Judging from your input, your base file's header has column that contains space. Try to replace the space with things like _. This should solve your problem

On a side note, it look as if your base file only contains a handful of SNPs. It is usually better if you use the SNPs from the whole GWAS as the base file

**Comment by Philippa36** [comment]
Thank you, I've just amended that and still get a similar error further down -
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 69 did not have 10 elements

I've checked and there's no space or anything diffeent I can see in that line

**Comment by choishingwan** [comment]
That's likely that on line 69, you don't have 10 inputs (maybe some missing numbers?)

**Comment by Philippa36** [comment]
Thank you, that was a problem.

It now says ERROR: No SNP's present in both base and target dataset. Exiting.

But, I don't think this is true? (I'm using the TwinsUK data)

**Comment by choishingwan** [comment]
If the rs id on your base and target data does not match, then it will show this error message. 

You can easily check that manually

**Comment by Philippa36** [comment]
Hi there,
I've checked and the rs IDs do match. It must be something else to do with the format of the data? I will try some different things but please let me know if you have any ideas.
Thank you

**Comment by choishingwan** [comment]
Without the full data, it is impossible to know. Some of the guesses are

1. The rs id match but their alleles doesn't (e.g. Capital letter vs small case)
2. All the SNPs are ambiguous (A/T, C/G)

**Comment by Philippa36** [comment]
Thank you for your help and for being so responsive, hoping I can find the problem.
