### ISSUE TITLE
data type: bgen || large number of SNP mismatch and core dump

### ISSUE THREAD

**Issue by sariya** [choishingwan/PRSice#231]
hi sam,
I'm using PRSice 2.3.3 (2020-08-05) with bgen file format. The bgen files were created using qctool from the IMPUTE2 data. I also create bgen index.

I'm running into two issues:

1) there are 754272 SNP mismatches.
I may have vague idea of this. Probably the reference and alt allele bgen makes from the IMPUTE2 are wrong? 
The output from IMPUTE2 doesn't specify effect or non effect allele. I hope I'm making some sense.  

2) There's a core dump. Please see attached log. [PRS_unrelated.log](https://github.com/choishingwan/PRSice/files/5268716/PRS_unrelated.log)

thanks.

**Comment by choishingwan** [comment]
Large numbers of mismatches are likely due to differences in build. You can
check the mismatch file to see if that is the case.

For the core dump, it is likely due to insufficient memory. I will work on
something to reduce the memory requirement of PRSice after the grant
application deadline.
