### ISSUE TITLE
Calculate PRS at specific threshold

### ISSUE THREAD

**Issue by mvacher** [choishingwan/PRSice#235]
Hi,

I'm not sure if this is a bug or intended behaviour.
I'm trying to calculate a PRS using a specific p-value threshold. To do so, I use the --upper and --lower switches to lock the p-value range to test to the desired threshold like this:

```
Rscript PRSice.R \
    --prsice ./PRSice_mac \
    --base TOY_BASE_GWAS.assoc \
    --target TOY_TARGET_DATA \
    --lower 0.005 \
    --upper 0.005 \
    --out test \
    --print-snp \
    --all-score
```

This seems to work but in addition to the 0.005 threshold, a threshold of 1 is also used.

```
$ cat test.summary
Phenotype	Set	Threshold	PRS.R2	Full.R2	Null.R2	Prevalence	Coefficient	Standard.Error	P	Num_SNP
-	Base	1	0.0291467	0.0291467	0	-	48.6308	7.43662	6.17769e-11	88836
```

```
$ head test.all.score
FID IID 0.005 1
CAS_1 CAS_1         -0.0651589222    -0.0143159198
CAS_2 CAS_2         0.104254804      -0.00752766754
CAS_3 CAS_3         0.100395908      -0.00508844193
...
```

How can I prevent this ?

Thanks

**Comment by choishingwan** [comment]
The best way to do it is by

--bar-levels 0.05 --fastscore --no-full --all-score

Sam

**Comment by mvacher** [comment]
Perfect, thanks
