### ISSUE TITLE
P-value threshold < 0.0005 are ignored

### ISSUE THREAD

**Issue by mvacher** [choishingwan/PRSice#236]
Hi,

It looks like there is limit on the minimum p-value threshold that can be used.

Example:
```
Rscript PRSice.R \
    --prsice ./PRSice_mac \
    --base TOY_BASE_GWAS.assoc \
    --target TOY_TARGET_DATA \
    --bar-levels 0.00005,0.0005,0.005,0.05 \
    --fastscore --all-score \
    --out test --print-snp

$ head test.all.score
FID IID 0.0005 0.005 0.05 1
CAS_1 CAS_1         2.24731886       -0.0651589222    0.00334673407    -0.0143159198
CAS_2 CAS_2         0.278976842      0.104254804      -0.0101116051    -0.00752766754
CAS_3 CAS_3         1.45705622       0.100395908      -0.0193139015    -0.00508844193
...
```
PRS for threshold below  0.0005 was not calculated.

- Is there any way around this ?

Thanks

**Comment by choishingwan** [comment]
If you don't have any SNPs less than 0.0005, we will not be able to
calculate the PRS for that.

**Comment by mvacher** [comment]
There are some SNPs below this threshold (I used the test data provided in the archive)

```
df <- read_delim('TOY_BASE_GWAS.assoc', delim = " ")
dim(df[df$P<0.0005,])
# 6
```

**Comment by choishingwan** [comment]
Sorry, there are no SNPs below 0.00005, that's why we didn't calculate
that. Smallest P-value is 0.0002198

(PRS for 0.0005 0.005 0.05 1 were calculated)

**Comment by mvacher** [comment]
Of course that makes perfect sense, thanks a lot for your help.
