### ISSUE TITLE
How to identify SNPs used in PRS calculation

### ISSUE THREAD

**Issue by PyunJung-Min** [choishingwan/PRSice#241]
Hi,

I got a certain PRS, which 204 SNPs are included.
How can i identify these SNPs?
 
Thank you,

Jung-Min

**Comment by choishingwan** [comment]
Use --print-snp

**Comment by PyunJung-Min** [comment]
i tried "--print-snp ADNI4". 
This command produced ADNI4.snp file. (which, somehow i couldn't open on linux..)
This file contained 832918 SNPs with each p-values.
Is there a way to get a list of only 204 SNPs used PRS calculation, meaning below certain p-value threshold? 

always thanks,

Jung-Min

**Comment by choishingwan** [comment]
You don't need to give a parameter to --print-snp, it will automatically
use the prefix stated in --out.

This file essentially contains all post-clumped SNPs. What you can then do
is to filter these SNPs by their p-value (included in the file) according
to the best p-value threshold.

We design the output this way to cater to PRSet.
