### ISSUE TITLE
PRS - Single Sample Testing 

### ISSUE THREAD

**Issue by sinog** [choishingwan/PRSice#247]
Hello. 

Because I have very few data samples I tried using just a single sample for testing in PRSice2 but got a fatal error saying that not enough samples were used for testing. 

However, in your paper in nature protocols 'Tutorial: a guide to performing polygenic risk score analyses' you briefly mention 'The incremental R2 is necessarily greater than zero when testing is performed within a single sample [...]' (p. 8).

Do you believe it would make any sense to try and make a test sample containing just a single sample?

Thanks!

**Comment by choishingwan** [comment]
in our paper, for that particular sentence, we "sample" refer to data sample instead of an individual. While you can calculate PRS for a single sample, you cannot perform optimization nor clumping (which is what PRSice does) as there isn't enough information. 

Sam
