### ISSUE TITLE
Issue with plotting the bar graph

### ISSUE THREAD

**Issue by LindsayMMB** [choishingwan/PRSice#249]
Hi,

I am so sorry to bother you. I am trying to run PRSice and everything runs smoothly until it tries to plot the results. Then I get the following error: 

Begin plotting
Current Rscript version = 2.3.3
Plotting Bar Plot
Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  :
  unable to start device PNG
Calls: process_plot ... bar_plot -> plot.bar -> ggsave -> dev -> <Anonymous>
In addition: Warning message:
In grDevices::png(..., res = dpi, units = "in") :
  unable to open connection to X11 display ''
Execution halted

I'm not sure what this error means exactly and google isn't helping. I did check and I'm using the latest version of R.

Any help would be greatly appreciated!

**Comment by choishingwan** [comment]
You likely haven't got the X11 installed. Are you working on a mac? If so,
this can help: http://www.prsice.info/extra_steps/#mac-users

**Comment by choishingwan** [comment]
If you are working on linux, then these two post online might help:

https://stackoverflow.com/questions/1710853/how-to-run-r-on-a-server-without-x11-and-avoid-broken-dependencies
https://stackoverflow.com/questions/13067751/how-to-run-r-scripts-on-servers-without-x11

**Comment by LindsayMMB** [comment]
Hi,

Sorry for the late reply.

X11 is installed. I even double-checked that. I'm running it on a linux based server as well. But I still keep getting the same issue.

**Comment by choishingwan** [comment]
In your R session, type:


capabilities()

 

And send me the result

**Comment by LindsayMMB** [comment]
jpeg         png        tiff       tcltk         X11        aqua
       TRUE        TRUE        TRUE        TRUE        TRUE       FALSE
   http/ftp     sockets      libxml        fifo      cledit       iconv
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
        NLS     profmem       cairo         ICU long.double     libcurl
       TRUE       FALSE        TRUE        TRUE        TRUE        TRUE

**Comment by choishingwan** [comment]
Strange, you’ve got everything. Are you working on a server? If so, did you ssh in with -Y option?


Sam

**Comment by LindsayMMB** [comment]
Now I am getting this error as I've added Xming to enable X11 forwarding.. 

Plotting Bar Plot
Error in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)) :
  X11 font -adobe-helvetica-%s-%s-*-*-%d-*-*-*-*-*-*-*, face 1 at size 14 could not be loaded
Calls: process_plot ... grid.Call -> <Anonymous> -> descentDetails.text -> grid.Call

How can I change this?
