### ISSUE TITLE
ERROR: Cannot open log file

### ISSUE THREAD

**Issue by ivangalvan** [choishingwan/PRSice#25]
Hi,

I am trying to reproduce the wiki examples but I obtain the following error:

#####################

 Rscript PRSice.R  --prsice PRSice_linux --base TOY_BASE_GWAS.assoc  --no-clump --target TOY_TARGET_DATA --stat OR --binary-target T --out outputs/out --full

PRSice 2.0.13.beta (14 October 2017) 
https://github.com/choishingwan/PRSice
(C) 2016-2017 Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly, Sam Choi
GNU General Public License v3

Wed Oct 25 17:12:58 2017

./PRSice_linux \
    --base TOY_BASE_GWAS.assoc \
    --out outputs/out \
    --target TOY_TARGET_DATA \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5 \
    --binary-target T \
    --stat OR \
    --chr CHR \
    --A1 A1 \
    --A2 A2 \
    --snp SNP \
    --bp BP \
    --pvalue P \
    --thread 1 \
    --interval 0.000050 \
    --lower 0.000100 \
    --upper 0.500000 \
    --no-clump \
    --full

Loading Genotype file: TOY_TARGET_DATA (bed)
2000 people (1024 males, 976 females) observed
2000 founder(s) included
91062 variants included

1 region included

Start processing: TOY_BASE_GWAS
==============================
Reading 100.00%
91063 SNP(s) observed in base file, with:
2226 variant(s) located on haploid chromosome
1 variant(s) not found in target file
88836 total SNPs included from base file

Seed: 2634118250
ERROR: Cannot open log file: 
Error: 
Execution halted

#########

What I am doing wrong?

Thank you,

Ivan

**Comment by choishingwan** [comment]
Hi Ivan,

Sorry this is an known bug and was fixed in the bugfix file. Could you please download the bugfix file to test if this is still the case?

Thanks

**Comment by ivangalvan** [comment]
Hi Choi,

I downloaded the PRSice_linux.bugfix.zip version and it works.

Thank you,

Ivan

**Comment by choishingwan** [comment]
That's great!
