### ISSUE TITLE
Error: Reporter not initialized!

### ISSUE THREAD

**Issue by jameskozubek** [choishingwan/PRSice#250]
jim@bashful:/mnt/BIOINFX$ Rscript PRSice.R --dir /data_for_PRSice/ --prsice PRSice_linux --base stats.assoc --target 80 --stat OR --or --out PRS_out  --no-full
Error: Reporter not initialized!
Error:
Execution halted

**Comment by choishingwan** [comment]
This is usually because you are working in an area that you are not allow to write a file.

**Comment by jameskozubek** [comment]
You are right. It worked when I used sudo.

**Comment by choishingwan** [comment]
might be better just work in somewhere where you have write permission instead of using sudo

**Comment by jameskozubek** [comment]
yes by setting out dir using --out
