### ISSUE TITLE
Adobe Helvetica font doesn't exist - need to edit prsice.r script

### ISSUE THREAD

**Issue by LindsayMMB** [choishingwan/PRSice#251]
Sorry, I am new to r and am having issues knowing where to edit the PRSice.r script so that I can change the font from the standard adobe-helvetica (which my system doesn't have) to a font that I have so that the plot doesn't error out. 

100dpi is loaded but there is no "Adobe Helvetica" font, just "Helvetica". 

Thank you in advance.

**Comment by choishingwan** [comment]
I've not done that before.

But maybe you can try these:
https://stackoverflow.com/questions/34522732/changing-fonts-in-ggplot2
https://stackoverflow.com/questions/27689222/changing-fonts-for-graphs-in-r

and just add the code on top of the PRSice.R file
