### ISSUE TITLE
./PRSice_linux: Permission denied

### ISSUE THREAD

**Issue by AndreaG5** [choishingwan/PRSice#253]
Hi,
I am brand new to PRSice, so I read the guide and I was approaching to start the tutorial with the toy data provided. I am facing issues on launching PRSice. I am operating with Windows 10 but as I saw PRSice is available on linux and mac only. I decided to switch to Windows subsystem Linux and I installed Ubuntu bash in order to launch the analysis.

I created a folder "PRSice" which contains PRSice.R, PRSice_linux, and all of the toy data. I set my working directory in this folder and I launch the command   > Rscript PRSice.R --dir . --prsice PRSice_linux --base TOY_BASE_GWAS.assoc --target TOY_TARGET_DATA (as you suggest on https://github.com/choishingwan/PRSice/issues/150).

I got the error:   "./PRSice_linux: Permission Denied" and I don't know how to solve it.

Could you help me?

p.s. I saw online that there's a file for windows "PRSice_win64.exe" but I am unable to find it online and maybe it could help me to solve these problems. I think you could help me in such way either.

Thank you!

Andrea Gaudio

**Comment by choishingwan** [comment]
Likely that you'll need to do `chmod 777 PRSice_linux`

**Comment by fmadani** [comment]
I got the same error, and applied `chmod 777 PRSice_linux`. Still, the error persists. Any help?

**Comment by fmadani** [comment]
I simply put the code in a nextflow file as below:

#!/usr/bin/env nextflow
process Presice_2 {
	echo true
	
	"""
	Rscript $baseDir/PRSice.R \
    --prsice $baseDir/PRSice_linux \
    --base $baseDir/Height.QC.gz \
    --target $baseDir/EUR.QC \
    --binary-target F \
    --pheno $baseDir/EUR.height \
    --cov $baseDir/EUR.covariate \
    --base-maf MAF:0.01 \
    --base-info INFO:0.8 \
    --stat OR \
    --or \
    --out EUR
	"""		
}

When I run the file in ubuntu, I get 'Permission denied" on PRScie_linux folder. I examined many ways but I could not solve this issue. Just when I pasted the below code, taken from the tutorial, in the PRSice_linux folder (in ubuntu), I could run the code and get the results.

Rscript PRSice.R \
    --prsice PRSice_linux \
    --base Height.QC.gz \
    --target EUR.QC \
    --binary-target F \
    --pheno EUR.height \
    --cov EUR.covariate \
    --base-maf MAF:0.01 \
    --base-info INFO:0.8 \
    --stat OR \
    --or \
    --out EUR

Please let me know why I get the error.

Thanks

**Comment by choishingwan** [comment]
PRSice_linux should not be a folder, but an executable. So if you are
trying to do ./PRSice_linux where PRSice_linux is a folder, then there will
be an Permission denied error message as folder isn't executable. But if
PRSice_linux is the executable that you download from our website, then you
should be able to run it with ./PRSice_linux

Unless I have the full path / information on your data structure, it's not
possible for me to see what's going on
