### ISSUE TITLE
Error: No vairant remained! When using --chr-id[BUG]

### ISSUE THREAD

**Issue by kalkairis** [choishingwan/PRSice#255]
**Describe the bug**
I've downloaded summary statistics of age of disease onset from [link](https://pdgenetics.org/resources). 
The data does not have a SNP rsID and so I've added the --no-default flag and used --chr-id flag.

I'm using a CentOS, and specifically my command was:
__[PRSice directory]/PRSice_linux PRsice -b IPDGC_AAO_GWAS_sumstats_april_2018.txt --a1 Allele1 --a2 Allele2 --no-default --stat Effect --pvalue P-value --chr-id MarkerName --beta --fastscore --snp MarkerName -t merged__

My available target files are:
- merged.bed
- merged.bim
- merged.fam
- merged.pgen
- merged.psam
- merged.pvar

**Error Log**
PRSice 2.3.3 (2020-08-05) 
https://github.com/choishingwan/PRSice
(C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2021-02-07 11:40:41PRSice/Code/PRSice_linux \
    --a1 Allele1 \
    --a2 Allele2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base IPDGC_AAO_GWAS_sumstats_april_2018.txt \
    --beta  \
    --binary-target F \
    --chr-id MarkerName \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --fastscore  \
    --no-default  \
    --num-auto 22 \
    --out PRSice \
    --pvalue P-value \
    --seed 732507993 \
    --snp MarkerName \
    --stat Effect \
    --target merged.qc \
    --thread 1

Initializing Genotype file: merged.qc 
(bed) 

Start processing IPDGC_AAO_GWAS_sumstats_april_2018 
================================================== 

Base file: IPDGC_AAO_GWAS_sumstats_april_2018.txt 
Header of file is: 

MarkerName	Allele1	Allele2	Freq1	FreqSE	MinFreq	MaxFreq	Effect	StdErr	P-value	Direction	HetISq	HetChiSq	HetDf	HetPVal 

6813423 variant(s) observed in base file, with: 
1031546 ambiguous variant(s) excluded 
5781877 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

3685 people (0 male(s), 0 female(s)) observed 
3685 founder(s) included 

9164945 variant(s) not found in previous data 
0 variant(s) included 

Error: No vairant remained! 

**To Reproduce**
I cannot upload the data and thus cannot make this reproduceable. 

**Additional context**

**Comment by choishingwan** [comment]
Chr-id is used to construct a new ID from chromosome and coordinate. So a normal use case will be –chr-id c:l (url)
