### ISSUE TITLE
[BUG]Error: optparse cannot be load nor install!

### ISSUE THREAD

**Issue by forevertl** [choishingwan/PRSice#256]
**Describe the bug**
Hello,I run a code which worked before and it doesn't work now and I got error as below. I suspect it is server connection issue. Is it PRsice server issue instead of issue from my end? Thank you very much!
Lin

**Error Log**
* About to connect() to proxy hsd-proxy.bsd.uchicago.edu port 8080 (#0)
*   Trying 128.135.138.202...
* Connected to hsd-proxy.bsd.uchicago.edu (128.135.138.202) port 8080 (#0)
> GET http://cran.rstudio.com/src/contrib/PACKAGES.rds HTTP/1.1
User-Agent: libcurl/7.29.0
Host: cran.rstudio.com
Accept: */*
Proxy-Connection: Keep-Alive
Pragma: no-cache

< HTTP/1.1 200 OK
< Content-Length: 743324
< Connection: keep-alive
< Date: Sun, 07 Feb 2021 23:39:36 GMT
< Server: Apache/2.4.39 (Unix)
< Last-Modified: Sun, 07 Feb 2021 23:00:48 GMT
< ETag: "b579c-5bac7062a50c8"
< Accept-Ranges: bytes
< Cache-Control: max-age=1800
< Expires: Mon, 08 Feb 2021 00:09:36 GMT
< X-Cache: Hit from cloudfront
< Via: 1.1 6aec8f1aa09edf6116ef0f638212a7c6.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: ORD51-C2
< X-Amz-Cf-Id: Ak5-vPfM5EzkbIh1kJFCLhBYyKhvKx5O8QVQ41mYBbqzJmFK1RJDiA==
< Age: 55
<
* Connection #0 to host hsd-proxy.bsd.uchicago.edu left intact
* About to connect() to proxy hsd-proxy.bsd.uchicago.edu port 8080 (#1)
*   Trying 128.135.138.202...
* Connected to hsd-proxy.bsd.uchicago.edu (128.135.138.202) port 8080 (#1)
> GET http://cran.rstudio.com/src/contrib/optparse_1.6.6.tar.gz HTTP/1.1
User-Agent: libcurl/7.29.0
Host: cran.rstudio.com
Accept: */*
Proxy-Connection: Keep-Alive

< HTTP/1.1 200 OK
< Content-Type: application/x-gzip
< Content-Length: 37896
< Connection: keep-alive
< Server: Apache/2.4.39 (Unix)
< Last-Modified: Thu, 16 Apr 2020 21:20:09 GMT
< Accept-Ranges: bytes
< Date: Sun, 07 Feb 2021 23:27:18 GMT
< Expires: Sun, 07 Feb 2021 23:57:18 GMT
< Cache-Control: max-age=1800
< ETag: "9408-5a36eff56f999"
< X-Cache: Hit from cloudfront
< Via: 1.1 1c91c8b378f1050c39056fd5f8656d1a.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: ORD51-C2
< X-Amz-Cf-Id: O2Gmzhqh010jS0yFJs7gCh8a4crFqo1Por98V9ELA_T5Dz6pTy_UOw==
< Age: 794
<
* Connection #1 to host hsd-proxy.bsd.uchicago.edu left intact
Error: Error: optparse cannot be load nor install!
Execution halted

**To Reproduce**
If possible, provide a minimum working example for me to reproduce the problem. This can usually speed up the debugging process. 

**Additional context**

**Comment by poppyzenzi** [comment]
Did you find a fix for this?
