### ISSUE TITLE
Issue with bgen vs bed

### ISSUE THREAD

**Issue by batzler** [choishingwan/PRSice#257]
Version PRSice 2.2.10.b (2019-10-09) 

When I submit a PRS job using the above version with bgen data I get the error below.  PRSice executes as far as the clumping process then fails.  However if I convert my bgen file to binary, I do NOT get the error.  Any idea what issue PRSice is having with my bgen file?  My bgen file was created from TopMed imputation server VCF output, using dosage=DS and --export bgen-1.2
Thanks in advance

**Error Log**
Start performing clumping 

773957 MB RAM detected; reserving 1 MB for clumping 

Allocated 1 MB successfully 

Clumping Progress: 0.00%*** glibc detected *** /research/bsi/tools/biotools/prsice/2.2.10.b/bin/PRSice_linux: free(): invalid next size (fast): 0x00002b0fba9d3210 ***
======= Backtrace: =========
[0x5da392]
[0x46e2cc]
[0x422413]
[0x4044e3]
[0x5ba7c6]
[0x404a15]
======= Memory map: ========
00400000-006cb000 r-xp 00000000 00:2b 103342084647                       /research/bsi/tools/biotools/prsice/2.2.10.b/bin/PRSice_linux
008cb000-008d5000 rw-p 002cb000 00:2b 103342084647                       /research/bsi/tools/biotools/prsice/2.2.10.b/bin/PRSice_linux
008d5000-00960000 rw-p 00000000 00:00 0 
01b4d000-21b25000 rw-p 00000000 00:00 0                                  [heap]
2b0faea23000-2b0fb3423000 rw-p 00000000 00:00 0 
2b0fb349b000-2b0fb5189000 rw-p 00000000 00:00 0 
2b0fb7e17000-2b0fd2f93000 rw-p 00000000 00:00 0 
7ffda22f6000-7ffda231b000 rw-p 00000000 00:00 0                          [stack]
7ffda2325000-7ffda2327000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Error: 
Execution halted

**Comment by batzler** [comment]
Additionally, 
I've successfully used the UKB bgen files to run PRSice.  So its the creation of bgen files from the Michigan imputation server VCF's that is presenting a problem.  Thanks,
Tony

**Comment by choishingwan** [comment]
Likely memory problem. 2.2.10 is rather old so I can't remember what
exactly are the problem. If you use the latest version (2.3.3), then it
should work with bgen file as long as you use --allow-inter option.
(currently there's a bug that prevent bgen analysis without --allow-inter)

Sam

**Comment by batzler** [comment]
Ok, Thank you.  Will work on getting the most recent version downloaded and give that a try.
Any idea why I can successfully run PRSice with UKB bgen data (400K samples) but I’m unable to my small study of (300 samples)?  If PRSice could handle the memory for UKB I would think it should handle for a smaller set?

It seems that however you allocate the memory, it is not allocating properly for my study data?
Any thoughts?

Thanks,
Tony

**Comment by choishingwan** [comment]
the --memory option is really just there for permutation. It doesn't work
for other stuff. Can you confirm if you can run the QCTools on your small
bgen samples? Currently PRSice only support BGEN v1.1. and v1.2, so if your
bgen file is v1.3, then PRSice might crash. There are also many other
reason that might be happening here, but since 2.2.10 is rather old, it'd
be very hard for me to figure that out.

Sam

**Comment by batzler** [comment]
I’m using plink2 to export bgen-1.2

I just got this to run for chr22 successfully.

The problem occurs when I try to run more than that.

If I provide the chroms 1-22 base data (8 million variant results), and provide the chr# bgen target data, it fails due to memory.
If I provide the chroms 1-22 base data, but I only provide chr22 bgen target data (83,000 variants),  it fails due to memory.
If I subset the base data to chr22 (100,000 variant results) , and provide chr22 bgen target data (83,000 variants) only, it finishes properly.

Any explanation of why this might happen?

**Comment by choishingwan** [comment]
It might be related to an old bug related to multiple chromosome input.
Again, I am uncertain because 2.2.10 is more than a year ago... Sorry about
that .

Sam

**Comment by batzler** [comment]
No problem.  This is very helpful to know.  Will try the new version and keep you posted.  Thanks
Tony

**Comment by batzler** [comment]
Sam,
Thanks again for suggestions to use the new version.  I had our IT dept install the new version and I’m trying out now.
I’ve got all of my data setup and everything looks to be correct however I’m running into this error when trying to execute PRSice.
Any thoughts here?

Error: Reporter not initialized!
Error:
Execution halted

Thanks,
Tony

**Comment by choishingwan** [comment]
you don't have write permission to the out file directory

**Comment by batzler** [comment]
Forgive me if I’m misunderstanding, but the OUTDIR that I’m attempting to write, does not have permission issues.  I even tried chmod 777 and still received the error below.
Thanks,
Tony

**Comment by choishingwan** [comment]
That error occurs when PRSice failed to write the log file into the
designated output directory. Can you run PRSice with just PRSice --version
or PRSice --help? If so then it is very likely due to the permission / disk
quota problem as those are the two commands that doesn't require file write
access.

Sam

**Comment by batzler** [comment]
Here is version

batzler@mforgehn2 GWAS12merged.EUR.lindner_EUR.00001.MAF0.05.dosR20.8]$ /research/bsi/tools/biotools/prsice/2.3.3/PRSice_linux --version
2.3.3 (2020-08-05)

Here is help (abbreviated)

[batzler@mforgehn2 GWAS12merged.EUR.lindner_EUR.00001.MAF0.05.dosR20.8]$ /research/bsi/tools/biotools/prsice/2.3.3/PRSice_linux --help
usage: PRSice [options] <-b base_file> <-t target_file>

Base File:
    --a1                    Column header containing allele 1 (effective allele)
                            Default: A1
    --a2                    Column header containing allele 2 (non-effective allele)

I’m calling PRSice with the following

  ${R} ${PRSice}/PRSice.R \
      --prsice ${PRSice}/PRSice_linux \

I’m assuming this is still appropriate as this is how we called the old version of PRSice.
Also, my output and current directories both have plenty of space available…

Any other thoughts?  I can discuss with our IT as well.  Not sure if this is an install issue on their end…?

Thanks,
Tony

**Comment by choishingwan** [comment]
If you do --out <full pathway to directory>/<prefix>

does that work?

**Comment by batzler** [comment]
Seems there is some issue with the script writing to a different location other than the current directory from which I’m running.
Some kind of permissions issue.  Even though the –out dir is open for write access.  I can work around this.  Thanks for the suggestions.  Seems to be working now.
Thanks,
Tony
