### ISSUE TITLE
Necessary to include phenotype for all individuals despite using --keep ?

### ISSUE THREAD

**Issue by gunns2** [choishingwan/PRSice#259]
Hi I'm looking to run prsice on a subset of individuals without subsetting the bgen file myself, using the --keep function. However, it appears I need to provide the phenotype for all individuals in the bgen file, according to this error "Number of samples in phenotype file does not match number of samples specified in bgen file. Please check you have the correct phenotype file input." I don't have the phenotype information for everyone in the bgen file.  Any advice? Would you recommend subsetting the bgen file externally? I'm also curious about time, would it be much faster to subset the bgen file first?
thanks so much!

**Comment by choishingwan** [comment]
You will need to provide PRSice with either a sample file or a fake
phenotype file that contain the sample ID of all samples in the bgen using
the external sample method --target <bgen prefix>,<sample or phenotype
file>
