### ISSUE TITLE
--keep-ambig not implemented?

### ISSUE THREAD

**Issue by wvdaphna** [choishingwan/PRSice#26]
Hi,  
is --keep-ambig implemented ?  if so it was not working for me, can you please provide an example usage code?

many thanks!
Daphna

**Comment by choishingwan** [comment]
Hi,

Do you mind letting me know how it doesn’t work? Does the ambiguous SNPs got removed???

Sam

**Comment by choishingwan** [comment]
You are absolutely right, the flag wasn't set probably in PRSIce when we parse the command. I have now fixed it in the latest code  345d56b  and you can download the latest version [here](https://github.com/choishingwan/PRSice/releases/tag/2.0.14.beta)

**Comment by wvdaphna** [comment]
super! many thanks
