### ISSUE TITLE
Using bgen file as the ld reference

### ISSUE THREAD

**Issue by hengi110** [choishingwan/PRSice#260]
Hi Sam,

I used PRSet to get pathway scores for a validation dataset and would like to test them in an independent test set, both of which are in bgen format. When I tried to use the validation data as the ld reference while testing, it gave an error referring to a fam file that does not exist:
Error: Malformed fam file. Fam file should have 6 
       columns.Line: 1

I'm guessing that's because ld does not accept bgen format. Is that true? I'm afraid that converting to bed/bim/fam would affect clumping. How can I reproduce the same ld matrix as the validation data in this case?

Thanks.

**Comment by choishingwan** [comment]
you need --ld-type bgen. though if you are running PRSet, it will likely be
very slow

Sam

**Comment by hengi110** [comment]
Thank you for your response. When I added --ld-type bgen, it didn't give the previous error but didn't run either:
...
Start performing clumping 
Error: 
Execution halted

Any thoughts?

**Comment by choishingwan** [comment]
Likely ran out of memory. PRSice with BGEN uses a lot of memory, like >
100GB of memory. Will try to solve this problem when I have time, but at
the moment, you will need to give PRSice a lot of memory for it to run with
BGEN, especially BGEN with PRSet.

Sam

**Comment by choishingwan** [comment]
The --memory function of PRSet really doesn't do anything to be honest. It
was my failed attempt to control the memory. If you managed to complete the
clumping, then it is good news, as clumping usually take up most memory. If
you are on HPC, maybe try increasing the amount of memory by a bit and if
that still fail, then please do send me the full log.

Sam

**Comment by hengi110** [comment]
Unfortunately, this is the max memory I can use on our server. I will use the .snp file to filter base data.

**Comment by choishingwan** [comment]
The .snp file isn't perfect for PRSet. A easier way might be reduce the
gene set number (e.g. put it by batch). This should reduce the number of
SNPs included in each analysis, thus reduce the memory usage (especially
PRSet will attempt to store the best score in memory before outputting
everything to reduce the IO burden). Did you use --set-perm by any chance?
If not, I am rather surprise that you can complete the clumping but not the
PRS calculation, as clumping usually uses more memory.

**Comment by hengi110** [comment]
I'm trying to perform PRSet on 46 pathways that had the best R2 in the validation set. Let me recap, PRS calculation successfully completed on the validation set (110k individuals, 735k snps) for ~2800 pathways on the server. The same calculation completed on the test set (235k individuals) without specifying an ld reference, but when I provided the validation set as the ld reference, it crashed. Here's my full command:
Rscript PRSice.R \
    --prsice --prsice PRSice_linux \
    --base  base.txt \
    --target target.bgen,target.sample
    --ld ld.bgen,ld.sampe \
    --ld-type bgen \
    --type bgen \
    --pheno pheno.pheno \
    --gtf Homo_sapiens.GRCh38.86.chr.gtf \
    --msigdb c2.cp.v7.2.symbols.subsetR2.01.gmt \
    --multi-plot 30 \
    --memory 125G \
    --stat BETA \
    --out output

Thanks for all your help.

**Comment by choishingwan** [comment]
might have been some kinda memory inefficiency when dealing with the LD
then. May I ask why do you need to specify the validated sample as
reference? It is possible that --extract .snp will help with some of the
memory issue, though I doubt that will be significant

**Comment by hengi110** [comment]
I wanted to make sure snp correlations are computed consistently across multiple test sets with different sizes.

**Comment by choishingwan** [comment]
I see. Usually, if your samples are from similar population, then the
clumping should result in very similar SNP correlation as long as you have
large sample size (e.g. > 1000)

**Comment by hengi110** [comment]
True, but I'm using four test sets two of which are less than 1000 so I thought it would be best to use the same reference for all. FYI, I get the same error when I run the above command for the smaller target samples.

**Comment by choishingwan** [comment]
Ya, there must be some kind of memory error / memory leak when using bgen
reference samples. Does using --allow-inter help?

**Comment by hengi110** [comment]
Unfortunately not.
