### ISSUE TITLE
Issue with plotting

### ISSUE THREAD

**Issue by nscarene** [choishingwan/PRSice#261]
Hi Sam,

Thank you so much for taking the time to help us clarify aspects of the software that we do not entirely understand.

I have an issue with plotting while using PRSice v2.3.3 and I really need your help, please!

Everything runs smoothly while calculating PRSs (all the files are generated). The issue arises with plotting. It does not plot any graphs at all, while using my own data. However, there is no issue at all when I use the TOY_DATA.

**Here is the command I ran**: 
Rscript PRSice.R --dir ./ --prsice PRSice_linux --base SAC_no_EAS_logistics_results_just_ADD.txt --a1 A1 --bp BP --snp SNP --chr CHR --pvalue P --or T --target MEGA_update_name5 --binary-target T --clump-kb 100 --clump-p 1e-05 --clump-r2 0.1 --interval 5e-05 --lower 1e-05 --upper 0.5 --num-auto 22 --seed 299084563 --thread 1 --cov COVARIATE_FID_IID_SEX_AGE_GA%.txt --cov-col SEX,AGE,AFR,EUR,SAN,SAS --perm 100 --logit-perm --prevalence 0.01 --bar-levels 0.05 --quantile 10 --quant-break 1,2,3,4,5 --quant-ref 3 --print-snp --out PRS_SAC_LD0.1_clump-p1e-05_clump-kb100_20210302

**Here is the error message that I get after running the command (just when it comes to plotting):** 

Begin plotting
Current Rscript version = 2.3.1.c
Error in names(x) <- value :
  'names' attribute [4] must be the same length as the vector [2]
Calls: colnames<-
Execution halted

How can I solve this issue? Thank you for your help in advance

**Comment by choishingwan** [comment]
What if you try the latest PRSice R script? (Your version is 2.3.1.c which
is different from 2.3.3). Might have something to do with that. Otherwise,
I might need some part of your file to check what's the problem

**Comment by nscarene** [comment]
Hi Sam, 

Thank for your prompt answer! 

I haven't tried with the latest Rscript version, since I didn't know there was a latest version. Could you please tell me where I could download the latest PRSice Rscript ?

**Comment by choishingwan** [comment]
It should be downloaded together with your executable but you can find the
link to download here:

https://github.com/choishingwan/PRSice/releases/tag/2.3.3

Dr Shing Wan Choi
Postdoctoral Fellow
Genetics and Genomic Sciences
Icahn School of Medicine, Mount Sinai, NYC

**Comment by nscarene** [comment]
Thank you so much! 
I will give it a try right this instant and keep you updated.

**Comment by nscarene** [comment]
Hello again Sam,

**I ran into the same error**: 

Begin plotting
Current Rscript version = 2.3.3
Error in names(x) <- value :
  'names' attribute [4] must be the same length as the vector [2]
Calls: colnames<-
Execution halted

What is the next course of action here? Thank you for your help, as it is truly appreciated.

**Comment by choishingwan** [comment]
Can you send me the following?

Full log and command you use

If I can't figure it out from the log, then I will need to check some of
your files

Sam

**Comment by nscarene** [comment]
**Here is my log file**

[PRS_SAC_LD0.1_Clump-p1e-05_clump-kb100_20210302.log](https://github.com/choishingwan/PRSice/files/6069628/PRS_SAC_LD0.1_Clump-p1e-05_clump-kb100_20210302.log)


**Here is the command I used:** 
Rscript PRSice.linux.R --dir ./ --prsice PRSice_linux --base SAC_no_EAS_logistics_results_just_ADD.txt --a1 A1 --bp BP --snp SNP --chr CHR --pvalue P --or T --target MEGA_update_name5 --binary-target T --clump-kb 100 --clump-p 1e-05 --clump-r2 0.1 --interval 5e-05 --lower 1e-05 --upper 0.5 --num-auto 22 --seed 299084563 --thread 1 --cov COVARIATE_FID_IID_SEX_AGE_GA%.txt --cov-col SEX,AGE,AFR,EUR,SAN,SAS --perm 100 --logit-perm --prevalence 0.01 --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 --print-snp --out PRS_SAC_LD0.1_clump-p1e-05_clump-kb100_20210302

Thank you for your time Sam!

**Comment by choishingwan** [comment]
Mind sending me the header (first 2 line should be enough) of your
covariate file, phenotype file, .prsice file, .summary file and .best file?

**Comment by nscarene** [comment]
First 2 lines of requested files:

**Covariate file:** 
FID     IID     SEX     AGE                              AFR     EAS     EUR     SAN     SAS
2       1        2      18.1534246575342        0.3074  0.0839  0.037   0.512   0.0596

**.prsice file:**

Pheno   Set     Threshold       R2      R2.adj  P       Coefficient     Standard.Error  Num_SNP
-       Base    1e-05   0.332491        0.212605        8.57838e-32     22.9836 1.95879 11

**.summary file:** 
Phenotype       Set     Threshold       PRS.R2  PRS.R2.adj      Full.R2 Null.R2 Prevalence      Coefficient        Standard.Error  P       Num_SNP Empirical-P
-       Base    1e-05   0.332491        0.183219        0.212605        0.029386        0.01    22.9836    1.95879 8.57838e-32     11      0.00990099
 **.best file:** 
FID IID In_Regression PRS
2 1 Yes -0.00489976643

Note: I did not include a pheno file while running the command. Is that file compulsory? 

Thank you!

**Comment by choishingwan** [comment]
It is ok, that means PRSice is getting the phenotype information from the
fam file.

I suspect the problem is with your covariate file, can you maybe generate a
covariate file with tab delimited settings and see if that solves the
problem (use --plot so that you don't need to re-run PRSice).

If that doesn't solve the problem, then I will have a deeper look into the
situation once I completed the work at hand.

Sam

**Comment by nscarene** [comment]
Thank you Sam! I will try and do that and will keep you informed. 
Thank you again for your time!

Carene,

**Comment by nscarene** [comment]
Hi Sam,
Thank you again for your help. The issue was resolved. It seems the problem was with the spacing in my covariate file. I changed it into tab delim et everything went smoothly from there. 

Thank you again so very much for your time.
