### ISSUE TITLE
Error in if (pheno.name != "-") { : missing value where TRUE/FALSE needed Calls: process_plot

### ISSUE THREAD

**Issue by lovelymaoqin** [choishingwan/PRSice#262]
Hi,

This is my code, and I got the error. Not sure how to fix it, would you give me some suggestions?

Thanks in advance!!!

Rscript PRSice.R --dir . \
--prsice ./PRSice_linux \
--bar-levels 0.001,0.01,0.05,0.1,0.2,0.3,0.4,0.5,1 \
--quantile 5 \
--quant-ref 1 \
--snp MarkerName --A1 A1 --A2 A2 --stat LogOR --beta --pvalue P \
--base 23andMe_genome-wide.txt \
--target imp.plink.bed \
--keep mydata.all \
--pheno-file mydata.phenotype \
--pheno-col W3_D_YN,W8_D_RS,W3_P_YN,W3_P_RS,W3_P_YN,W3_P_RS,W3_PC_YN,W3_PC_RS,M3_D_YN,M3_D_rs,M3_P_YN,M3_P_RS,M3_P_YN,M3_P_RS,M3_PC_YN,M3_PC_RS \
--binary-target T,F,T,F,T,F,T,F,T,F,T,F,T,F,T,F \
--cov mydata.covariate \
--cov-col Site,Sex,Age,@PC[1-10] \
--cov-factor Site,Sex \
--out gwasdata \
--thread max

Error in if (pheno.name != "-") { : missing value where TRUE/FALSE needed
Calls: process_plot

**Comment by choishingwan** [comment]
Do you have the version number? It should be provided when you run PRSice.R
(use --plot to skip the calculation)

Sam

**Comment by ealopera** [comment]
Hello, I had exactly the same problem.

this is my input code
```
Rscript ${presice_dir}/PRSice.R \
--prsice ${presice_dir}/PRSice_linux \
--base ${wkdir}/data/meta.mydata.fixed.prsice.txt \
--snp rsid \
--chr CHR \
--A1 Allele1 \
--A2 Allele2 \
--stat Effect \
--bp BP \
--pvalue P.value \
--target ${targetdir}/#.imputed_info_maf_filtered,${targetdir}/pedigree.fam \
--binary-target F,T,T,T,T,T \
--pheno ${wkdir}/data/phenotype_covs_target_v3.tsv  \
--pheno-col METAmy.Freq,IBWS,IBWS_sub_A,IBWS_sub_B,IBWS_sub_C,IBWS_sub_D \
--thread 18 \
--beta \
--quantile 20 \
--print-snp \
--cov ${wkdir}/data/phenotype_covs_target_v3.tsv \
--cov-col sex,age,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10 \
--cov-factor sex \
--plot \
--out ${wkdir}/output/PRS_stoolfreq/v3_IBS/target.mydata >& PRScise.out

```

this is the error message
```

Begin plotting
Current Rscript version = 2.3.3
Error in if (pheno.name != "-") { : missing value where TRUE/FALSE needed
Calls: process_plot
Execution halted
```
