### ISSUE TITLE
Error: No vairant remained! [BUG]

### ISSUE THREAD

**Issue by sara-wennersten** [choishingwan/PRSice#263]
I am trying to run PRSice using .bgen dosage files that were converted from .vcf dosage files using plink, but I keep getting "Error: No vairant remained!". I've seen bug reports with similar issues and it appears to be an issue with inconsistencies between the base and target files. Could you help me figure out what the issue is with my files? Thank you!!

**Error Log**
> PRSice 2.3.3 (2020-08-05) 
> https://github.com/choishingwan/PRSice
> (C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
> GNU General Public License v3
> If you use PRSice in any published work, please cite:
> Choi SW, O'Reilly PF.
> PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
> GigaScience 8, no. 7 (July 1, 2019)
> 2021-04-07 17:09:27
> ./PRSice_mac \
>     --a1 A1 \
>     --a2 A2 \
>     --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
>     --base GWAS.txt \
>     --base-info INFO:0.9 \
>     --base-maf MAF:0.01 \
>     --binary-target F \
>     --bp BP \
>     --chr CHR \
>     --clump-kb 250kb \
>     --clump-p 1.000000 \
>     --clump-r2 0.100000 \
>     --interval 5e-05 \
>     --lower 5e-08 \
>     --num-auto 22 \
>     --or  \
>     --out 1000 \
>     --pheno GWAS.phenotype \
>     --pvalue P \
>     --seed 2639240484 \
>     --snp SNP \
>     --stat OR \
>     --target chr# \
>     --thread 1 \
>     --type bgen \
>     --upper 0.5
> 
> Initializing Genotype file: chr# (bgen) 
> 
> Start processing GWAS 
> ================================================== 
> 
> Base file: GWAS.txt 
> Header of file is: 
> SNP	CHR	BP	A1	A2	MAF	INFO	model	OR	SE	P	het_pvalue	N 
> 
> 9455778 variant(s) observed in base file, with: 
> 69459 variant(s) excluded due to MAF threshold 
> 2533783 variant(s) with INFO score less than 0.900000 
> 200 NA stat/p-value observed 
> 3470050 negative statistic observed. Maybe you have 
> forgotten the --beta flag? 
> 482325 ambiguous variant(s) excluded 
> 2899961 total variant(s) included from base file 
> 
> Loading Genotype info from target 
> ================================================== 
> 
> Assume phenotype file has header line: FID	IID	Phenotype
>  
> 
> 264 people (0 male(s), 0 female(s)) observed 
> 264 founder(s) included 
> 
> 23206585 variant(s) not found in previous data 
> 0 variant(s) included 
> 
> Error: No vairant remained! 

**These are the first few lines of the target data file:**
```
  id          rsid chrom     pos  nalleles allele_ids  vaddr
0      1:77470:T:C     1   77470         2        C,T   4231
1     1:135094:C:T     1  135094         2        T,C   4414
2     1:234441:C:T     1  234441         2        T,C   4626
3     1:324814:C:G     1  324814         2        G,C   4875
4     1:362895:A:G     1  362895         2        G,A   5020
```

**These are the first few lines of the base data file:**
```
SNP	CHR	BP	A1	A2	MAF	INFO	model	OR	SE	P	het_pvalue	N
rs143225517	1	751756	C	T	.158264	.92	FIXED	.013006	.017324	.4528019	.303481	35
rs3094315	1	752566	A	G	.763018	1	FIXED	-.005243	.0157652	.7394597	.146867	36
rs3131972	1	752721	G	A	.740969	.96034	FIXED	-.003032	.0156381	.8462652	.340843	36
rs3131971	1	752894	C	T	.744287	.793	FIXED	.00464	.0162377	.7750657	.035821	37
rs61770173	1	753405	A	C	.775368	.91694	FIXED	-.006291	.016708	.7065265	.377485	36
```

**Comment by choishingwan** [comment]
If you use the same sample for both base and target, even if that is for a
different trait, that will still cause an inflation in beta, thus
invalidate your result.

The only situation where this might be ok is that if the base phenotype and
your target phenotype is completely uncorrelated, but in that case, it
doesn't really make sense to run a PRS on that.

Equations in this paper should help:
https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-018-4859-7

Sam

**Comment by sara-wennersten** [comment]
Got it. Thank you so much for your quick response!

Could this technically be caused by an error in the phenotype file? Perhaps by using incorrect values for the phenotype?

**Comment by choishingwan** [comment]
Oh sorry, I replied to the wrong email....

For your situation, it is because the rs id wasn't even located in the
summary statistic file. What you need to do is to do something akin to
--chr-id. e.g. your rsid in the target is 1:77470:T:C but they are actually
rs id in your base

**Comment by sara-wennersten** [comment]
No worries! I appreciate you taking the time to respond.

So, is this because the rsid header and/or format of the values don't match between the base and target files (for example rs3094315 vs 1:77470:T:C)? If so, would adding a column to the base file with the SNP in the format of "1:77470:T:C" make it work? Is this even something that's possible through some sort of package? I converted vcf dosage files to bgen using plink, but I wonder if there's a setting I can use during the conversion process that also converts the "1:77470:T:C" format to a format like "rs3094315"... 

I apologize if these are silly questions, I am new to this sort of analysis.

And now that I think about it, I am just curious about the phenotype file. What would happen if you had the wrong phenotype values in the phenotype file?

**Comment by sara-wennersten** [comment]
Or do I just need to add "--chr-id SNP"?

**Comment by choishingwan** [comment]
Something along the line of `--chr-id c:L:a:B --no-default` might work

However, --chr-id was added on a whim, thus it is likely buggy. If that
doesn't work, then the best way forward will be as you mention, manually
build a column in your base with the chr:bp:a1:a2 format

Sam
