### ISSUE TITLE
Sample mismatch in BGEN files

### ISSUE THREAD

**Issue by GiulioCentorame** [choishingwan/PRSice#264]
**Describe the bug**
Not sure if a bug, but I have been trying to generate PRS using PRSice over BGEN dosage data from the UKBB (admittedly for the first time using this format), but I keep getting an error related to a sample mismatch between the files (see the log).

**Error Log**
Log:
```
PRSice 2.3.5 (2021-04-06) 
https://github.com/choishingwan/PRSice
(C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2021-04-19 17:52:47
PRSice \
    --a1 effect_allele \
    --a2 other_allele \
    --allow-inter  \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base path/to/ieu-b-40.tsv \
    --beta  \
    --binary-target F \
    --bp base_pair_location \
    --chr chromosome \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --extract test.valid \
    --interval 5e-05 \
    --lower 5e-08 \
    --no-regress  \
    --num-auto 22 \
    --out test \
    --pvalue p_value \
    --seed 2309329951 \
    --snp variant_id \
    --stat beta \
    --target-list /path/to/list-bgen.txt,/path/to/data.chr1-22.sample \
    --thread 1 \
    --type bgen \
    --upper 0.5

Initializing Genotype info from file: 
/path/to/list-bgen.txt 
(bgen) 
With external fam file: 
/path/to/data.chr1-22_plink.sample 

Start processing ieu-b-40 
================================================== 

SNP extraction/exclusion list contains 5 columns, will 
assume first column contains the SNP ID 

Base file: 
/path/to/ieu-b-40.tsv 
Header of file is: 

variant_id	p_value	chromosome	base_pair_location	effect_allele	other_allele	effect_allele_frequency	beta	standard_error 

Reading 100.00%
2336255 variant(s) observed in base file, with: 
359454 variant(s) excluded based on user input 
1976801 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

463005 people (211845 male(s), 251082 female(s)) observed 
463005 founder(s) included 

Error: Sample mismatch between bgen and phenotype file! 
       Name in BGEN file is :IEU1303390 and in phentoype 
       file is: -1 -1. Please note that PRSice require the 
       bgen file and the .sample (or phenotype file if 
       sample file is not provided) to have sample in the 
       same order. (We might be able to losen this 
       requirement in future when we have more time) 
```

**To Reproduce**
PRSice is running from bash (not the R wrapper).
I am parsing a list of paths through `list-bgen.txt` (as it has zeroes in the chr number, e.g. data.chr01.bgen) and the relative `.sample` files, that are in the same folder, i.e.

```
$ ls -1
data.chr01.bgen
data.chr01.bgen.bgi
data.chr02.bgen
data.chr02.bgen.bgi
[...]
data.chr1-22.sample
data.chr1-22_plink.sample
[...]
data.chrX.bgen
data.chrX.bgen.bgi
data.chrX.sample
data.chrXY.bgen
data.chrXY.bgen.bgi
data.chrXY.sample
data.chrXY_plink.sample
data.chrX_plink.sample
```
Thanks in advance for your help

**Comment by choishingwan** [comment]
When you use bgen format, PRSice will try and check if your bgen sample ID
is the same as those provided in the phenotype / sample data. In your case,
they ain't. I suspect that's because some of the samples who withdrawn
their consent has now been labelled as -1 -1 in your phenotype file, but
not in your bgen file.

May I ask why do you use a customed bgen ukb file instead of the one
provided? (the one provided by UKB does not contain sample information)

Sam

**Comment by GiulioCentorame** [comment]
Thanks for the help. The files I am using should be already QCd: they should be filtered for a European subset, have standard exclusions, and filtered with varying imputation quality for different MAFs.

I have reason to believe the withdrawn participants have been deleted manually from the `.sample` file and left in the `.bgen` files, would it be possible that PRSice returns `-1 -1` in this case?

**Comment by choishingwan** [comment]
The main reason behind this check is that PRSice was designed with the
default UKB bgen file in mind, which doesn not contain the sample ID. As a
result, to actually report the sample PRS with their corresponding ID,
instead of their order in the bgen file, we force users to provide a
phenotype file / sample file with the exact same number of samples as those
in bgen. In the case when the sample information is located within the bgen
file, we will check if the order between the phenotype / sample file is
correct (admittedly, there are better way to handle this when sample ID is
located in bgen file, but we don't have the development time to account for
that).

In your case, I guess the easiest way to do it will be to get the sample ID
from the bgen file and manually generate a mock .sample file. Then provide
the current phenotype file you've got with the --pheno parameter.

Sam

**Comment by GiulioCentorame** [comment]
That makes sense, thank you very much.

May I ask if you have in mind any method in particular? I was thinking of importing and exporting the file through plink (e.g. `plink --bgen /path/to/file --export bgen-1.1 -out mock`), but I am not sure if that would cause PRSice to read the (potentially wrong) columns "missing" and "sex" from the mock .sample file.

A possible fix would be substituting the last two columns of the mock file with the ones from the original .sample file, but I am not sure if this would cause problems for the missing data points on "missing" and "sex" (due to the discrepancy between the two files).

**Comment by choishingwan** [comment]
If I remember correctly, sample file only require 3 columns, the FID, IID
and missing column. As long as those ID align with the ID in your bgen
file, then it should be fine. You can even give PRSice a simple ID file
contain two column (FID and IID) as an external fam file --target
bgen_prefix,ID_file. This should also work as long as your ID_file matches
your bgen  file sample list exactly. The phenotype will only be extracted
from the --pheno

Sam

**Comment by GiulioCentorame** [comment]
I submitted the job by using the sample file with an external fam file, as it was the easier way, but it's taking a fair amount of time (1.32% of clumping after 3 days with 20 GB memory, 4 nodes, 12 cpu cores per task). 
Is it expected time/behaviour on dosage data? I can definitely increase the resources if needed but I have an upper ceiling of runtime on the current node.

Might this be due to the aforementioned discrepancy between the .sample file I generated and the one I had before? 

E.g.

```
$ head data.chr1-22.sample 
ID_1 ID_2 missing sex
0 0 0 D
[...]
IEU1234567 IEU1234567 0 2
[...]
```
```
$ head fixed.data.1-22.sample 
ID_1 ID_2 missing sex
0 0 0 D
[...]
IEU1234567 IEU1234567 0.0328148 NA
[...]
```

Thank you very much for your help.

**Comment by choishingwan** [comment]
Inherently, bgen is an extremely computational intensive process. If you
give PRSice --thread 22, then it will run a bit faster, but then I am sure
the memory usage will be much higher. Am kinda surprise that you can run it
with only 20GB of memory with 2.3.5.

Sam

**Comment by GiulioCentorame** [comment]
Hmm. Thank you for this, I gave it a try with a couple of runs more but by default it was using 1 thread and not doing any progress after 1.32% (even using days, memory up to 120 GB, 28 cores).

Using `--thread` (tried both `--thread 22` & `--thread 28`) gives out the following error:

```
$ tail slurm-4362728.out    
Note: If the phenotype file does not contain a header, the 
column name will be displayed as the Sample ID which is 
expected. 

There are a total of 1 phenotype to process 

Start performing clumping 

PRSice: (path/to/PRSice/lib/bgen_lib.hpp:134: void genfile::zlib_uncompress(const byte_t*, const byte_t*, std::vector<_RealType>*) [with T = unsigned char; genfile::byte_t = unsigned char]: Assertion `result == 0' failed.
/tmp/slurmd/job4362728/slurm_script: line 46:  9946 Aborted                 PRSice --base (path/to/ieu-a-2.tsv --snp variant_id --chr chromosome --A1 effect_allele --A2 other_allele --stat beta --beta --bp base_pair_location --pvalue p_value --type bgen --target-list /path/to/fixed.data.1-22.sample --pheno /path/to/df_prs.tsv --pheno-col "body_mass_index_bmi_f21001_0_0" --thread 22 --out bmi --extract bmi.valid

```

Log file:

```
$ cat bmi.log     
PRSice 2.3.5 (2021-04-06) 
https://github.com/choishingwan/PRSice
(C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2021-04-29 11:59:32
PRSice \
    --a1 effect_allele \
    --a2 other_allele \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base /path/to/ieu-a-2.tsv \
    --beta  \
    --binary-target F \
    --bp base_pair_location \
    --chr chromosome \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --extract bmi.valid \
    --interval 5e-05 \
    --lower 5e-08 \
    --num-auto 22 \
    --out bmi \
    --pheno /path/to/df_prs.tsv \
    --pheno-col body_mass_index_bmi_f21001_0_0 \
    --pvalue p_value \
    --seed 1070926516 \
    --snp variant_id \
    --stat beta \
    --target-list /path/to/list-bgen.txt,/path/to/fixed.data.1-22.sample \
    --thread 22 \
    --type bgen \
    --upper 0.5

Initializing Genotype info from file: 
/path/to/list-bgen.txt 
(bgen) 
With external fam file: 
/path/to/fixed.data.1-22.sample 

Start processing ieu-a-2 
================================================== 

SNP extraction/exclusion list contains 5 columns, will 
assume first column contains the SNP ID 

Base file: 
/path/to/ieu-a-2.tsv 
Header of file is: 

variant_id	p_value	chromosome	base_pair_location	effect_allele	other_allele	effect_allele_frequency	beta	standard_error 

2554285 variant(s) observed in base file, with: 
417468 variant(s) excluded based on user input 
2136817 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

463005 people (0 male(s), 0 female(s)) observed 
463005 founder(s) included 

Warning: Currently not support haploid chromosome and sex 
         chromosomes 

10103956 variant(s) not found in previous data 
4176 variant(s) with mismatch information 
2136817 variant(s) included 

Phenotype file: 
/path/to/df_prs.tsv 
Column Name of Sample ID: ID_1+ID_2 
Note: If the phenotype file does not contain a header, the 
column name will be displayed as the Sample ID which is 
expected. 

There are a total of 1 phenotype to process 

Start performing clumping 

```

**Comment by choishingwan** [comment]
Try and use --allow-inter, that should solve this problem

**Comment by GiulioCentorame** [comment]
Had a try with it, but this created an allocation issue:

```
Calculate MAF and perform filtering on target SNPs 
================================================== 

Calculating allele frequencies: 100.00%
2136817 variant(s) included 

Phenotype file: 
/mnt/storage/home/zh20667/scratch/data/df_prs.tsv 
Column Name of Sample ID: ID_1+ID_2 
Note: If the phenotype file does not contain a header, the 
column name will be displayed as the Sample ID which is 
expected. 

There are a total of 1 phenotype to process 

Start performing clumping 

Clumping Progress: 0.27%terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/tmp/slurmd/job4362966/slurm_script: line 48: 20528 Aborted                 PRSice --base /mnt/storage/home/zh20667/scratch/data/gwas/ieu-a-2.tsv --snp variant_id --chr chromosome --A1 effect_allele --A2 other_allele --stat beta --beta --bp base_pair_location --pvalue p_value --type bgen --target-list ~/scratch/data/gwas/list-bgen.txt,/mnt/storage/home/zh20667/scratch/data/ukb/geno/fixed.data.1-22.sample --pheno /mnt/storage/home/zh20667/scratch/data/df_prs.tsv --pheno-col "body_mass_index_bmi_f21001_0_0" --thread 22 --allow-inter --out bmi --extract bmi.valid
```

I was concerned of running out of scratch quota but the .inter file doesn't seem to be big enough

**Comment by GiulioCentorame** [comment]
I tried another run, but it ran out of memory again:

```
2554285 variant(s) observed in base file, with: 
417468 variant(s) excluded based on user input 
2136817 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

slurmstepd: error: Job 4421339 exceeded memory limit (1396136 > 1024000), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 4421339 ON compute387 CANCELLED AT 2021-05-04T11:08:55 ***
```

Which is the last thing I was expecting, considering I allocated 1TB and 28 cores for this:
```
$ head test_job.sh 
#!/bin/bash

#SBATCH --job-name=prsice_bmi
#SBATCH --partition=cpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=28
#SBATCH --mem=1000
#SBATCH --mail-type=ALL,TIME_LIMIT_80
#SBATCH --time=14-00:00:00
```

I was wondering if it could be a I/O problem similar to the one mentioned [here](https://groups.google.com/g/prsice/c/HkuLVgPiFIw/m/qTGVsDUGCgAJ)?

**Comment by choishingwan** [comment]
As of now, bgen can be extremely memory intensive. So if you don't really
need the dosage score, the best way will be to first translate the bgen to
plink format. I will try to improve this section of the code once I have
time for it. Sorry about that.

Sam
