### ISSUE TITLE
Reverse quantile plot

### ISSUE THREAD

**Issue by jPontix** [choishingwan/PRSice#267]
Hi, I'm calculating the PRS for a binary trait. I'm using a GWAS composed of ~8000 samples and as target data ~2000 samples. In the target data, we have the 323 participants affected (1) and 2187 that are not affected(0). Looking at the quantile plot it seems that is reverse. What do you suggest doing?

The code that I using is the following:

`/data/shared/bioinf/R/bin/Rscript-4.0-BioC3.12 PRSice.R --prsice ./PRSice_linux --A1 Allele1 --A2 Allele2 --base /GWAS/SAIGE_binary_association.txt --binary-target T --ignore-fid --beta --stat BETA --pheno /pheno/muo.txt --pheno-col metNotHlty --pvalue p.value --snp SNPID --target /genotypingData/10k_imputedData --keep /pheno/subset.txt --nonfounders --quantile 10 --out /prs_muo`

![prs_sr1_QUANTILES_PLOT_2021-05-13](https://user-images.githubusercontent.com/45068286/118543363-7d2a6b80-b754-11eb-99f3-b2937269bc89.png)

**Comment by choishingwan** [comment]
It is possible, especially if your base and target are for different
phenotype or if there is a negative correlation between the phenotype
measurement in base and in target.

**Comment by jPontix** [comment]
The base and target data are based on the same binary phenotype

**Comment by choishingwan** [comment]
The encoding of case control are identical in both?

What's the association R2 and P-value?

**Comment by jPontix** [comment]
Yes, I built my gwas with the same encoding that I have in the target data.

PRS.R2= 0.0352465
P=1.65997e-12

**Comment by choishingwan** [comment]
That is strange.

Which version of PRSice are you using? Also, can you check the genetic
correlation between your base and target samples (if you have enough sample
size).

**Comment by jPontix** [comment]
I'm using the PRSice 2.3.3 (2020-08-05). Ok, I'm going to check the correlation between the base (7378 samples) and the target (2509 samples) samples. Thanks

**Comment by anastazie-dnanexus** [comment]
I have the same issue and solved it by reversing `--a1` and `--a2` as following:
`    --a1 A2 \
    --a2 A1 \` I have GWAS results from regenie, so` A1` is `Ref` and `A2` is `Alt`.
