### ISSUE TITLE
Blank PRS column in all_score file when using .bgen target files

### ISSUE THREAD

**Issue by LiliGM** [choishingwan/PRSice#269]
Dear Sam,

I am using PRSice 2.3.1.e to calculate PRS on .bgen target files (I have one .bgen file per chromosome). The log file indicates that the whole process went well, but when I open the all_score file (this is my main output of interest; I am requesting PRS calculated at a single p threshold of 1), the Pt_1 column that should have the PRS is empty, e.g.:

FID IID Pt_1
11194A 11194A                   
15457A 15457A                   
14240A 14240A                   
13689A 13689A                   
13322A 13322A                   
6258A 6258A    

The all_score file has the ID's and rows for the correct amount of participants, but the PT_1 column is just blank. I have tested this on three different summary statistics, and I get the same result each time. 

For additional information, I was previously using non-imputed PLINK binary target files from the same sample and when I calculated PRS on the same summary statistics, the all_score files looked fine. The reason why I am interested in using imputed genetic data now is because the PRS on the non-imputed data are calculated on a small number of SNPs and they are not correlated to each other in the way they should, so I would like to get more accurate PRS. 

I am sharing the log files for the PRS calculation on the .bgen target files ('Anxiety_imp.log') and on the PLINK target files ('Anxiety.log'), in case this is useful.

Thank you for your attention!

[PRS_ALSPAC_Anxiety_imp.log](https://github.com/choishingwan/PRSice/files/6545647/PRS_ALSPAC_Anxiety_imp.log)
[PRS_ALSPAC_Anxiety.log](https://github.com/choishingwan/PRSice/files/6545660/PRS_ALSPAC_Anxiety.log)

**Comment by choishingwan** [comment]
If you don't mind, can you use the latest version (2.3.3)? It seems like a
bug, but I am not sure if this is solved in the latest version.

**Comment by LiliGM** [comment]
Dear Sam,

Thank you very much for your answer, and I am sorry for the delay in my reply!

I have tried using the latest version of PRSice, and the scores have been generated without issues now!

However, I see that the correlations between my PRS are still not making much sense... I am looking at correlations between anxiety and depression PRS; the PRS should in theory be positively correlated, and LDSC shows that the genetic correlations between the summary statistics used to compute these PRS are high and positive (0.87), however, the correlation between these PRS in my sample is equal to -0.33.

If you would happen to have any advice or suggestion on what I could check or modify to make sure the computed PRS are accurate, could you please let me know? Otherwise, if this question is outside of the queries for this forum, I want to thank you for your help this far.

Best wishes,
Liliana

**Comment by choishingwan** [comment]
Some questions to help understanding the situation:
1. Did you use the same GWAS samples for LDSC analysis and PRS?
2. Did you calculate the PRS on the same target data?

It is indeed odd that the PRS is negatively correlated to that degree.
Might need more information to understand what's going on

**Comment by LiliGM** [comment]
Hi Sam,

Thank you for your quick reply!

1. Yes, I used the same summary statistics/GWAS for both the LDSC and the PRS calculation.
2. Yes, I calculated both PRS on the same target data.

I have also looked at the correlations between the PRS computed with non-imputed and imputed target data, and those correlations are high (the correlation between the anxiety PRS obtained from imputed and non-imputed target data is .87, and the correlation between the depression PRS obtained from imputed and non-imputed target data is .7).

If there is any other information that I could provide for you to help better understand this issue, could you please let me know?
