### ISSUE TITLE
INFO score filtering on BGEN file directly

### ISSUE THREAD

**Issue by choishingwan** [choishingwan/PRSice#27]
We can calculate the INFO score using the following equation (similar to PLINK)

import numpy as np

m=Mean of expected genotype
v=variance of expected genotype
p=m/2
p_a = 2*p*(1-p)
INFO = v/p_a

**Comment by JoniColeman** [comment]
How does this relate to IMPUTE / MACH info scores?

**Comment by choishingwan** [comment]
This is the MaCH imputation r-squared value.

**Comment by choishingwan** [comment]
The code for this is now ready. Need to test run once the whole major update is completed
