### ISSUE TITLE
[BUG]Error: No valid variant remaining

### ISSUE THREAD

**Issue by joannananana** [choishingwan/PRSice#271]
**Describe the bug**
After using the --extract *.valid file that PRSice produces, I got the following error. The valid file is empty.

**Error Log**
PRSice 2.3.3 (2020-08-05) 
https://github.com/choishingwan/PRSice
(C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2021-06-18 01:21:42
/home/gsoft/PRSice_linux/PRSice_linux \
    --a1 A1 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base /home/jgavra/PRS.17.6/base/Resample02_train.txt.assoc.logistic \
    --beta  \
    --binary-target 3F \
    --bp BP \
    --chr CHR \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov /home/jgavra/PRS.17.6/target/covar/Resample02_covar.txt \
    --extract /home/jgavra/PRS.17.6/results/2.valid \
    --interval 5e-05 \
    --lower 5e-08 \
    --num-auto 22 \
    --out /home/jgavra/PRS.17.6/results/2 \
    --pheno /home/jgavra/PRS.17.6/target_phen.pheno \
    --pheno-col TGmgdL,SGOTASTUL,SGPTALTUL \
    --print-snp  \
    --pvalue P \
    --seed 4054952183 \
    --snp SNP \
    --stat OR \
    --target /home/jgavra/PRS.17.6/target/pca/Resample02 \
    --thread 1 \
    --upper 0.5

Initializing Genotype file: 
/home/jgavra/PRS.17.6/target/pca/Resample02 (bed) 

Start processing Resample02_train.txt.assoc 
================================================== 

SNP extraction/exclusion list contains 0 columns, will 
assume first column contains the SNP ID 

Base file: 
/home/jgavra/PRS.17.6/base/Resample02_train.txt.assoc.logistic 
Header of file is: 
 CHR                  SNP         BP   A1       TEST    
NMISS         OR         STAT            P  

2839331 variant(s) observed in base file, with: 
2839331 variant(s) excluded based on user input 
0 total variant(s) included from base file 

Error: No valid variant remaining 

**comments**
I have already checked issue #189 and the format of the columns is the same accross the files.

**Comment by choishingwan** [comment]
Think this might be a bug that I've not got time to fix as of yet (printing
empty valid file). You can manually remove duplicated SNPs from your GWAS
data and see if this issue persists.

Sam
