### ISSUE TITLE
Validating pathway scores in independent datasets and p-value threshold

### ISSUE THREAD

**Issue by hengi110** [choishingwan/PRSice#273]
Hello,

I'd like to use PRSet to compute pathway scores in one dataset and validate significant scores according to p-value of association in three other datasets. To make sure I'm using the same set of SNPs for each pathway in all datasets, I used the --print-snp flag. I will then use plink to compute scores in other datasets. Does this sound correct?
Another question I have is that I had --bar-levels in the command but --fastscore is not set, so according to previous posts --bar-levels is ignored and p-value threshold of 1 should have been used. However, in the .summary file 'Threshold' varies across pathways. Shouldn't they all be 1? The first few lines look like this:
Phenotype       Set     Threshold      ...
-       Base    0.0718001       0.027855       ...
-       BIOCARTA_FEEDER_PATHWAY 0.1213  ...
-       BIOCARTA_PROTEASOME_PATHWAY     0.1761  ...
-       BIOCARTA_KREB_PATHWAY   1      ...
...
This is the command I used:
Rscript PRSice.R \
    --prsice PRSice_linux \
    --base summary.txt \
    --bar-levels 5e-8,5e-6,5e-4,0.005,0.05,0.5 \
    --target target_chr#,target.sample \
    --type bgen \
    --print-snp \
    --prevalence 0.0015 \
    --beta \
    --cov taget.Covar.txt \
    --pheno target.Pheno.txt \
    --gtf Homo_sapiens.GRCh38.86.chr.gtf \
    --msigdb c2.cp.v7.2.symbols.subsetR2.01.gmt \
    --multi-plot 20 \
    --memory 120G \
    --stat BETA \
    --binary-target T \
    --out output

Thanks very much for your help.

Best,
Hope

**Comment by choishingwan** [comment]
Sorry for the delay,

1. If you set **any** parameters related to thresholding i.e. `--fastscore` `bar-levels` `inter` `lower` or `upper`, the current behaviour of PRSet is to run the thresholding. I am looking for something more intuitive to control PRSet's behaviour in future releases. 
2.
