### ISSUE TITLE
[Suggestions please] Including X chromosome in PRS using PRSice (sex-stratified data)

### ISSUE THREAD

**Issue by ettheberge** [choishingwan/PRSice#276]
Hello!

I'm new to the field of generating PRSs and would appreciate your help.

I have two sex-stratified GWASs for my trait of interest that I'm contrasting against a classic "sex-naive" one (where sex is regressed out during the GWAS analyses). The GWASs (unsurprisingly) resulted in different SNPs and effect sizes on the X between the males and females: I'd like to make PRSs that include this X chromosome information with PRSice. However, the dosage data for the X requires special consideration between males and females per an additive model: effect allele dosage for females are encoded as 0, 1, 2 and 0, 2 for males.

I'd appreciate your thoughts on how you think is best to integrate this sex-specific dosage information in the PRSice pipeline. I've done autosome-only analyses so far and am wondering how to include the X using the [available commands](https://www.prsice.info/command_detail/). 

My current autosomal-SNPs-only input into PRSice is as following:

```
Rscript PRSice.R --dir . \
--prsice PRSice_linux \
--base <my_base_data>.txt \
--stat BETA \
--target <my_target_data> \
--pheno <my_binary_pheno_data>.txt \
--pheno-col <pheno_label> \
--thread 1 \
--binary-target T \
--quantile 99 \
--quant-break 10,20,30,40,50,60,70,80,90,99 \
--lower 0.0001 \
--upper 0.4 \
--print-snp \
--out <name_output> \
```

Look forward to hearing what you think I should add to this for effectively incorporating the X into the PRS using my sex-stratified base and target data. Thank you!

**Comment by choishingwan** [comment]
Hi Emilie,

Thank you for your email. Your idea is very interesting and I am sure that
is of great importance. If you are only looking at the autosome (likely not
though...), then you can "manipulate" PRSice to calculate PRS for male and
female separately by providing the different GWAS and use the `--keep` and
`--remove` parameter to select / remove male / female from your PRS
calculation. You can then combine the male / female output together and
re-run the regression to get the final regression performance.

However, if you are trying to work on the sex chromosome, you are out of
luck with PRSice as support for sex chromosomes are yet to be implemented.
For now, the best way to move forward would be to use PLINK for that as
PLINK can calculate LD and PRS for the sex chromosome. Again, --keep and
--remove will be your friend in terms of what you want to do .

Hope this help

Sam

**Comment by ettheberge** [comment]
Hi Sam,

Thank you! Hoping to put out a paper next year about it, stay tuned. :) 

To your first point, actually yes, I have created PRSs just using the autosomes so far (spoiler alert: sex differences...). 

Darn, that's too bad there isn't support for the sex chromosomes yet in PRSice (yet, hopefully soon!). Glad I asked you here first. I'll work in plink for the X with those flags in mind as you've suggested. thank you so much for the tips! Much appreciated.

Hope you have a good week.

Best,
Emilie

**Comment by choishingwan** [comment]
FYI, if I remember correct, this paper might be of interest to you: https://pubmed.ncbi.nlm.nih.gov/26763874/
