### ISSUE TITLE
Regress out Covariates from PRS when --no-regress is used

### ISSUE THREAD

**Issue by choishingwan** [choishingwan/PRSice#28]
Requested by Jessye

**Comment by JoniColeman** [comment]
I would suggest making this an option, rather than a default.

**Comment by choishingwan** [comment]
Hm... this should only happen if someone use both --no-regress and --cov-file

Or do you think I should add an additional flag just to make this clearer? Or do you think this will also be a good option for people who are not using --no-regress?
