### ISSUE TITLE
[BUG] related to unknown/sex chromosome? 

### ISSUE THREAD

**Issue by asthakhatiwada** [choishingwan/PRSice#280]
bug issue: seems related to processing the base data that contains SNP, CHR, BP, A1, OR, P. All SNPs are excluded as they are "on unknown/sex chromosome" -- this seems irrelevant for the base data.. but my target data doesn't include sex information.. is that what's causing the issue? Does PRSice not work when sex information is not present in the target data?

 
**Error Log**

PRSice 2.3.3 (2020-08-05) 
https://github.com/choishingwan/PRSice
(C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2021-10-14 17:00:40
./PRSice_mac \
    --a1 A1 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base AA_base.txt.gz \
    --binary-target T \
    --bp BP \
    --chr CHR \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --interval 5e-05 \
    --lower 5e-08 \
    --num-auto 22 \
    --or  \
    --out AA_PRS \
    --pvalue P \
    --seed 2742174452 \
    --snp SNP \
    --stat OR \
    --target topmed_imputed_allchr_qc_phenotype_onlyAA \
    --thread 1 \
    --upper 0.5

Initializing Genotype file: 
topmed_imputed_allchr_qc_phenotype_onlyAA (bed) 

Start processing AA_base.txt 
Base file: AA_base.txt.gz 
GZ file detected. Header of file is: 
SNP	CHR	BP	A1	OR	P 

Reading 100.00%
789303 variant(s) observed in base file, with: 
789303 variant(s) excluded as they are on unknown/sex 
chromosome 
0 total variant(s) included from base file 

Error: No valid variant remaining 

Error: 
Execution halted

**Comment by choishingwan** [comment]
Mind showing the first 2~3 lines of your summary statistic file?

**Comment by asthakhatiwada** [comment]
Also, if you look at the error log I posted yesterday, it is reading in the correct columns. I have copied part of the error log below...

--bp BP 
--chr CHR 
--clump-kb 250kb 
--clump-p 1.000000 
--clump-r2 0.100000 
--interval 5e-05 
--lower 5e-08 
--num-auto 22 
--or 
--out AA_PRS 
--pvalue P 
--seed 2742174452 
--snp SNP 
--stat OR

**Comment by asthakhatiwada** [comment]
You are correct - row names were added to my data that's why I was seeing that error log. I was able to resolve that particular issue by removing those row names...thanks for your help!
