### ISSUE TITLE
Obtaining results for pre-specified SNP inclusion thresholds

### ISSUE THREAD

**Issue by tpillinger** [choishingwan/PRSice#283]
Hi Sam,

Apologies if I have missed how to do this on the ‘available commands’ page, but I would like to obtain results for pre-specified SNP inclusion thresholds (e.g., 0.01, 0.05, 0.1, 0.5, 1) rather than the ‘best fit’ threshold calculated by PRSice. In other words, I would like to get a ‘PRSice.summary’ file but for the SNP inclusion thresholds of my choice. Can you let me know how to achieve this? I’ve pasted the current commands below that I’m using – I can create the barplot with different bar levels but can’t get the associated results.  

Many thanks, 

Toby 

 

Command: 
 
Rscript PRSice.R --dir . \ 
--prsice PRSice_linux \ 
--base /rds/general/user/tpilling/projects/toby_ukbb/live/genetics/imputed_data/PGC3_SCZ_wave3_clumped.Transformed.tsv.gz \ 
--no-clump \ 
--snp SNP --chr CHR --bp BP --A1 A1 --A2 A2 --stat OR --pvalue P \ 
--target BB_imputed_PGC3_SCZ_wave3_clumped_SNPs_only_allCHR.QC_final \ 
--pheno pheno_noscz_lvesvi.pheno \ 
--binary-target F \ 
--cov covariates_noscz.txt \ 
--stat OR \ 
--base-info INFO:0.8 \ 
--quantile 10 \ 
--bar-levels 0.01, 0.05, 0.1, 0.5, 1

**Comment by choishingwan** [comment]
You can just read the .prsice file, which should include the per threshold
results.

You just need `--fastscore` and you are good to go.

**Comment by tpillinger** [comment]
Got it, thanks Sam!
