### ISSUE TITLE
Extract the exact snps included in the best model

### ISSUE THREAD

**Issue by Fnyasimi** [choishingwan/PRSice#285]
@choishingwan  Thanks for the nice software.

I am wondering is there a way to extract the SNPs used in the best model instead of just the number of SNPs? I would like to find the specific SNPs for further analysis and mapping for downstream process. What would be the best way to extract these individual SNPs from the best fit model?

**Comment by choishingwan** [comment]
--print-snp

You will need to filter by p-value though.

**Comment by Fnyasimi** [comment]
The threshold p-value right. Thanks

**Comment by choishingwan** [comment]
correct

**Comment by Fnyasimi** [comment]
Thank you

**Comment by michellekee** [comment]
Hi, when filtering for the best p-value threshold ( aka pT) to obtain the SNP list , do we filter as p < pT or p <= pT?

**Comment by choishingwan** [comment]
<=
