### ISSUE TITLE
How to apply to Discovery dataset

### ISSUE THREAD

**Issue by ArashLab** [choishingwan/PRSice#290]
Hi, I am a bit confused about how to use PRSice-2 to calculate the Polygenic Risk Score for the discovery dataset.

I have a Case/Control dataset (binary phenotype) and I split samples into 70% (base dataset) and 30% (target dataset)
I used the plink --assoc for the base dataset and then use PRSice to calculate PRS for the target dataset.

I have a separate dataset (discovery) without the phenotype. How can I calculate PRS for the discovery dataset? It seems that PRS requires phenotype for the target data and complaints if no phenotype is provided.

**Comment by choishingwan** [comment]
You can use `--no-regress --no-full --bar-levels XXX --fastscore` where XXX is the best threshold you found via your CV
