### ISSUE TITLE
Error: Cannot open file: 510

### ISSUE THREAD

**Issue by theclairecamp** [choishingwan/PRSice#295]
**Issue**
I have used the recommended input files but am getting an error. This is the exact line of code I used to run PRSice:
`Rscript PRSice.R --dir . --prsice PRSice_mac --base Base_Data.gz --target Target_Final --binary-target F --pheno Final.phenotype --cov Final.covariate --ignore-fid --clump-r2 0.25 --clump-kb 200 --fastscore T --x-range chr6:28,510,120-33,480,577 --stat OR`

I am running the code in the directory with all the files necessary. The phenotype and covariates are tab-delimited files, and the Target_Final.bed/bim/fam files are located within the current directory. I'm wondering what exactly isn't loading, I tried looking at the specific line of code in PRSice.R to figure it out but still haven't figured out the bug yet. I'm thinking maybe it's a simple issue with formatting somewhere?

**Error Log**
This is the error log that popped up:

```
Error: Cannot open file: 510 

Begin plotting
Current Rscript version = 2.3.3
Error in fread(paste0(argv$out, ".summary"), data.table = F) : 
  File 'PRSice.summary' does not exist or is non-readable. getwd()=='/Users/claire/Desktop/Genotype/PRSice_mac'
Execution halted
```

**To Reproduce**
_Here is the PRSice log file info:_
PRSice 2.3.5 (2021-09-20) 
https://github.com/choishingwan/PRSice
(C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2022-05-16 15:29:02
./PRSice_mac \
    --a1 A1 \
    --a2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base Base_Data.gz \
    --base-info INFO:0.9 \
    --binary-target F \
    --bp BP \
    --chr CHR \
    --clump-kb 200kb \
    --clump-p 1.000000 \
    --clump-r2 0.250000 \
    --cov Final.covariate \
    --fastscore  \
    --ignore-fid  \
    --num-auto 22 \
    --or  \
    --out PRSice \
    --pheno Final.phenotype \
    --pvalue P \
    --seed 1941739298 \
    --snp SNP \
    --stat OR \
    --target Target_Final \
    --thread 1 \
    --x-range chr6:28,510,120-33,480,577

Error: Cannot open file: 510 

**Thanks for you help!**

**Comment by choishingwan** [comment]
Hi,  that's because your x-range command contains comma which was
interpreted as a file input instead of range (see that the missing file
name is 510). Remove the comma from the range input and you should be good
to go

**Comment by theclairecamp** [comment]
THANK YOU! That was it! I was wondering where 510 was coming from...I really appreciate your response.
(also, I've tried to remove the 'bug' label but I can't seem to remove it...my bad)
