### ISSUE TITLE
can not find the "PRSice_win64.exe"

### ISSUE THREAD

**Issue by junjiaoFeng** [choishingwan/PRSice#303]
Hi, choishingwan,
I want to run PRSice functions on window system, however, I can not find the "PRSice_win64.exe".

**Comment by choishingwan** [comment]
You can download it here https://choishingwan.github.io/PRSice/

**Comment by junjiaoFeng** [comment]
Thank you for your kindness help!
Junjiao Feng
















At 2022-10-01 06:56:40, "Shing Wan Choi" ***@***.***> wrote:

You can download it here https://choishingwan.github.io/PRSice/
