### ISSUE TITLE
PRSice website is down

### ISSUE THREAD

**Issue by theclairecamp** [choishingwan/PRSice#304]
**Describe the bug**
The PRSice website is down (http://prsice.info/)

**Additional context**
Is there are timeline as to when this will be back up? 
Thanks!

**Comment by choishingwan** [comment]
Thanks Claire, long story short, we've forgotten to pay the domain hosting
service and have lost the domain. You can still access the site here:
https://choishingwan.github.io/PRSice/

**Comment by FischyM** [comment]
You should update the link in your README.md NOTE section as well.
