### ISSUE TITLE
Plotting PRSice results 

### ISSUE THREAD

**Issue by oalavijeh** [choishingwan/PRSice#305]
I have a binary trait and have generated a PRSice file. 

I would like to plot this but work on a HPC environment where plotting doesn't really work. 

I have tried following the code from here: https://choishingwan.github.io/PRS-Tutorial/plink_visual/ to turn the PRSice.summary score into a bar plot but I think because I haven't binned the P-values into slot the plot is supercongested (See screenshot). 

How would I convert a PRSice.summary score into the "prs.result" file that would be needed to plot from your tutorial? 

Many thanks 

![image](https://user-images.githubusercontent.com/56344383/194878849-47761623-b931-4865-9561-73fc64a04dbd.png)

**Comment by choishingwan** [comment]
I don't know what you are trying to do. But if you have all the PRSice output, and you can download them to your local machine, then you can run `--plot` to do the plotting. You only need to result files for that, so you won't need to download the genotype data

**Comment by Janina24** [comment]
I have the same issue ... After running PRSice no plots are in the results

**Comment by choishingwan** [comment]
Log please?

**Comment by Janina24** [comment]
[AugUR2.log](https://github.com/choishingwan/PRSice/files/9829605/AugUR2.log)
