### ISSUE TITLE
Standardization of effect sizes

### ISSUE THREAD

**Issue by chrislowh14** [choishingwan/PRSice#313]
Hi Sam,

Hope you are doing well!

I am working with PRSice-2 on calculating polygenic scores.

In particular, I am wondering about the actual function of the --std flag.
While the --con-std flag standardized the effect sizes based on mean and sd of controls, how does the --std flag differ from the --con-std flag in terms of standardization?

Does the --std flag standardize the effect sizes to mean of 0 and sd of 1?

Many thanks!

**Comment by choishingwan** [comment]
`--std` does the same thing except the mean and sd were calculated from the full dataset, thus might subject to ascertainment bias
