### ISSUE TITLE
it is likely that your base and target data has different encoding for SNPs. You will need to check that.

### ISSUE THREAD

**Issue by theclairecamp** [choishingwan/PRSice#314]
it is likely that your base and target data has different encoding for SNPs. You will need to check that.

_Originally posted by @choishingwan in https://github.com/choishingwan/PRSice/issues/189#issuecomment-600703938_

I actually have this issue, with two different types of encoding for SNPs, my base file is in this format: rs62513865, while my target file is in this format: chr1:54490:G:A

Do you have any recommendations for easily switching the format? I am using build hg19.

**Comment by choishingwan** [comment]
That's something we tried to implement before I left academic. As of now, the best way to move forward is to update the encoding in your base file to the chr code.
