### ISSUE TITLE
SNPs with extremely low P-value

### ISSUE THREAD

**Issue by Apprentice2** [choishingwan/PRSice#320]
I would like to construct a Polygenic risk score using PRSice-2. However, our summary statistics contains a very small P-value, such as P-value=5.0x10^-1200.
Perhaps that is why we cannot use this summary statistics to construct the PRS. How can I solve this problem? I would be grateful if you could enlighten me.

**Comment by choishingwan** [comment]
Yes, they are problematic. Easiest way is to set them to have the smallest
non-zero p-value (e.g. 1e-300) and make sure the rank of the SNPs remain
the same. The p-values are only used for clumping, so it should not affect
your results as long as the rank are the same (and p-value of 1e-700 are
technically 0 for computer anyway)

**Comment by Apprentice2** [comment]
Thank you for your advice. Based on your advice, I will change the P-value to 1e-301 for SNPs with the smallest P-value that I want to be selected as PRS to remain clumping, and change the P-value to 1e-300 for all other SNPs with P-values below 1e-300.
