### ISSUE TITLE
Is PRS.R2=Full.R2-Null.R2 correct?

### ISSUE THREAD

**Issue by Apprentice2** [choishingwan/PRSice#321]
Thank you for developing a great tool.
I am developing a PRS for quantitative traits using PRSice-2. Of course, --beta, --binary-target F options were implemented it. I developed PRS with target data and the resulting summary file shows the following.

Phenotype	Set	Threshold	PRS.R2	Full.R2	Null.R2	Prevalence	Coefficient	Standard.Error	P	Num_SNP
-	Base	5e-08	0.0149295	0.283942	0.273089	-	19.5742	2.03261	8.50818e-22	30

I am aware that PRS.R2=Full.R2-Null.R2. However, Full.R2-Null.R2=0.010853 in this result, which does not match 0.0149295 above. Why is this? I would appreciate it if you could enlighten me.

**Comment by choishingwan** [comment]
It's 1-(1-full)/(1-null)

**Comment by Apprentice2** [comment]
Thank you for you quick reply. I found a perfect match with the formula you gave me.
