### ISSUE TITLE
How to use PRSice without a p-value (e.g data from PGSCatalog)

### ISSUE THREAD

**Issue by frankMusacchia** [choishingwan/PRSice#323]
Hello, I am using PRsice with base data from PGScatalog. Nonetheless, I should use a --pvalue but it is not used in PGS catalog.
The following are the first lines of a PGSCatalog file for ADHD disease
rsID	chr_name	chr_position	effect_allele	other_allele	effect_weight	OR	hm_source	hm_rsID	hm_chr	hm_pos	hm_inferOtherAllele
rs139197039	10	10000797	A	G	-0.09709477124079369	0.90747	ENSEMBL	rs139197039	10	9958834	
rs139360817	10	10001085	A	G	-0.08110160143704147	0.9221	Unknown				
rs7907011	10	100034296	T	C	0.04009533056394215	1.04091	ENSEMBL	rs7907011	10	98274539	

as you can see there is no pvalue here to use. I went through a forum and someone tells to add a column with 0s. Yet, this idea conduct to false data and plots IMHO.
Could you tell me what is the best thing to do in such cases?
Thanks in advance
Francesco

**Comment by choishingwan** [comment]
Effect sizes from PGS catalog were already optimized. As such you don't
need to do clumping nor thresholding with them. You can either directly use
PLINK to obtain the score, or as stated in other thread, give each SNP the
same P-value and then use the following comment:

--no-clump --no-full --bar-levels 1 --fastscore

Such that PRSice will use all the SNPs to calculate the target PRS without
doing thresholding or clumping.

Sam

**Comment by frankMusacchia** [comment]
Dear Sam, thanks for your prompt response. And thanks for suggesting how to do the analysis. Best regards Francesco Il giorno 14 giu 2023, alle ore 02:58, Shing Wan Choi ***@***.***> ha scritto:﻿
Effect sizes from PGS catalog were already optimized. As such you don't

need to do clumping nor thresholding with them. You can either directly use

PLINK to obtain the score, or as stated in other thread, give each SNP the

same P-value and then use the following comment:



--no-clump --no-full --bar-levels 1 --fastscore



Such that PRSice will use all the SNPs to calculate the target PRS without

doing thresholding or clumping.



Sam
