### ISSUE TITLE
No error but getting no plot

### ISSUE THREAD

**Issue by zillurbmb51** [choishingwan/PRSice#327]
[prs_scz_bmi_maf_0.05_beta.log](https://github.com/choishingwan/PRSice/files/11939938/prs_scz_bmi_maf_0.05_beta.log)
Hi,
I ran PRSice without any error. At the end it shows "`Begin plotting``\n`" `Current Rscript version = 2.3.3`
I have downloaded the latest code from this github page. Should not it be 2.3.5?
The point is it generates no plot. Even I added the `--plot` argument but still same. No plot. How could I plot the results? Attached is the log file. I am using HPC environment but it should not be an issue because other Rscripts that create plots, they work perfectly without any issue. Any help?

**Comment by choishingwan** [comment]
No plot will be generated if you use `--no-regress` as we cannot plot the performance of regression model that was not performed

**Comment by SoumenMaity922** [comment]
Hi, 
I have written the following codes to run PRSice-2. It run without any error but it doesn't create any plot, it only creates three files EUR.prsice, EUR.best and EUR.all_score. 
PRSice --base Height.QC.gz --base-info INFO:0.8 --base-maf MAF:0.01 --target EUR.QC --pheno EUR.height --cov EUR.covariate --stat OR --or --out EUR  --pvalue P --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5 --binary-target F.
I am using the HPC environment through Mobaxterm. Please help.

**Comment by choishingwan** [comment]
Have answered the question in another issue.
