### ISSUE TITLE
All the variants are excluded, No valid variants

### ISSUE THREAD

**Issue by msarguru** [choishingwan/PRSice#340]
Good day! 

There are similar threads with the same issue. 
I have tried out all the different solutions, which did not help. Please see the log below, 

Using PRSice version 2.3.5
And the SNPID from base file and from the target file matches, no duplicates, no special characters.
Tried to follow https://www.biostars.org/p/9499252/ 
And I could see, 9612 variants have matching Rsids between the base and target file, allele, chr:pos details are also matching. 

It would be great to have your suggestions.. 
Thanks 

The log reads as..
PRSice/bin/PRSice \
    --a1 Allele1 \
    --a2 Allele2 \
    --bar-levels 1e-05,0.001,0.01,0.1,0.5,1 \
    --base basefile32K.forPRSICE \
    --beta  \
    --binary-target F \
    --bp POS \
    --chr CHR \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.010000 \
    --cov UKB.COVAR \
    --fastscore  \
    --id-delim "tab" \
    --num-auto 22 \
    --out UKBK.forPRSICE.PRSice \
    --perm 10000 \
    --pheno ukbgen.PHE \
    --pvalue pvalue \
    --seed 3019675116 \
    --snp MarkerName \
    --stat Effect \
    --target ukb668904.Set.chr# \
    --thread 1

Initializing Genotype file:
ukb668904.Set.chr# 
(bed)

Start processing
UKBK
==================================================

SNP extraction/exclusion list contains 5 columns, will
assume first column contains the SNP ID

Base file:
basefile32K.forPRSICE
Header of file is:
MarkerName      CHR     POS     Allele1 Allele2 Effect  StdErr  pvalue

9714 variant(s) observed in base file, with:
9714 variant(s) excluded based on user input
0 total variant(s) included from base file

Error: No valid variant remaining

**Comment by choishingwan** [comment]
Are you sure that's the command? The log mentioned snp extraction/
exclusion file with 5 column, but I don't see a corresponding input in the
command

**Comment by msarguru** [comment]
Thank you for the reply.
I think there was feedback with the option --extract being used in the script. That removes all the valid SNPs..
omitting this option, the script runs fine..
