### ISSUE TITLE
scores

### ISSUE THREAD

**Issue by mfazel** [choishingwan/PRSice#342]
Hi,
I have a probably simple question which I tried to answer by reading docs and previous issues but could not find an answer to it.
I could not find anywhere in the documentations and --help what your definition for --a1 (A1) and --a2 (A2) are. If I assume you are using plink output and PRSice A1/A2 and plink's are the same, then A1 is usually the minor allele and the one that is tested. It's also mentioned in the documentation that PRSice2 takes care of flipping the OR/BETA direction and converting 0/1/2 to 2/1/0 if necessary to count the risk alleles for each individual. 
Now my question is, why when I run any dataset including PRSice toy example, there are negative scores in the toy.best file? Am I missing something or how do I interpret the negative scores? should user manually modify sumstat and plink file before running PRSice?
here are the first 10 values from toy.best

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\siose\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\siose\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">

</head>

<body link=blue vlink=purple>

FID | IID | In_Regression | PRS
-- | -- | -- | --
CAS_1 | CAS_1 | Yes | -0.006
CAS_2 | CAS_2 | Yes | -0.00631
CAS_3 | CAS_3 | Yes | -0.00227
CAS_4 | CAS_4 | Yes | -0.00204
CAS_5 | CAS_5 | Yes | -0.00083
CAS_6 | CAS_6 | Yes | -0.00225
CAS_7 | CAS_7 | Yes | -0.00069
CAS_8 | CAS_8 | Yes | -0.00413
CAS_9 | CAS_9 | Yes | 0.002567
CAS_10 | CAS_10 | Yes | 0.001863

</body>

</html>

Thanks.
Mehdi

**Comment by choishingwan** [comment]
score can be negative. The way to understand that is to think that a variant with a negative effect size is reducing the risk of disease relative to the non-effective allele.
