### ISSUE TITLE
Unrecognized Option

### ISSUE THREAD

**Issue by SoumenMaity922** [choishingwan/PRSice#343]
Hi, 
I am new to this application. In the following link https://choishingwan.github.io/PRSice/command_detail/ they have mentioned some commands for plotting purposes like  --bar-col-high, --bar-col-low, and few more. But When i write the command like PRSice --base Height.QC.gz --target EUR.QC --binary-target F --pheno EUR.height --cov EUR.covariate --base-maf MAF:0.01 --base-info INFO:0.8 --stat OR --or --out EUR --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5 --bar-col-high "firebrick" --bar-col-low "dodgerblue" It shows an error like Unrecognized option '--bar-col-high'. Why this is happening?? Any help??

**Comment by choishingwan** [comment]
Same answer to your previous question:

You need to use the PRSice R script in addition to the executable.

**Comment by SoumenMaity922** [comment]
But sir,
I am writing the above command in the HPC environment. Truly speaking, I don't understand what are you trying to say. I am really new in this domain. Can you please tell me in a more elaborate and what I have to do exactly?  It will be very helpful. 
Thanks in advance.

**Comment by choishingwan** [comment]
I'd refer you to our documentation

https://choishingwan.github.io/PRSice/quick_start/

Am currently away in a conference

Sam
