### ISSUE TITLE
Error can't open base file

### ISSUE THREAD

**Issue by youniwerse** [choishingwan/PRSice#344]
Hi, 

I'm trying to use a GWAS summary data as the base file. But I keep receiving the following error message: 

youwang@Yous-MacBook-Pro PRsice_mac % Rscript PRSice.R --prsice PRSice_mac --base "/Users/youwang/Desktop/PUMC/GFAP_analysis/shunyi_data/HDL_EA"
Error: Cannot open file - /Users/youwang/Desktop/PUMC/GFAP_analysis/shunyi_data/HDL_EA

Below is the first 10 rows of the GWAS summary data I'm trying to use. Is it because it's not formatted properly?

X SNP_hg19 ID A1 A2 BETA SE N P Freq.A1.1000G.EAS SNP
14235 10:113913222 rs2297991 C T -0.04947 0.007203 47456 6.52e-12 0.7579 10:113913222:T:C
14239 10:113933886 rs2255141 G A -0.04921 0.007199 47456 8.15e-12 0.7579 10:113933886:A:G
14241 10:113940329 rs2792751 C T -0.04941 0.007208 47456 7.14e-12 0.7629 10:113940329:T:C
14243 10:113944271 rs2419604 G A -0.05399 0.008813 30661 9.02e-10 0.7609 10:113944271:A:G
14244 10:113949664 rs10787429 C T -0.05316 0.008835 30661 1.77e-09 0.7609 10:113949664:T:C
14245 10:113950418 rs7096937 C T -0.05359 0.008829 30661 1.28e-09 0.7619 10:113950418:T:C
18190 11:61552680 rs174537 T G -0.0484723 0.009278 25759 1.75e-07 0.5675 11:61552680:G:T
18191 11:61557803 rs102275 C T -0.0439944 0.008215 33279 8.54e-08 0.5675 11:61557803:T:C
18193 11:61569830 rs174546 T C -0.0457092 0.00821 33279 2.59e-08 0.5665 11:61569830:C:T
18194 11:61570783 rs174547 C T -0.0458525 0.008211 33279 2.35e-08 0.5665 11:61570783:T:C

**Comment by choishingwan** [comment]
Make sure you're path is right.

It said it cannot find the file.  And maybe don't use the double quote

**Comment by youniwerse** [comment]
Hi,

Just moved the base file to the folder where PRSice is located and it works. Seems to be the issue of the path. 

Thank you!
