### ISSUE TITLE
Reduce time 

### ISSUE THREAD

**Issue by SoumenMaity922** [choishingwan/PRSice#345]
Hi, 
Every time I run the PRSice using the PRSice.R and PRSice_linux files, it needs to install the 
necessary libraries. Is that necessary? I am working on an HPC environment.

**Comment by choishingwan** [comment]
Rather give it the same directory with --dir so that we install to the same
place, or install those packages manually.

**Comment by SoumenMaity922** [comment]
ok. Thank you.
