### ISSUE TITLE
Issue with PRSice-v2 output

### ISSUE THREAD

**Issue by JessG1981** [choishingwan/PRSice#356]
Hi,

I have run my data through PRSice-v2 to generate polygenic indices and have an issue with the output for the best-fit model. It looks like this:

PRS.R2: 0.195985
Full.R2: 0.867389
Null.R2: 0.835064

To me this doesn't make sense, as I thought that Full.R2 = PRS.R2 + Null.R2, but in these figures, the PRS.R2 + Null.R2 = 0.195985 + 0.835064 = 1.031049...

Please can anyone help explain what could be wrong with this?

This is the code that I used:

    --a1 A2 \
    --a2 A1 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base GWAS.data \
    --beta  \
    --binary-target F \
    --bp POS \
    --chr CHR \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov combined_covar.covariate \
    --interval 5e-05 \
    --ld g1000_eur \
    --lower 5e-08 \
    --num-auto 22 \
    --out PRS_CO \
    --pheno pheno.txt \
    --pvalue Pval \
    --seed 1286160406 \
    --snp MarkerName \
    --stat Beta \
    --target target.data \
    --thread 1 \
    --upper 0.5

The phenotype is a continuous variable.

Thanks in advance!

Jess

**Comment by JessG1981** [comment]
PS if it makes any difference - the target data sample size  is less than 20 (I know, it is very small)

**Comment by choishingwan** [comment]
The r2 calculation is

1 - (1 - full) / (1 - null)

Sam

**Comment by JessG1981** [comment]
Thank you very much! That makes sense now.
