### ISSUE TITLE
Clumped SNPs

### ISSUE THREAD

**Issue by MonfeugaT** [choishingwan/PRSice#36]
Hello,

Would it be possible to have an option to get the list of clumped SNPs for each SNPs used to construct the best PRS (when using the --print-snp command)?

Thanks a lot,
Thomas

**Comment by choishingwan** [comment]
Yes, that’s possible. Can do it sometime after I finished the current release

**Comment by choishingwan** [comment]
This is now the default behaviour of --print-snp. The best SNPs are now indicated using the Y/N under the In_Regression column
