### ISSUE TITLE
Error happens in small sample size

### ISSUE THREAD

**Issue by YujianLiang** [choishingwan/PRSice#37]
Hi,

When I try to utilize PRSice in our data which only contain 105 samples, errors happened as below:
     ERROR: GLM model did not converge!
       Please send me the DEBUG files

So the question is that whether PRSice is usable for small sample size analysis?

Thanks!

Eugene

**Comment by choishingwan** [comment]
Hi, have you QCed your data? Also, have you looked at the DEBUG file generated? If it is not full of nan or inf, it suggest that there’s perfect separation in your  data which leads to the GLM model not converging. If however you see nan and inf in the DEBUG file, then it might be some other problem, e.g samples that are not QCed or bug. It’d be helpful if you can send me the log file and the debug file for me to know what’s the exact problem

To answer your question, PRSice should work on small sample size

**Comment by YujianLiang** [comment]
Hi, Shing Wan Choi,

Thanks for answering my question.
The attachment is the DEBUG file and the log file. 

The fact is, I got two different dataset from different research. Both of them had passed the sample QC filtering procedure, and one returned error information while the other one got a non-error result. So I thought it might be the sample size problem, since one sample size is 100 and the other one is 1000.

Hoping you can help me to solve this problem. Thank you!



Best,
Eugene

**Comment by choishingwan** [comment]
Hi, sorry, it seems like github is having some trouble and I can’t see the attachment, can you send it out again?

The thing is, with a smaller sample size, it is more likely for one to encounter this perfect separation problem

**Comment by choishingwan** [comment]
This is due to perfect separation of samples which is common for small sample size.
