### ISSUE TITLE
PRS for controls/unknown phenotypes

### ISSUE THREAD

**Issue by brielin** [choishingwan/PRSice#38]
I have been trying to use this software to compute PRS for a group of individuals where it is unknown whether they have the phenotype. However when everyone in the .fam file of the target is a control I get an error:

There are no cases

And the program terminates. Is there a way to use this tool to give PRS for unknown phenotype/control individuals at a few p-value cutoffs, rather than an exhaustive search to the best model fit?

**Comment by choishingwan** [comment]
Yes, what you need is the no-regress option
