### ISSUE TITLE
No variants remain after clumping

### ISSUE THREAD

**Issue by brielin** [choishingwan/PRSice#39]
When running PRSice using a reference LD panel, I get the following output with the default clumping parameters:

Loading Genotype file: 
reference
(bed) 
 
503 people (0 male(s), 0 female(s)) observed 
503 founder(s) included 
 
38 ambiguous variant(s) excluded 
552458 variant(s) excluded based on MAF threshold 
6566803 variant(s) included 
 
Start performing clumping 
Clumping Progress: 100.00%
Number of variant(s) after clumping : 0 
 
No SNPs left for PRSice processing 

And the program terminates. Increasing the r2 cutoff even to 1.0 doesn't help and I get the same error.

**Comment by choishingwan** [comment]
Which version are you using?? (MAC,Linux, windows?) did re downloading PRSice works? (We have received a big report similar to yours and it was fixed)

**Comment by brielin** [comment]
I pulled the latest version from github (2.1.0.beta) from here yesterday, built from source and running on ubuntu 14.04 in a docker container. I can try grabbing the binary instead, will get back to you.

**Comment by choishingwan** [comment]
Did you check out the beta_testing branch?

**Comment by brielin** [comment]
I dont think so, I pulled the tagged release (https://github.com/choishingwan/PRSice/archive/2.1.0.beta.zip)

**Comment by choishingwan** [comment]
Ar, that explains it, that was linked to the pre bug fix version (still
learning how to change that)

So if you checkout the beta_testing branch of the github, you will get the
latest code

Meanwhile I will try to figure out if I can change the linked source code

**Comment by choishingwan** [comment]
Alright, I have now fixed the tag. This should solve the problem

**Comment by brielin** [comment]
Working now, thank you for the prompt fix!
