### ISSUE TITLE
Warning: No significant --clump results. 

### ISSUE THREAD

**Issue by Kathryn123456** [choishingwan/PRSice#41]
Hi, 

I am getting the warning below (and soon after the execution is halted):

Warning: No significant --clump results.  Skipping.
tail: cannot open `cleaned_base.clumped' for reading: No such file or directory
 ################################# 
 # 
 #   Deal with strand flips if target is in genotype format and produce input files for polygenic scoring 
 # 
 ################################# 
Error in read.table("Complete_Allele_List.txt", head = F) : 
  no lines available in input
Execution halted

Any idea what "No significant --clump results" means?

Thanks!

**Comment by Kathryn123456** [comment]
Resolved: cannot have spaces in pathway names

**Comment by choishingwan** [comment]
Hi there, it seems like you are using the old version of PRSice (v1.25). We have now released PRSice 2 and you can find the documentation [here](http://prsice.readthedocs.io/en/latest/). 

As for the no significant clump result. Did you use **--clump-p1** ? If so, it is likely that none of your SNPs have a p-value less than the --clump-p1 threshold

**Comment by Kathryn123456** [comment]
I only used --clump-p1 if that is a default option, I did not specify that. What is the the default --clump-p1 threshold?

**Comment by choishingwan** [comment]
Should have p value of 1 by default, which is strange for your case

Can you try PRSice2?

**Comment by Kathryn123456** [comment]
Yes, I can try PRSice 2. Does the same code and input files work for both versions?

**Comment by choishingwan** [comment]
The same input files work for PRSice 2 but the code can be slightly different. If you should be the code that you are currently using, I can tell you what code you should use for PRSice 2. Otherwise, you can always read the documentation

**Comment by Kathryn123456** [comment]
Thank you!

I tried to convert my code using the documentation, could you help me confirm it is accurate?

**Old code:**
R --file=/project/EngelmanGroup/software/PRSice/PRSice_v1.25.R -q --args \
		plink /software/plink/plink \
		base /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/AnalysisFilesAndCodes/EU_base.txt \
		target /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/ARIC_EU_Aim1_Round1_N1000 \
		slower 0 \
		supper 0.5 \
		barchart.levels 0.05, \
		best.thresh.on.bar T \
		clump.r2 0.5 \
		report.individual.scores T \
		pheno.file /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/EU_baseset_phenotypes.txt \
		user.covariate.file /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/EU_baseset_covariates.txt \
		binary.target F \
		allow.no.sex T \
		wd /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/FinalResults \
		figname PRSice_v1_EU \
		quantiles T \
		quant.ref 1 \
		num.quantiles 10

**New code:**
Rscript PRSice.R --dir /project/EngelmanGroup/software/PRSice/Version2 \
    --prsice ./PRSice \
    --base /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/AnalysisFilesAndCodes/EU_base.txt \
    --target /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/ARIC_EU_Aim1_Round1_N1000 \
    --thread 1 \
    --stat BETA \
    --binary-target F \
    --pheno-file /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/EU_baseset_phenotypes.txt \
    --clump-r2 0.5 \
    --bar-levels 0.5, \
    --out PRSice_v1_EU \
    --quatile 10 \
    --cov-file /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/EU_baseset_covariates.txt \
    --binary-tarfet F \
    --lower 0 

_DID NOT FIND UPDATED COMMAND LINE OPTIONS FOR:_
		plink /software/plink/plink \
		best.thresh.on.bar T \
		report.individual.scores T \
		allow.no.sex T \
		wd /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/FinalResults \

**Comment by choishingwan** [comment]
ya, those command line options are no longer required. So your new script looks good. The only thing that you should know is that PRSice 2 no longer automatically calculate the PCA for you. So if you want to adjust for population stratification, you might need to calculate the PCA manually and supply those to PRSice using the **--cov-file** option. Also, if your phenotype file only contain the IID (as PRSice 1.25 required), you will also need the **--ignore-fid** flag

**Comment by Kathryn123456** [comment]
Thank you! Do you know what could be causing "--prsice: Command not found"? Maybe an issue with my PRSice 2 download? I downloaded the linux version, do I have to install it somehow?

**Comment by choishingwan** [comment]
You can try typing the full command in one line. This is usually the problem

**Comment by Kathryn123456** [comment]
What location should follow Rscript, --dir and --prsice? How do I ensure the prsice is executable?

**Comment by Kathryn123456** [comment]
I had a / instead of \ at the end of the line, hoping it is fixed now.

**Comment by Kathryn123456** [comment]
fixed by using "PRSice_linux" instead of "PRSice" after --prsice option

**Comment by Kathryn123456** [comment]
I think it worked!!! Thank you, thank you for all of your help :) Is PRSice2 supposed to be way faster than the prior version?

**Comment by choishingwan** [comment]
Yes, it should also be more efficient in disk space and have more
functionality
