### ISSUE TITLE
Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column

### ISSUE THREAD

**Issue by Kathryn123456** [choishingwan/PRSice#42]
I get this error at the Regression Model stage in running PRSice. What could be the cause of this error? Which files are being merged? Does it mean that I need a variable by the same name in each file?

Thanks in advance for any help!

**Comment by choishingwan** [comment]
Which version are you using? It seems like you are using PRSice V1.25

Can you try using PRSice2 and see if you get the same error?

**Comment by Kathryn123456** [comment]
I fixed the error, I had a typo in my covariate IID label. I am now getting ""Error in `[.data.frame`(prof, , c("V2", "SCORE", covariates)) : 
  undefined columns selected
Calls: glm ... model.frame.default -> is.data.frame -> [ -> [.data.frame" 

Again, this seems like a covariate file related error? My variables have headings/names, do I need to specify those somewhere in my code? Or are there any other common errors this error associates with?

Thanks for working with me to fix this!

**Comment by choishingwan** [comment]
Maybe you should try with PRSice 2 (as in the discussion in the other issue). This kind of issues are difficult to identify with the old PRSice so we have implemented a better log for PRSice 2 and hopefully it will be clearer as to what the problem is

**Comment by Kathryn123456** [comment]
It seems to have run fine with PRSice2!

**Comment by choishingwan** [comment]
Great!
