### ISSUE TITLE
Automatically use position information

### ISSUE THREAD

**Issue by choishingwan** [choishingwan/PRSice#45]
Maybe add a flag to allow PRSice using the CHR:Coordinate mapping instead of using the rs id?

**Comment by JoniColeman** [comment]
Potential trip up - same position SNPs and indels, i.e. need allele information that differentiates these.

On 1 Feb 2018 10:47 pm, Shing Wan Choi <notifications@github.com> wrote:

Maybe add a flag to allow PRSice using the CHR:Coordinate mapping instead of using the rs id?

**Comment by choishingwan** [comment]
Yes, that's true. Though an added complication with adding the allele information as the SNP name i.e. CHR:Coordinate:A1:A2 or CHR:Coordinate:A1 is that when flipping required, we won't be able to map the target and base, simply because they will have a different ID. Will need to figure out something to avoid this problem...

**Comment by yun-fh** [comment]
My VCF files are from WGS so only a subset of SNPs have rs ids. When I transformed vcfs to bed, the SNP id field in bim file has many "." and leads to error "Duplicated SNP ID detected!...". Any suggestions to handle this? Thanks.

**Comment by choishingwan** [comment]
You can try and recode those rs id of . to something that matches up your base file. I.e. if your base file contain chr:bp encoding, then you can manually generate the chr:bp encoding for your bim file. Or you can also recode both your bim and base file with chr:bp encoding, then examine the mismatch file generated by PRSice to further refine the encoding. Unfortunately, there isn't any automated solution to this problem .
