### ISSUE TITLE
clumping-r2 algorithm

### ISSUE THREAD

**Issue by Kathryn123456** [choishingwan/PRSice#46]
Hi, 

I have a general question about how the clumping algorithm works, with background on why below:

The reason I am curious is because of differences I got in results with the same input files. The two models I ran were:

1. Target files, base file coded as reference and minor allele, where either allele could be the risk allele

2. Same target files and same base file, but this time coded as reference and minor allele, where the reference allele was always the risk allele

Mathematically, I think these two base file types should give the same results, however they didn't. In contemplating how they gave different results, I noticed that the number of common SNPs (in base and target files) post-clumping differed in each instance---I presume this is what drove the differences in results (i.e. a different p-value was selected as best (i.e. highest R2)).

So my question, more specifically is what could cause differences in clumping between these two different runs? Or is there something else that could be causing these differences? If you would like any more specifics about my datasets or command-line options, I can send that along.

Thanks!
Kathryn 

*******************************************UPDATE******************************************************

After further investigation, it seems like the differences stem from different number of mismatched variants being excluded (when finding overlap between base and target file). What kinds of SNPs are excluded at this point and why might this differ in these two different coding schemes?

Thanks!

**Comment by choishingwan** [comment]
Hi there,

The main reason for your problem is that we need a correct mapping for the risk allele for any PRS analysis software to work. With your first input, there is no way for PRSice to identify the risk allele and we will run into trouble when trying to assign a effect 

In PRSice, we do the following matching:

1. The SNP must be on the same chromosome for both base and target
2. They should have the same coordinates (to ensure they are of the same genome build)
3. We then map the SNPs based on their allele (and will "flip" them if required). 

Any SNPs that doesn't match between the base and target will be removed. 

The likely problem with the two coding schemes might be how you provide the column headers. E.g. if you only provide **--A1** flag but not the **--A2** flag, that might lead to difference in the allele presented. If you provided both **--A1** and **--A2** flags, then I will need to examine your data before I can have a certain answer

All in all, you should always ensure the risk allele is of the same column in the base file such that we can correctly assign the effect sizes when calculating the PRS

**Comment by Kathryn123456** [comment]
Hi,

Thanks for the answer. I do however have A1 and A2 flags in my data. More specifically,  the flags I have in my base dataset are A1, A2, BETA and P. I have been trying to think how these flags could cause any difference in exclusions, and haven't come up with anything. 

When you say "you should always ensure the risk allele is of the same column in the base file"...does this mean all risk alleles must be either A1 or A2? 

Thank you!

**Comment by choishingwan** [comment]
In this case, do you mind sending me the two base files and also your bim file? I will take a look and see why the change of the two base files lead to difference in number of variant matched.

Yes, you should ensure the risk allele, or the effective allele of your summary statistic is always of the same column.

**Comment by Kathryn123456** [comment]
Yes, I can send the files. How should I send them to you?

**Comment by choishingwan** [comment]
Hi,maybe send that to my email directly: k1516652@kcl.ac.uk

**Comment by Kathryn123456** [comment]
Thank you, I sent the files. Please let me know if you have any trouble with them.

**Comment by choishingwan** [comment]
Hi there,

I am unable to reproduce your problem (the same amount of mismatch and ambiguous SNP is detected for both base file). 

Do you mind posting the log file for both of your run so that I can see if that is due to some other reasons?

**Comment by Kathryn123456** [comment]
Yes, I will do that now. Thank you so much for helping me! How many mismatch SNPs did it exclude when you ran it?


Thanks!

Kathryn


________________________________

**Comment by choishingwan** [comment]
Sorry, I didn't mark down the total number. But your log file should be very helpful.

You can get it faster by doing

--fastscore --bar-levels 1 --no-clump --print-snp

(--print-snp will generate the list of SNPs that passed the filtering, which allow us to identify the problematic SNPs)

**Comment by choishingwan** [comment]
hm.. strange...

Can you use the **--no-clump** flag and the **--print-snp** flag. This should produce the *.snps file which contain the valid SNPs (SNPs post matching)

We maybe able to identify the difference

As for the best threshold, no, my dummy genotype file doesn't contain a phenotype, so it will terminate after matching the SNPs.

**Comment by Kathryn123456** [comment]
1. 
PRSice 2.1.0.beta (14 Jan 2018) 
https://github.com/choishingwan/PRSice
(C) 2016-2017 Shing Wan (Sam) Choi, Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Jack Euesden Cathryn M. Lewis Paul F. O'Reilly (2015)
PRSice: Polygenic Risk Score software.
Bioinformatics 31 (9): 1466-1468

2018-02-06 18:03:17
/project/EngelmanGroup/software/PRSice/Version2/PRSice_linux \
    --A1 A1 \
    --bar-levels 0.000000,0.050000,0.100000,0.150000,0.200000,0.250000,0.300000,0.350000,0.400000,0.450000,0.500000,1.000000 \
    --base /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/AnalysisFilesAndCodes/EU_base_mixed.txt \
    --beta  \
    --binary-target F \
    --cov-file /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/EU_baseset_covariates.txt \
    --ignore-fid  \
    --info-base INFO,0.9 \
    --interval 0.000050 \
    --lower 0.000000 \
    --model add \
    --no-clump  \
    --out PRSice_v1_EU \
    --pheno-file /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/EU_baseset_phenotypes.txt \
    --print-snp  \
    --pvalue P \
    --seed 2067923044 \
    --snp SNP \
    --stat BETA \
    --target /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/ARIC_EU_Aim1_Round1_N1000 \
    --thread 1 \
    --upper 0.500000


Loading Genotype file: 
/project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/ARIC_EU_Aim1_Round1_N1000 
(bed) 
 

1000 people (0 male(s), 0 female(s)) observed 
1000 founder(s) included 
 

1257916 ambiguous variant(s) excluded 
7057845 variant(s) included 
 

1 region included 

Start processing EU_base_mixed 
============================== 
 

Base file: 
/project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/AnalysisFilesAndCodes/EU_base_mixed.txt 
1251241 variant(s) observed in base file, with: 
224569 variant(s) not found in target file 
481980 mismatched variant(s) excluded 
544692 total variant(s) included from base file 
 
 

Check Phenotype file: 
/project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/EU_baseset_phenotypes.txt 
Column Name of Sample ID: 0_580525_0_580525 
Note: If the phenotype file does not contain a header, the 
column name will be displayed as the Sample ID which is ok. 
Phenotype Name: 3.749896897 
There are a total of 1 phenotype to process 
 

1000 sample(s) with valid phenotype 
 

4 valid covariates included 
 

Processing the covariate file: 
/project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/EU_baseset_covariates.txt 
============================== 
 

After reading the covariate file, 1000 sample(s) included 
in the analysis 
 

There are  and 1 region(s) with p-value less than 1e-5. 
Please note that these results are inflated due to the 
overfitting inherent in finding the best-fit PRS (but it's 
still best to find the best-fit PRS!). 
You can use the --perm option (see manual) to calculate an 
empirical P-value. 

2. 
PRSice 2.1.0.beta (14 Jan 2018) 
https://github.com/choishingwan/PRSice
(C) 2016-2017 Shing Wan (Sam) Choi, Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Jack Euesden Cathryn M. Lewis Paul F. O'Reilly (2015)
PRSice: Polygenic Risk Score software.
Bioinformatics 31 (9): 1466-1468

2018-02-06 18:06:57
/project/EngelmanGroup/software/PRSice/Version2/PRSice_linux \
    --A1 A1 \
    --bar-levels 0.000000,0.050000,0.100000,0.150000,0.200000,0.250000,0.300000,0.350000,0.400000,0.450000,0.500000,1.000000 \
    --base /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/AnalysisFilesAndCodes/EU_base_risk.txt \
    --beta  \
    --binary-target F \
    --cov-file /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/EU_baseset_covariates.txt \
    --ignore-fid  \
    --info-base INFO,0.9 \
    --interval 0.000050 \
    --lower 0.000000 \
    --model add \
    --no-clump  \
    --out PRSice_v1_EU \
    --pheno-file /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/EU_baseset_phenotypes.txt \
    --print-snp  \
    --pvalue P \
    --seed 3024586424 \
    --snp SNP \
    --stat BETA \
    --target /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/ARIC_EU_Aim1_Round1_N1000 \
    --thread 1 \
    --upper 0.500000


Loading Genotype file: 
/project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/ARIC_EU_Aim1_Round1_N1000 
(bed) 
 

1000 people (0 male(s), 0 female(s)) observed 
1000 founder(s) included 
 

1257916 ambiguous variant(s) excluded 
7057845 variant(s) included 
 

1 region included 

Start processing EU_base_risk 
============================== 
 

Base file: 
/project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/AnalysisFilesAndCodes/EU_base_risk.txt 
1251241 variant(s) observed in base file, with: 
224569 variant(s) not found in target file 
506073 mismatched variant(s) excluded 
520599 total variant(s) included from base file 
 
 

Check Phenotype file: 
/project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/EU_baseset_phenotypes.txt 
Column Name of Sample ID: 0_580525_0_580525 
Note: If the phenotype file does not contain a header, the 
column name will be displayed as the Sample ID which is ok. 
Phenotype Name: 3.749896897 
There are a total of 1 phenotype to process 
 

1000 sample(s) with valid phenotype 
 

4 valid covariates included 
 

Processing the covariate file: 
/project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/EU_baseset_covariates.txt 
============================== 
 

After reading the covariate file, 1000 sample(s) included 
in the analysis 
 

There are  and 1 region(s) with p-value less than 1e-5. 
Please note that these results are inflated due to the 
overfitting inherent in finding the best-fit PRS (but it's 
still best to find the best-fit PRS!). 
You can use the --perm option (see manual) to calculate an 
empirical P-value.

**Comment by Kathryn123456** [comment]
Should I send the SNPs file?

**Comment by choishingwan** [comment]
Sure

**Comment by choishingwan** [comment]
Bingo!

So the reason for the mismatch is because you have missed out the --A2 flag. 

When the --A2 isn't provided to PRSice, we can only have the A1 information. So for, for example, if you have a SNP

Target:

A1 = A, A2 = G

And Base is 

A1=G, A2=A

We can normally match it through flipping the A1 and A2 flag in the base file. However, when the A2 flag is not provided, all PRSice can see will be the following

Target: 
A1=A, A2=G

Base:
A1=G

As we don't know what A2 is, we will not do the automatic flipping, and will therefore exclude this SNP.

This explain the difference between your two data set.

However, one thing I don't understand is why the --A2 flag is being ignored. By default, PRSice will check for a column named A2 within your file (and this automatic search works on the data you sent me). So unless you have typed a wrong --A2 input, or you have used the --no-default option (which you didn't judging from your log), it is possible that there is some special new line character in your file (which got stripped off when I download the file from the web) which causes PRSice unable to recognize the A2 column in your specific file.

Do you mind checking if that is the case?

Thanks

**Comment by Kathryn123456** [comment]
Yes, I can check this. Thank you so much for your help!!! Which file (and where in the file) should I be looking for a new line character? Should I be specifying an --A2 flag?

**Comment by Kathryn123456** [comment]
I checked the base file for a new line character near the A@ column and did not see any. Could you help me to better check for this? Or do you have any other ideas what could be happening?

I then tried new code with the A1 and A2 flags specified (see below) and still got the same SNP discrepancies. 

Thanks!

Rscript /project/EngelmanGroup/software/PRSice/Version2/PRSice.R --dir /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/FinalResults/EU \
    --prsice /project/EngelmanGroup/software/PRSice/Version2/PRSice_linux \
    --base /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/AnalysisFilesAndCodes/EU_base_mixed.txt \
    --target /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/ARIC_EU_Aim1_Round1_N1000 \
    --thread 1 \
    --stat BETA \
    --A1 A1 \
    --A2 A2 \
    --binary-target F \
    --pheno-file /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/EU_baseset_phenotypes.txt \
    --ignore-fid \
    --no-clump T \
    --bar-levels 0.0,0.05,0.1,0.15,0.2,0.25,0.3,0.35,0.4,0.45,0.5 \
    --out PRSice_v1_EU \
    --quantile 5 \
    --bar-col-high maroon4 \
    --scatter-r2 T \
    --print-snp T \
    --cov-file /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/EU/EU_baseset_covariates.txt \
    --lower 0

**Comment by Kathryn123456** [comment]
I even tried running with a downloaded version of the files I sent you and the issue remained.

**Comment by choishingwan** [comment]
Can you show me the log and the *.snp file?

It is strange as when I use your base file, PRSice does automatically detect the --A2 column and didn't have this mismatch problem. This is getting weird... haha

**Comment by Kathryn123456** [comment]
I emailed you the files. Thanks for your continuing help! I agree, getting very weird and confusing.

**Comment by choishingwan** [comment]
Hi, 
I am unable to reproduce your problem using the downloaded file and a dummy genotype file generated using PLINK (see attached)

Maybe try downloading this version (though should be similar to the one you are using, right??)?

https://github.com/choishingwan/PRSice/releases/download/2.1.0.beta/PRSice_linux_20180201.zip



[mixed.log](https://github.com/choishingwan/PRSice/files/1708133/mixed.log)

[PRSice.log](https://github.com/choishingwan/PRSice/files/1708134/PRSice.log)

**Comment by Kathryn123456** [comment]
The problem still remains for me with the new version. How many mismatched SNPs did you get when you used my base and target files and command line options?

**Comment by choishingwan** [comment]
Base file: EU_base_mixed.webarchive 
1251241 variant(s) observed in base file, with: 
15 ambiguous variant(s) excluded 
224569 variant(s) not found in target file 
29 mismatched variant(s) excluded 
1026643 total variant(s) included from base file 
 
 
Hm... I downloaded your base file as a webarchive file and manually removed those pesky html header one drive added to them. So maybe that's the difference?

There isn't an option to force it to do strand flipping. That should be automatic, which is why I can't really figure out what's the problem as I have already use the same bim and base file as you did. 

What I can do, when I got the time, maybe to output a file explaining why the SNPs doesn't match between the base and target file? But that will have to wait until I have finished what I have at the moment.

**Comment by Kathryn123456** [comment]
I got it to work! I added another arbitrary column after my A2 column and the mismatch variants issue is solved. When I exported the base data file from SAS to text it must format it someway that the A2 is ignored. Thank you so much for your help, I really appreciate it!!! Best, Kathryn

**Comment by choishingwan** [comment]
Great! Then this issues must be due to special characters. They tends to be elusive but are painful as they can change the String. For example, A can become A^M where ^M is invisible, leading to the problem. 

Good to know it work out fine for you

**Comment by Kathryn123456** [comment]
Thanks again!!
