### ISSUE TITLE
Issues when calculating a PRS for a specific p-value (i.e. how to turn of full model PRS calculation and graphing errors) 

### ISSUE THREAD

**Issue by Kathryn123456** [choishingwan/PRSice#47]
Hi,

I am looking to calculate a PRS for a specific p-value cutoff: 0.00035. I am doing this for several cohorts. I am having two issues in doing this:

1. In one cohort, the full-model PRS (for p-value=1.0) outperforms the PRS at p-value 0.00035. I would like to turn off a PRS calculation for the full model so that participants can get the PRS corresponding to SNPs with p-value <= 0.00035 instead of 1 (i.e. to have this be the PRS in the best file. 

I tried adding 
" --full F \ " AND " --lower 0.00035 and --upper 0.00035" AND "--fastscore and --bar-levels 0.00035" to my code with no success. Is there something else I should be doing?

2. Second, two cohorts are having issues with the graphic outputs.

Error #1: Plotting the quantile plot
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
Calls: run_plot ... model.matrix -> model.matrix.default -> contrasts<-
Execution halted

---could be because all participants in this cohort are female? (although I did get graphs for another all female cohort) 

Error #2: Error in glm.fit(x = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  : 
  NA/NaN/Inf in 'y'
Calls: run_plot ... quantile_plot -> rstandard -> glm -> eval -> eval -> glm.fit
In addition: Warning messages:
1: In Ops.factor(y, mu) : ‘-’ not meaningful for factors
2: In Ops.factor(eta, offset) : ‘-’ not meaningful for factors
3: In Ops.factor(y, mu) : ‘-’ not meaningful for factors
Execution halted

----could be because sparse genotyping in this cohort?

Any input would be greatly appreciated! Thank you!!!

**Comment by choishingwan** [comment]
You can turn that off using `--no-full`

Again, do you have the full log?

I'm actually surprise PRSice let you run with `--full`, which is now depreciated

Will need to see the log to know why error 1 and 2 occurs as if it is what I though, the core algorithm of PRSice should also have failed to begin with.

**Comment by Kathryn123456** [comment]
Although I didn't get figure outputs from these cohorts, I still got PRSs, is it fair to assume the PRS algorithm worked correctly?

**Comment by choishingwan** [comment]
opps... I was too busy with other stuff and forgot about this thread.

Yes, your errors are only from the plotting, not the PRS. So your PRS algorithm definitely work. However, given the error you receive, I won't be able to tell what caused the error (one of the disadvantage of R) without you data. To be honest, I'd expect the quantile plot to work. How many quantiles did you specified?

**Comment by Kathryn123456** [comment]
No problem, I was working on other stuff too. I specified 5 quantiles. I have some time tomorrow and can work on troubleshooting a bit. I will report back if I come up with anything. Thank you!!

**Comment by Kathryn123456** [comment]
I resolved the errors: 
Error 1: There were two subjects missing a covariate causing this error. 
Error 2: There was one subject missing a phenotype causing this to fail.

**Comment by choishingwan** [comment]
Thanks. Strange that it happen as I'd have a flag in the file which the Rscript should use to filter out samples without phenotype and covariates.

**Comment by ysx0226** [comment]
PRSice was used to calculate the PRS in ADNI dataset, but the results are quite abnormal ,see belows:

When I use the ADNI data in PRSice dir,the results R2 were quite large (eg:0.749622);

When I use the example data in PRSice dir,the results R2 were quite small (eg:0.0133696);

PRSice.prsice on ADNI

Set Threshold   R2  P   Coefficient Standard.Error  Num_SNP

Base    0.0001  0.749622    8.43404e-23 56.3465 5.7326  33

Base    0.00015 0.829959    4.56913e-21 80.9499 8.59464 54
PRSice.prsice on example

Set Threshold   R2  P   Coefficient Standard.Error  Num_SNP

Base    0.00025 0.0133696   8.43169e-06 -0.197266   0.0442903   2

Base    0.0003  0.00824473  0.000456434 -0.225204   0.0642503   3

**Comment by choishingwan** [comment]
Hi, as this is a new issue, it is best if you can open  a new issue, otherwise I will likely miss it. 

As you are using two different dataset, it is more than likely for you to obtain a different result. Considering that you are getting result as hig as 0.74, I'd suspect that your ADNI data (whatever it is), is also used as your target genotype, which lead to an inflated R2 estimation
