### ISSUE TITLE
Error in reg$coefficients[1:num_quant, 1] : subscript out of bounds

### ISSUE THREAD

**Issue by Kathryn123456** [choishingwan/PRSice#48]
Hi,

I am getting the error below, any suggestions? My code runs error free when I remove the print quantile plot option.

Plotting the quantile plot
Error in reg$coefficients[1:num_quant, 1] : subscript out of bounds
Calls: run_plot -> quantile_plot
Execution halted

Thanks!
Kathryn

**Comment by choishingwan** [comment]
Thanks for letting me know. My guess is that there isn't enough quantile for the analysis. I will have a look into the script and let you know of any updates

**Comment by Kathryn123456** [comment]
Thanks! Could it be that my sample is small ~60, and I am trying to break into 5 quantiles?

**Comment by choishingwan** [comment]
Did you use covariates? I just noted that the number of quantile check in place occurs before the regress out the covariate analysis. Thus that might have lead to the problem. I have now updated the Rscript to also capture this problem. But with only 60 samples, the quantile plot won't be too informative

(I will update the official release once I finish the current fixes and features. For now, you can use the attached Rscript to replace yours and see if it will capture the error)

[PRSice.update.zip](https://github.com/choishingwan/PRSice/files/1800464/PRSice.update.zip)

**Comment by Kathryn123456** [comment]
Yes, I had covariates. I will try the attached script, thank you.

**Comment by Kathryn123456** [comment]
Unfortunately, I do not think that fixed the issue, I get the same error. Thanks!

"Plotting the quantile plot
Error in reg$coefficients[1:num_quant, 1] : subscript out of bounds
Calls: run_plot -> quantile_plot
Execution halted"

**Comment by choishingwan** [comment]
If you don't mind, could you please run the following script (can add in --plot to skip the PRS calculation) and send me the "DEBUG" file? 

[RScript.zip](https://github.com/choishingwan/PRSice/files/1803396/RScript.zip)

**Comment by Kathryn123456** [comment]
I get this output:  


Plotting the quantile plot
            Estimate Std. Error    t value  Pr(>|t|)
(Intercept)        1   1.414214  0.7071068 0.6081734
quantile1         -1   1.732051 -0.5773503 0.6666667
quantile2         -2   2.000000 -1.0000000 0.5000000
[1] 5
Error in reg$coefficients[1:num_quant, 1] : subscript out of bounds
Calls: run_plot -> quantile_plot
Execution halted

**Comment by choishingwan** [comment]
I see, what happened is that you've only got 3 quantiles. Though PRSice should be able to capture that.... Let me see where this problem occurs.

Thanks for letting me know. I will update you once I found the problem

**Comment by choishingwan** [comment]
Try and see if this solve the problem (as in PRSice refuse to run quantile plot)

If not, can you send me the DEBUG file, which should contain the phenotype value and quantile and nothing else. This allow me to examine the regression model and the output to truly identify the problem

Sorry for the troubles

**Comment by Kathryn123456** [comment]
I still get the same error. I also do not get an outputted DEBUG file... should I be getting one?

**Comment by choishingwan** [comment]
Yes, it should be called DEBUG

If not, it is strange because the DEBUG file output should come before the regression...

**Comment by Kathryn123456** [comment]
I see it now, was in the wrong folder. I will email you.

**Comment by choishingwan** [comment]
Thanks

**Comment by choishingwan** [comment]
Got it. I see where the problem was. It seems like after performing the regress out the covariates, your phenotypes are all NA (with the exception of 4 individual). Could you please check if your covariate file is correct (e.g. there is no missingness in the covariate file). 

In this situation, it might also be beneficial to look at the PRSice log file, which should give a better picture of the analysis. In the log, there will be a section which let us know the situation of your covariates. It will tell us if some of the covariates are missing in most samples e.t.c.

**Comment by Kathryn123456** [comment]
That is very weird, all subjects have phenotypes and all subjects have 3 covariates (there are 5 missing the 4th covariate, but I have denoted these as "." in the datafile). Should I remove the 5 with missing BMI and retry? The log gave no indication of this: 

62 sample(s) with valid phenotype 
 

4 valid covariates included 
 

Processing the covariate file: 
/project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/AFA/ARIC_AFA_N62_covar.txt 
============================== 
 

After reading the covariate file, 62 sample(s) included in 
the analysis

**Comment by Kathryn123456** [comment]
PRSice 2.1.0.beta (14 Jan 2018) 
https://github.com/choishingwan/PRSice
(C) 2016-2017 Shing Wan (Sam) Choi, Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Jack Euesden Cathryn M. Lewis Paul F. O'Reilly (2015)
PRSice: Polygenic Risk Score software.
Bioinformatics 31 (9): 1466-1468

2018-03-12 10:53:42
/project/EngelmanGroup/software/PRSice/Version2/PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --bar-levels 0.000000,0.050000,0.100000,0.150000,0.200000,0.250000,0.300000,0.350000,0.400000,0.450000,0.500000,1.000000 \
    --base /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/AnalysisFilesAndCodes/AFA_base_mixed.txt \
    --beta  \
    --binary-target F \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.500000 \
    --cov-file /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/AFA/ARIC_AFA_N62_covar.txt \
    --ignore-fid  \
    --info-base INFO,0.9 \
    --interval 0.000050 \
    --ld /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/RawGeneticData/QC-ed/R2andMAFapplied/FilesForMergingBackGenotypeData/ARIC_AFA/FINALS/ARIC_AFA_MERGED_QC_FINAL \
    --lower 0.000000 \
    --model add \
    --out PRSice_AFA_mixed_LD \
    --pheno-file /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/AFA/ARIC_AFA_N62_pheno.txt \
    --print-snp  \
    --pvalue P \
    --seed 2447676354 \
    --snp SNP \
    --stat BETA \
    --target /project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/AFA/ARIC_AFA_Aim1_round1_N62 \
    --thread 1 \
    --upper 0.500000


Loading Genotype file: 
/project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/AFA/ARIC_AFA_Aim1_round1_N62 
(bed) 
 

62 people (0 male(s), 0 female(s)) observed 
62 founder(s) included 
 

1435113 ambiguous variant(s) excluded 
7900672 variant(s) included 
 

1 region included 

Start processing AFA_base_mixed 
============================== 
 

Base file: 
/project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/AnalysisFilesAndCodes/AFA_base_mixed.txt 
8438945 variant(s) observed in base file, with: 
1328 ambiguous variant(s) excluded 
4914761 variant(s) not found in target file 
3694 mismatched variant(s) excluded 
3520490 total variant(s) included from base file 
 
 

Loading reference panel 
 

Loading Genotype file: 
/project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/RawGeneticData/QC-ed/R2andMAFapplied/FilesForMergingBackGenotypeData/ARIC_AFA/FINALS/ARIC_AFA_MERGED_QC_FINAL 
(bed) 
 

1908 people (0 male(s), 0 female(s)) observed 
1908 founder(s) included 
 

3520490 variant(s) included 
 

Start performing clumping 

387491 MB RAM detected; reserving 193745 MB for clumping 
 

Number of variant(s) after clumping : 850697 
 

Check Phenotype file: 
/project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/AFA/ARIC_AFA_N62_pheno.txt 
Column Name of Sample ID: 0_102557_0_102557 
Note: If the phenotype file does not contain a header, the 
column name will be displayed as the Sample ID which is ok. 
Phenotype Name: 0.998983273 
There are a total of 1 phenotype to process 
 

62 sample(s) with valid phenotype 
 

4 valid covariates included 
 

Processing the covariate file: 
/project/EngelmanGroup/dbGaP-Kathryn/_DISSERTATIONFOLDER_/Aim1/RawData/AFA/ARIC_AFA_N62_covar.txt 
============================== 
 

After reading the covariate file, 62 sample(s) included in 
the analysis 
 

There are 1 region(s) with p-value > 0.1 ([1;31mnot 
significant[0m); Please note that these results are 
inflated due to the overfitting inherent in finding the 
best-fit PRS (but it's still best to find the best-fit 
PRS!). 
You can use the --perm option (see manual) to calculate an 
empirical P-value.

**Comment by choishingwan** [comment]
I see. Judging from that, it might be because of your "." being considered as a valid covariate (treated as factor). Missingness should all be specified as NA (I should add this to the document). You can try and replace those "." with NA and see if the results is ok. If not, you can run the attached script and it will generate the DEBUG file which you can send me. Though please beware that this DEBUG file will contain the raw phenotype and all the covariates of your samples (without the ID). Don't send that to me if that will violate your data management policy. 

[RScript.zip](https://github.com/choishingwan/PRSice/files/1803712/RScript.zip)

**Comment by Kathryn123456** [comment]
that fixed it, thank you!
