### ISSUE TITLE
multiple bgen files

### ISSUE THREAD

**Issue by zimrahe** [choishingwan/PRSice#51]
PRSice allows for bgen files split across chromosomes as bgenfilename#, but my data is in many smaller chunks (e.g. bgenfilename_chr1_00001-40000, bgenfilename_chr2_40001-80000, ... etc). The input doesn't seem to allow boolean. How can I use PRSice for data in this format?

For example, when I try to run:
 Rscript PRSice.R \
--dir . \
--prsice PRSice_linux \
--base basedata.assoc \
--target bgenfilename_chr#*,samplefile.sample \
--thread 1 \
--stat OR \
--binary-target T \
--type bgen \
--keep ids.txt \
--ignore-fid

I get this error message:
ERROR: Cannot open bgen file bgenfilename_chr1*.bgen

Any assistance would be greatly appreciated.

Thank you very much!

**Comment by choishingwan** [comment]
Unfortunately, we have not anticipated this kind of usage of listed input, thus we only currently support substituting the # with 1-22. I guess an alternative will be to allow user to submit a file contain list of files for PRSice to run on. Something call `--target-list`. Maybe I will consider adding this in for the next release if I have enough time.

**Comment by choishingwan** [comment]
Btw, if you can't wait (I am currently in a huge backlog of work), then all you need to do is to somehow initialize the m_genotype_files vector in the Genotype class with your file prefix, then PRSice should transverse your files accordingly

**Comment by zimrahe** [comment]
Hi Shing-Wan, I think I have a workaround for the moment (I only need a small subset of SNPs for this run which should fit into a single file, I will try it that way). However, I would greatly appreciate if you could implement a "--target-list" option in the future, which will allow PRSice to be used on truly large datasets.

Thanks so much.

**Comment by choishingwan** [comment]
Implementation is now completed. In the next release, the function of `--target-list` and `--ld-list` will be live
