### ISSUE TITLE
output.all.score has only one column with PRS 

### ISSUE THREAD

**Issue by andreyshabalin** [choishingwan/PRSice#53]
I am trying to get PRS for multiple p-value thresholds, but I get only one columns of values in the .all.score file.

I'm running the 2.1.2 version. The log and the .all.score files are here:

[log](http://shabal.in/PRSice/Asthmanoambig.log.txt)

[all.score](http://shabal.in/PRSice/Asthmanoambig.all.score.txt)

**Comment by choishingwan** [comment]
Ar, this is a know problem and has been fixed in the latest update, so you mind trying that again with the latest update?

**Comment by andreyshabalin** [comment]
Affirmative. I've downloaded and compiled the most recent version from github, it works correctly.

Thank you for prompt response.
