### ISSUE TITLE
Regional or PRS-LOCO option

### ISSUE THREAD

**Issue by JoniColeman** [choishingwan/PRSice#54]
It would be useful to provide an option to limit the PRS to certain variants, or to exclude certain variants or regions - obviously this could be achieved by producing a target file without the region, but this may be impractical for generating multiple PRS in one run. 

Specifically, what I am thinking of is something akin to PLINK's variant window or chromosomes commands.

No urgency on this at all - just an idea as a potentially useful addition.

**Comment by choishingwan** [comment]
Sure, so, something like, provide a SNP list or a `--chr` parameter for chromosome filtering? Will it be similar to the use of `--extract` , `--exclude` feature?

**Comment by choishingwan** [comment]
Do you think #57 will help to solve this problem? Albeit that wouldn't be as nice as the `--from` `--to` command of plink
