### ISSUE TITLE
chr# not working

### ISSUE THREAD

**Issue by quattro** [choishingwan/PRSice#55]
In the latest release (2.1.2 beta) the 'chr#' formatting for target plink files is broken

**Comment by quattro** [comment]
The entire pipeline runs fine until. It looks like it does perform expansion on '#' for the plink data, but breaks at the end for the fam file?

Processing 100.00%
There are 1 region(s) with p-value between 0.1 and 1e-5 
(may not be significant); Please note that these 
results are inflated due to the overfitting inherent in 
finding the best-fit PRS (but it's still best to find the 
best-fit PRS!). 
You can use the --perm option (see manual) to calculate an 
empirical P-value.

Error in fread(pheno.file, data.table = F, header = F) : 
  File '//data/plink//run3_updated/chr#.clean.fam' does not exist. Include one or more spaces to consider the input a system command.

**Comment by choishingwan** [comment]
I see, that’s the problem of the Rscript, will fix it tlday

**Comment by choishingwan** [comment]
This should be fixed.

You can quickly testing that out by adding the '--plot' to your command (therefore skip right into plotting)
