### ISSUE TITLE
vcf, gen.gz and/or bgen 1.1 dosage support

### ISSUE THREAD

**Issue by BEFH** [choishingwan/PRSice#56]
PRSice isn't working with bgen 1.2 files generated with QCTool2 (the only bgen 1.2 file conversion software). I don't think PRSice is at fault: I believe the bgen files are malformed. However, that doesn't help me create a proper bgen file.

I have standard VCF files with GT, DS and GP fields, which I likely convert easily into gen.gz files, and possibly convert into bgen 1.1 files with plink 2.0. Is there any way support for vcf dosage could be added, or failing that, one of the more common Oxford formats?

**Comment by choishingwan** [comment]
That is strange. We are currently using the bgen library (written by author of QCTool) to process bgen files and in theory that should support both bgen 1.1 and 1.2. If you don't mind could you please send me the error log so that I can know what is happening? 
However, if the bgen file is malformed, there is nothing we can do on PRSice. Though I guess you can convert your VCF file into bgen v1.1, which is also a supported format of PRSice. 

While in theory, we can provide support for the VCF format, we currently don't have the manpower for this feature (in fact, we are currently having a backlog of feature development).

**Comment by BEFH** [comment]
I am almost 100% sure that it's a problem with qctool2 and not with prsice. I can't load the file in any of the other bgen libraries, except for QCTOOL.

Here's what the output looks like:

```
RSice 2.1.1.beta (26 Mar 2018)
https://github.com/choishingwan/PRSice
(C) 2016-2017 Shing Wan (Sam) Choi, Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Jack Euesden Cathryn M. Lewis Paul F. O'Reilly (2015)
PRSice: Polygenic Risk Score software.
Bioinformatics 31 (9): 1466-1468

2018-06-11 12:27:20
/hpc/users/fultob01/local/bin/PRSice \
    --A1 Effect_allele \
    --A2 Non_Effect_allele \
    --bar-levels 0.001000,0.050000,0.100000,0.200000,0.300000,0.400000,0.500000,1.000000 \
    --base /sc/orga/projects/LOAD/Data/IGAP_Summary_Statistics/IGAP_stage_1.txt \
    --beta  \
    --binary-target F \
    --bp Position \
    --chr Chromosome \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --hard-thres 0.900000 \
    --info-base INFO,0.9 \
    --interval 0.000050 \
    --lower 0.000100 \
    --maf 0.05 \
    --model add \
    --out PRSice \
    --pvalue Pvalue \
    --se SE \
    --seed 5540891 \
    --snp MarkerName \
    --stat Beta \
    --target merged_chr#_filtered,test.sample \
    --thread 1 \
    --type bgen \
    --upper 0.500000


Loading Genotype file: merged_chr#_filtered (bgen)
With sample file: test.sample


Detected bgen sample file format
10042 people (4213 male(s), 5829 female(s)) observed
10042 founder(s) included


Error:  processed in merged_chr1_filtered.bgen
Execution halted
```

**Comment by choishingwan** [comment]
Hm.. First off, maybe try a later version of PRSice? Earlier versions tends to have problem with BGEN format.

**Comment by BEFH** [comment]
I compiled it myself from github today. Should I be downloading from somewhere else?

**Comment by choishingwan** [comment]
My bad, I haven't update the master branch ( I should really do that). You
can either compile from
https://github.com/choishingwan/PRSice/tree/feature/competitive or use the
release https://github.com/choishingwan/PRSice/releases/tag/2.1.2.beta

**Comment by BEFH** [comment]
I just downloaded and compiled the tarball. I'll let you know how it works. Thanks for your help.

**Comment by BEFH** [comment]
It appears to now be working. I will see if the results make sense.

```
Loading Genotype file: merged_chr#_filtered (bgen)
With sample file: test.sample


Detected bgen sample file format
10042 people (0 male(s), 0 female(s)) observed
10042 founder(s) included


380K SNPs processed in merged_chr1_filtered.bgen
```

**Comment by choishingwan** [comment]
We didn't actually use the Sex information beyond providing the error messages. As long as your data is ok, then that should be fine. 

Close as it seems to be solved by new version of PRSice
