### ISSUE TITLE
Allow user to switch off library installation

### ISSUE THREAD

**Issue by choishingwan** [choishingwan/PRSice#59]

**Comment by choishingwan** [comment]
Need to write the help message for this feature
Otherwise it is implemented now

**Comment by choishingwan** [comment]
Need to write the help message for this feature
Otherwise it is implemented now

**Comment by choishingwan** [comment]
Need to write the help message for this feature
Otherwise it is implemented now

**Comment by choishingwan** [comment]
Need to write the help message for this feature
Otherwise it is implemented now

**Comment by choishingwan** [comment]
Need to write the help message for this feature
Otherwise it is implemented now

**Comment by choishingwan** [comment]
Need to write the help message for this feature
Otherwise it is implemented now

**Comment by choishingwan** [comment]
Need to write the help message for this feature
Otherwise it is implemented now

**Comment by JoniColeman** [comment]
I think you need to write the help message for this feature
Otherwise it is implemented now

**Comment by choishingwan** [comment]
The git manager go crazy and resubmit this comment multiple times, haha

**Comment by choishingwan** [comment]
Done.
