### ISSUE TITLE
CSV problems

### ISSUE THREAD

**Issue by wiedenhoeft** [choishingwan/PRSice#70]
I have a rather large CSV phenotype file (1076 columns) with FID and IID. I've noticed that PRSice does not seem to be able to handle comma separators:

> Error: Not enough column in Phenotype file. Have you use the --ignore-fid option

(I have not, since I have FID, Also "use" should be "used").

When using whitespace or as separator, missing data values cause problems later-on:

> Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  : 
>   line 1 did not have 1076 elements
> Calls: read.table -> scan
> Execution halted

(it does have 1076 elements, assuming this is about the phenotype file)

This could be mitigated by quoting all fields, so that missing entries would appear as "", but this does not work, and columns are not recognized (using --pheno-col leads to a segfault):

> Phenotype: T1_zravens cannot be found in phenotype file 
> There are a total of 1 phenotype to process 
>  
> Processing the 1 th phenotype
> Segmentation fault (core dumped)
> Error: 
> Execution halted

I have also noticed that "quoted columns", as used for manual notes, are not handled well (PRSice seems to be using the whitespace within quoted text as delimiter), and had to remove those fields.

I think it would be good to precisely specify a CSV dialect which is used as input, and make sure missing data and quoted text are handled correctly and consistently by PRSice and R.

In case this is relevant for the problem, I also get the following message at the beginning:

> Trying to install data.table in /opt/versions/R-packages/lib
> Cannot install data.table, will fall back and use read.table instead
> Note: It will be slower when reading large files

**Comment by wiedenhoeft** [comment]
Thanks. Then what is the phenotype file supposed to be if not CSV?

**Comment by choishingwan** [comment]
Space / Tab delimited file. I will clarify that in our document.

**Comment by wiedenhoeft** [comment]
Ah, okay, I meant CSV in the broadest sense ("C" for "character" instead of "comma" ;-) ).

**Comment by choishingwan** [comment]
I see. I thought you were talking about Comma-separated values, haha. Though using that notion, PRSice expect something similar to TSV, Tab-separated values file.
