### ISSUE TITLE
Segfault when using BED file

### ISSUE THREAD

**Issue by wiedenhoeft** [choishingwan/PRSice#72]
I'm using version 2.1.3.beta. I got a hg19 BED file from UCSC, however, I get a segfault:

> Reading: 
/home/wiedenhoeft/projects/brainchild/data//hg19.bed 

> Segmentation fault (core dumped)
Error: 
Execution halted

When I omit --bed, this does not happen, and scores are calculated as expected.

**Comment by choishingwan** [comment]
Do you mind showing me your whole log file and also head your bed file for me?

Thanks

**Comment by wiedenhoeft** [comment]
head data/hg19-3col.bed 
chr1    11873   14409
chr1    11873   14409
chr1    11873   14409
chr1    14361   16765
chr1    16857   17751
chr1    15795   18061
chr1    14361   19759
chr1    14361   19759
chr1    14361   19759
chr1    16857   19759


PRSice 2.1.3.beta (20 July 2018) 
https://github.com/choishingwan/PRSice
(C) 2016-2017 Shing Wan (Sam) Choi, Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Jack Euesden Cathryn M. Lewis Paul F. O'Reilly (2015)
PRSice: Polygenic Risk Score software.
Bioinformatics 31 (9): 1466-1468

2018-08-16 05:45:04
/opt/versions/PRSice/2.1.3.beta//PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --all-score  \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base /home/wiedenhoeft/projects/brainchild/data//discovery//GWAS_CP_all.txt \
    --bed /home/wiedenhoeft/projects/brainchild/data//hg19-3col.bed \
    --beta  \
    --binary-target F,F,F,F \
    --bp dummy1 \
    --chr dummy2 \
    --feature exon,gene,protein_coding,CDS \
    --lower 1e-06 \
    --missing no_mean_imputation \
    --model add \
    --no-clump  \
    --no-default  \
    --out /home/wiedenhoeft/projects/brainchild/data/output/segfault/prsice \
    --pheno-col T1_AWMA_tot,T1_Backdig_tot,T1_Threeback_corr_min_FA,T1_zravens \
    --pheno-file /home/wiedenhoeft/projects/brainchild/data/output/segfault/BRAINCHILD_MASTERFILE_IID.csv \
    --pvalue Pval \
    --se SE \
    --seed 0 \
    --snp MarkerName \
    --stat Beta \
    --target /home/wiedenhoeft/projects/brainchild/data//karolinska//QCfinal \
    --thread 150 \
    --upper 1


Loading Genotype file: 
/home/wiedenhoeft/projects/brainchild/data//karolinska//QCfinal 
(bed) 
 

76 people (35 male(s), 41 female(s)) observed 
76 founder(s) included 
 

111650 ambiguous variant(s) excluded 
611666 variant(s) included 
 

Reading: 
/home/wiedenhoeft/projects/brainchild/data//hg19-3col.bed

**Comment by wiedenhoeft** [comment]
P.S. I tried to use the full BED file [(http://genome.ucsc.edu/cgi-bin/hgTables?hgsid=686362417_RgWmtAKWaDIaBpA9aAUHoD16dvMf&boolshad.hgta_printCustomTrackHeaders=0&hgta_ctName=tb_knownGene&hgta_ctDesc=table+browser+query+on+knownGene&hgta_ctVis=pack&hgta_ctUrl=&fbQual=whole&fbUpBases=200&fbExonBases=0&fbIntronBases=0&fbDownBases=200&hgta_doGetBed=get+BED)](url), but PRSice seems to freeze then.

**Comment by choishingwan** [comment]
If you don't mind, could you check the latest release and see if that solves the problem?

**Comment by wiedenhoeft** [comment]
Istn't 2.1.3 the latest?

**Comment by choishingwan** [comment]
Yes, but I also update the same build (not the best practice I know) whenever some important bug is fixed

**Comment by wiedenhoeft** [comment]
Agreed, that is certainly an issue with reproducibility. Isn't that what the last digit in the version number is for? ;-) But anyway, it doesn't crash anymore, thanks so much for the quick fix!
