### ISSUE TITLE
cannot open 'TOY_BASE_GWAS.assoc' for reading

### ISSUE THREAD

**Issue by csuzfq** [choishingwan/PRSice#79]

**Comment by csuzfq** [comment]
I run the command:
R --file=PRSice_v1.25.R -q --args plink ./plink_1.9_linux_160914 base TOY_BASE_GWAS.assoc target TOY_TARGET_DATA slower 0 sinc 0.02 supper 0.3

I got the message:
head: cannot open 'TOY_BASE_GWAS.assoc' for reading: No such file or directory
Error in read.table("head_disc", header = T) : 
  no lines available in inputhead: cannot open 'TOY_BASE_GWAS.assoc' for reading: No such file or directory
Error in read.table("head_disc", header = T) : 
  no lines available in input

**Comment by choishingwan** [comment]
You have to check if the TOY_BASE_GWAS.assoc is located in your current directory i.e. You can see the TOY_BASE_GWAS.assoc with `ls`

**Comment by csuzfq** [comment]
Thanks, @choishingwan .
I am sure that the TOY_BASE_GWAS.assoc is located in the current directory. I can see it using ls.

**Comment by choishingwan** [comment]
Are you running this command within that folder though? If you type 
`head TOY_BASE_GWAS.assoc` within your current directory before you run PRSice v1.25, what do you get?

**Comment by csuzfq** [comment]
$ head TOY_BASE_GWAS.assoc
SNP CHR BP A1 A2 P OR
SNP_22857 4 103593179 1 2 0.2852 13.29
SNP_13879 2 237416793 1 2 0.8784 21.624
SNP_20771 4 16957461 1 2 0.1994 91.265
SNP_13787 2 235355721 1 2 0.7234 3.178
SNP_25383 4 189927377 1 2 0.3309 3.167
SNP_25290 4 187995996 1 2 0.6327 0.427
SNP_21478 4 40161304 1 2 0.06454 5.066
SNP_12129 2 176643771 1 2 0.9378 1.276
SNP_22809 4 101441465 1 2 0.8111 0.004

**Comment by choishingwan** [comment]
Did you see the error message when you run
```
head TOY_BASE_GWAS.assoc
R --file=PRSice_v1.25.R -q --args plink ./plink_1.9_linux_160914 base TOY_BASE_GWAS.assoc target TOY_TARGET_DATA slower 0 sinc 0.02 supper 0.3
```

**Comment by csuzfq** [comment]
Thank you very much @choishingwan. It works!
I got the reason. The current working directory for R was set to another folder, while I am working in a different folder. After I moved current files into R's  current working directory, it runs OK.
