### ISSUE TITLE
Cannot use "--quantile" 

### ISSUE THREAD

**Issue by udube** [choishingwan/PRSice#82]
When trying to use the option --quantile, I encounter the following error: 

> Error in eval(predvars, data, env) : object 'Pheno' not found
> Calls: process_plot ... eval -> <Anonymous> -> model.frame.default -> eval -> eval
> Execution halted

PRSice-2 has no problems running and producing the bar or high resolution plots without that option.

**Comment by choishingwan** [comment]
Could you please try download 2.1.4 and see if that solves your problem?

**Comment by udube** [comment]
I can confirm that this is no longer an issue in version 2.1.4. 

Thank you.
