### ISSUE TITLE
Incomplete sentence in documentation

### ISSUE THREAD

**Issue by wiedenhoeft** [choishingwan/PRSice#83]
In the manual, the entry for --perm reads "Repeat PRSice analysis *N* times with permuted phenotype. Count the number of time where the p-value of the most significant threshold for the permuted". This sentence is incomplete

**Comment by choishingwan** [comment]
Thanks, we are planning to rewrite our manual to fix some of these issues and include documentation of the new features. We will let you know once we've completed the update

**Comment by choishingwan** [comment]
Just completely updated the documents
