### ISSUE TITLE
invalid phenotypes using 1000 Genome dataset as target data set

### ISSUE THREAD

**Issue by csuzfq** [choishingwan/PRSice#86]

**Comment by csuzfq** [comment]
I use the 1000 Genome as target dataset, the program stops with error message:

Processing the 1 th phenotype
Phenotype is a binary phenotype 
503 sample(s) with invalid phenotype 
Error: All sample has invalid phenotypes! 

Error: No sample left 

The phenotype in 1000G should be set as '-9'. Modifying the phenotype may solve the issue. Is there a convenient way to avoid the error?

**Comment by choishingwan** [comment]
Seems like this issue is closed. Just for your reference, you can do —no-regress

**Comment by hcurley2** [comment]
Hi, I am getting a similar error with phenotypes using a bgen sample file. 
Any ideas what is wrong? I have phenotypes that I want to include.. 

./PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base basfile_riskscore.txt \
    --binary-target T \
    --bp BP \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --hard-thres 0.100000 \
    --interval 5e-05 \
    --lower 5e-08 \
    --missing MEAN_IMPUTE \
    --model add \
    --or  \
    --out TEST \
    --pvalue Pvalue \
    --score avg \
    --seed 1208309582 \
    --snp SNP \
    --stat OR \
    --target EO_LO_AllChrs_RiskSNPs3,EO_LO_AllChrs_RiskSNPs3.sample \
    --thread 1 \
    --type bgen \
    --upper 0.5


Initializing Genotype file: EO_LO_AllChrs_RiskSNPs3 (bgen) 
With external fam file: EO_LO_AllChrs_RiskSNPs3.sample 
 

Start processing basfile_riskscore 
================================================== 

Reading 100.00%
Base file: basfile_riskscore.txt 
103 variant(s) observed in base file, with: 
10 ambiguous variant(s) excluded 
1 variant(s) located on haploid chromosome 
1 NA stat/p-value observed 
92 total variant(s) included from base file 
 
 

Loading Genotype info from target 
================================================== 

1149 people (0 male(s), 0 female(s)) observed 
1149 founder(s) included 

0K SNPs processed in EO_LO_AllChrs_RiskSNPs3.bgen
9 ambiguous variant(s) excluded 
84 variant(s) included 
 

Start processing gene set information 
================================================== 

1 region included 

There are a total of 1 phenotype to process 
 

Start performing clumping 

63437 MB RAM detected; reserving 1 MB for clumping 
Allocated 1 MB successfully 

Clumping Progress: 100.00%

Number of variant(s) after clumping : 77 

Processing the 1 th phenotype
Phenotype is a binary phenotype 
1149 sample(s) with invalid phenotype 
Error: All sample has invalid phenotypes! 

Error: No sample left

------------------------------------
head EO_LO_AllChrs_RiskSNPs3.sample 
FID IID Age sex
3376108 3376108 2 2
5940728 5940728 1 2
5331048 5331048 1 1
3755184 3755184 2 2
5622914 5622914 2 2
4045797 4045797 2 2
5895455 5895455 1 1
1889134 1889134 1 2
5208703 5208703 2 2

**Comment by choishingwan** [comment]
This doens't look like a valid sample file (a sample file should have 3
mandated columns: ID1 ID2 missing, and have 2 rows, with the first row
being the header and the second column being 0 0 0). Basically, with BGEN
format, PRSice doesn't know that it should read the phenotype from the
separate file from --target, therefore, here, in your use case, as --pheno
isn't provided, it will lead to undefined phenotype. I should try and
figure out how best to take into account of the phenotype from the separate
fam file from --target.


Dr Shing Wan Choi
Postdoctoral Fellow
Genetics and Genomic Sciences
Icahn School of Medicine, Mount Sinai, NYC
