### ISSUE TITLE
--quant-break 1,5,10,40,100 option doesn't work.

### ISSUE THREAD

**Issue by chulghim** [choishingwan/PRSice#87]
This command does good work..
Rscript PRSice.R --dir /UUU/chul/test1 --prsice ./PRSice_linux --base TOY_BASE_GWAS.assoc --target /genomeplay/chul/prs/TOY_TARGET_DATA --thread 1  --stat OR --binary-target T --out XX1 --quantile 100  --quant-ref 40

but, this command happens error.
Rscript PRSice.R --dir /UUU/chul/test1 --prsice ./PRSice_linux --base TOY_BASE_GWAS.assoc --target /genomeplay/chul/prs/TOY_TARGET_DATA --thread 1  --stat OR --binary-target T --out XX1 --quantile 100  --quant-ref 40   --quant-break 1,5,10,40,100 

error message : 
Plotting the quantile plot
Error in plot.quant(quantiles.df, num_quant, binary, extract, prefix,  : 
  argument "uneven" is missing, with no default
Calls: process_plot ... uneven_quantile_plot -> call_quantile -> plot.quant
Execution halted

help me!!!

**Comment by choishingwan** [comment]
Hi, which version did you use? Think I have fixed this problem in 2.1.5. Sorry for the trouble

On Tue, 11 Dec 2018 at 02:25 chulghim <notifications@github.com<mailto:notifications@github.com>> wrote:

This command does good work..
Rscript PRSice.R --dir /UUU/chul/test1 --prsice ./PRSice_linux --base TOY_BASE_GWAS.assoc --target /genomeplay/chul/prs/TOY_TARGET_DATA --thread 1 --stat OR --binary-target T --out XX1 --quantile 100 --quant-ref 40

but, this command happens error.
Rscript PRSice.R --dir /UUU/chul/test1 --prsice ./PRSice_linux --base TOY_BASE_GWAS.assoc --target /genomeplay/chul/prs/TOY_TARGET_DATA --thread 1 --stat OR --binary-target T --out XX1 --quantile 100 --quant-ref 40 --quant-break 1,5,10,40,100

error message :
Plotting the quantile plot
Error in plot.quant(quantiles.df, num_quant, binary, extract, prefix, :
argument "uneven" is missing, with no default
Calls: process_plot ... uneven_quantile_plot -> call_quantile -> plot.quant
Execution halted

help me!!!

**Comment by chulghim** [comment]
thanks for your reply. 
I got result txt file about "--quant-break " option.
