### ISSUE TITLE
Error: can not open .bim file

### ISSUE THREAD

**Issue by mehul4frnds** [choishingwan/PRSice#88]
#I used shell script to run the command
#!/bin/sh

Rscript PRSice.R --dir . \
    --prsice ./PRSice_linux \
    --base /home/cnap_lab_gwas/Downloads/try_2.assoc \
    --target /mnt/data/hrc_plinkb/chr#_MDRF_hrcimputedbed,chr1_MDRF_hrcimputedb$
    --type bed \
    --out /home/cnap_lab_gwas/mehul_PRS/HDL_mdrf_1912 \
    --thread 1 \
    --stat BETA \
    --beta \
    --binary-target F

it displayed the following error:

PRSice 2.1.4.beta (19 October 2018) 
https://github.com/choishingwan/PRSice
(C) 2016-2017 Shing Wan (Sam) Choi, Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Jack Euesden Cathryn M. Lewis Paul F. O'Reilly (2015)
PRSice: Polygenic Risk Score software.
Bioinformatics 31 (9): 1466-1468

2018-12-20 15:03:53
./PRSice_linux \
    --A1 A1 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base /home/cnap_lab_gwas/Downloads/try_2.assoc \
    --beta  \
    --binary-target F \
    --bp BP \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --interval 5e-05 \
    --lower 0.0001 \
    --model add \
    --out /home/cnap_lab_gwas/mehul_PRS/HDL_mdrf_1912 \
    --pvalue P \
    --seed 3694859724 \
    --snp SNP \
    --stat BETA \
    --target /mnt/data/hrc_plinkb/chr#_MDRF_hrcimputedbed,chr1_MDRF_hrcimputedbed.fam \
    --thread 1 \
    --type bed \
    --upper 0.5

Loading Genotype file: 
/mnt/data/hrc_plinkb/chr#_MDRF_hrcimputedbed,chr1_MDRF_hrcimputedbed.fam 
(bed) 
With external fam file: chr1_MDRF_hrcimputedbed.fam 
 

2059 people (0 male(s), 0 female(s)) observed 
2059 founder(s) included 
 

**Error: Cannot open bim file: 
       /mnt/data/hrc_plinkb/chr1_MDRF_hrcimputedbed.bim** 

Error: 
Execution halted

Please suggest, how to avoid these problem. 
Thanks in advance

**Comment by choishingwan** [comment]
Could you check if you have a file named:

/mnt/data/hrc_plinkb/chr1_MDRF_hrcimputedbed.bim

**Comment by mehul4frnds** [comment]
Yes, I have all the 22 bim and bed files in the designated folder in the given name. I tried with individual chromosomes as well. But, It gave the same error

**Comment by choishingwan** [comment]
What's the output of 

ls -lh /mnt/data/hrc_plinkb/chr1_MDRF_hrcimputedbed.bim

??

**Comment by choishingwan** [comment]
Interesting... And it seems like github isn't associating my latest release with the actual latest release... Can you try and download the latest version here and see if that works?

https://github.com/choishingwan/PRSice/releases/tag/2.1.5

**Comment by mehul4frnds** [comment]
Same error is showing 
PRSice 2.1.5 (7 November 2018) 
https://github.com/choishingwan/PRSice
(C) 2016-2017 Shing Wan (Sam) Choi, Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Jack Euesden Cathryn M. Lewis Paul F. O'Reilly (2015)
PRSice: Polygenic Risk Score software.
Bioinformatics 31 (9): 1466-1468

2018-12-20 16:41:26
./PRSice_linux \
    --A1 A1 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base /home/cnap_lab_gwas/Downloads/try_2.assoc \
    --beta  \
    --binary-target F \
    --bp BP \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --interval 5e-05 \
    --lower 0.0001 \
    --model add \
    --out /home/cnap_lab_gwas/mehul_PRS/HDL_mdrf_1912 \
    --pvalue P \
    --seed 23706795 \
    --snp SNP \
    --stat BETA \
    --target mnt/data/hrc-plinkb/chr#_MDRF_hrcimputedbed,chr1_MDRF_hrcimputedbed.fam \
    --thread 1 \
    --type bed \
    --upper 0.5


Loading Genotype file: 
mnt/data/hrc-plinkb/chr#_MDRF_hrcimputedbed,chr1_MDRF_hrcimputedbed.fam 
(bed) 
With external fam file: chr1_MDRF_hrcimputedbed.fam 
 

2059 people (0 male(s), 0 female(s)) observed 
2059 founder(s) included 
 
Error: Cannot open bim file: 
       mnt/data/hrc-plinkb/chr1_MDRF_hrcimputedbed.bim 

Error: 
Execution halted

**Comment by mehul4frnds** [comment]
I tried with another method too such as, to keep all the binary files in the same folder, but it shows another error:

PRSice 2.1.5 (7 November 2018) 
https://github.com/choishingwan/PRSice
(C) 2016-2017 Shing Wan (Sam) Choi, Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Jack Euesden Cathryn M. Lewis Paul F. O'Reilly (2015)
PRSice: Polygenic Risk Score software.
Bioinformatics 31 (9): 1466-1468

2018-12-20 16:48:46
./PRSice_linux \
    --A1 A1 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base /home/cnap_lab_gwas/Downloads/try_2.assoc \
    --beta  \
    --binary-target F \
    --bp BP \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --interval 5e-05 \
    --lower 0.0001 \
    --model add \
    --out /home/cnap_lab_gwas/mehul_PRS/HDL_mdrf_1912 \
    --pvalue P \
    --seed 154528568 \
    --snp SNP \
    --stat BETA \
    --target chr#_MDRF_hrcimputedbed,chr1_MDRF_hrcimputedbed.fam \
    --thread 1 \
    --type bed \
    --upper 0.5


Loading Genotype file: 
chr#_MDRF_hrcimputedbed,chr1_MDRF_hrcimputedbed.fam (bed) 
With external fam file: chr1_MDRF_hrcimputedbed.fam 
 

2059 people (0 male(s), 0 female(s)) observed 
2059 founder(s) included 
 

**Error: Currently do not support sample major format** 

Error: 
Execution halted

**Comment by choishingwan** [comment]
Can you add the / in front of mnt and try again?

**Comment by mehul4frnds** [comment]
> Can you add the / in front of mnt and try again?
Yes, it says same error:
Error: Cannot open bim file: 
       /mnt/data/hrc-plinkb/chr1_MDRF_hrcimputedbed.bim 

Is there any problem with my files?

**Comment by choishingwan** [comment]
ok, I missed on of the log you send me which detail the problems:

1. All binary file must be put in the same file. That's why when you did that in the latest run, we see the second error message: **Error: Currently do not support sample major format**, which leads us to 
2. It seems like your binary files are currently of the sample major format instead of the SNP major format we required. You will need to convert them to the latest plink binary format in order for PRSice to work. The reason why we don't support the sample major format is because all operations were performed on the SNP major fashion. As such, given a sample major format, we will first need to convert it to SNP major format which users can do that with PLINK easily.

Hope this is helpful

**Comment by mehul4frnds** [comment]
Thanks. I have .bim .fam and .bed files . 
It would be helpful, if you can suggest command for the converting file into SNP major format. I could not find it anywhere online. 
Are you referring to .pgen format ?
I look forward to your reply

Thanks again

**Comment by mehul4frnds** [comment]
Thanks,  I have converted the files into  SNP major format from plink1 with --make-bed command.
