### ISSUE TITLE
Getting error running the tutorial 

### ISSUE THREAD

**Issue by ffaghri1** [choishingwan/PRSice#89]
Hello,

I'm getting the same error running PRSice on my data or on the tutorial data. Running:
`Rscript PRSice.R --dir .  --prsice ./PRSice --base TOY_BASE_GWAS.assoc  --target TOY_TARGET_DATA  --thread 1 --stat OR --binary-target T`

output:

> Clumping
> Progress: 100.00%
> 
> Number of variant(s) after clumping : 88836
> 
> 
> 
> Processing the 1 th phenotype
> Error:
> Execution halted

I'm running PRSice on Mac and "xcode-select" is installed. What is the issue?

**Comment by choishingwan** [comment]
Can you send me the full log? Also, what sample size are you working with?

Thanks
On Wed, 26 Dec 2018 at 3:50 AM, Faraz Faghri <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,

I'm getting the same error running PRSice on my data or on the tutorial data. Running:
Rscript PRSice.R --dir . --prsice ./PRSice --base TOY_BASE_GWAS.assoc --target TOY_TARGET_DATA --thread 1 --stat OR --binary-target T

output:

Clumping
Progress: 100.00%

Number of variant(s) after clumping : 88836

Processing the 1 th phenotype
Error:
Execution halted

I'm running PRSice on Mac and "xcode-select" is installed. What is the issue?

**Comment by choishingwan** [comment]
What file did it managed to generate? Do you have enough disk space left?

**Comment by ffaghri1** [comment]
No file other the .log is generated. Plenty of disk space.

**Comment by choishingwan** [comment]
hm... that's rather strange. It seems like PRSice crash when it try to creat the .best file. Usually this is due to insufficient disk space (which is something that I couldn't catch...). Will this same error occur if you use the 2.1.5 version?

**Comment by choishingwan** [comment]
That is very odd. As mentioned in previous reply, the only logical reason for such error is maybe you've ran out of quota / disk space in your directory. Unfortunately, if that isn't the case, then I'm afraid the only way for me to find out the problem is to actually try and run the program on your computer in person.

**Comment by ffaghri1** [comment]
The issue has been resolved in the 2.1.6 release. Thank you!
