### ISSUE TITLE
GLM algorithm did not converge

### ISSUE THREAD

**Issue by kaibios0101** [choishingwan/PRSice#90]
Hi choishingwan ,
when I run the PRSice, I get a strange problem which I cannot solve it. The problem is follow:

PRSice 2.1.5 (7 November 2018) 
https://github.com/choishingwan/PRSice
(C) 2016-2017 Shing Wan (Sam) Choi, Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly
GNU General Public License v3

If you use PRSice in any published work, please cite:
Jack Euesden Cathryn M. Lewis Paul F. O'Reilly (2015)
PRSice: Polygenic Risk Score software.
Bioinformatics 31 (9): 1466-1468

2019-01-02 17:25:23
/home/kwang/softwares/PRSice/PRSice \
    --A1 A1 \
    --all-score  \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base /home/kwang/project/DFTJ_20181109/result/illu/cad_20181217_p.assoc.logistic \
    --beta  \
    --binary-target T \
    --bp BP \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 0.500000 \
    --clump-r2 0.600000 \
    --cov-col sex,base_age,pc1,pc2,pc3,pc4,pc5,pc6,pc7,pc8,pc9,pc10 \
    --cov-file /home/kwang/data/DTFJ_20181109/geno/FinalIllumina/vcf2bed/illu_covariates.txt \
    --interval 1e-06 \
    --lower 1e-07 \
    --model add \
    --out /home/kwang/project/cad/result/PRSice/PRSice2/temp_illu_2_illu_r6 \
    --pheno-col cad \
    --pheno-file /home/kwang/data/DTFJ_20181109/geno/FinalIllumina/vcf2bed/illu_covariates.txt \
    --pvalue P \
    --score standard \
    --seed 20190101 \
    --snp SNP \
    --stat BETA \
    --target /home/kwang/data/DTFJ_20181109/geno/FinalIllumina/vcf2bed/illu_chrall \
    --thread 112 \
    --upper 0.5

Warning: Duplicated argument --score 
 
Loading Genotype file: 
/home/kwang/data/DTFJ_20181109/geno/FinalIllumina/vcf2bed/illu_chrall 
(bed) 
 
5258 people (2287 male(s), 2945 female(s)) observed 
5258 founder(s) included 

1223760 ambiguous variant(s) excluded 
6592212 variant(s) included 
 

1 region included 

Check Phenotype file: 
/home/kwang/data/DTFJ_20181109/geno/FinalIllumina/vcf2bed/illu_covariates.txt 
Column Name of Sample ID: FID+IID 
Note: If the phenotype file does not contain a header, the 
column name will be displayed as the Sample ID which is ok. 
There are a total of 1 phenotype to process 
 

Start processing cad_20181217_p.assoc 
============================== 
 

Reading 100.00%
Base file: 
/home/kwang/project/DFTJ_20181109/result/illu/cad_20181217_p.assoc.logistic 
7815972 variant(s) observed in base file, with: 
1223760 variant(s) not found in target file 
6592212 total variant(s) included from base file 
 
 

Start performing clumping 

257660 MB RAM detected; reserving 14 MB for clumping 
Allocated 14 MB successfully 
 
Clumping Progress: 100.00%

Number of variant(s) after clumping : 641144 
 

Processing the 1 th phenotype
cad is a binary phenotype 
2971 control(s) 
2287 case(s) 
 

Include Covariates: 
Name	Missing	Number of levels 
sex	26	- 
base_age	26	- 
pc1	0	- 
pc2	0	- 
pc3	0	- 
pc4	0	- 
pc5	0	- 
pc6	0	- 
pc7	0	- 
pc8	0	- 
pc9	0	- 
pc10	0	- 
 

26 sample(s) with invalid covariate: 
 
 

Processing the covariate file: 
/home/kwang/data/DTFJ_20181109/geno/FinalIllumina/vcf2bed/illu_covariates.txt 
============================== 
 

After reading the covariate file, 5232 sample(s) included 
in the analysis 
 

Processing 13.65%Error: GLM model did not converge!
       This is usually caused by small sample
       size or caused by problem in the input file
       If you are certain it is not due to small
       sample size and problematic input, please
       send me the DEBUG files
Error: GLM algorithm did not converge
Processing 13.67%Error: GLM model did not converge!
       This is usually caused by small sample
       size or caused by problem in the input file
       If you are certain it is not due to small
       sample size and problematic input, please
       send me the DEBUG files
Error: GLM algorithm did not converge

Only the last step has a mistake, I check the sample size and input files and do not find any problem under the instruction of the output. In addition, I check the code in the PRSice/src/regression.cpp, and do not get any useful information because of the lack of c language ability. Thus, I wish you could give me some help. Thank you very much!

Best wishes!
kai

**Comment by choishingwan** [comment]
Hi there, this error message means that the logistic regression model cannot converge. This is usually caused by small sample size or caused by problem in the input file.

You should first check the DEBUG file and see if that contains any NaN or Inf. These will likely be caused by input that didn't go through proper quality controlles, which can contain complete missingness. If that isn't the case, then you can load the DEBUG and DEBUG.y file into R and see if you can perform the logistic regression on the data (DEBUG.y is the y, whereas DEBUG contains the independent variables, including the intercept). 

Another possible reason will be that your case control sample are perfectly seperated, i.e. if all your cases are male and controls are female, this error will also occur. Hope this help

**Comment by kaibios0101** [comment]
Hi choishingwan，thank you for your help. I found the problem that the snp predictors can totally separate cases from controls. And I can successfully run the code. Thanks very much.

kai

**Comment by JuRaGa** [comment]
Hello,

I am also getting this error. In my case, I have a very small dataset with 15 cases and 25 controls. I am able to use PRSice to derive a PRS? I did find significant SNVs with a case-control GWAS.
Thank you for your help.

**Comment by choishingwan** [comment]
Unlikely, the sample size is just too small.
