### ISSUE TITLE
Multi-set-plot error

### ISSUE THREAD

**Issue by jbakell** [choishingwan/PRSice#92]
Hi

I keep getting the following error message when I run PRSet:

> Plotting Multi-Set-Plot
Error in paste(prefix, "_MULTISET_BARPLOT_", Sys.Date(), ".", device,  : 
  argument "device" is missing, with no default
Calls: process_plot ... plot_dev -> tolower -> <Anonymous> -> regexpr -> paste
In addition: Warning messages:
1: In fread(paste0(prefix, ".best"), data.table = F) :
  Detected 189 column names but the data has 190 columns (i.e. invalid file). Added 1 extra default column name for the first column which is guessed to be row names or an index. Use setnames() afterwards if this guess is not correct, or fix the file write command that created the file to create a valid file.
2: In max(pheno$Pheno) : no non-missing arguments to max; returning -Inf

I've tried with the tutorial data and MSigDB sets and continiue to get the error. Any ideas?

Thanks

**Comment by choishingwan** [comment]
Which version are you using?

This is a known issue with the Rscript.

Maybe try version 2.1.4 or 2.1.5?  https://github.com/choishingwan/PRSice/releases/tag/2.1.5


Dr Shing Wan Choi
Postdoctoral Research Worker
MRC Centre for Social, Genetic and Developmental Psychiatry
Institute of Psychiatry, Psychology and Neuroscience
King's College London



On Tue, Jan 15, 2019 at 10:41 AM jbakell <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi

I keep getting the following error message when I run PRSet:

Plotting Multi-Set-Plot
Error in paste(prefix, "MULTISET_BARPLOT", Sys.Date(), ".", device, :
argument "device" is missing, with no default
Calls: process_plot ... plot_dev -> tolower -> -> regexpr -> paste
In addition: Warning messages:
1: In fread(paste0(prefix, ".best"), data.table = F) :
Detected 189 column names but the data has 190 columns (i.e. invalid file). Added 1 extra default column name for the first column which is guessed to be row names or an index. Use setnames() afterwards if this guess is not correct, or fix the file write command that created the file to create a valid file.
2: In max(pheno$Pheno) : no non-missing arguments to max; returning -Inf

I've tried with the tutorial data and MSigDB sets and continiue to get the error. Any ideas?

Thanks

**Comment by jbakell** [comment]
I'm using the most recent version of PRSice_mac and have XQuartz installed. :/

**Comment by choishingwan** [comment]
I can confirm this is a problem. Have patched it in 2.1.6. Will now do some quality assessment and should release the patch right after. Thank you

**Comment by jbakell** [comment]
Thanks

**Comment by choishingwan** [comment]
2.1.6 is out now and this problem should be solved
