### ISSUE TITLE
Does PRSice2 work on the new Plink2 format called ".pfile (.pgen,  .pvar, .psam)"

### ISSUE THREAD

**Issue by Fryera** [choishingwan/PRSice#93]
The new Plink2 program is dedicated for use on what they are now calling ".pfile (.pgen,  .pvar, .psam)" formatted data files.
I am wishing to use PRSice2 on the 1000 genomes phase 3 dataset which is on my computer in Plink2 .pfile (.pgen,  .pvar, .psam) formatted files.   Will PRSice2 work on this new type of plink2 file format??

**Comment by choishingwan** [comment]
Unfortunately no. Those formats are currently in alpha state. We might consider supporting it when it is stable and when we have time
On Mon, 28 Jan 2019 at 2:28 AM, Fryera <notifications@github.com<mailto:notifications@github.com>> wrote:

The new Plink2 program is dedicated for use on what they are now calling ".pfile (.pgen, .pvar, .psam)" formatted data files.
I am wishing to use PRSice2 on the 1000 genomes phase 3 dataset which is on my computer in Plink2 .pfile (.pgen, .pvar, .psam) formatted files. Will PRSice2 work on this new type of plink2 file format??
