### ISSUE TITLE
clumping not progressing

### ISSUE THREAD

**Issue by alessandrotestori** [choishingwan/PRSice#99]
Hi!
  I am trying to run PRSice, but it doesn't progress with clumping, so I stopped it after 15 minutes.
  Is it because I have too many SNPs? Please let me know, thanks!

PRSice 2.1.9 (25 Feburary 2019) 
https://github.com/choishingwan/PRSice
(C) 2016-2017 Shing Wan (Sam) Choi, Jack Euesden, Cathryn M. Lewis, Paul F. O'Reilly
GNU General Public License v3
 
If you use PRSice in any published work, please cite:
Jack Euesden Cathryn M. Lewis Paul F. O'Reilly (2015)
PRSice: Polygenic Risk Score software.
Bioinformatics 31 (9): 1466-1468
 
2019-03-15 14:35:48
./PRSice_linux \
    --A1 A1 \
    --A2 A2 \
    --bar-levels 5e-08,1e-07,1e-06,1e-05,0.0001,0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base base.assoc \
    --binary-target T \
    --bp BP \
    --chr CHR \
    --clump-kb 250 \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --hard-thres 0.900000 \
    --interval 1e-07 \
    --lower 5e-08 \
    --model add \
    --out PRSice \
    --pheno-file sample.sample \
    --pvalue P \
    --seed 2036506040 \
    --snp SNP \
    --stat OR \
    --target to_bgen_all \
    --thread 25 \
    --type bgen \
    --upper 0.5
 
 
Loading Genotype  file: to_bgen_all (bgen 
 
We assume the following line is not a header:0  A-1       1 (first column isn't FID or IID)
3653 people (0 male(s), 0 female(s)) observed 
3653 founder(s) included 
 
 
5974K SNPs processed in to_bgen_all.bgen
87558 variant(s) were pre-filtered as they did not appeared 
in base 
890375 ambiguous variant(s) excluded 
4996109 variant(s) included 
 
 
1 region included 
 
Check Phenotype file: sample.sample 
Column Name of Sample ID: 0+A-1
Note: If the phenotype file does not contain a header, the 
column name will be displayed as the Sample ID which is ok. 
Phenotype Name: 1 
There are a total of 1 phenotype to process 
 
 
Start processing base 
============================== 
 
 
Reading 100.00%
Base file: base.assoc 
7379709 variant(s) observed in base file, with: 
2992 duplicated variant(s) 
1034 ambiguous variant(s) excluded 
2380608 variant(s) not found in target file 
10915 mismatched variant(s) excluded 
4985194 total variant(s) included from base file 
 
Warning: Mismatched SNPs detected between base and 
         target!You should check the files are based on the same 
         genome build, or that can just be InDels 
 
 
Start performing clumping 
 
128829 MB RAM detected; reserving 3 MB for clumping 
Allocated 3 MB successfully 
 
 
Clumping Progress: 0.00

**Comment by choishingwan** [comment]
15 minutes is nothing when working on BGEN data as it there are 4985194 SNPs. PRSice's progress bar only increment per 0.01% which is around 500 SNPs. While it doesn't sounds much, but without using `--allow-inter` parameter, which allow PRSice to generate a large intermediate file, PRSice will need to de-compress each SNPs and convert them into hard-coded genotypes for each clumping iteration, which can be time consuming. If you have enough disk space (like, around 150GB), then I strongly recommend enabling the `--allow-inter` flag, which should in theory allow you to finish the whole PRSice analysis on BGEN samples within 48 hours

**Comment by alessandrotestori** [comment]
Thanks! Using the --allow-inter parameter is fast, but the number of variants after clumping is the same as the number of total variants included from base file, so it seems that no variant is removed by clumping.

**Comment by choishingwan** [comment]
Sorry, missed the update to this issue. If you are worry about the clumping performance, you can try using PLINK 2.0 (not 1.9) and perform clumping on the bgen file. I'd suspect similar results should be obtained between the two program
